### ISSUE TITLE
Missing or invalid authentication error on firebase logs

### ISSUE THREAD

**Issue by OsamaNasir** [googleapis/google-cloud-dotnet#11151] opened 2023-10-09 07:30 UTC
I Implemented Firebase in my project, I get real time data successfully, but getting error on firebase logs.
I refresh the token before It's expire, why I am getting invalid or missing authentication.

#### Environment details

  - OS: Windows
  - .NET version: Targeted Framework 4.8
  - Package name and version:
```
  <packages>
  <package id="Google.Api.CommonProtos" version="2.4.0" targetFramework="net48" />
  <package id="Google.Api.Gax" version="3.5.0" targetFramework="net48" />
  <package id="Google.Api.Gax.Grpc" version="3.5.0" targetFramework="net48" />
  <package id="Google.Api.Gax.Grpc.GrpcCore" version="3.5.0" targetFramework="net48" />
  <package id="Google.Apis" version="1.55.0" targetFramework="net48" />
  <package id="Google.Apis.Auth" version="1.55.0" targetFramework="net48" />
  <package id="Google.Apis.Core" version="1.55.0" targetFramework="net48" />
  <package id="Google.Cloud.Firestore" version="2.4.0" targetFramework="net48" />
  <package id="Google.Cloud.Firestore.V1" version="2.4.0" targetFramework="net48" />
  <package id="Google.LongRunning" version="2.3.0" targetFramework="net48" />
  <package id="Google.Protobuf" version="3.19.1" targetFramework="net48" />
  <package id="Grpc.Auth" version="2.41.1" targetFramework="net48" />
  <package id="Grpc.Core" version="2.41.1" targetFramework="net48" />
  <package id="Grpc.Core.Api" version="2.41.1" targetFramework="net48" />
  <package id="Microsoft.Bcl.AsyncInterfaces" version="1.0.0" targetFramework="net48" />
  <package id="Newtonsoft.Json" version="13.0.1" targetFramework="net48" />
  <package id="System.Buffers" version="4.4.0" targetFramework="net48" />
  <package id="System.Collections.Immutable" version="1.4.0" targetFramework="net48" />
  <package id="System.Linq.Async" version="4.0.0" targetFramework="net48" />
  <package id="System.Memory" version="4.5.3" targetFramework="net48" />
  <package id="System.Numerics.Vectors" version="4.4.0" targetFramework="net48" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.2" targetFramework="net48" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.2" targetFramework="net48" />
</packages>
```

#### Steps to reproduce

 There's no steps where I get the error, when my application in production I get this error on firebase logs.
Firebase Logs : 
![image](https://github.com/googleapis/google-cloud-dotnet/assets/47819999/fcc17cab-7c59-43c1-8fa0-2ae857783539)

Thanks!

**Comment by OsamaNasir** [comment] 2023-10-09 07:33
`        private async Task<FirestoreDb> GetFirestoreDb(IConnectionStringProvider connectionStringProvider)
        {
            var builder = new FirestoreDbBuilder();
            builder.ProjectId = ConnectionStringProvider.ProjectId;

            var customToken = await ConnectionStringProvider.GetCustomTokenAsync();
            signInWithCustomToken = await SignInWithCustomToken(customToken, ConnectionStringProvider.APIKey);
            ITokenAccess credential = GoogleCredential.FromAccessToken(signInWithCustomToken.IdToken);
            builder.TokenAccessMethod = credential.GetAccessTokenForRequestAsync;

            return builder.Build();
        }`
        `        private async Task<IssueAccessTokenFromRefreshToken> IssueRefreshtoken(SignInWithCustomTokenReply signInWithCustomTokenReply, string apiKey)
        {
            try
            {
                var requestBuilder = new RequestBuilder
                {
                    Method = HttpConsts.Post,
                    BaseUri = new Uri("https://securetoken.googleapis.com/v1"),
                    Path = "token"
                };
                requestBuilder.AddParameter(RequestParameterType.Query, "key", apiKey);
                var request = requestBuilder.CreateRequest();
                var jsonSerializer = Google.Apis.Json.NewtonsoftJsonSerializer.Instance;

                var lstOfPropertiesForRefreshToken = new List<KeyValuePair<string, string>>()
                {
                     new KeyValuePair<string, string>("refresh_token", signInWithCustomTokenReply.RefreshToken),
                     new KeyValuePair<string, string>("grant_type", "refresh_token"),
                };

                request.Content = new FormUrlEncodedContent(lstOfPropertiesForRefreshToken);

                using (var client = new HttpClient())
                {
                    var response = await client.PostAsync($"https://securetoken.googleapis.com/v1/token?key={apiKey}", request.Content);
                    response.EnsureSuccessStatusCode();
                    var json = await response.Content.ReadAsStringAsync();
                    var parsed = jsonSerializer.Deserialize<IssueAccessTokenFromRefreshToken>(json);
                    return parsed;
                }
            }
            catch
            {
                return default;
            }
        }`
        
        In above code I created a Firebase instance using custom token and after one I updated the token with help of google API. but still getting thousands of errors in logs . I using firebase as a client side application.

**Comment by OsamaNasir** [comment] 2023-10-09 07:34
Firebase Logs: 
![image](https://github.com/googleapis/google-cloud-dotnet/assets/47819999/f15422d8-23f9-4f4b-96ff-bf86214daf5b)

**Comment by jskeet** [comment] 2023-10-09 07:39
What's the timeline of your service starting vs when you start seeing errors? Note that an access token expires after a while - `GoogleCredential.FromAccessToken` only returns a credential for the *current* access token, with no way of refreshing it.

You say "I refresh the token before It's expire, why I am getting invalid or missing authentication" - but you haven't shown how you're using the `FirestoreDb` that's being created, or stopping the watch operation.

The other issue *may* be that your access token doesn't have appropriate scopes. The way you're creating it is one I'm unfamiliar with, and it may not have appropriate authorization for the watch operation. Please provide more information.

**Comment by jskeet** [comment] 2023-10-09 07:40
@amanda-tarafa You're more likely to know about this approach to creating access tokens - please could you have a look and see if anything jumps out at you?

**Comment by OsamaNasir** [comment] 2023-10-09 07:45
I handle refresh token logic on my app side, I just show a refresh token method after getting access token I again Initialize the FirebaseDB, because there's no Option to update it, But my question is that all things are working fine, Why I get thousands of errors in logs, I think Firestore library send multiple request and I can't handle it. Please look at this error I provide more info and code.

**Comment by jskeet** [comment] 2023-10-09 07:48
Again, you haven't shown us the code where you're *using* FirestoreDb, or told us how the timing works. Does the app work for a period and then start failing? Does it fail immediately?

If you could provide a minimal but complete console application we could use to reproduce the issue, that would make things a lot simpler for us to help you.

**Comment by jskeet** [comment] 2023-10-09 07:50
I'd also encourage you to run a test with your application using a service account instead of this custom credential approach - I'm not suggesting that's what you'd want to do in the long run, but it would help to diagnose the issue.

**Comment by OsamaNasir** [comment] 2023-10-09 07:58
It's a Lot of code of Implementation, but I only subscribe the firestore listener, working fines mean I can't reproduce on my end , getting error logs after app release on production, This application is client side, I am not using a service account file on my applicaiton.

**Comment by OsamaNasir** [comment] 2023-10-09 08:03
please look into apis calling, this is Library issue of calling multiple API, If my token is expire still Firestore library didn't send thousand of api calling and getting error on logs It's a serious issue on Firestore Library. If token is expire there's no API calling from Firestore Library.
Note It just a example, I refresh the token before It's expire.

**Comment by jskeet** [comment] 2023-10-09 08:46
> It's a Lot of code of Implementation, but I only subscribe the firestore listener, working fines mean I can't reproduce on my end , getting error logs after app release on production

So you can't reproduce the problem *at all* before production? If so, that will make it hard to diagnose the problem further. I'd encourage you to look at reproducing it locally - do you start seeing it if you leave the application running for multiple hours, for example? What log entries do you see if you provide a deliberately-invalid access token?

> This application is client side, I am not using a service account file on my applicaiton.

I know you're not using a service account file in production. I'm suggesting using one to diagnose the problem.

> please look into apis calling, this is Library issue of calling multiple API, If my token is expire still Firestore library didn't send thousand of api calling and getting error on logs It's a serious issue on Firestore Library. If token is expire there's no API calling from Firestore Library.

It's not calling multiple APIs - only the Firestore API, with retries. The retries have a backoff though, so I wouldn't expect it to be making the calls as frequently as you're seeing.

> Note It just a example, I refresh the token before It's expire.

But do you stop the existing listener? If not, then that would cause a problem. Indeed, if you're creating a new FirestoreDb and starting it listening each time you refresh the token, that may explain why you've got so many log entries - you may well have a lot of instances, all retrying at more reasonable frequencies.

**Comment by amanda-tarafa** [comment] 2023-10-09 16:30
> But do you stop the existing listener? If not, then that would cause a problem. Indeed, if you're creating a new FirestoreDb and starting it listening each time you refresh the token, that may explain why you've got so many log entries - you may well have a lot of instances, all retrying at more reasonable frequencies.

To make emphasis on what @jskeet said. If your application is working fine, but you still see the authentication errors after creating a new FirestoreDb instance, then it's very likely that you are leaving the previous listeners running with the expired token and those continue to make API requests.

Please stop the listener(s) that's using the expired token. See the [Stopping Listeners](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Firestore/latest/userguide#stopping-listeners) documentation.

**Comment by OsamaNasir** [comment] 2023-10-12 11:28
I always Stop Listeners before Initiazlize the firestore, and after initialization we again subscribe the firestore listeners. 
I created this case, sleep the laptop and coming after 2 hrs and after 2 hrs firestore we get the access token and initialize the firestore again.  but I get un Authentication error on firebase logs. I think GRPC library sents the un auth request when system is open from sleep mode.

**Comment by OsamaNasir** [comment] 2023-10-12 11:43
`{
            if (this.QueryListeners != null)
                foreach (var item in this.QueryListeners)
                    try { await item.Value.StopAsync(); } catch { }
            this.QueryListeners?.Clear();
            this.Database = null;
        }`
        
        here's my stop listener code, nothing wrong with that code. and I always call this method before initialize the firestore

**Comment by jskeet** [comment] 2023-10-12 13:19
Rather than giving us bits and pieces of code, it would really, really help if you could provide a minimal but complete application we could use to reproduce this.

It also doesn't help that your code to stop listeners has an empty catch block - if that's reporting an error, that would be good to know.

> I think GRPC library sents the un auth request when system is open from sleep mode.

Well I'd expect it to be authenticated with the "old" access token if the listener hasn't been stopped yet, yes. But until you've provided us with a way of reproducing this (without cobbling together lots of *bits* of code) we're really not going to be able to help you.

**Comment by OsamaNasir** [comment] 2023-10-16 14:18
Is there any solution to Stop Firestore logs from .Net Firestore Library ?

**Comment by jskeet** [comment] 2023-10-16 14:23
At the moment we can't really tell what's going the logging. But rather than focusing on logging, I'd focus on avoiding making incorrectly-authenticated calls - and at the moment we still don't have enough information to help you with that. Again, please provide a way of reproducing the issue.

**Comment by OsamaNasir** [comment] 2023-10-16 14:58
I successfully created  a this case. here' the step to reproduce:
1. Launch the app, successfully created a connection with firebase and getting firestore call back listeners.
2. Now the application is running,Laptop on sleep mode.
3. After an hour token is expire but my laptop is also on sleep mode so there's no un authentication errors on
firebase Logs.
4. Now I open the laptop from sleep mode and understand the senario, For e.g token is expire on 5:00 PM and I open the Laptop 5:15 PM now the 5:00 PM TO 5:14 PM There no error logs on firebase, Now I open the laptop 5:15 PM and all the thousand Logs we getting on firebase explorer.
5. One thing is also I notice , the error logs time is 5:00 PM to 5:14 PM after the laptop open and app get the internet also the logs posted on firebase form sdk side and after 5:15 PM there's no Logs because I refresh the token.

Conclusion: So simple is that if the laptop is on sleep mode Firestore library  don't need to created a logs on local and after the internet availability the logs are posted on firebase console logs. 
Please suggest how Can I handle this case from my app or you can please fix this error in your library?

**Comment by jskeet** [comment] 2023-10-16 15:06
> here' the step to reproduce

That may be the steps required for *you* to reproduce it, but that doesn't help *us* to reproduce it, because we don't have the app.

What's very unclear to me at the moment is how the app is making requests while it's still asleep. (Unless it's not the laptop making the requests... again, if you could provide a *lot* more context about what the app is doing, it would really help.)

> you can please fix this error in your library?

What error? You've *explicitly* decided to use a credential which expires, but you're continuing to make requests from it after it's expired (by having a watcher that isn't stopped). The fact that that causes errors isn't a bug in the library as far as I'm concerned. (Authentication errors are treated as being transient, by design.) You should either stop the watcher, or use a credential which autorefreshes.

**Comment by OsamaNasir** [comment] 2023-10-16 16:49
How Can I use credentials to auto refreshed ?

**Comment by jskeet** [comment] 2023-10-16 17:02
You'd need to implement something a bit like RefreshTokenManager: https://github.com/googleapis/google-api-dotnet-client/blob/main/Src/Support/Google.Apis.Auth/OAuth2/TokenRefreshManager.cs

But that's something we can't really spend a lot of time helping you with, I'm afraid. The Google.Cloud.Firestore library is really aimed at server-side use cases, where the existing set of credential classes - which already handle auto-refresh - are expected to be sufficient.

I don't think we'll be able to help you any further with this, as it doesn't look like the library is doing anything wrong, and we don't have any way of reproducing the problem ourselves to check whether it *is* doing anything wrong.

**Comment by jskeet** [comment] 2023-11-01 11:36
Closing now as we don't have any further information to suggest this is a bug in the library.

**Closed by jskeet** 2023-11-01 11:36 UTC
Labels: type: question, needs more info, api: firestore
