### ISSUE TITLE
The call is ambiguous between the following methods or properties: 'System.Linq.AsyncEnumerable.Where<TSource>(System.Collections.Generic.IAsyncEnumerable<TSource>, System.Func<TSource, bool>)' and 'System.Linq.Queryable.Where<TSource>(System.Linq.IQueryable<TSource>, System.Linq.Expressions.Expression<System.Func<TSource, bool>>)

### ISSUE THREAD

**Issue by abbjetmus** [googleapis/google-cloud-dotnet#9284] opened 2022-11-05 11:44 UTC
Hi I get this error on all versions of the [Google.Cloud.Firestore] package.
I working on a Asp.net Web API Core project with version 3.0

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'System.Linq.AsyncEnumerable.Where<TSource>(System.Collections.Generic.IAsyncEnumerable<TSource>, System.Func<TSource, bool>)' and 'System.Linq.Queryable.Where<TSource>(System.Linq.IQueryable<TSource>, System.Linq.Expressions.Expression<System.Func<TSource, bool>>)'	conmigo_server	C:\Development\Conmigo\conmigo_server\conmigo_server\Controllers\CompanyController.cs	36	Active

**Comment by jskeet** [comment] 2022-11-05 11:52
I suspect this is a duplicate of https://github.com/googleapis/google-cloud-dotnet/issues/6315. Please could you review that issue (and the suggested workaround of specifying `using static System.Linq.Queryable;` instead of `System.Linq`)?

**Comment by abbjetmus** [comment] 2022-11-05 12:06
Thank you @jskeet for the quick response and the workaround.

**Closed** 2022-11-05 12:06 UTC
Labels: type: question, api: firestore
