### ISSUE TITLE
[Bigtable] No support for label filters

### ISSUE THREAD

**Issue by billyjacobson** [googleapis/google-cloud-dotnet#4396] opened 2020-02-20 19:55 UTC
I was writing code snippets for Cloud Bigtable's filters and noticed that the filters for labelling data were missing. Can we get support for this added? Thanks

**Comment by jskeet** [comment] 2020-02-20 19:58
Could you clarify which operations you're referring to? If you could link to the (Cloud site) docs for each of the relevant operations, that would be even better. It shouldn't be hard to add it to the relevant Options classes when I know what's required.

**Comment by billyjacobson** [comment] 2020-02-20 21:36
Here are the RowFilters: https://cloud.google.com/bigtable/docs/reference/data/rpc/google.bigtable.v2#rowfilter

It's the "apply_label_transformer"

**Comment by jskeet** [comment] 2020-02-20 21:42
Whoops, I'd been thinking about BigQuery rather than Bigtable.

It looks like we do have [`RowFilter.ApplyLabelTransformer`](https://googleapis.dev/dotnet/Google.Cloud.Bigtable.V2/latest/api/Google.Cloud.Bigtable.V2.RowFilter.html#Google_Cloud_Bigtable_V2_RowFilter_ApplyLabelTransformer).

You can just use `new RowFilter { ApplyLabelTansformer = "..." }`.

**Comment by jskeet** [comment] 2020-02-20 21:43
(We could add another method in `RowFilters` if necessary - although I'd rather not have to change manual code every time a new filter is added, really...)

**Comment by billyjacobson** [comment] 2020-02-20 21:53
Oh nevermind... I am using version 1.1.0 but we are on v2

**Comment by billyjacobson** [comment] 2020-02-20 21:56
Reopening because I am curious as to why we have version 2.0.0 Beta? It's a GA client, so is the beta marker for something else?

Thanks 
![image](https://user-images.githubusercontent.com/5743695/74982277-d4cb1180-5401-11ea-8c9d-6d5451e94634.png)

**Comment by jskeet** [comment] 2020-02-20 22:02
No, it's a beta *client library* for a GA *API*. We're in the middle of a major version bump having made breaking changes in the underlying support libraries, so we've published beta libraries to get feedback before we go GA. See https://googleapis.github.io/google-cloud-dotnet/docs/guides/versioning.html for the versioning strategy.

I suggest you use the stable library version 1.5, which still has ApplyLabelTransformer.

**Comment by jskeet** [comment] 2020-02-24 10:11
(Closing as I believe everything is working as intended.)

**Closed by jskeet** 2020-02-24 10:11 UTC
Labels: api: bigquery, type: feature request

**Comment by billyjacobson** [comment] 2020-02-24 22:23
I am on version 1.1.0 and I agree that it should have been working fine, but when I try to view the source of the RowFilter it isn't there and doesn't give me autocomplete for this 
<img width="1136" alt="Screen Shot 2020-02-24 at 5 22 44 PM" src="https://user-images.githubusercontent.com/5743695/75196612-5edce800-572a-11ea-81c2-90df053c37ce.png">

**Comment by jskeet** [comment] 2020-02-24 22:42
That's `RowFilters`, not `RowFilter`. The `RowFilters` class is just a static class with convenient factory methods for `RowFilter`, but you can create a `RowFilter` directly as per my earlier comments.

**Comment by billyjacobson** [comment] 2020-02-25 00:14
Ah sorry! Thanks again!!
