### ISSUE TITLE
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses")

### ISSUE THREAD

**Issue by OsamaNasir** [googleapis/google-cloud-dotnet#10578] opened 2023-06-23 11:45 UTC
Why do I get this error while fetching data from the Fire store. Fire store works fine with no issue with the Firebase service. I get data using Postman. I just want to get a Fire store collection using an access token.
This project worked perfectly last year, but I muted it. Now that I want to resume it, I'm getting a GRPC exception. 
I've tried using the google-service-account.json file as well, but I still get the same error.Anyone face the same problem as me?
Note: I get this error on Windows 11.
Code:
```chsarp
private static  FirestoreDb GetFirestoreDb()
{
    var builder = new FirestoreDbBuilder();
    builder.ProjectId = "ProjectId";
    //Get From https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken Api
    string oauthToken = "AccessToken";
    ITokenAccess credential = GoogleCredential.FromAccessToken(oauthToken);
    builder.TokenAccessMethod = credential.GetAccessTokenForRequestAsync;

    return builder.Build();
}

private static async void GetDataFromFireStore()
{
    try
    {
        var db =  GetFirestoreDb();
        CollectionReference collectionRef = db.Collection("windows_test");

        // Perform a query and retrieve documents
        QuerySnapshot querySnapshot = await collectionRef.GetSnapshotAsync();
        Console.WriteLine(querySnapshot);
    }
    catch (Exception exp)
    {
        Console.WriteLine(exp);
    }
}
```

Error: 
```
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1686227565.417000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":5397,"referenced_errors":[{"created":"@1686227565.417000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\ext\filters\client_channel\lb_policy\pick_first\pick_first.cc","file_line":398,"grpc_status":14}]}")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.ClientResponseStream`2.<MoveNext>d__5.MoveNext() in /var/local/git/grpc/src/csharp/Grpc.Core/Internal/ClientResponseStream.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Api.Gax.Grpc.AsyncResponseStream`1.<MoveNextAsync>d__8.MoveNext() in /_/Google.Api.Gax.Grpc/AsyncResponseStream.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.<<ForEachAsync>g__Core|295_0>d`1.MoveNext() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ForEach.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Linq.AsyncEnumerable.<<ForEachAsync>g__Core|295_0>d`1.MoveNext() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ForEach.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Cloud.Firestore.Query.<GetSnapshotAsync>d__62.MoveNext() in /_/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/Query.cs:line 738
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FreibaseLibraryOld.Program.<GetDataFromFireStore>d__2.MoveNext() in C:\Users\osama.nasir\source\repos\FreibaseLibraryOld\FreibaseLibraryOld\Program.cs:line 36
```

**Comment by amanda-tarafa** [comment] 2023-06-23 12:15
(Note, I've modified your question to format the code use 3 backticks instead of 1 when you want to format multiple lines of code).

The error looks mostly enviromental. You most likely have no internet conection in the machine you are trying to execute this code, or there's a firewall that does not allow HTTP/2 which is a requirement for gRPC. A few questions for you:

- Does the code succeeds in a different machine/connected to a different network?
- Can you make a simple HTTP request from within the failing machine, say to http://www.google.com?
- Can you confirm with your network admins that HTTP/2 traffic is allowed in the failing machine?
- Can you share the exact versions of the libraries involved?

**Comment by OsamaNasir** [comment] 2023-06-23 14:26
@amanda-tarafa Use the code mentioned above to see if you can access the firestore collection and If you have a more effective method, please share it.
**Additionally, if you need it, I'll provide you access to my Firebase project.**

**Comment by OsamaNasir** [comment] 2023-06-26 07:19
@amanda-tarafa Firstly I use **3.3.0** version of Google.Cloud.Firestore which is release at May,2023.
Secondly if same code works in windows 10 so why we get GRPC exception in windows 11, May be windows 11 have some restriction on GRPC socket. can you please execute above code on windows 11 ?

**Comment by amanda-tarafa** [comment] 2023-06-26 07:58
@OsamaNasir when I asked you to specify the version of the libraries you are using, you posted the packages section of an old-style project file that contains the following line:

```
<package id="Google.Cloud.Firestore" version="2.4.0" targetFramework="net48" />
```

That library version is over 2 years old. When you now say:

```
Firstly I use 3.3.0 version of Google.Cloud.Firestore which is release at May,2023.
```

1. Do you mean that you have changed your application to use the newer version of the library and you still see the error?

1. Or do you mean that you believe you have been using Google.Cloud.Firestore 3.3.0 from the start, i.e. since you posted this question, even though your answer a couple of comments above indicates otherwise.

Before I attempt to reproduce anything anywhere, I need to know exactly what code, with what dependinces, targetting which .NET version I need to run. If I run something different to what you are running, whatever result I get, it doesn't help at all.

**Comment by amanda-tarafa** [comment] 2023-06-26 08:02
Actually, at this point, it's best if you share a simple console application with minimum code and dependencies that reproduces the problem, that is a Program.cs file and a *.csproj file. Run it in your environment to make certain it fails, and then share it here, making sure you remove any Google Cloud Project identifiers, or service account identifiers, etc. I will use that to attempt to reproduce.

**Comment by OsamaNasir** [comment] 2023-06-26 12:18
@amanda-tarafa From the start I use 3.3.0 Google Cloud Firestore library,I also tried with old package to see that error are same or not. so, I mistakenly write a "2.4.0" library. I write simple code and share a dependencies which I used in my project. Please resolve my Issue why firebase is not working on windows 11. I want to use SignIn with Custom token method to authenticate, and get the firestore collection.
Note: I also share a Console application with you can you please provide a email so I can share my project.

**Comment by OsamaNasir** [comment] 2023-06-26 12:20
Config File data of my Project:

**<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Google.Apis.Auth" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.58.0.0" newVersion="1.58.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Protobuf" publicKeyToken="a7d26565bac4d604" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.15.8.0" newVersion="3.15.8.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Api.Gax" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Api.Gax.Grpc" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Api.CommonProtos" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.7.0.0" newVersion="2.7.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Google.Api.Gax.Grpc.GrpcCore" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.3.0.0" newVersion="3.3.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>**

**Comment by jskeet** [comment] 2023-06-26 12:25
Please use triple backticks to make sure your code and project file contents are formatted appropriately. I would expect it to be feasible to include the console app here directly - I wouldn't expect it to be more than about 20 lines of code for a minimal example.

**Comment by jskeet** [comment] 2023-06-26 14:11
I've just tried the code, and it worked for me on my personal Windows 11 machine. A few notes though:

- I'd strongly advise you to move to using the "SDK style" projects if you possibly can. They're *so* much simpler - and yes, you can still use them with .NET framework.
- I used a service account JSON file instead of a custom access token. I wouldn't *expect* that to be an issue, but please try with a suitable service account JSON file to see if that's relevant.
- Your `GetDataFromFireStore` method is async but returns void, which means you can't actually wait for it to complete. I've provided what I'd consider to be a cleaner minimal example below
- Printing out the QuerySnapshot won't provide useful information, so my modified code joins the document IDs together

New code:

```csharp
using Google.Cloud.Firestore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace FirebaseConnectionDemo
{
    class Program
    {
        static async Task Main()
        {
            var db = FirestoreDb.Create("... your projectid ...");
            CollectionReference collectionRef = db.Collection("windows_test");
            QuerySnapshot querySnapshot = await collectionRef.GetSnapshotAsync();
            Console.WriteLine(string.Join(", ", querySnapshot.Documents.Select(doc => doc.Id)));
        }
    }
}
```

Or using an SDK style project:

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="3.3.0" />
  </ItemGroup>
</Project>
```

Program.cs:

```csharp
using Google.Cloud.Firestore;

var db = FirestoreDb.Create("...");
CollectionReference collectionRef = db.Collection("windows_test");
QuerySnapshot querySnapshot = await collectionRef.GetSnapshotAsync();
Console.WriteLine(string.Join(", ", querySnapshot.Documents.Select(doc => doc.Id)));
```

(That's literally all you need.)

**Comment by jskeet** [comment] 2023-06-26 14:12
My experience of "failed to connect to all addresses" errors is that it's *always* something in the network layer - typically a proxy or a firewall.

**Comment by OsamaNasir** [comment] 2023-06-27 05:55
@jskeet you said , **I used a service account JSON file instead of a custom access token. I wouldn't expect that to be an issue, but please try with a suitable service account JSON file to see if that's relevant.** 
But I didn't see that in the code where you using .json file.

**Comment by jskeet** [comment] 2023-06-27 06:15
> But I didn't see that in the code where you using .json file.

If you don't specify any credentials, the code uses [Application Default Credentials](https://cloud.google.com/docs/authentication/application-default-credentials). I have the GOOGLE_APPLICATION_CREDENTIALS environment variable set to the path to the service account JSON file.

**Comment by OsamaNasir** [comment] 2023-06-27 07:56
@jskeet KasperSky installed in my system, and it's control by admin I think due to kaspersky security I face this error.

**Comment by jskeet** [comment] 2023-06-27 07:58
That seems entirely plausible. I suggest you ask your admin for help with it. (You might want to try reproducing on a personal machine just to convince yourself that it really is down to your specific environment.)

**Comment by jskeet** [comment] 2023-06-28 14:26
Closing as we expect this to be due to Kaspersky. Please add another comment if you still have issues that need investigating after talking with your admin.

**Closed by jskeet** 2023-06-28 14:26 UTC
Labels: type: question, needs more info, api: firestore, priority: p3
