### ISSUE TITLE
Cannot use any api depending on Grpc.Core on arm64 osx

### ISSUE THREAD

**Issue by NinoFloris** [googleapis/google-cloud-dotnet#8297] opened 2022-04-02 20:51 UTC
Trying to use something like Cloud.Kms locally on an M1 macbook does not work due to missing arm64 native assets, these do ship for linux already.
```
Unhandled exception. System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: bin/Debug/net6.0/libgrpc_csharp_ext.arm64.dylib,bin/Debug/net6.0/runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib,bin/Debug/net6.0/../../runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.GrpcCore.GrpcCoreAdapter.CreateChannelImpl(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options)
   at Google.Api.Gax.Grpc.GrpcAdapter.CreateChannel(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(GrpcAdapter grpcAdapter, String endpoint, GrpcChannelOptions channelOptions, ChannelCredentials credentials)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(GrpcAdapter grpcAdapter, String endpoint, GrpcChannelOptions channelOptions)
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateCallInvoker()
   at Google.Cloud.Kms.V1.KeyManagementServiceClientBuilder.BuildImpl()
   at Google.Cloud.Kms.V1.KeyManagementServiceClientBuilder.Build()
```

See https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Grpc.Core.csproj#L38-L41 and https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/NativeDeps.Mac.csproj.include for the included mac assets.

@jskeet hopefully you can add some urgency to the following issue https://github.com/grpc/grpc/issues/28433

**Comment by NinoFloris** [comment] 2022-04-02 21:08
Ah I missed the pr https://github.com/grpc/grpc/pull/29101. Paraphrased "we're waiting for our CI to support mac arm binaries" doesn't give me much faith this will be solved anytime soon... 

Not that it would be any less work (or faster for that matter) but a switch to https://github.com/grpc/grpc-dotnet#grpc-for-net-is-now-the-recommended-implementation would be another way to go. Probably not so feasible either, any other suggestions?

**Comment by jskeet** [comment] 2022-04-03 06:37
This is effectively a duplicate of #7560, so I'll close it now.

Basically, the interim solution is to add a dependency to Google.Api.Gax.Grpc.GrpcNetClient and manually specify the GrpcAdapter when building the client.

I'm hoping that in the about 6 weeks, we'll be releasing a new version of *all* the client libraries, using Grpc.Net.Client by default when it's available, at which point you won't need that workaround.

**Closed by jskeet** 2022-04-03 06:37 UTC

**Comment by NinoFloris** [comment] 2022-04-03 11:55
Thanks for the workaround. And apologies for the duplicate, I should have done a search in this repo as well! (if there was an issue left open I would have seen it)

Initially when reading this I got the impression the sdk would stay on grpc.core for the foreseeable future. So it's great to see the move happen so soon! Replacing native dependencies with a like-for-like managed alternative is always welcome.
https://grpc.io/blog/grpc-csharp-future/
> 
> I’m not using gRPC directly in my code, but I’m using the Google Cloud Client Libraries (which do use Grpc.Core under the hood). How does this impact me?
> 
> This deprecation does not currently impact existing users of Google Cloud Client Libraries.
> 
> Since Grpc.Core is an integral part of these client libraries, security and bug fixes for Grpc.Core will continue to be provided for Google Cloud Client Libraries.
> 
> The client libraries for which the extended support will be provided:
> 
>     [Google Cloud Libraries for .NET](https://github.com/googleapis/google-cloud-dotnet)
>     [Google Ads Client Library for .NET](https://github.com/googleads/google-ads-dotnet/)
> 
> Note that the extended support of Grpc.Core will only be provided for Grpc.Core when used as part of these client libraries. For other use cases than the Google Cloud Client Libraries, Grpc.Core won’t be officially supported past the deprecation date and users must migrate existing workloads to grpc-dotnet before the deprecation happens.

Thanks again!

**Comment by jskeet** [comment] 2022-04-03 11:58
Grpc.Core is an integral part of the *current generation* of the Google Cloud Libraries, and it's vital that it continues to be *supported* for the next generation as well, so that we can continue to support .NET Framework users until .NET Framework and Windows fully supports Grpc.Net.Client.

**Comment by NinoFloris** [comment] 2022-04-03 12:03
That I understood, .net framework will stick around for a while :) I was just not sure what the implications would be for future versions.

**Comment by sidsbrmnn** [comment] 2025-07-15 06:42
Hey @jskeet, jump to 2025, any update on migrating the Google Cloud Libraries to use grpc-dotnet?

**Comment by jskeet** [comment] 2025-07-15 06:53
grpc-dotnet has been the default adapter since June 2022.
