### ISSUE TITLE
Challenges while using Google.Cloud.Language from a .NET Framework EXE

### ISSUE THREAD

**Issue by sdg002** [googleapis/google-cloud-dotnet#3044] opened 2019-05-01 09:50 UTC
My environment is a simple **.NET Framework 4.6** Console EXE which calls a **.NET Standard 2.0** assembly that in turn does "part of speech tagging" using the  "Google.Cloud.Language.v1"  package. I am on **Windows 10** and using **Visual Studio 2017 15.9.8**

I have listed the steps here to repro the problem and also how I worked around.  Please note that I faced 3 challenges sequentially.  I wonder what am I doing wrong. I think the mix of .NET Framework might be complicating matters. However, for my environment, we are still dependent on some .NET Framework only libraries so we cannot move to .NET 

**Steps to reproduce the issue**

1. Create Console EXE "MainConsoleApp"(.NET Framework 4.6)
2. Create Class library "DoSomeNLP"(.NET Standard 2.0)
3. Add Nuget reference to "Google.Cloud.Language.V1 1.2.0"
2. Write some code to do Part of Speech tagging
3. Add a class file in "DoSomeNLP"
4. Compile and run the EXE
5. 

**Problem 1**
The EXE threw this exception
`System.IO.FileNotFoundException: Could not load file or assembly 'Google.Cloud.Language.V1, Version=1.2.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0' or one of
`
**Solution to Problem 1**
Added  _CopyLocalLockFileAssemblies_ attribute to the csproj of the class library "DoSomeNLP". This ensured that all the assemblies are copied over to the Bin\Debug of the Console EXE. This solved problem 1. 

**Problem 2**
Compile and run the EXE. Exception message was:
```
System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: C:\TrueTemp\GoogleNLPIssue\MainConsoleApp1\bin\Debug\grpc_csharp_ext.x64.dll,C:\TrueTemp\GoogleNLPIssue\MainConsoleApp1\bin\Debug\runtimes/win/native\grpc_csharp_ext.x64.dll,C:\TrueTemp\GoogleNLPIssue\MainConsoleApp1\bin\Debug\../..\runtimes/win/native\grpc_csharp_ext.x64.dll
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)


```
**Solution to Problem 2**

1. I examined the list of Dependencies for the project DoSomeNLP
2. It was referencing Grpc.Core (1.18.0)
3. Browse to the Nuget packages folder located under %USERPROFILE%\ .nuget and search for "grpc_csharp_ext.x64.dll". 
1. Copy and pasted this DLL to the .NET Standard class library project DoSomeNLP and set the property Copy to output Directory=Always.
2. This specific problem was solved. 

**Problem 3**
Compile and run the EXE. Exception message was:
```
System.TypeInitializationException: The type initializer for 'Microsoft.Extensions.PlatformAbstractions.PlatformServices' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment.GetEntryAssembly()
   at Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment..ctor()

```
**Solution to problem 3**
Added the following nuget package to MainConsoleApp
`Install-Package System.Reflection.TypeExtensions -Version 4.0.0`

**Request to Google**
While trying something similar with AWS, the experience was very smooth. Please look into this.

**Comment by jskeet** [comment] 2019-05-01 09:59
Looking into this now. I'm hoping to have cleaner solutions for all problems :)

**Comment by jskeet** [comment] 2019-05-01 10:06
Could you clarify exactly how you've created the console project, and how you've added a reference to the class library? Having created it in VS (2019, admittedly), I have an error of:

> Project '..\ClassLibrary\ClassLibrary.csproj' targets 'netstandard2.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.6'.	ConsoleApp			

The error goes away with .NET 4.6.1, which makes sense given the chart at https://docs.microsoft.com/en-us/dotnet/standard/net-standard
I'm going to proceed with a 4.6.1 project for now...

**Comment by jskeet** [comment] 2019-05-01 10:25
Issue 1
---

I have a couple of alternative suggestions:

- Add a NuGet reference to Google.Cloud.Language.V1 in your console app. This fixes all the problems, and the code just runs.
- Change the console app to be a .NET Core SDK style project, with a target framework of net461. This skips problem 1, but just goes to problem 2.

Fundamentally, problem 1 isn't really a problem with the Google.Cloud.Language.V1 library at all - I'd expect you to see the same issue with *any* transitive dependency.
I'd generally suggest that using a .NET Core SDK style project ends up with a nicer experience (smaller and simpler project files) and I'd recommend that approach if possible, but I realize it may not be feasible for you.

On to issue 2...

Issue 2
---

This is caused by the native libraries for gRPC not being copied automatically. It's [described briefly in the FAQ](https://googleapis.github.io/google-cloud-dotnet/docs/faq.html#why-arent-the-grpc-native-libraries-being-found)

The solution will depend on how you've solved issue 1. If you've changed the console app to be a .NET Core SDK project, then you can add this dependency to the class library:

```xml
<PackageReference Include="Grpc.Core" Version="1.20.1" PrivateAssets="None" />
```

That should work for all projects that depend on the class library directly. You could add the same dependency into the console app instead, if you wish.

Otherwise, if you've used the `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` approach instead, the simplest fix is to add a Grpc.Core dependency directly to the console app. I would definitely do this rather than copying the file manually somewhere else.

Issue 3
---

This issue goes away if you make the console app a .NET Core SDK project, because the right dependency versions are just used automatically.

Other options:

- Install System.Reflection.TypeExtensions as you've already done
- Add a dependency to Google.Api.Gax.Grpc version 2.7.0-beta04 in your class library; this newer version of GAX doesn't use `Microsoft.Extensions.PlatformAbstractions.PlatformServices`, so it may well just work.

Fundamentally, my advice is that if you *can* possibly change your console app project to use a .NET Core SDK style, you'll end up with a better experience.

**Comment by sdg002** [comment] 2019-05-01 11:21
Thank you very much for the detailed response. I can confirm that changing the Console application to the new project style makes things a lot easier.
`<TargetFramework>net461</TargetFramework>`

**grpc_csharp_ext.x64.dll and performance issues - Not copying the DLL to output**

Added a Nuget reference to Grpc.Core
`<PackageReference Include="Grpc.Core" Version="1.20.1" PrivateAssets="None" />`
Run the same code and measure time taken . About **21 seconds** over 3 observations.

```
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Stopwatch sw = new Stopwatch();
            try
            {
                sw.Start();
                System.Diagnostics.Trace.Listeners.Add(new System.Diagnostics.ConsoleTraceListener());
                DoSomeNLP.PartOfSpeechDemo oNlp = new DoSomeNLP.PartOfSpeechDemo();
                oNlp.DoPosTagging("Quick brown fox jumps over the lazy dog");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            finally
            {
                sw.Stop();
                Console.WriteLine($"Complete. Time elapsed={sw.Elapsed} ms");
            }
        }

```

**grpc_csharp_ext.x64.dll and performance issues - Copying the DLL to output**

I added the file grpc_csharp_ext.x64.dll to the Project and set it for copying to output.

```
  <ItemGroup>
    <None Update="grpc_csharp_ext.x64.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

```
Run the same code and measure time taken . About **2 seconds** over 3 observations.

**Comment by jskeet** [comment] 2019-05-01 11:31
That performance difference sounds *very* strange to me. Are you happy to try a few further tests to diagnose it further?

- Try putting the code you've got in `Main` in a loop, so we can see whether this is some odd one-time issue (maybe probing for the DLL?) or a steady-state difference
- Try adding logging (with timestamps) in your class library so you can see where the time is going. With a time taken of 21 seconds, I suspect it'll be reasonably obvious which part is causing the issue.

I understand not wanting to add new references directly to your console app. If you're happy to use the new-style project, you should be fine - we just need to work out what's going on with the performance.

I don't know how loading libraries via MEF will affect all of this, mind you. At that point I can imagine binding redirects etc could make the whole thing much more complicated. Does your sample app already use MEF, or is that coming later?

**Comment by sdg002** [comment] 2019-05-01 11:41
[GoogleNLPNewProjStyle.zip](https://github.com/googleapis/google-cloud-dotnet/files/3134406/GoogleNLPNewProjStyle.zip)

Hi @jskeet 
I have attached herewith the sample VS.NET solution that I was using to demonstrate the problem. In this sample we are doing nothing beyond a simple Part of speech tagging.

1. **ConsoleApp1** - EXE project. Created using .NET Core Console App project template and then changed the csproj manually to target 4.61
1. **DoSomeNLP** - This is a .NET Standard 20 class library project which simply calls the Google NLP library and does a Part of speech tagging. 

I would like to let you know that all of this has been working fine in our existing application which was primarily on .NET Framework. We started encountering challenges while doing a phased transition of our class libraries to .NET Standard.

**Comment by jskeet** [comment] 2019-05-01 12:44
Please note: you included your service account file in the zip. I strongly advise you to disable that service account immediately. I'll use my own service account for testing, so we don't need any secret sharing. I've removed the link from the comment, but it would be best to be sure.

**Comment by jskeet** [comment] 2019-05-01 12:49
Separately to that - I can't reproduce the performance problem. I've removed the copy of grpc_csharp_ext.x64.dll (and the licence file) so now the structure is just:

- One project file per project
- One C# file per project
- The solution file

This is what the project files look like for me:

ConsoleApp1:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DoSomeNLP\DoSomeNLP.csproj" />
  </ItemGroup>
</Project>
```

DoSomeNLP:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Cloud.Language.V1" Version="1.2.0" />
    <PackageReference Include="Grpc.Core" Version="1.20.1" PrivateAssets="None" />
  </ItemGroup>
</Project>
```

That executes the code in just under 2 seconds, every time I run it. Are you still able to reproduce the 20 second version?

**Comment by sdg002** [comment] 2019-05-01 13:06
Hi  @jskeet  ,
Yes. Just tested. Did a Clean solution each time and re-tested. Same metrics. 
Could you share the ZIP of your solution please? 


**Console EXE**
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DoSomeNLP\DoSomeNLP.csproj" />
  </ItemGroup>

</Project>

```

**Class library**

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Google.NLP.License.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Google.NLP.License.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Language.V1" Version="1.2.0" />

    <!-- Step1 - uncomment this line for slower execution -->
    <!--<PackageReference Include="Grpc.Core" Version="1.20.1" PrivateAssets="None" />-->
  </ItemGroup>

  <ItemGroup>
    <!-- Step 2- comment this line for slower execution -->
    <None Update="grpc_csharp_ext.x64.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

```

**Comment by jskeet** [comment] 2019-05-01 13:11
[Issue3044b.zip](https://github.com/googleapis/google-cloud-dotnet/files/3134578/Issue3044b.zip)

I've attached the zip file. It assumes you have the GOOGLE_APPLICATION_CREDENTIALS environment variable already set. But if that's the case, you should just be able to unzip, go into Issue3044b, then run `dotnet run -p ConsoleApp1`... or build it and then run `ConsoleApp1/bin/Debug/net461/ConsoleApp1.exe` directly.

Note that I've removed the `CopyLocalLockFileAssemblies` from the library project file as well, as that's not necessary.

**Comment by sdg002** [comment] 2019-05-01 13:37
Same issues.  

**Your code before any changes**
![image](https://user-images.githubusercontent.com/20245330/57018897-f530a200-6c1c-11e9-9e29-a7d4cac0f2a0.png)
Note the time taken > 20 seconds

**After making slight changes to the CSPROJ of the class library**
![image](https://user-images.githubusercontent.com/20245330/57019107-640dfb00-6c1d-11e9-9d69-6ed7bde898d8.png)

Time taken < 3 seconds.  I made the following changes

1. I have re-added grpc_csharp_ext.x64.dll to the class library and set copy to output folder.
2. I uncommented the package reference to Grpc.Core


I am not sure what is going on. This issue is reminiscent of the DLL HELL of years ago. Possibly some Nuget HELL  or something else.  It would be nice to know the root cause. For now, I am fine with my workaround.  (Steps 1 and 2 above)

Thank you for all the support.

**Comment by jskeet** [comment] 2019-05-01 13:50
That's *really* odd. I think it's probably worth spending a *bit* more time getting it to work without the workaround, if you're happy to - you really shouldn't need to be copying the file around like that, and I can see it causing problems later.

If you change the `DoPosTagging` method body to this:

```csharp
Console.WriteLine($"{DateTime.UtcNow:HH:mm:ss} Before client creation");
var client = Google.Cloud.Language.V1.LanguageServiceClient.Create();
var doc = new Google.Cloud.Language.V1.Document() { Content = input, Type = Google.Cloud.Language.V1.Document.Types.Type.Html };
var features = new Google.Cloud.Language.V1.AnnotateTextRequest.Types.Features { ExtractEntities = true, ExtractSyntax = true };
Console.WriteLine($"{DateTime.UtcNow:HH:mm:ss} Before RPC");
var response = client.AnnotateText(doc, features);
Console.WriteLine($"{DateTime.UtcNow:HH:mm:ss} After RPC");
Google.Cloud.Language.V1.Entity[] allEntities = response.Entities.ToArray();
foreach (var entity in allEntities)
{
    Console.WriteLine($"Ent={entity}");
}
Console.WriteLine($"{DateTime.UtcNow:HH:mm:ss} After output logging");
```

... and change your Main code that constructs the instance and calls the method to this:

```csharp
Console.WriteLine($"{DateTime.UtcNow:HH:mm:ss} Before constructor call");
DoSomeNLP.PartOfSpeechDemo oNlp = new DoSomeNLP.PartOfSpeechDemo();
Console.WriteLine($"{DateTime.UtcNow:HH:mm:ss} Before method call");
oNlp.DoPosTagging("Quick brown fox jumps over the lazy dog");
```

... what does the output look like in the slow case?

**Comment by sdg002** [comment] 2019-05-01 14:00
Similar behavior with Grpc version 1.20.1

**Greater than 20 seconds**
![image](https://user-images.githubusercontent.com/20245330/57020634-c9fc8180-6c21-11e9-8ba7-1a251af6183d.png)

**With my work around, less than 3 seconds**
![image](https://user-images.githubusercontent.com/20245330/57020590-a3d6e180-6c21-11e9-9d85-6aabc2a9f510.png)

**Comment by sdg002** [comment] 2019-05-01 14:08
With Grpc.Core. 1.18.0 , it looks very good.  **Less than 2 seconds.**

![image](https://user-images.githubusercontent.com/20245330/57020938-cc131000-6c22-11e9-96b1-39427443c1de.png)

This is good. I will regress our code base to 1.18 for now.

**Comment by jskeet** [comment] 2019-05-01 14:12
Okay, it's good to know that - but I'm very confused about why 1.20.1 would take longer. I'd love to investigate that further (and I'm sure the gRPC team would want to know too), but I completely understand if it's not a priority for you.

If you *do* want to investigate it, this would help, running from a command line in the ConsoleApp1 directory:

```sh
> set GRPC_TRACE=all
> set GRPC_VERBOSITY=DEBUG
> bin\Debug\net461\ConsoleApp1.exe 2> log
```

... then look at the log file, which will be *huge*. I wouldn't suggest posting that here, but if you're happy to capture it and then send the log to me at jonskeet@google.com, I'd love to take a look.

**Comment by sdg002** [comment] 2019-05-01 14:43
I am happy with the fix.   However, if Google wants to find out where they might have to make some fixes then I am happy to help. This is the log with 1.18

[jskeet.zip](https://github.com/googleapis/google-cloud-dotnet/files/3134813/jskeet.zip)

**Comment by jskeet** [comment] 2019-05-01 14:44
The important log is the one in the slow situation, so we can see where time is going. But please email it to me rather than attaching it here - while I don't know of any long-term sensitive data that would be in the log, it's best not to include it publicly IMO.

**Comment by sdg002** [comment] 2019-05-01 15:57
Ok. Logs with 1.20.1 of GRPC.Core sent to your email.  Thanks for all the support.

**Comment by jskeet** [comment] 2019-05-01 18:57
Great, thanks. I'll look at the logs tomorrow. I'm going to close this issue now as the remaining performance difference isn't really related to the main issue (and if anything, it belongs on the gRPC repo - I'll file something there if I can).

**Closed by jskeet** 2019-05-01 18:57 UTC
Labels: priority: p2, type: question

**Comment by jskeet** [comment] 2019-05-07 14:58
Hi, I've heard back from the team and they have a lead.

If you still have the program handy, could you try running the code with 1.20 again, but with an environment variable `GRPC_DNS_RESOLVER` set to `native`? Apologies for not doing this myself - I can't reproduce the problem! Of course, if it's inconvenient to do so, don't feel any obligation. (It's probably helpful to you to be able to run the most recent version of Grpc.Core without this problem though - as the libraries get updated, we generally take the latest dependencies.)
