### ISSUE TITLE
Firestore C# does not exectute after Async

### ISSUE THREAD

**Issue by heeshala** [googleapis/google-cloud-dotnet#8429] opened 2022-05-02 19:13 UTC
```
Dictionary<string, object> info= new Dictionary<string, object>()
{
    { },

};

                DocumentReference a= db.Collection("Document").Document(ID);
                
            try
            {
                await a.UpdateAsync(info);


                //Record 
                await RecordAsync();


            }
```

Here i set a degub point and it doesnet go on after the UpdateAsync
the RecordAsync function is also another async function that executes other firestore function

**Comment by jskeet** [comment] 2022-05-03 07:29
I'm afraid with the pseudo-code presented here, we don't really have enough information.

If you could provide a minimal, complete program that demonstrates the problem - ideally as a small console app - that would really help. I'd expect that even if this fails, an exception would be thrown so you should be able to see that exception for details.

If you could also provide more details of how and where you're running this, that would help - can I assume that as you're talking about debugging, it's on your local developer machine? What operating system is that using? What version of the Firestore library are you using? The more information you can provide, the more likely it is that we'll be able to help you.

**Comment by jskeet** [comment] 2022-05-10 07:24
Closing for now due to lack of enough information to reproduce. Please add a comment with more information and I'll gladly reopen the issue.

**Closed by jskeet** 2022-05-10 07:24 UTC
Labels: type: question, needs more info, api: firestore
