### ISSUE TITLE
Incompatibility with Grpc.Core.Api v2.25.0 and Grpc.Core 1.22.1

### ISSUE THREAD

**Issue by jbehren1** [googleapis/google-cloud-dotnet#4511] opened 2020-03-04 23:07 UTC
It appears that Grpc.Core.Api v2.x is incompatible with Grpc.Core v1.x, however the dependencies listed on each library does not restrict users from installing the two incompatible versions.

This can possibly be triggered in normal situations by doing a "global" update for all Nuget packages in your solution - if you happen to have Grpc.Core v1.x and Google.Api.Gax.Grpc v2.10.0 installed as I did, attempting to perform "all available" updates in VS2019 will result in a scenario where Grpc.Core remains on v1.x but Grpc.Core.Api gets updated to the incompatible v2.x library.

#### Environment details

  - OS: Windows (Server 2016, Windows 10)
  - .NET version: Framework 4.6.1, 4.7.2
  - Package name and version: Grpc.Core.Api v2.25.0, Grpc.Core 1.22.1, Google.Api.Gax.Grpc v2.10.0, Google.Cloud.Pubsub.V1 v1.1.0

#### Steps to reproduce

  1. Create new .net Framework console application (4.6.1 and 4.7.2 confirmed, likely impacts additional versions), in Visual Studio 2019 (VSCode may work as well)
  2. Using Nuget package manager, add reference to Google.Cloud.PubSub.V1 (v1.0.0 or v1.1.0)
  3. Follow steps at https://cloud.google.com/pubsub/docs/pull to create a topic/subscription, and configure your console application to create subscriber for newly created topic. 
   3a. Ensure you are using the async/await modifiers. Do not `await` subscriber.StartAsync, but ensure the stop is called as `await subscriber.StopAsync(TimeSpan.FromSeconds(1))` after a 10 second `Task.Delay`.
   3b. Log the message body to console or debug window for visual verification (exactly as in documentation - but always `return SubscriberClient.Reply.Ack`
   3c. Add a debug/console output immediately after the `await subscriber.StopAsync` line.
  4. Seed topic with messages (any size or content - this step is optional as one part of the bug does not require any messages). Around 20 small (<10kb) messages usually proves sufficient.
  5. Using Nuget package manager, Update Grpc.Core.Api version from 1.x to 2.x (note that Grpc.Core and Grpc.Auth 1.x does not have any dependency on Grpc.Core.Api version, nor is the inverse true)
  6. Debug the application. Note that messages are being consumed from the stack. With 10-20 messages, you should see all messages that were previously in the queue within a few seconds. After 15 seconds, note that the 10 second `Task.Delay` has passed, and the `stopAsync` should have aborted any connections, yet the application still has not closed nor reached the output after `subscriber.StopAsync` (bug number 1)
  7. Stop/Cancel Debugging in VS. 
  8. Inspect the subscription's unacked message count on console.cloud.google.com. Note that while it may have gone down by a few messages, all (10-20) messages *should* be gone, but some still remain. (bug number 2).
  9. Update Grpc.Core.Api to v1.x (matching Grpc.Core version) and re-run applications. Note that after approximately 10 seconds, the application gracefully exits, and the unacked message count is now at zero.

**Comment by jskeet** [comment] 2020-03-05 04:26
Thanks for the detailed issue. At the root of this is NuGet not really following semantic versioning, IMO - ideally, it would "know" that a dependency from Grpc.Core 1.22.1 to Grpc.Core.Api 1.22.1 would have an exclusive upper bound of version 2.0. As it is, that has to be made explicit - which is was what we did in Google.Api.Gax.Grpc 2.10, as we know that's not compatible with Grpc.Core 2.x - predictably enough, given the major version bump.

We currently have beta releases of Google.Api.Gax.Grpc (etc), and all the client libraries, supporting Grpc.Core 2.x. We're hoping to release a GA version in around two weeks, assuming we don't see any issues with the betas (which we haven't yet).

I would propose closing this issue as we're covering the "we don't work with Grpc.Core 2.x" part in #3519, and there's nothing that code in *this* repository can do about the lack of an upper bound of a dependency on from Grpc.Core to Grpc.Core.Api. While we *could* release new libraries that explicitly take an extra dependency, it would be pretty odd to add that dependency *just* for this sake.

**Comment by draganjovanovic1** [comment] 2020-03-05 08:56
I dealt with this issue for some time, solved it yesterday, and today I see this :) 

My 2 cents. I use Paket package manager. 

When I add `Google.Cloud.PubSub.V1` via project file's PackageReference, NuGet by default pulls working version of `Grpc.Core.Api` which is `1.22.1` but Paket pulls latest stable as there is no upper bound defined (`2.27.0`). 

The workaround for Paket users is to add version in `paket.dependencies` file:

```
nuget Google.Cloud.PubSub.V1
nuget Grpc.Core.Api 1.22.1
```

The issue is quite hard to debug as the first call to PubSub works but thread stays blocked forever. It wasn't easy one to catch.

**Comment by jskeet** [comment] 2020-03-05 10:38
I've been talking about this a bit more with @chrisdunelm, and worked out that we *could* just release GAX 2.11.0 libraries with this direct dependency on Grpc.Core.Api with an upper bound, without releasing any client libraries. Anyone who doesn't update everything to the latest stable version wouldn't get the new GAX libraries - but they wouldn't see the problem anyway.

Or we could just wait for the ~2 weeks until we release GAX 3.0, at which point anyone updating everything will get GAX 3.0, Grpc.Core 2.x and Grpc.Core.Api 2.x, and all will be well.

I'd mildly prefer not to do another GAX release just for the sake of this, but we could if necessary.

**Comment by draganjovanovic1** [comment] 2020-03-05 10:47
Since this issue is not such new I see no reason for rush. It is good that we have valid workaround. 

I would suggest you to add some note on top of the README file within the repo stating that `Google.Cloud.PubSub.V1` will not work with `Grpc.Core.Api` > 1.* or point to this thread. Just to save some time to others having the same problem. That should be good enough. My main problem was that I couldn't find anyone with the problem and therefore any proposed solution.

**Comment by jskeet** [comment] 2020-03-05 10:51
@draganjovanovic1: We already have that in the [README.md](https://github.com/googleapis/google-cloud-dotnet) - "Incompatibility with gRPC 2.x and C# 8 async sequences". I'm not entirely sure whether folks will be able to find that, admittedly... but it's not obvious how to make it more discoverable.

**Comment by draganjovanovic1** [comment] 2020-03-05 11:02
I couldn't find it neither. :-) Maybe because process stays quiet w/o errors so I didn't have an idea what to search for. 

Maybe add some keywords e.g. PubSub. Don't have good idea TBH just want to help others with this as I spent quite a while discovering the issue.

**Comment by jskeet** [comment] 2020-03-05 11:12
There's nothing PubSub specific about this. It would happen with absolutely any of the APIs that use gRPC.

Given that this should resolve itself naturally in a couple of weeks, I think I'll stick with the documentation we've got.

**Comment by draganjovanovic1** [comment] 2020-03-05 11:23
It is clear that `PubSub` is not the only library affected, my idea was to increase discoverability as I experienced it trying to integrate `PubSub` in my project. 

I would say that this thread is already useful in that direction.

**Comment by jskeet** [comment] 2020-03-09 07:56
Closing this issue now as there's no change required in this repo. Hopefully only a week until it becomes naturally obsolete...

**Closed by jskeet** 2020-03-09 07:56 UTC
Labels: api: pubsub, priority: p2, type: bug
