### ISSUE TITLE
Lots of connections to 1e100.net domains in CLOSE_WAIT on CentOS / ASP.NET Core 2.2.4

### ISSUE THREAD

**Issue by rh78** [googleapis/google-cloud-dotnet#3121] opened 2019-06-11 10:21 UTC
#### Environment details

  - OS: CentOS Linux release 7.6.1810 (Core)
  - .NET version: .NET Core 2.2.4
  - Package name and version: Google.Cloud.Storage.V1 2.3.0

#### Steps to reproduce

Issue calls like this:

```
using (var storageClient = await StorageClient.CreateAsync(credential))
{
    var blockBlob = await storageClient.GetObjectAsync(containerName, fileName);

    await storageClient.DownloadObjectAsync(blockBlob, stream);
}
```

Over time a lot of connections to 1e100.net endpoints end up in CLOSE_WAIT state:

```
tcp        1      0 xxx-3:36561   ams15s33-in-f10.1:https CLOSE_WAIT
tcp        1      0 xxx-3:46323   ams15s30-in-f138.:https CLOSE_WAIT
tcp        1      0 xxx-3:35959   ams15s33-in-f10.1:https CLOSE_WAIT
tcp        1      0 xxx-3:35768   ams15s29-in-f10.1:https CLOSE_WAIT
tcp        1      0 xxx-3:46764   ams16s32-in-f10.1:https CLOSE_WAIT
tcp        1      0 xxx-3:36227   ams16s31-in-f10.1:https CLOSE_WAIT
tcp        1      0 xxx-3:38221   ams16s30-in-f10.1:https CLOSE_WAIT
tcp        1      0 xxx-3:38094   ams15s30-in-f138.:https CLOSE_WAIT
tcp        1      0 xxx-3:42465   ams16s31-in-f10.1:https CLOSE_WAIT
tcp        1      0 xxx-3:45406   ams16s32-in-f10.1:https CLOSE_WAIT
tcp        1      0 xxx-3:36245   ams17s08-in-f10.1:https CLOSE_WAIT
tcp        1      0 xxx-3:44719   ams16s32-in-f10.1:https CLOSE_WAIT
tcp        1      0 xxx-3:40427   ams16s30-in-f10.1:https CLOSE_WAIT
tcp        1      0 xxx-3:34067   ams16s30-in-f10.1:https CLOSE_WAIT
tcp        1      0 xxx-3:35798   ams16s32-in-f10.1:https CLOSE_WAIT
tcp        1      0 xxx-3:35853   ams16s31-in-f10.1:https CLOSE_WAIT
...
MANY
...
```

**Comment by jskeet** [comment] 2019-06-11 11:07
Could you clarify what you mean by "1e100.net endpoints" please?

Additionally, we had a [bug](https://github.com/googleapis/google-api-dotnet-client/issues/1399) which was fixed very recently - could you try adding a dependency to `Google.Apis` version 1.40.2 and see if that fixes the problem? Obviously we'll update our dependency over time, but we might do an extra release specifically for this if it fixes the problem.

**Comment by rh78** [comment] 2019-06-11 11:12
Hello "1e100.net" endpoints means it goes to DNS names ending with "1e100.net" (which is a Google property). So I should stay on Google.Cloud.Storage.V1 dependency, and add Google.Apis 1.40.2 on top of that?

**Comment by jskeet** [comment] 2019-06-11 11:20
Yes, just add that extra dependency (which is already there transitively, but at an older version)

**Comment by rh78** [comment] 2019-06-11 11:41
I am just deploying the build. I will tell you ASAP if it fixes the problem.

**Comment by rh78** [comment] 2019-06-12 12:53
Hello - sorry the fix has not solved the problem.

**Comment by jskeet** [comment] 2019-06-12 12:56
Okay, thanks for letting me know. Do you have a different credential for each request? If there's any way that you could use one `StorageClient` per credential, with some limited set of credentials, that *might* help. (If you're able to test that, it would be great - I totally understand if you can't though.)

I'll see if I can reproduce the problem here.

**Comment by jskeet** [comment] 2019-06-12 15:08
Hmm.. that same code passes for me on my Linux box.

Could you try the same example yourself in the environment where you're seeing the problem? Once we've got isolated sample code which definitely reproduces the problem in your environment, we can try to reproduce it in my environment too, and then fix it.

**Comment by rh78** [comment] 2019-06-13 16:49
I am a bit busy right now I'll do ASAP.

**Comment by jskeet** [comment] 2019-06-19 10:54
Any updates on this?

**Comment by jskeet** [comment] 2019-07-01 13:55
Closing for the moment due to a lack of information. Please add another comment with more information if you'd like me to reopen the issue.

**Closed by jskeet** 2019-07-01 13:55 UTC
Labels: api: storage, needs more info, priority: p2, type: bug

**Comment by ChristianVermeulen** [comment] 2024-01-16 09:19
I'm so much hoping this will be picked up again by someone. We are having this exact same issue (but not related to cloud dotnet). We run a php application using Ratchet for websockets. Somehow we are seeing this same phenomenon happen to our ratchet server.

![image](https://github.com/googleapis/google-cloud-dotnet/assets/1062751/7fac9117-2876-4c96-a282-5bc92b441f41)

It seems to connect on all kinds of different ports as well, even though we have closed incoming connections through UFW, allowing only our own port (9999). This is what baffles me most.

**Comment by jskeet** [comment] 2024-01-16 10:01
If you're not using .NET then it's definitely not relevant in this repo I'm afraid.

**Comment by ChristianVermeulen** [comment] 2024-01-16 10:02
> If you're not using .NET then it's definitely not relevant in this repo I'm afraid.

I'm just hoping if a solution is found here, it might be relevant or point me to a solution for us as well.
