### ISSUE TITLE
Long publish message times for PubSub on Windows 

### ISSUE THREAD

**Issue by twgraham** [googleapis/google-cloud-dotnet#6461] opened 2021-05-13 11:37 UTC
We're experiencing long really long, semi-consistent publish times when using pubsub in our .NET 5 asp net project. It's actually uncanny how consistent the long publish times are... Some would even suggest it's a timeout/deadline. When I go to publish a small message using `PublisherClient`, it's taking around **20 seconds.**

Our service is hosted on GCP, in a windows LTSC container on k8s. It's pretty unremarkable, only has a few endpoints, and only publishes to PubSub. When it first starts, the publish times are quick, but after a short time (~30 mins), it starts taking a long time to publish. Tracing shows just how consistent these long publishes are...

![image](https://user-images.githubusercontent.com/7763403/118120189-d3d13600-b432-11eb-9fae-9090ff4b4a3c.png)

We have many other, more complex services running on the same k8s cluster in Linux containers that have no issue.

As I mentioned - I suspect its probably some gRPC socket timeout or ack deadline issue, but I'm not too sure what to log or look for when it comes to that.

#### Environment details

  - OS: Windows LTSC
  - .NET version: 5.0.5
  - Package name and version: Google.Cloud.PubSub.V1 2.4.0

**Comment by jskeet** [comment] 2021-05-13 11:42
Are you able to reproduce in a development environment, ideally with a small console app? Are the Linux containers *also* publishing to the same PubSub topics? (I'm trying to get a sense of whether the operating system is actually relevant here, or whether it's a coincidence.)

**Comment by jskeet** [comment] 2021-05-13 11:46
Oh, and I quite agree that the timing is too consistent to be a coincidence.

If we can get to the stage of being able to reproduce this with a test app where you can share the code (even if it only reproduces in a Windows LTSC container) then we should be able to make progress.

(As a heads-up, I'm on vacation tomorrow so won't be able to do any work on this issue then.)

**Comment by twgraham** [comment] 2021-05-13 11:57
Thanks @jskeet! I'll do my best to reproduce in a public repo using windows container.

**Comment by jskeet** [comment] 2021-05-19 07:03
Hi @twgraham - have you managed to reproduce this at all? I'm definitely keen to help if possible.

**Comment by twgraham** [comment] 2021-05-19 12:31
Apologies, I've attempted some further debugging, but no success yet. Give me another 24 hours, I'm going to see if I can reproduce with a simple app on the same base docker image in GCP.

**Comment by twgraham** [comment] 2021-05-20 02:45
@jskeet I've managed to reproduce the issue [here](https://github.com/twgraham/AspNetPubsubWindows). I used the dockerfile to build a container and publish it to GKE. I haven't tried on a local windows machine yet though.

At first publishes are fast (sub 500ms), but after about 10 mins the publishes reliably become ~20 seconds.

**Comment by twgraham** [comment] 2021-05-20 06:15
So far I haven't been able to reproduce using a standard windows VM on GCP and the repo I linked 😕. I'm starting to suspect its a docker/k8s issue. I'll try run the docker image on a local windows machine tonight as well as a container on a windows VM.

**Comment by jskeet** [comment] 2021-05-20 06:32
Interesting - and thanks for the continued efforts to reproduce. I'll try to reproduce it myself on a Windows k8s node. Just to check a couple of other things:

- Have you tried this on a Linux k8s node? I know you said earlier that you've got other Linux k8s jobs running, but are they making PubSub calls?
- Do I need to send a lot of traffic to the server to reproduce this, or will just refreshing a browser tab once every few minutes be enough, in your experience?

**Comment by twgraham** [comment] 2021-05-20 06:39
Yes we've got a number of other linux containers that publish, usually with *a lot* more traffic too. These are typically based on `mcr.microsoft.com/dotnet/aspnet:5.0` and run in the same k8s cluster (stable channel).

Refreshing the browser infrequently works fine - you can see that there is not much data in the message either.

**Comment by jskeet** [comment] 2021-05-20 07:17
Great, thanks. I'll give that a try now. (I should mention that I've never used Windows with Docker at all before, so it may take me a little while to get going.)

**Comment by jskeet** [comment] 2021-05-20 08:56
Thanks @twgraham: I was still in the "getting going" section of trying to reproduce this, without actually deploying anything yet, so it's much appreciated if I can abort that! Well done spotting those GKE node logs... let's *hope* that's what's going on.

I'm not sure why it would only affect Windows rather than Linux though... and if you were accessing the server more than once every 10 minutes, I'd expect the connection to stay open. Hmm.

Will reach out to folks internally to try to find a networking expert to help - I'll post here when I've found one.

**Comment by jskeet** [comment] 2021-05-20 10:53
I've persevered, and it's now deployed... I'll see whether I observe the same behavior. (I'm still contacting appropriate folks internally too.)

**Comment by jskeet** [comment] 2021-05-20 11:11
@twgraham: I've now managed to reproduce the issue. Just to check we're seeing the same thing: after the "long" publish time, if you make another request fairly soon after, do you get a "quick" publish again? That's what I'm seeing.

I'm now going to use PublisherServiceApiClient to get rid of all the logic that's in the library, leaving basically just a very thin wrapper around gRPC.

**Comment by twgraham** [comment] 2021-05-20 11:48
Hooray! I knew I wasn't crazy...
> if you make another request fairly soon after, do you get a "quick" publish again? That's what I'm seeing

Exactly. However I've had cases where I need to do 2-4 refreshes before it goes back to normal. Maybe something to do with the number of underlying channels/connections that are made that are killed 🤷

**Comment by twgraham** [comment] 2021-05-20 11:53
FWIW it looks like keepalives could have been changed at the OS level for [linux nodes to be within GCE limits](https://github.com/kubernetes/kubernetes/issues/32457#issuecomment-761259529), maybe they haven't for windows nodes?

I could very well be barking up the wrong tree...

**Comment by jskeet** [comment] 2021-05-20 12:40
Just managed to reproduce this using the underlying API (PublisherServiceApiClient in C#). Now going to try with custom gRPC options to see whether gRPC keepalive helps.

**Comment by jskeet** [comment] 2021-05-20 13:36
> However I've had cases where I need to do 2-4 refreshes before it goes back to normal. Maybe something to do with the number of underlying channels/connections that are made that are killed 

Yup, I've observed the same thing.

Currently things are looking good having set the gRPC keepalive to be one minute, enabling "keepalive pings when there aren't in-flight requests" as well. I'm not saying this is how the code should be configured - just that it suggests you're right about the connection dropping being the cause. Will wait a long time (an hour) before hitting the server again.

**Comment by jskeet** [comment] 2021-05-20 15:09
And yes, an hour later it's still publishing quickly!

I don't think it's really feasible to create a `PublisherClient` with custom gRPC options, so for the moment the only workaround in code would be to use the underlying `PublisherServiceApiClient` - which would be doable, but potentially less efficient if you're publishing a lot of messages. If this is really a service that will only ever publish messages occasionally, then let me know and I can provide you sample code for that. Otherwise, I think it's really a matter of changing the GKE node config, which is something I don't know anything about. Will let you know when I hear back from folks internally - but at least we believe we understand the issue better now. Thanks so much for your diligence and insight in figuring it out!

**Comment by twgraham** [comment] 2021-05-21 00:55
Thanks @jskeet, I'd appreciate an sample code you have. I'll attempt to patch the service with it in the meantime until a more appropriate fix can be made to the GKE node.

It's not a high traffic service which could be the reason we see this and others don't - particularly if our service is not hit often out of peak hours.

It could also be people don't use the combination of windows, GKE, and grpc 😆

**Comment by jskeet** [comment] 2021-05-21 11:40
Sure.

Firstly, add a new dependency for an updated version of GAX (we need to update the PubSub library at some point to include this anyway, but it's not urgent):

```xml
<PackageReference Include="Google.Api.Gax.Grpc.GrpcCore" Version="3.3.0" />
```

Then change your dependency injection to inject a `PublisherServiceApiClient`:

```csharp
var grpcOptions = GrpcChannelOptions.Empty
    .WithKeepAliveTime(TimeSpan.FromMinutes(1))
    .WithCustomOption("grpc.keepalive_permit_without_calls", 1);
services.AddSingleton(new PublisherServiceApiClientBuilder { GrpcChannelOptions = grpcOptions }.Build());
```

(You may well find that you can change the keep-alive time to 5 minutes without any problems, although it's not going to be creating a huge amount of traffic anyway.) You'll want to inject the `TopicName` as a singleton too, probably.

Then to publish a message, you'd have something like this:

```csharp
string text = "The text you want to publish in the message";
var message = new PubsubMessage { Data = ByteString.CopyFromUtf8(text) };
await apiClient.PublishAsync(topicName, new[] { message });
```

Hopefully that makes sense - do let me know if you have any problems with it.

I'll close this issue now as I think we've got to the bottom of it (in terms of it not being in the library), but I'm chasing the underlying issue internally.

**Closed by jskeet** 2021-05-21 11:40 UTC
Labels: api: pubsub, needs more info, type: question

**Comment by jskeet** [comment] 2021-06-22 06:36
Just to close the loop on this - the PR referenced just above should fix this without you having to set a custom keepalive (once it's rolled out and you're on that version, of course).

Thanks so much for reporting it and bearing with us on this.
