### ISSUE TITLE
Retrieving custom event from Firebase console

### ISSUE THREAD

**Issue by vukasinpetrovic** [googleapis/google-cloud-dotnet#6734] opened 2021-07-12 18:58 UTC
We are struggling to retrieve any custom event from Firebase console. Custom event is logged and can be seen on Firebase. Custom metric is created for that event. But when we try to receive data via api call, we get no results (empty rows list). We tried many combinations with custom metrics and dimensions, but nothing seems to work. Below we'll attach images that better describe this problem. Any help would be much appreciated.

Platform: .NET CORE 3.1, windows & mac
API/NuGet: Google.Analytics.Data.V1Beta (v1.0.3 beta)

Here you can see that custom event is registered and logged properly in firebase console. APP_REMOVE event is the one we try to receive.
![image](https://user-images.githubusercontent.com/23005422/125340779-2bb4ec00-e353-11eb-85d2-3a8c24395ecb.png)

Here is custom metric that was created for that event.
![image](https://user-images.githubusercontent.com/23005422/125340850-3ff8e900-e353-11eb-89de-8bbf7d0145d3.png)

This is a c# function that calls the API
![image](https://user-images.githubusercontent.com/23005422/125341147-9534fa80-e353-11eb-98da-0488a42b7e25.png)

And this is a result from that call
![image](https://user-images.githubusercontent.com/23005422/125341318-cad9e380-e353-11eb-98e9-fe6d9e503545.png)

**Comment by jskeet** [comment] 2021-07-12 19:18
I'll have a look at this on Wednesday (I'm on vacation tomorrow) - but if it ends up being specific to the API rather than to the client library itself, I may not be able to help. (Maintainers of this repo know about the client libraries, but don't necessarily have knowledge of all APIs.)

**Comment by jskeet** [comment] 2021-07-14 07:29
Okay, looking at this again now... and I personally have no experience with Analytics and relatively little experience with Firebase. In particular, I don't know whether the *Google* Analytics API can be used to access *Firebase* Analytics, even if they're the same thing behind the scenes.

To rule out the client library, I'd suggest running the report "live" from here: https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport
I'm guessing that's the right method - your code doesn't actually show how you're making the request. It looks like it's calling a method called `RunGoogleAnalyticsRequest`, but that's not one we provide in the library - so presumably it's your own code that uses the library.

If calling the API "live" from the browser gives the same result (which I expect it will), please follow one of the [Google Analytics Data API support routes](https://developers.google.com/analytics/devguides/reporting/data/v1/help) or [Firebase Analytics support](https://firebase.google.com/support/troubleshooter/analytics).

If the API call from the browser *does* give you results, then that *would* suggest it's either a problem with the library or how you're using it - in which case please add a comment with the content of your `RunGoogleAnalyticsRequest` method.

(As a side note, it would be helpful to show code as text rather than images - in cases where we want to use the same code to reproduce the issue, it's a lot easier if we can copy/paste rather than having to retype everything, potentially accidentally fixing a typo we hadn't even noticed.)

I'll close this issue now as I don't expect it to be an issue with any code in the libraries in this repository - and because I don't have the expertise to help you further, I'm afraid. Of course, if it *does* look like it's the client library that's at fault, I'll reopen it when you've added more information about trying to use the API from the browser.

**Closed by jskeet** 2021-07-14 07:29 UTC
Labels: type: question
