### ISSUE TITLE
SIGSEGV on SpeechClient.LongRunningRecognizeAsync call under Alpine Linux (Docker)

### ISSUE THREAD

**Issue by vanufryiuk** [googleapis/google-cloud-dotnet#5120] opened 2020-06-26 14:40 UTC
#### Environment details

  - OS: Alpine Linux (Docker, mcr.microsoft.com/dotnet/core/sdk:3.1-alpine)
  - .NET version: .NET Core 3.1
  - Package name and version: Google.Cloud.Speech.V1 v2.0.0

#### Steps to reproduce

  1. Clone git@github.com:vanufryiuk/Google.Cloud.Speech.V1.SIGSEGV.git (https://github.com/vanufryiuk/Google.Cloud.Speech.V1.SIGSEGV)
  2. Copy your GoogleCredentials.json inside
  3. Run "docker-compose build"
  4. Run "docker-compose up"

**Comment by jskeet** [comment] 2020-06-26 15:05
I suspect this is a duplicate of the known libc compatibility issue with gRPC 2.x in Alpine.

See https://github.com/googleapis/google-cloud-dotnet/issues/4780#issuecomment-608304477 for a potential solution.

I can try reproducing it (and then applying the fix) next week, but it won't be today, I'm afraid, due to other commitments. If you could try that fix earlier, that would be very useful.

**Comment by vanufryiuk** [comment] 2020-06-26 15:27
@jskeet thank you. The workaround with libc6-compat=1.1.19-r11 works.
But I can't find any related issue in Alpine repos. Do you know if it exists?

**Comment by jskeet** [comment] 2020-06-26 15:30
Glad to hear it works.

I'm afraid I don't know much about the details of it, or whether there's any effort on the Alpine or gRPC side to fix things... it's all at least one level lower than I normally work :( I'll close this issue now that we've confirmed the workaround fixes it - I do hope eventually it will be unnecessary, of course.

**Closed by jskeet** 2020-06-26 15:30 UTC
Labels: type: question
