### ISSUE TITLE
FireStore listener as a service stop working after a day

### ISSUE THREAD

**Issue by nicksav** [googleapis/google-cloud-dotnet#2721] opened 2018-11-23 03:20 UTC
Version: Google.Cloud.Firestore-1.0.0-beta13 

Guys, I am having some issues with FireStore real time updates. I have deployed a web app to Azure Web Site. On a start up, this application subscribes to the updates in the FireStore users table.
`

            GoogleCredential googleCredential = googleCredential = GoogleCredential.FromJson(JsonConvert.SerializeObject(secret));
            var channel = new Grpc.Core.Channel(FirestoreClient.DefaultEndpoint.Host,
                googleCredential.ToChannelCredentials());

            FirestoreClient client = FirestoreClient.Create(channel);
            FirestoreDb db = FirestoreDb.Create(projectId: "myproject-2018", client: client);

            CollectionReference collection = db.Collection("users");

            FirestoreChangeListener listener = collection.Listen(async querySnapshot =>
            {
            })
`

All works perfect, but after a couple hours, or sometimes days, it just stop receiving updates without any errors. Is there any way for me to debug it to understand why?

**Comment by jskeet** [comment] 2018-11-23 06:42
When you say "without any errors" - what happens to the task exposed as `listener.ListenerTask`? Does that:

- Complete
- Stay uncompleted
- Become faulted

? That would be the first piece of interesting information.

In terms of further diagnostics, there's nothing particularly built into the library to help here, unfortunately. You could turn on gRPC tracing, but that would generate a huge amount of logging.

Does everything else in the application continue to work? In particular, are you doing other Firestore operations on the same `Channel` (or even with the same `FirestoreClient`)?

If we could work out a way of reproducing this in an isolated way, that would be ideal. Do you think having one console application which had basically the code you've already shown, and another that just updates a single user entry once every (say) 15 seconds, would be a good start? I'd be happy to create that and just leave it running.

**Comment by nicksav** [comment] 2018-12-04 10:51
Hey jskeet. Was working ok after some time?

**Comment by jskeet** [comment] 2018-12-04 11:43
Eek! I sincerely apologise - I dropped the ball on this one. I started it running on my laptop first, and of course that dropped the connection when the laptop went to sleep.

Will get it running on a desktop, writing to a file so I can see what's going on...

**Comment by jskeet** [comment] 2018-12-04 15:15
(It's been running for 4 hours now - no problems so far, but we'll see what happens over the next 24-48 hours...)

**Comment by nicksav** [comment] 2018-12-05 10:08
Yep, also deployed to Azure. Will provide link tomorrow. So if its running on Azure how to prevent from getting ServiceUnavailable error? Just to re-attach the listener to continue listening for changes?

**Comment by DenSmoke** [comment] 2018-12-05 11:05
I had the same issue but it disappeared by itself somehow. I mean listeners stopped to work without exception after about one day

**Comment by jskeet** [comment] 2018-12-05 11:11
@DenSmoke: I'm not quite sure I understand what you mean by "it disappeared by itself" - the issue disappeared, or the listener disappeared? If you still have listeners that are stopping reporting changes (but without the task failing), that's what we're trying to reproduce.

@nicksav: The *listener* should reattach itself on ServiceUnavailable errors (I think - it certainly does for *some* errors; I'd need to check exactly which). In my case it was the code making the change that failed with that error.

**Comment by DenSmoke** [comment] 2018-12-05 11:20
@jskeet I couldn't reproduce the issue again so "issue disappeared". It was on beta11

**Comment by jskeet** [comment] 2018-12-06 08:31
The new test has been running for 25 hours with no problems so far. That doesn't mean it won't happen eventually though...

**Comment by DenSmoke** [comment] 2018-12-07 12:10
Problem happen again in .NET Core 2.2 console app with Google.Cloud.Firestore beta14 on Ubuntu 18.04 running in Compute Engine f1-micro instance.

**Comment by pauloevpr** [comment] 2018-12-07 12:37
I have a similar issue. I am running a Asp.Net Core 2.1 Web API on Google Cloud App Engine. The FirestoreListener stops working eventually. I can't say it is precisely after 24 hours. It seems just random.

From my analysis so far, it seems to be an issue with Firestore backend rather than the Firestore .NET SDK. Firestore randomly fails when reading/writing documents. It is not just about the listeners.

For example. Yesterday my Asp.Net Core Web API had the following exception when getting a document snapshot:

Grpc.Core.RpcException: Status(StatusCode=PermissionDenied, Detail="Missing or insufficient permissions.")

I have seen this at least once every month.

That is not the only one. I also have this one randomly once in a while:

Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="The datastore operation timed out, or the data was temporarily unavailable.")

My conclusion is that, as a beta product, it is possible that Firestore backend randomly fails to serve requests for whatever reason.

For the specific listener issue, my workaround is simply to have a function triggered by a timer which will restore the listener as required.

**Comment by jskeet** [comment] 2018-12-07 12:57
Thanks for the updates everyone - and particularly for that extra detail, @pauloevpr.
My own test is still going strong after about 52 hours, so isn't giving any more information :(

I'll contact the Firestore internal team and point them at this issue. They may have some ideas about what's going on.

**Comment by jskeet** [comment] 2018-12-10 07:53
Internal feedback suggests this *may* be a gRPC issue rather than a server side issue. Obviously it being hard to reproduce doesn't help us :( (The test I started 5 days ago is still going strong...)

@pauloevpr: I've filed #2760 for the Unavailable issue. The PermissionDenied issue is odder. Have you seen it more than just the once? If you see it again, could you send me an email (jonskeet@google.com) with your project ID and a timestamp, and we'll look in the logs?

**Comment by nicksav** [comment] 2018-12-14 00:54
Ok left to run on Azure and again, stooped working after time. 
![pic](https://user-images.githubusercontent.com/9266365/49976676-a85e6e80-ff8e-11e8-870d-e3c7adc71709.png)

**Comment by jskeet** [comment] 2018-12-14 06:08
Thanks - will check mine!

**Comment by jskeet** [comment] 2018-12-14 07:02
@nicksav: Thanks very much for the log - that's interesting to see. Interestingly, my test failed, but in a different way: the process was aborted.

I realized that the Main method wasn't going to tell me the listener task status, either. I've changed it to:

```csharp
static void Main(string[] args)
{
    try
    {
        Task updatingTask = UpdateAsync(args[0]);
        Task listeningTask = ListenAsync(args[0]);
        listeningTask.Wait();
        Console.WriteLine("Listening task finished");
        updatingTask.Wait();
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
    }
}
```

I've restarted the test. I suspect eventually we'll need to capture gRPC detailed logs, but as lots of folks are now going on holiday, I suspect that'll be in 2019. Apologies that it's taking so long to work out what's going on here, but we'll get there eventually...

**Comment by DenSmoke** [comment] 2018-12-14 15:16
This issue with listeners started to happen suspiciously often. I had to restart our server 3 times today. Is there some good workaround to detect listener disfunction? I can restart listeners after some interval but this will consume operations quota

**Comment by DenSmoke** [comment] 2018-12-14 15:43
Thanks for explanation. I never awaited ListenerTask result so didn't see that exception was thrown. I can easily observe it now and restart listener on failure

**Comment by jskeet** [comment] 2018-12-14 15:50
@DenSmoke: Should I take it from that comment that you'd prefer not to test a speculative fix? (I *completely* understand if so - just making sure I've understood you correctly.)

I'm going to try that speculative fix now... (with a tiny bit of extra diagnostic code to observe when it's happened).

**Comment by DenSmoke** [comment] 2018-12-14 16:01
@jskeet Yes, you understood correctly. I have not enough time to test the fix now

**Comment by pauloevpr** [comment] 2018-12-14 16:18
@jskeet: Regarding the PermissionDenied error, Stackdriver reports that it has happened 10 times in the past 30 days. It was last seen 2 hours ago, btw. I will email you with addition details.

**Comment by jskeet** [comment] 2018-12-14 16:21
@pauloevpr: Thanks. I think it's probably worth opening a separate issue about that.

**Comment by pauloevpr** [comment] 2018-12-14 16:44
I have opened #2771 for the PermissionDenied error.

**Comment by nicksav** [comment] 2018-12-16 10:09
Hi @jskeet  
I am ok to get a test fix and deploy to Azure to let it running and test.

Thanks
Nick

**Comment by jskeet** [comment] 2018-12-18 11:55
I saw a failure yesterday and this morning which was unrelated (and which I've asked about internally). I *could* merge my expected fix in and do another release today; I don't believe it's *harmful*, and it would let others test over Christmas.

**Comment by jskeet** [comment] 2018-12-18 14:56
I've now released 1.0.0-beta15. I won't close this issue just yet, but your feedback would be much appreciated. (The only change compared with 1.0.0-beta14 is swallowing exceptions when closing the listener stream.)

Note that if you get an exception about "Server removed watch target" that's a separate issue - I've seen it twice so far today, but never before.

**Comment by jskeet** [comment] 2018-12-18 16:34
Note that until #2776 is fixed (and even after that, really), it's still worth watching the `ListenerTask` to detect failures.
I'll be looking at 2776 in the New Year.

**Comment by nicksav** [comment] 2018-12-28 02:54
hi guys
Can anybody provide a good code example on how to correctly handle exceptions and restart listener?

**Comment by DenSmoke** [comment] 2018-12-28 04:52
@nicksav the most simple way:
```C#
private async void ListenerRestarter(FirestoreChangeListener listener, Func<CancellationToken, Task> startListener, CancellationToken ct = default)
{
    try
    {
        await listener.ListenerTask.ConfigureAwait(false);
    }
    catch (Exception ex)
    {
        if (ex.GetType() != typeof(TaskCanceledException))
        {
            //handle exception
            await startListener(ct).ConfigureAwait(false);
        }
        else
            throw ex;
    }
}
```

**Comment by Thaina** [comment] 2019-01-02 05:54
Just to make it easier

```C#
private async void ListenerRestarter(FirestoreChangeListener listener, Func<CancellationToken, Task> startListener, CancellationToken ct = default)
{
    try
    {
        await listener.ListenerTask.ConfigureAwait(false);
    }
    catch (Exception ex)
    {
        if(ex is TaskCanceledException)
            throw ex;

        //handle exception
        await startListener(ct).ConfigureAwait(false);
    }
}
```

**Comment by DenSmoke** [comment] 2019-01-11 19:15
Something strange is going on today. My restarter catched these errors (time in UTC):
```
11.01.2019 8:53:46 FB reports listener error: RpcException Status(StatusCode=Aborted, Detail="The operation was aborted.")
11.01.2019 11:35:26 FB users reports listener error: RpcException Status(StatusCode=Aborted, Detail="The operation was aborted.")
11.01.2019 17:01:51 FB userLocations reports listener error: RpcException Status(StatusCode=Aborted, Detail="The operation was aborted.")
11.01.2019 18:33:09 FB orders reports listener error: RpcException Status(StatusCode=Aborted, Detail="The operation was aborted.")
```
Idk is this related to this issue or not

**Comment by jskeet** [comment] 2019-01-11 19:37
Odd indeed. I'm at a conference right now, but will look into it when I can.

**Comment by DenSmoke** [comment] 2019-01-16 10:54
@jskeet program is working on Compute Engine instance so I can't debug it. But I can modify exception catcher to log stack trace also

**Comment by jskeet** [comment] 2019-01-16 10:56
@DenSmoke: That would be handy, thanks. I've asked internally about whether we should add Aborted to the list of status codes to retry.

**Comment by jskeet** [comment] 2019-01-16 17:33
@DenSmoke: It looks like I should add Aborted to the list of server statuses to retry. I'll do that tomorrow.

**Comment by DenSmoke** [comment] 2019-01-17 06:38
@jskeet New errors with stack traces. What's interesting - they were thrown right after program start. Until January 11, there were almost no such errors, but now I see about 3 errors a day.
```
17.01.2019 6:21:40 FB orders listener error: RpcException Status(StatusCode=Aborted, Detail="The operation was aborted.")
   at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token)
   at Google.Cloud.Firestore.WatchStream.<>c__DisplayClass16_0.<<StartAsync>g__GetNextResponse|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Google.Cloud.Firestore.WatchStream.StartAsync()
   at Google.Cloud.Firestore.WatchStream.StartAsync()
   at DpTools.Firebase.ListenerRestarter(String collectionName, FirestoreChangeListener listener, Func`2 startListener, CancellationToken ct) in D:\a\1\s\DpTools\Firebase.cs:line 316

17.01.2019 6:21:40 FB reports listener error: RpcException Status(StatusCode=Aborted, Detail="The operation was aborted.")
   at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token)
   at Google.Cloud.Firestore.WatchStream.<>c__DisplayClass16_0.<<StartAsync>g__GetNextResponse|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Google.Cloud.Firestore.WatchStream.StartAsync()
   at Google.Cloud.Firestore.WatchStream.StartAsync()
   at DpTools.Firebase.ListenerRestarter(String collectionName, FirestoreChangeListener listener, Func`2 startListener, CancellationToken ct) in D:\a\1\s\DpTools\Firebase.cs:line 316
```

**Closed as completed** 2019-01-17 10:24 UTC
Labels: type: bug, priority: p2, api: firestore
