### ISSUE TITLE
FirestoreDb.Create and Query.Listen do not fail on invalid credentials

### ISSUE THREAD

**Issue by oofpez** [googleapis/google-cloud-dotnet#7174] opened 2021-09-16 11:20 UTC
FirestoreDb.Create() does not fail on invalid credentials

Regardless of whether the ChannelCredentials would allow access, it seems like no request is made to the database yet.
There also does not seem to be an easy call to validate that the connection is correct, and a listener set up to this database does not return a snapshot at all - it seems the only way to tell that the connection is not made is via a timeout on the callback

#### Environment details

  - OS: Windows/Linux
  - .NET version: net5.0
  - Package name and version: Google.Cloud.Firestore 2.4.0

#### Steps to reproduce

  1. Set up credentials file with access to a disabled project or with invalid credentials
  2. Set up code to connect to the collection in firestore
  

```
GoogleCredential googleCredential = GoogleCredential.FromFile(CredentialFilePath);
FirestoreClientBuilder builder = new() { ChannelCredentials = googleCredential.ToChannelCredentials() };
Database = FirestoreDb.Create(databaseConfiguration.ProjectId, builder.Build());

Query deviceQuery = Database.Collection("###/###")
deviceQuery.Listen(
snapshot =>
   {
   //Do things - this code is never reached if the connection is not made.
   });
```

**Comment by jskeet** [comment] 2021-09-16 11:27
It's not surprising to me that `FirestoreDb.Create` itself makes no RPCs.

I would suggest that the simplest way to test the connection would be to try to fetch a document - ideally one that you wouldn't expect to exist, so that it doesn't actually transfer any data.

For example:

```csharp
await Database.Document("ShouldNotExist/ShouldNotExist").GetSnapshotAsync();
```

That will return a "document missing" snapshot if the credentials are okay, but I'd expect it to throw an exception if they're not.

As an aside, there's a simpler way to build your client:

```csharp
Database = new FirestoreDbBuilder
{
    ProjectId = databaseConfiguration.ProjectId,
    CredentialsPath = CredentialFilePath
}.Build();
```

Now, I *am* surprised that `Listen` isn't failing - I'm going to mark this issue as a bug on those grounds, and I'll investigate it when I can. But it's not a bug that `FirestoreDb.Create` doesn't perform any RPCs, and without any RPCs it can't test the credentials.

**Comment by jskeet** [comment] 2021-09-20 10:01
I've looked into this now, and actually I believe it's okay: you just need to use the return value of `deviceQuery.Listen`, which you should do to monitor for other failures anyway.

So:

```csharp
Query deviceQuery = Database.Collection("###/###")
var listener = deviceQuery.Listen(snapshot => { ... });
await listener.ListenerTask;
```

... will fail if the authentication is invalid with:

> Unhandled exception. Grpc.Core.RpcException: Server removed target. Code: PermissionDenied Message: Missing or insufficient permissions.

I can't really give advice about where in your app you'd monitor that listener task, but if you add appropriate code to do so, that should be all you need.

Please let me know if this solves your problem, and I'll close this issue. (I'll change the type from "bug" to "question" now, as I believe it's working as intended. I should have recognized this last week, but I didn't get properly into it...)

**Comment by jskeet** [comment] 2021-09-24 06:49
Closing as "working as intended" - please comment if you wish me to reopen.

**Closed by jskeet** 2021-09-24 06:49 UTC
Labels: type: question, api: firestore

**Comment by oofpez** [comment] 2021-10-04 16:32
I did try this but I couldn't get the Listener Task to complete - it would just block on the await forever.
There might still be something broken but I'm not sure why you couldn't reproduce it.

I made use of the call you suggested when setting up the Database though, and that works.
So it's not an issue for me anymore, just giving my feedback.

**Comment by jskeet** [comment] 2021-10-04 16:35
Hmm... I'm surprised the listener task didn't complete as faulted immediately. I can share my code if you'd like - or if you have a minimal example that you could share, that would probably be even more helpful (and put the work onto me rather than you - and it does belong with me, of course). I suspect it may well depend on details of the context.
