### ISSUE TITLE
Transaction failing due to error "The service is temporarily unavailable. Please retry with exponential backoff."

### ISSUE THREAD

**Issue by mmiro1** [googleapis/google-cloud-dotnet#12669] opened 2024-04-30 07:46 UTC
#### Environment details

  - OS: Hosting on a Cloud Run
  - .NET version: 6.0
  - Package name and version: Google.Cloud.Firestore from Google LLC 3.4.0

#### Steps to reproduce

Sadly no steps.

#### Description

A couple of weeks ago, I have started to receive errors with Firestore transactions with the following message:

`
The referenced transaction has expired or is no longer valid. (at Google.Api.Gax.Grpc.ApiCallRetryExtensions.b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n at Google.Cloud.Firestore.WriteBatch.CommitAsync(ByteString transactionId, CancellationToken cancellationToken)\n at Google.Cloud.Firestore.FirestoreDb.RunTransactionAsync[T](Func 2 callback, TransactionOptions options, CancellationToken cancellationToken)\n at Google.Cloud.Firestore.FirestoreDb.RunTransactionAsync[T](Func 2 callback, TransactionOptions options, CancellationToken cancellationToken))
`

I don't think there is a problem in the code, since some transactions that fail are pretty simple and have not been modified in a long time. I also have seen that these failures occur during small periods of time (see times below), which makes me think that it is something related to the moment of the request/the availability of the service.

2024-04-20 05:21:24.737 CEST
2024-04-20 06:18:13.679 CEST
2024-04-20 16:01:29.846 CEST
2024-04-20 16:01:43.408 CEST
2024-04-20 16:01:57.471 CEST
2024-04-20 16:02:31.865 CEST
2024-04-20 16:02:57.235 CEST

We have activated the Audit logs and have seen that transactions are failing due to this error:
  The service is temporarily unavailable. Please retry with exponential backoff.
After that, the transaction retries but fails due to the previous error:
  The referenced transaction has expired or is no longer valid.

The first error occurs very often, what could be causing this issue? Could it be something related to the availability of Firestore, if so, is there any way to upgrade the Firestore to sustain more movement?

Errors "The referenced transaction has expired or is no longer valid." catched by the server:
![image](https://github.com/googleapis/google-cloud-dotnet/assets/91881285/bd191347-f220-47ec-b438-b3d864bfa432)
Errors "The service is temporarily unavailable. Please retry with exponential backoff." catched by the Audit logs:
![image](https://github.com/googleapis/google-cloud-dotnet/assets/91881285/6b1c3160-5390-4f60-b38e-133e8d799f8b)

Stacktrace from today (2024-04-30 05:02:49.338 CEST):
`
"Message": "Status(StatusCode=\"InvalidArgument\", Detail=\"The referenced transaction has expired or is no longer valid.\")",
    "Data": {},
    "InnerException": null,
    "HelpLink": null,
    "Source": "System.Private.CoreLib",
    "HResult": -2146233088,
    "StackTrace": "   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0 2.<<WithRetry>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at Google.Cloud.Firestore.WriteBatch.CommitAsync(ByteString transactionId, CancellationToken cancellationToken)\n   at Google.Cloud.Firestore.FirestoreDb.RunTransactionAsync[T](Func 2 callback, TransactionOptions options, CancellationToken cancellationToken)\n   at Google.Cloud.Firestore.FirestoreDb.RunTransactionAsync[T](Func 2 callback, TransactionOptions options, CancellationToken cancellationToken)"
`

On another topic, we have experienced a ton of errors, a total of 1180, on 27-04-2024 between 7:00 am and 8:00 am CEST. The error was "Error connecting to subchannel." and it happened when trying to read a document. I know it is not the topic of the issue, but I am not sure if it is related to the problem. It looks like a Firestore was failing on that time but I don't know where I can check the status of Firestore, since there is no Firestore on the status page (https://status.firebase.google.com/).

Thank you in advance.

**Comment by jskeet** [comment] 2024-04-30 08:35
The Firestore status is on the Cloud dashboard at https://status.cloud.google.com/ - but there's no sign of an outage there.

I wonder whether there's some intermittent connectivity issue between your code and GCP - could you give more context about:

- Where your code is running
- What .NET platform you're using
- What authentication credentials you're using
- What library version / versions you're using

(If you're able to provide a complete console app that demonstrates the problem at least occasionally, that would be really helpful so that I could try to reproduce it myself.)

Additionally, if you're able to add your own local logs to record when you *start* using each transaction ID, it would be interesting to know how much time elapses between that and the failure.

My guess is that eventually you'll need to talk to Firestore support - the maintainers of this repository are only responsible for client libraries, and these all sound like server-side errors which I *suspect* aren't related to the client libraries themselves, but the more information we can collect before then, the better.

**Comment by mmiro1** [comment] 2024-04-30 09:39
Thanks for the quick response! I am trying to create a small sample project to reproduce the error, but I haven't had luck yet.
Meanwhile I am looking the Audit logs to try to undestand what is happening and located one of these errors in order to find the time elapses you commented.

I have found this error in which the transaction opens at 44.187, fetches documents on 44.206, fails to commit the changes due to "The service is temporarily unavailable. Please retry with exponential backoff." error at 44.236, and then fails the commit again with the error "The referenced transaction has expired or is no longer valid." at 49.303. Between both commits there is no movement of that transaction, but 3 other transactions are opened and completed successfully.

Does it make sense? Why does the read work but not the commit? How does the library behaves when getting the "The service is temporarily unavailable. Please retry with exponential backoff." error? At this point any guidance is apreciated.

Just to clearify the logs where filtered by the transaction id and where also showing Begin transaction methods, since those are not identified by the transaction id (which I found strange).
![image](https://github.com/googleapis/google-cloud-dotnet/assets/91881285/12b105e1-86b3-48ae-b950-0012cd212d98)

Thank you again.

**Comment by jskeet** [comment] 2024-04-30 09:59
Hmm... I'd expect `FirestoreDb.RunTransactionAsync` to rerun all of the user code *in a new transaction*. The logic here did change *relatively* recently (in #11564). You might want to *try* downgrading Google.Cloud.Firestore to version 3.4.0 (which didn't include the change). We previously never actually backed off (there was an unused `backoff` variable). It's unclear whether that's actually relevant here though.

Another possibility is that what you're seeing is the purely-internal retry for Commit, within Google.Cloud.Firestore.V1 - which we should probably disable, in order to retry the whole transaction without retrying the Commit call itself. I wonder whether that's actually the problem.

Can you add your own logging that will tell use whether your user code is being called multiple times?

For the logs you've shown, is this with lots of requests coming in, so some of these could just be completely concurrent? At the moment there's a bunch of confounding factors that mean we're guessing more than I'd like to :(

**Comment by mmiro1** [comment] 2024-04-30 10:15
Hey! Really appreciating the help. I will add the log in the transaction logic and keep an eye on it. 

Also, just to clarify I am not fully updated on the Google.Cloud.Firestore version, I am currently on the version 3.4.0, which you asked me to downgrade. I was thinking on updating to the latest to see if it has something to do with the problem, but I wanted to collect as much data as posible before doing so.

I will get back to you with the data once I got it.

**Comment by jskeet** [comment] 2024-04-30 10:19
Ah, interesting - sorry, I stupidly didn't check the version you included in the first comment. That's good to know. Will be interested to see what happens with the extra logging. It might be worth sticking to the old (3.4.0) version for now, just to avoid changing too much at a time, but we'll see.

Do your logs show the status codes for the two failures, by the way? (I wonder whether we're not actually doing any of the "whole transaction" retry, if Commit is retrying internally and ending up with an invalid transaction reference. I don't know how long transaction references normally stay valid for.)

**Comment by mmiro1** [comment] 2024-04-30 10:31
No problem. I actually have the codes:
```
The service is temporarily unavailable. Please retry with exponential backoff. -> Code: 14
The referenced transaction has expired or is no longer valid. -> Code: 3
```

Regarding the transaction times, I understood that the transaction is valid during 270 seconds. In the documentation it says that "270 seconds, with a 60-second idle expiration time" (https://firebase.google.com/docs/firestore/quotas#writes_and_transactions), which creates me more doubts on why the transaction expires.

**Comment by jskeet** [comment] 2024-04-30 10:44
For the codes (from [code.proto](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto)): 14=UNAVAILABLE, 3=INVALID_ARGUMENT - which makes sense.

The [default retry configuration for commit](https://github.com/googleapis/googleapis/blob/master/google/firestore/v1/firestore_grpc_service_config.json) will time out after a minute - well before the 270 seconds, but I guess it's feasible to hit the idle expiration time.

Is it possible that the logs for "the referenced transaction has expired" are actually from a transaction that started 270 or 60 seconds earlier? It would be easy to miss that in busy logs...

(We'll get there eventually...)

**Comment by mmiro1** [comment] 2024-04-30 11:07
As you said, it is very dificult to know the begining of a transaction since there are a lot going on, and the log does not provide a transaction id for the BeginTransaction method. I asumed that it would be the one closer to the Reading of the documents but I could be wrong.

I hope that with the added log in the transaction logic, I will be able to detect exactly where it starts.

On another topic, I have been thinking that the retry took to much time and the transaction expired before being able to retry. Is there something else that could be invalidating it?

**Comment by jskeet** [comment] 2024-04-30 11:09
> On another topic, I have been thinking that the retry took to much time and the transaction expired before being able to retry. Is there something else that could be invalidating it?

When you say "the retry took too much time" do you mean your code within the retry? (If you can tell me a bit more about what you're doing, I'll try to reproduce this myself.)

> Is there something else that could be invalidating it?

Not that I know of - but that's really not my area of expertise :(

**Comment by jskeet** [comment] 2024-04-30 14:28
> I meant more the backoff time that the package is giving to Firestore to respond. 

Right. If it *is* taking more than a minute, that's definitely a bug. I suspect it's not, but until we can see reasonably definitive logs for a single transaction, it'll be hard to say.

One thing you could do to add more logging is to set an `ILogger` in `FirestoreDbBuilder` when creating your `FirestoreDb`. For example:

```csharp
var loggerFactory = LoggerFactory.Create(builder =>
{
    builder.AddSimpleConsole();
    builder.SetMinimumLevel(LogLevel.Trace);
});

var db = new FirestoreDbBuilder
{
    Logger = loggerFactory.CreateLogger("Firestore"),
    ProjectId = "..."
}.Build();
```

(You might want to use Google.Cloud.Logging.Console as a console log formatter to get structured logs.)

That way you'll see the underlying API calls being logged, which could help.

**Comment by mmiro1** [comment] 2024-05-02 07:40
Good morning! Sorry for the late reply. I have more details on the timing of the transaction, one example:

2024-04-30 23:30:22.333 -> [Server Log] Request made (HTTP post)
2024-04-30 23:30:22.441 -> [Audit Log] Potential BeginTransaction
2024-04-30 23:30:22.448 -> [Audit Log] Transaction Get
2024-04-30 23:30:22.469 -> [Custom Log] Log in transaction internal logic
2024-04-30 23:30:22.579 -> [Audit Log] Transaction first error (The service is temporarily unavailable. Please retry with exponential backoff.)
2024-04-30 23:30:22.663 -> [Audit Log] Transaction second error (The referenced transaction has expired or is no longer valid.)
2024-04-30 23:30:22.684 -> [Custom Log] Server detects the error and logs it

The logic is only excetued once and all the operation takes less than a second. Does this give you any valuable data?
I also tested the transaction logic and executes in a second or less.

I will also try to add the logs you commented, but aren't those like the Audit Logs?

**Comment by jskeet** [comment] 2024-05-02 07:54
> I will also try to add the logs you commented, but aren't those like the Audit Logs?

The audit logs are recorded server-side. The logs I've shown are client-side logging.

> The logic is only excetued once and all the operation takes less than a second. Does this give you any valuable data?

Well, it strongly suggests that the transaction *hasn't* actually "expired" - but probably just become invalid due to being used in a commit that failed for the internal error.
I think I *should* be able to write a sample that disables the "internal" retry configuration, if you'd be able to test that. It'll be later today or maybe even tomorrow though due to the other things I've got on. If that works, I can fairly easily change the code to do that by default.

**Comment by mmiro1** [comment] 2024-05-02 08:07
When you say:
> I think I should be able to write a sample that disables the "internal" retry configuration
Does it mean removing the retry completely? Or just the retry without reexecuting the logic? I would like to keep the retry, since I prefer not having to prompt the client with a retry message.

I don't feel very comfortable testing things on production (where I have these errors), but if you can create that sample I would likely test it on my other environments before putting it on production, which would delay the results.

I also think, you mentioned that the new version of the package did retry with backoff. Should I try upgrading to see if the problem is there?

**Comment by jskeet** [comment] 2024-05-02 08:25
> Does it mean removing the retry completely?

No, just the "inner" retry which will make a second Commit RPC if the first fails - but that's a bug, I believe. Basically the retry should be "of the whole transaction", an "outer" retry.
My change would still have the "outer" retry... which I believe isn't actually being used at all, because the failure we end up with from the "inner" retry is a non-outer-retriable one, basically.

However (there are lots of layers to this) it looks like the "outer" retry *still* wouldn't end up firing, because the very first RPC error is UNAVAILABLE, which isn't deemed retriable. Basically I *suspect* it would fail with the initial "The service is temporarily unavailable".

I'll need to talk to colleagues about whether the "outer" retry *should* actually retry the whole transaction on UNAVAILABLE.

> I don't feel very comfortable testing things on production (where I have these errors), but if you can create that sample I would likely test it on my other environments before putting it on production, which would delay the results.

I completely understand not wanting to test in production - but we really need some way of being able to reproduce the problem in a test environment. Have you been able to reproduce in an isolated way at all?

> I also think, you mentioned that the new version of the package did retry with backoff. Should I try upgrading to see if the problem is there?

You could do so, but given the logs we've seen so far, I don't think that would have any impact.

**Comment by jskeet** [comment] 2024-05-02 08:37
Looking at some internal design docs, it looks like the "outer" retry should be happening on more status codes, including both UNAVAILABLE and RESOURCE_EXHAUSTED.

So I think the fix should be:

- Disable inner Commit retries (and possibly other RPCs)
- Retry on more status codes in the outer retry

That's easy to implement - I just wish I had a good way of reproducing the current issue you're seeing so that I could be more confident that it'll fix the issue.

Do you know what proportion of your transactions are failing in this way, and what level of concurrency you usually have? (I could easily write code to just execute one transaction per second for hours at a time, but I don't know how representative that would be.)

**Comment by mmiro1** [comment] 2024-05-02 09:08
I haven't had the luck to reproduce it yet, I am starting to focus more on simplifing the transaction logic and analysing the logs. But I have some data on the proportion of transactions that are failing in this way.

Some examples closing on the time interval (from the 2024-04-30):

Period of 5 minutes: 1.27%
- Time = 11:30:00 pm
- Transactions opened = 392 
- Errors = 5

Period of 1 minute: 3.37%
- Time = 11:32:00 pm
- Transactions opened = 89
- Errors = 3

Period of 30 seconds: 5.12%
- Time = 11:32:00 pm
- Transactions opened = 39
- Errors = 2

Period of 10 seconds: 12.5%
- Time = 11:32:10 pm
- Transactions opened = 16
- Errors = 2

Generally speaking on the last 2 days there has been 202.467 transactions of which 10 have failed.

**Comment by jskeet** [comment] 2024-05-02 09:15
Thanks, that's helpful. Can I check which region your code is running in? That may be relevant. (It's odd that you're getting that many failures at all, to be honest, even leaving aside the retry issue.)

It does sound like it should be pretty clear if we fix it.

**Comment by mmiro1** [comment] 2024-05-02 10:41
The region is us-central1. 

Btw, on the previous message I only counted the transactions that failed with the retry error causing "The referenced transaction has expired or is no longer valid.". But the Audit Logs, in the same period of time than before, have catched ~30 errors of "The service is temporarily unavailable. Please retry with exponential backoff." of which 10 didn't recover. I really don't know if that is an expectable amount of fails.

**Comment by jskeet** [comment] 2024-05-02 10:44
> I really don't know if that is an expectable amount of fails.

Me either - but at least there are enough that we should be able to tell that the retry is working, when we've fixed it. Thanks for your patience while we get to the bottom of this.

**Comment by jskeet** [comment] 2024-05-03 02:55
I'm pretty certain the fix in #12684 will fix this. I'll do a new new release tomorrow.

**Closed** 2024-05-03 02:54 UTC

**Comment by mmiro1** [comment] 2024-05-03 06:23
Thank you! I will try it as soon as it is live. Will you create a new version in the NuGet packages?

**Comment by jskeet** [comment] 2024-05-03 06:52
Yes, that's what I meant.

**Comment by jskeet** [comment] 2024-05-03 16:58
Version 3.7.0 has just been released. (It may take a while to get indexed by nuget.org.) Please do let us know if you still see problems (or, conversely, let us know if it's resolved as we expect!).

**Comment by mmiro1** [comment] 2024-05-09 14:29
Hey @jskeet!
Just so you know we have been testing this week the update on our development branch, and now, we have already push it to production. So far so good, I will keep you updated.

**Comment by jskeet** [comment] 2024-05-09 14:57
So glad to hear that! Thanks for letting me know :)

**Comment by mmiro1** [comment] 2024-05-14 10:36
Hey @jskeet !
Just wanting to let you know that it looks like the error is not occurring anymore, so nice fix! 
I still see errors of "The service is temporarily unavailable. Please retry with exponential backoff." on the audit logs, ~15 a day, and I think that is something related on the Firestore end, but for now it is a more or less acceptable rate.
Thank you again, you were very helpfull.
