### ISSUE TITLE
Unable to send logs using TimedBuffer if aggregated logs size exceeds 10MB

### ISSUE THREAD

**Issue by CommitedSajmon** [googleapis/google-cloud-dotnet#8556] opened 2022-06-06 07:16 UTC
#### Environment details

  - OS: Windows
  - .NET version: .NET 6
  - Package name and version: Google.Cloud.Diagnostics.Common (4.4.0)

I am not able to send log messages to Cloud Logging using `ILogger<>` if logs size exceed **10Mb** within defined `bufferWaitTime`.
Lets say that my application receives a burst of data that we have to log, so within a second I have to log 20Mb of data. 
It's not possible to achieve that using current library and TimedBuffer what is more it was extremely hard to debug what is causing the issue even with setting : 
`retryOptions: RetryOptions.Retry(exceptionHandling: ExceptionHandling.Propagate, bufferOverflow: BufferOverflow.ThrowException, retryAttempts: 0),`

I expected that eventually exception will be propagated but it is suppressed in [TimedBufferingConsumer](https://github.com/googleapis/google-cloud-dotnet/blob/ffa9c8456626be0270836428b7ff19408e8c9d2d/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/TimedBufferingConsumer.cs#L46), maybe exception propagation settings should be taken into account here as well? 

I've noticed logging API quota in the[ Logging API quotas and limits](https://cloud.google.com/logging/quotas)
| Category | Maximum value|
| --- | ----------- |
| Size of an [entries.write](https://cloud.google.com/logging/docs/reference/v2/rest/v2/entries/write) request | Maximum 10 MB|

then I wanted to make sure that it's causing the issue in my case, so I wrote simple asp net core app:
```c#
var app = builder.Build();

app.MapGet("/", (ILogger<Program> logger, int? messages) =>
{
    messages ??= 0;
    using (var scope = logger.BeginScope(new Dictionary<string, object> { { "messages", messages } }))
    {
        var result = Parallel.ForEach(Enumerable.Range(0, messages.Value), (s) =>
        {
            logger.LogDebug(s + ". Lorem ipsum dolor sit amet, consectetur adipiscing elit, " +
                    "sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. " +
                    "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat." +
                    "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. " +
                    "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.");
        });
    }

    return "Completed";
});

app.Run();
```

When `messages ` parameter is like ~9000, logs don't reach cloud logging. For everything below 8000 - logs reached the Cloud Logging. 

Then I wrote a simple LoggingDecorator to intercept logging consumer: 

```c#
    public class LoggingClientDecorator : LoggingServiceV2Client
    {
        private readonly LoggingServiceV2Client _decorated;

        public LoggingClientDecorator() 
        {
            _decorated = new LoggingServiceV2ClientBuilder().Build();
        }

        public override WriteLogEntriesResponse WriteLogEntries(WriteLogEntriesRequest request, CallSettings callSettings = null)
        {
            var size = request.CalculateSize();
            return _decorated.WriteLogEntries(request, callSettings);
        }
    }
```
and assigned this decorator while registering Logging :

```
 builder.AddGoogle(new LoggingServiceOptions
                {
                    Client = new LoggingClientDecorator(),
                    .....
                }
```

Finally I was able to get the exception:

`Status(StatusCode="InvalidArgument", Detail="Request payload size exceeds the limit: 10485760 bytes.", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1654499168.841000000","description":"Error received from peer ipv4:***","file":"..\..\..\src\core\lib\surface\call.cc","file_line":953,"grpc_message":"Request payload size exceeds the limit: 10485760 bytes.","grpc_status":3}")`

I expected the library to split the Request to smaller chunks if it's too big, but if within defined `bufferWaitTime` logs exceed 10MB it seems like there is nothing I can do to make logs reach the Cloud Logging. The only thing that comes to my mind is to enhance above decorator to do the split on my own.

**Comment by amanda-tarafa** [comment] 2022-06-06 09:36
There are two aspects to your question here:

The size of the write request:

- As you've found out, there's a limit in the size of the `entries.write` request (10MB).
- And no we don't split buffered entries in chunks when the whole request would exceed this size. This is simply because we haven't seen enough demand for it (you are the first person to run into this limit issue as far as I can remeber). I'll keep an eye out and if it becomes more of a problem, we'll reprioritize.
- What you can inmediately do is set a lower time span for the timed buffer to be flushed through `BufferOptions` (let me know if you need an example and I can share one). Default wait time is 5 seconds.

The propagation of the exception in the TimedBuffer:

- This has been on TODO for a while (see https://github.com/googleapis/google-cloud-dotnet/blob/ffa9c8456626be0270836428b7ff19408e8c9d2d/apis/Google.Cloud.Diagnostics.Common/Google.Cloud.Diagnostics.Common/TimedBufferingConsumer.cs#L46-L50 and #2182).
- The main problem is that  throwing the exception in a separate thread (the timer thread) may inmediately crash the application, and that's something we don't want to do even if the library is configured to propagate exceptions (i.e. "propagate exceptions" is not the same as "crash the application").
- What I can do here is evaluate adding a very specific option for throwing `TimedBuffer` exceptions that is set on `BufferOptions` and not on `RetryOptions` and add documentation to explain the difference and to carefully use the option for `TimedBuffer`, i.e. only for diagnostics purposes. Let me know if that would work for you and I'll reopen #2182 and add a note for this approach to be evaluated. To set expectations I don't expect to get around to actaully doing any of it until after a couple of weeks at least.

**Comment by amanda-tarafa** [comment] 2022-06-06 09:45
Another alternative for working around the write request limist is to use the SizedBuffer instead of the default TimedBuffer. The SizedBuffer default size is ~512Kb so you have room to increase the size there.

**Comment by CommitedSajmon** [comment] 2022-06-06 10:10
Thank you @amanda-tarafa for prompt reply. 

- **The size of the write request**:

I tried to set a lower timespan for `TimedBuffer `but it's not robust enough for my app. I would probably need to set it to milliseconds so that it runs nearly all the time to make sure I don't exceed 10MB between flushes. I also don't want to run in that frequently as I don't expect to have that amount of logs all the time. The concern here is also that all logs are dropped not only these which exceed the buffer, so I experienced loss of a lot of logs. 
It seems that for the time being I can either implement splitting on my own or use `SizedBuffer`.

- **The propagation of the exception in the TimedBuffer:**

I see your point and I thoroughly agree with you, but the options to configure exception propagation are very misleading, it was really hard to find out why it's not working in my case (I expected the exception to be propagated so I assumed the issue is somewhere else). Different options for `TimedBuffer` makes sense, you can even supply `Action<Exception>` as an option so that it's up to consumer how to preview/log it.

**Comment by amanda-tarafa** [comment] 2022-06-06 11:21
> The concern here is also that all logs are dropped not only these which exceed the buffer, so I experienced loss of a lot of logs.

I think you mean "which exceed the buffer" => "which make the request go over the limit". Note that the TimedBuffer is not size limited. This is an API constraint that you are running into.

This might make for a feature request for the Logging API itself (only drop the entries that make the request reach the size limit), try with their [Support channels](https://cloud.google.com/logging/docs/support). Although I wouldn't be surprised if they cannot process the over the limit requests at all, and that's why all the entries get dropped, or simply that they don't want to make a decision on which entries to drop, which is entirely reasonable.

If this becomes a problem for more users we'll evaluate what can be done client side. For the time being, yes SizedBuffer or splitting yourself seem to be the best options for you. I'm sorry we cannot help further.

Also, we should be releasing a beta of [Google.Cloud.Logging.Console](https://github.com/googleapis/google-cloud-dotnet/tree/main/apis/Google.Cloud.Logging.Console) this week which might work for you, depending on where you are running and whether you are using other Google.Cloud.Diagnostics components or not.

> The propagation of the exception in the TimedBuffer:

Yes, I fully understand the confusion and the difficulty you faced. I'll reopen #2182 and leave a note to see what we can do there. I like your idea of taking an action... let's see. Again, I won't get to it anytime soon, but as long as the issue is opend it will be on our radar.

I'll close this issue now as there's not much more we can do here. Of course create new issues if you run into other problems.

**Closed by amanda-tarafa** 2022-06-06 11:21 UTC
Labels: type: question, api: logging

**Comment by CommitedSajmon** [comment] 2022-06-06 11:42
Thanks for mentioning [Google.Cloud.Logging.Console](https://github.com/googleapis/google-cloud-dotnet/tree/main/apis/Google.Cloud.Logging.Console), I'll definitely take a look as it might work as well.
