### ISSUE TITLE
Cannot create TMX Glossary using Google.Cloud.Translate.V3 

### ISSUE THREAD

**Issue by andreaGhisa** [googleapis/google-cloud-dotnet#5393] opened 2020-10-01 10:53 UTC
#### Environment details

  - OS: Windows 10 Enterprise
  - .NET version: 4.8
  - Package name and version: Google.Cloud.Translate.V3

#### Steps to reproduce
I also open this Stackoverflow thread: https://stackoverflow.com/questions/63919102/cannot-create-tmx-glossary-using-google-cloud-translate-v3-in-c-sharp

  1. Download the latest version of the Google.Cloud.Translate.V3
  2. Try to create a glossary using a TMX File
  3. TMX source language = ro, target language = en (see file attached)
[ro-en-simple.zip](https://github.com/googleapis/google-cloud-dotnet/files/5311307/ro-en-simple.zip)
  4. Code sample
```
var glossary = new Glossary
{
    GlossaryName= new GlossaryName(ProjectName, Location, GlossaryId),
    LanguagePair = new Glossary.Types.LanguageCodePair
    {
        SourceLanguageCode = sourceLanguage,
        TargetLanguageCode = targetLanguage
    },
    InputConfig = new GlossaryInputConfig
    {
        GcsSource = new GcsSource
        {
            InputUri = GlossaryPath
        }
    }
};

var glossaryResponse = _translationServiceClient.CreateGlossary(new LocationName(ProjectName, Location).ToString(), glossary);
```
Error message:
Status(StatusCode=Internal, Detail="Failed to deserialize response message.")
StackTrace:
```
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.Translate.V3.TranslationService.TranslationServiceClient.CreateGlossary(CreateGlossaryRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.<>c__DisplayClass10_0.<WithCallSettingsOverlay>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Cloud.Translate.V3.TranslationServiceClientImpl.CreateGlossary(CreateGlossaryRequest request, CallSettings callSettings)
   at Google.Cloud.Translate.V3.TranslationServiceClient.CreateGlossary(LocationName parent, Glossary glossary, CallSettings callSettings)
   at Sdl.Community.MtEnhancedProvider.GoogleApi.GoogleV3Connecter.CreateGoogleGlossary(LanguagePair[] languagePairs)
```

 
![image](https://user-images.githubusercontent.com/16224379/94800554-6dd8f680-03ed-11eb-9527-07d79a2cbcbd.png)

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jskeet** [comment] 2020-10-01 11:47
Okay, I can't reproduce the issue, so I've created an absolutely complete application:

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Cloud.Translate.V3" Version="2.0.0" />
  </ItemGroup>
</Project>
```

Application:

```csharp
using Google.Api.Gax.ResourceNames;
using Google.Cloud.Translate.V3;
using System;

class Program
{
    static void Main(string[] args)
    {
        if (args.Length != 3)
        {
            Console.WriteLine($"Please provide three command-line arguments: <project-id> <location> <storage-uri>");
            return;
        }
        string projectId = args[0];
        string location = args[1];
        string storageUri = args[2];
        string glossaryId = "glossary-" + Guid.NewGuid();

        var client = TranslationServiceClient.Create();
        var glossary = new Glossary
        {
            GlossaryName = new GlossaryName(projectId, location, glossaryId),
            LanguagePair = new Glossary.Types.LanguageCodePair
            {
                SourceLanguageCode = "ro-RO",
                TargetLanguageCode = "en-US"
            },
            InputConfig = new GlossaryInputConfig
            {
                GcsSource = new GcsSource
                {
                    InputUri = storageUri
                }
            }
        };

        var response = client.CreateGlossary(new LocationName(projectId, location), glossary);
        Console.WriteLine("Polling until completed");
        var result = response.PollUntilCompleted();

        Console.WriteLine($"Glossary result: {result.Result}");
    }
}
```

I ran with:

```sh
dotnet run -- myproject-id us-central1 gs://my-bucket-name/ro-en-simple.tmx
```

Result:

```text
Polling until completed

Unhandled Exception: Google.LongRunning.OperationFailedException: Can't create glossary. There are conflicting entries. Number of conflicting entries: 31. Ratio of conflicting entries: 0.0971787
   at Google.LongRunning.Operation`2.get_Result()
   at Program.Main(String[] args) in [...] Program.cs:line 41
```

Please could you try the same code, and see what result you get? If you get the same result, your issue may be to do with dependencies - if you could provide a similar SDK-style project file showing all the dependencies you have, that would help. (In particular, it's interesting that it's failing to deserialize the `Operation` itself...)

**Comment by andreaGhisa** [comment] 2020-10-01 12:57
Thank you Jon Skeet for the code sample. 

I've created the sample application outside of my project and I confirm that the error message received is the same as in your code sample:
`Can't create glossary. There are conflicting entries. Number of conflicting entries: 31. Ratio of conflicting entries: 0.0971787`

I'll try to give you a context about the application I'm building. Is a  class library which is hosted in the desktop application. Basically is a plugin for a large desktop application.

After I've downloaded the NuGet package and I wanted to create the translation service client I've received the following error:
`Could not load file or assembly 'Google.Apis.Auth, Version=1.21.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The system cannot find the file specified.`

When I took a look at what version of the Api.Auth I actually have is: 1.44.1.0 (See zip attached with all the dependencies loaded by the application) 
[Uploading Dependencies.zip…]()
Manually I've decompliled all the dependencies and I saw that Grpc.Auth is using 1.21.0 
![image](https://user-images.githubusercontent.com/16224379/94811391-f9f31a00-03fd-11eb-8642-63e139c1d935.png)

For this plugin the conventional binding redirect is not working because that should be added in the main application which I don't have access to. So I had to fix this problem within my solution. 

What I did was to Resolve the assemblies programatically see code [attached](https://github.com/sdl/Sdl-Community/blob/Andrea_master/MT%20Enhanced%20Provider/Sdl.Community.MtEnhancedProvider/Helpers/AssemblyResolver.cs)

This did the trick I was able to authenticate, translate, get the languages, create the csv glossary, however I'm not able to create the tmx glossary and fails with the error provided above.

**Comment by jskeet** [comment] 2020-10-01 13:11
Okay, I *suspect* the problem isn't actually in Google.Apis.Auth, but in another dependency - although anything's possible.

It would be really helpful if you could provide a full list of *all* the assembly versions (for anything to do with Google or gRPC, at least) that you're using at execution time. Then we can try to work out the incompatibility.

You might want to try updating to Google.Api.Gax.Grpc.GrpcCore version 3.2.0, with all its dependencies - that should provide a fairly recent slate of dependencies. But it's going to be really hard to help you without being able to reproduce this.

**Comment by andreaGhisa** [comment] 2020-10-02 06:56
This is the list of the dependencies version loaded from memory:

Google.Api.Gax, Version=3.0.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47
Google.Api.Gax.Grpc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47
Google.Api.Gax.Grpc.GrpcCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47
Google.Apis.Auth, Version=1.44.1.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab
Google.Apis.Core, Version=1.44.1.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab
Google.Apis, Version=1.44.1.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab
Google.Cloud.Translate.V3, Version=2.0.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0
Google.LongRunning, Version=2.0.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0
Google.Protobuf, Version=3.11.4.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604
Grpc.Auth, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad
Grpc.Core.Api, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad
Grpc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad
grpc_csharp_ext.x86
System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

Before using Assembly resolve I've tried to manually go on NuGet and update all the references to the latest version, it failed because thre were libraries which pointed to the same library but with different version. One pointed to an old version the other one pointed to an early version. 

I could not make them work taking them directly from NuGet one by one and trying to find version which is compatible with the other dependencies.
![image](https://user-images.githubusercontent.com/16224379/94896048-4d647700-0495-11eb-9453-ff1733094dbb.png)

**Comment by jskeet** [comment] 2020-10-02 07:02
It's unfortunate that the gRPC libraries are only showing as "2.0.0.0" rather than the exact version. Fundamentally I think it's unlikely that I'll be able to help you without being able to reproduce the problem myself - we'd be going back and forth for months. Are you able to create a cut-down version of the application and library in order to reproduce the issue? Fundamentally I think you're likely to have significant problems with this approach if you can't get a consistent set of versions... if you can possibly use a separate AppDomain for the plugin, that's likely to make it easier to isolate things.

**Comment by jskeet** [comment] 2020-10-06 06:52
Do you have any more information on this? I'm afraid without more information, we won't be able to help you. At the end of the week I'll close this issue if we haven't heard anything more - we can reopen it later if necessary, of course.

**Comment by jskeet** [comment] 2020-10-09 11:11
Closing for now.

**Closed by jskeet** 2020-10-09 11:11 UTC
Labels: api: translate, needs more info, priority: p2, type: question
