### ISSUE TITLE
is there anyway (using either MP3 or Wav) I can work out the audioChannelCount value

### ISSUE THREAD

**Issue by SafeCab** [googleapis/google-cloud-dotnet#3164] opened 2019-06-21 17:40 UTC
Hi,

Sorry I am quite new to this but reading on the web on ways to work out the number of channels in a wav file seems to be different from the expected number of audio channels for translation 

using the following wav file

https://www.voiptroubleshooter.com/open_speech/american/OSR_us_000_0017_8k.wav

with this code I get 7 channels but audioChannelCount it must be 1 for it to work in this instance.  Please tell me what I am missing.  Is there a better way to determine the correct audioChannelCount for a given wav or MP£ file?  

    public enum Channels : uint
    {
        FrontLeft = 0x1,
        FrontRight = 0x2,
        FrontCenter = 0x4,
        Lfe = 0x8,
        BackLeft = 0x10,
        BackRight = 0x20,
        FrontLeftOfCenter = 0x40,
        FrontRightOfCenter = 0x80,
        BackCenter = 0x100,
        SideLeft = 0x200,
        SideRight = 0x400,
        TopCenter = 0x800,
        TopFrontLeft = 0x1000,
        TopFrontCenter = 0x2000,
        TopFrontRight = 0x4000,
        TopBackLeft = 0x8000,
        TopBackCenter = 0x10000,
        TopBackRight = 0x20000
    }

    public class Speech
    {

        public int NumberofChannels(string AudioFile)
        {
            var bytes = new byte[50];

            WebClient client = new WebClient();
            byte[] data = client.DownloadData(new Uri(AudioFile));
            var speakerMask = BitConverter.ToUInt32(new[] { data[40], data[41], data[42], data[43] }, 0);

            var foundChannels = new List<Channels>();
            foreach (var ch in Enum.GetValues(typeof(Channels)))
            {
                if ((speakerMask & (uint)ch) == (uint)ch)
                {
                    foundChannels.Add((Channels)ch);
                }
            }
            return foundChannels.Count;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="AudioFile"></param>
        public string SpeechToText(string AudioFile)
        {
            var translations = "";
            GoogleCredential googleCredential;

            int channelNumber = 0;

            try
            {

                channelNumber = NumberofChannels(AudioFile);

                var jsonpath = HttpContext.Current.Server.MapPath("~/speech.json");
                googleCredential = GoogleCredential.FromFile(jsonpath);
                var channel = new Grpc.Core.Channel(SpeechClient.DefaultEndpoint.Host, googleCredential.ToChannelCredentials());
                var speech = SpeechClient.Create(channel);

                RecognitionConfig config = new RecognitionConfig
                {
                    Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                    LanguageCode = LanguageCodes.English.UnitedStates,
                    EnableAutomaticPunctuation = true,
                    Model = "Phone",
                    AudioChannelCount = channelNumber
                };

                var response = speech.Recognize(config, RecognitionAudio.FetchFromUri(AudioFile));
                foreach (var result in response.Results)
                {
                    foreach (var alternative in result.Alternatives)
                    {
                        translations += alternative.Transcript;
                    }
                }

            }
            catch (Exception e)
            {
                throw e;
            }
            return translations;
        }
}

Thanks

Steve

**Comment by jskeet** [comment] 2019-06-22 06:23
I'll look at this on Monday - but basically I'd suggest using a separate library for this rather than building it yourself. I'm sure there are libraries around that can do this - I'll see if NAudio works, for example.

**Comment by SafeCab** [comment] 2019-06-22 07:06
hi,  Thanks.  I guess it comes down to my understanding the difference between channels - as the code does above and actual audio channels in the sense google speech means.

Thanks

Steve

**Comment by jskeet** [comment] 2019-06-24 07:45
Okay, looking again - I don't know where the code you're using comes from, but it's basically broken as far as I can see. According to http://soundfile.sapp.org/doc/WaveFormat/, the number of channels is in bytes 22 and 23, as a 16-bit little-endian value; you're using bytes 40-43 as a 32-bit value. Bytes 22 and 23 are 1 and 0 respectively, so there's 1 channel.

I'm going to close this now as it looks like the problem is just due to the code you're currently using to detect the number of channels. Again, I'd recommend using a dedicated library for this. NAudio makes it pretty easy, for example:

```csharp
using System;
using NAudio.Wave;

namespace Issue3164
{
    class Program
    {
        static void Main(string[] args)
        {
            var reader = new WaveFileReader("OSR_us_000_0017_8k.wav");
            Console.WriteLine(reader.WaveFormat.Channels);
        }
    }
}
```

Output: 1

**Closed by jskeet** 2019-06-24 07:45 UTC
Labels: api: speech, priority: p2, type: question
