### ISSUE TITLE
FirestoreChangeListener stops working silently

### ISSUE THREAD

**Issue by DenSmoke** [googleapis/google-cloud-dotnet#4813] opened 2020-04-05 09:06 UTC
Issue with the listener reappeared after upgrading the `Google.Cloud.Firestore` package to `2.0.0-beta02`, but now awaiting `ListenerTask` doesn't throw an exception, as before.

#### Environment details

  - OS: `Ubuntu 18.04 x64` GCE VM instance
  - .NET version: `.NET Core 3.1`
  - Package name and version: `Google.Cloud.Firestore 2.0.0-beta02`

#### Steps to reproduce

Start `FirestoreChangeListener` for a long time

**Comment by jskeet** [comment] 2020-04-05 09:08
Thanks, will try to reproduce tomorrow.

**Comment by jskeet** [comment] 2020-04-06 06:23
Right, now I'm around for more information, could you let me know:

- Does the task complete, or just stop doing anything useful?
- How long is "a long time"? Do you typically see this after an hour, a day, a week?
- What does your listener do? (For example, is it possible that it's the code reacting to the changes has hung?)
- Have you tried reproducing this locally rather than on GCE? (I completely understand if you haven't - I'm just trying to get as much information as possible.)
  - If you *have* tried this, have you tried it on Windows as well?

**Comment by DenSmoke** [comment] 2020-04-06 07:11
1. I have not manage to catch that yet.
2. It happened 2 times after 1 and 3 days.
3. It calls SQL command with ADO.NET. It is possible that code hangs.
4. I didn't try.

I have to make some changes to investigate 1 and 3.

**Comment by jskeet** [comment] 2020-04-06 07:21
Thanks for the details. Given how long it takes to reproduce, I'll start *trying* to reproduce it myself - any additional info you're able to provide over time would be very useful!

**Comment by jskeet** [comment] 2020-04-06 10:35
Right, I now have a GKE app with three tasks:

- A task to update a single document every 10 seconds
- A task to watch that document
- A regular ASP.NET Core web hosting task which displays the latest information

We'll see what happens...

**Comment by jskeet** [comment] 2020-04-07 05:34
Just to report in, it's been going for 19 hours, and is still fine. 6832 updates performed so far.

**Comment by jskeet** [comment] 2020-04-08 11:14
My test has now been running for over 48 hours, and is going strong.
Any more info from your side, @DenSmoke ?

**Comment by DenSmoke** [comment] 2020-04-08 12:34
Same. I'm starting to think that it was some weird build error

**Comment by jskeet** [comment] 2020-04-08 13:02
Okay, well I'm happy to keep it running for a week or so - we can close the issue when it's had that long.

**Comment by DenSmoke** [comment] 2020-04-08 15:14
Oh, I was looking for log messages showing if it's callback hang or task completion. Listener stopped but callback completed successfully and ListenerTask is still alive. And still no exceptions

**Comment by jskeet** [comment] 2020-04-08 15:16
@DenSmoke: I don't quite follow what you mean. Are you in a position to provide an example to reproduce the problem? My task is still going strong...

**Comment by DenSmoke** [comment] 2020-04-08 15:35
Example of my code:

```C#
//Usage
public async Task StartListenUsersAsync(CancellationToken ct = default)
{
    var query = FirestoreDb.Collection(CollectionNames.Users);
    async Task Callback(DocumentChange change, CancellationToken callbackCt)
    {
        if (change.ChangeType == DocumentChange.Type.Removed)
            return;
        var user = change.Document.ConvertTo<User>();
        if (UserChange != null && !string.IsNullOrWhiteSpace(user.Email))
        {
            var args = new ChangeEventArgs(user, null, callbackCt);
            //SQL operation
            await UserChange(this, args).ConfigureAwait(false); 
        }
    }
    _usersListener = await StartListenerAsync(CollectionNames.Users, query, _usersListener, StartListenUsersAsync, Callback, ct).ConfigureAwait(false);
}

//Common method
public async Task<FirestoreChangeListener> StartListenerAsync(string collectionName, Query query, FirestoreChangeListener listener, Func<CancellationToken, Task> starter, Func<Google.Cloud.Firestore.DocumentChange, CancellationToken, Task> callback, CancellationToken ct = default)
{
    if (listener is null || listener.ListenerTask is object && listener.ListenerTask.IsCompleted)
    {
        _logger?.LogInformation($"Starting listener of {collectionName}");
        var isStarting = true;
        async Task OnChange(QuerySnapshot snapshot, CancellationToken callbackCt)
        {
            try
            {
                var sw = new Stopwatch();
                var changes = snapshot.Changes.OrderBy(x => x.Document.UpdateTime);
                foreach (var change in changes)
                {
                    _logger?.LogInformation("Received change {0}: {1} {2} {3}", collectionName, change.Document.Id, change.ChangeType, change.Document.UpdateTime);
                    try
                    {
                        sw.Start();
                        await callback(change, callbackCt).ConfigureAwait(false);
                        _logger?.LogInformation("Processed change {0}: {1} {2} {3} {4}ms", collectionName, change.Document.Id, change.ChangeType, change.Document.UpdateTime, sw.ElapsedMilliseconds);
                        sw.Reset();
                    }
                    catch (Exception ex)
                    {
                        _logger?.LogError(ex, $"Error occured on {collectionName} change processing: Id={change.Document.Id}");
                    }
                }
            }
            finally
            {
                isStarting = false;
            }
        }
        listener = query.Listen(OnChange);
        ListenerRestarter(collectionName, listener, starter, ct);
        while (isStarting)
            await Task.Delay(500, ct).ConfigureAwait(false);
    }
    return listener;
}

//Restarts listener if task crashed
protected async void ListenerRestarter(string collectionName, FirestoreChangeListener listener, Func<CancellationToken, Task> startListener, CancellationToken ct = default)
{
    try
    {
        await listener.ListenerTask.ConfigureAwait(false);
        _logger?.LogInformation("Listening of {0} completed", collectionName);
    }
    catch (TaskCanceledException)
    {
        _logger?.LogInformation("Listening of {0} canceled", collectionName);
    }
    catch (Exception ex)
    {
        _logger?.LogError(ex, $"Error occured on {collectionName} listening");
        await startListener(ct).ConfigureAwait(false);
    }
}
```

**Comment by jskeet** [comment] 2020-04-09 09:00
Thanks for the code. So to clarify your previous comment:

- "Listener stopped" - in that it's not notifying your code of any further changes
- "but callback completed successfully" - as in, the last time you saw a log of "Received change [...]" you also saw "Processed change [...]"?
- "and ListenerTask is still alive" - so no logs for "Listening of [...] completed" or "Listening of [...] canceled", or "Error occured on [...]"

As a side note, your ListenerRestarter looks "pseudo-recursive" in that it's going to start a new listener - but wait for that to complete before saying that *this* one has completed. I suspect it's not relevant to this problem, but it feels a little odd and could make diagnostics hard in some cases.

In other news, my k8s task has now been restarted - I'm not sure why yet. Will look into it.

**Comment by jskeet** [comment] 2020-04-09 09:08
Okay, my k8s task restarted because the update task failed with an RPC exception of "Status(StatusCode=Unavailable, Detail="Connection reset by peer")" - which isn't terribly unusual to happen every so often, I guess.

The listening task was still running at that point.

**Comment by DenSmoke** [comment] 2020-04-09 10:28
> * Listener stopped" - in that it's not notifying your code of any further changes
> * "but callback completed successfully" - as in, the last time you saw a log of "Received change [...]" you also saw "Processed change [...]"?
> * "and ListenerTask is still alive" - so no logs for "Listening of [...] completed" or "Listening of [...] canceled", or "Error occured on [...]"

You got that right.
I made ListenerRestarter from scratch, but it was working more than year and I left it as it was.

**Comment by jskeet** [comment] 2020-04-09 13:13
Right. And there were further changes that definitely weren't being picked up? I'll keep an eye on my task, but I'm not sure where we go from here if I can't reproduce the problem...

**Comment by DenSmoke** [comment] 2020-04-09 13:39
There were also updated Google.Cloud.Storage.V1 and Google.Cloud.Logging.NLog. BTW Google.Cloud.Logging.NLog 3.0.0 causes errors in Firestore and Storage packages because uses newer Gax. That's why I upgraded these packages to beta release

**Comment by jskeet** [comment] 2020-04-09 13:43
Yes, you need to update everything to use GAX 3.0.0 at the same time. The Firestore and Storage GA releases targeting 3.0.0 are hopefully not too far away. I don't think the fact that you're using the betas is the problem.

**Comment by DenSmoke** [comment] 2020-04-09 14:09
It seems all packages use GAX 3.0.0. I have no more ideas what causes listener stop. I doubt .NET Core SDK 3.1.201 could break something

**Comment by DenSmoke** [comment] 2020-04-09 14:14
Oh, sorry. I missed that FirebaseAdmin uses GAX 2.7.0
![image](https://user-images.githubusercontent.com/16131575/78904554-627fc080-7a85-11ea-931e-b1ccc109dd58.png)
Could it be the reason?

**Comment by jskeet** [comment] 2020-04-09 14:18
Hmm. It's just possible that if something elsewhere in the code used the Firebase Admin project, that could trigger "weirdness" elsewhere.
You should definitely update that to the beta matching the version of Google.Cloud.Firestore. Basically you should have *nothing* targeting GAX 2.x.

Are you able to make that change and restart whatever tests you have? Does whatever uses the Admin API in your code happen to log so we could try to find a correlation between that and when the listener stopped?

**Comment by DenSmoke** [comment] 2020-04-09 15:45
> You should definitely update that to the beta matching the version of Google.Cloud.Firestore

Unfortunately, it seems there is no FirebaseAdmin beta with GAX 3.0.0. @hiranya911 any plans on this?

My project uses FirebaseAdmin only for FCM and I don't see correlation between sending push-messages and listener outage.

I think I can fork https://github.com/firebase/firebase-admin-dotnet and update dependencies to see if this helps.

**Comment by jskeet** [comment] 2020-04-09 15:55
In this case you don't need a beta - you can use Google.Cloud.Firestore.Admin.V1 version 2.0.0. That should be fine. (I acknowledge it's slightly odd that the Admin API is GA while the "main" API isn't, but the packages are completely independent - it's not like Spanner where the Spanner.Data package depends on the admin packages.)

**Comment by jskeet** [comment] 2020-04-09 15:57
Ah - I've just noticed we're talking about entirely different packages. I was unaware of the FiresbaseAdmin package, rather than the Google.Cloud.Firestore.Admin.V1 package.

You *may* be able to just fork the project and update the dependencies - but it may well not build. It depends on whether that package uses any of the parts that have breaking changes going from v2 to v3.

**Comment by DenSmoke** [comment] 2020-04-09 18:14
Well. I created own version of FirebaseAdmin with GAX 3.0.0 https://github.com/DenSmoke/firebase-admin-dotnet and updated my project. We'll see what happens

**Comment by DenSmoke** [comment] 2020-04-11 07:25
It didn't help. Last notification was at 2:12 UTC, after few minutes since instance reboot. So listener wasn't even highly loaded.

**Comment by jskeet** [comment] 2020-04-11 07:30
That's interesting. My task that was restarted about 58 hours ago is still going strong. That doesn't mean it won't fail at some point, of course.

If I made my code available in a zip file, would you be able to try that? We really need to know the difference between "your code in your cluster" and "my code in my cluster" - trying my code in your cluster might be a starting point for that. (I don't expect we'll get to a resolution for this very quickly I'm afraid - I think there's going to be a lot of waiting to see what happens...) I could also potentially try running several services, or run several listeners in a single service, to try to provoke an earlier failure. Hmm.

**Comment by DenSmoke** [comment] 2020-04-11 07:46
I think I can try to run your code at our environment.

BTW my app has 5 listeners and each of them can fail. I think you should run several listeners in one service - it would be closer to my code (and more chances to catch error)

**Comment by jskeet** [comment] 2020-04-11 08:14
Okay - I won't get to that until at least Tuesday, given that there's a public holiday on Monday in the UK. I'm only prepared to do so much actual work when I'm meant to be on holiday :) However, I've attached my code below - edit the constants in Program.cs to reflect your project ID etc. The singleton shared state is horrible, but this was just a quick and dirty attempt to try to reproduce the issue.

[Issue4813.zip](https://github.com/googleapis/google-cloud-dotnet/files/4464248/Issue4813.zip)

**Comment by jskeet** [comment] 2020-04-14 05:51
My single listener task is still running fine - it's at over 5 days now.

Before I start changing the code to work for 5 listeners, could you clarify how you're building the client? That could affect how many channels are used, which could be relevant.

**Comment by DenSmoke** [comment] 2020-04-14 07:09
Clients building:
```C#
public async Task InitAsync(CancellationToken ct = default)
{
    if (_isInitialized)
        return;
    var googleCredential = Options.Credential as GoogleCredential;
    FirestoreDb = await new FirestoreDbBuilder()
    {
        ChannelCredentials = googleCredential.ToChannelCredentials(),
        WarningLogger = x => _logger?.LogWarning(x),
        ProjectId = Options.ProjectId
    }.BuildAsync(ct).ConfigureAwait(false);
    StorageClient = await StorageClient.CreateAsync(googleCredential).ConfigureAwait(false);
    FirebaseApp.Create(new AppOptions()
    {
        Credential = googleCredential,
        ProjectId = Options.ProjectId
    });
    FirebaseMessaging = FirebaseMessaging.DefaultInstance;
    FirebaseAuth = FirebaseAuth.DefaultInstance;
    _isInitialized = true;
}
```

BTW your app crashed with error: 
```
2020-04-13T22:50:49: Listener received count of 5476
2020-04-13T22:50:49: Set count to 5476
Updater exception: Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="The service is temporarily unavailable. Please retry with exponential backoff.")
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Google.Cloud.Firestore.WriteBatch.CommitAsync(ByteString transactionId, CancellationToken cancellationToken)
   at Google.Cloud.Firestore.DocumentReference.SetAsync(Object documentData, SetOptions options, CancellationToken cancellationToken)
   at Issue4813.Program.UpdateDocumentAsync(FirestoreDb db) in C:\Users\densm\Desktop\Issue4813\Program.cs:line 78
Status of update task: Faulted
Status of listen task: WaitingForActivation
Status of web task: WaitingForActivation
```

**Comment by jskeet** [comment] 2020-04-14 07:24
Okay - so that's a little like my failure in https://github.com/googleapis/google-cloud-dotnet/issues/4813#issuecomment-611420807 - but it's not a listener error. (I'll make that code retry when I add the multiple-listeners.)

Just to check your client-building code - does each of your listeners execute that separately, or are they all sharing the same `FirestoreDb`?

**Comment by DenSmoke** [comment] 2020-04-14 07:26
They sharing the same instance.

**Comment by jskeet** [comment] 2020-04-14 07:30
Right, that's good to know. Thanks very much - I'll modify the code later today. (I'll probably have a single updater task which updates all the documents.)

**Comment by jskeet** [comment] 2020-04-14 08:21
Okay, I've now got it with 5 listeners for 5 separate docs, but a single updater (with retry).

The way I've read your previous comments, it sounds like *some* listening tasks stopped responding while others continued - is that correct?

**Comment by DenSmoke** [comment] 2020-04-14 08:43
Exactly

**Comment by jskeet** [comment] 2020-04-16 13:45
All 5 tasks still running smoothly for me. Would you like me to share the code for that with you so you can try it in your environment?

**Comment by DenSmoke** [comment] 2020-04-16 14:03
I have no outages already 3 days too.
Yes I can try.

**Comment by jskeet** [comment] 2020-04-16 14:11
Okay - I've attached a new zip file.
[Issue4813.zip](https://github.com/googleapis/google-cloud-dotnet/files/4487631/Issue4813.zip)

**Comment by jskeet** [comment] 2020-04-20 06:23
My test task failed last night, with one of the listeners throwing an exception of "Server removed target" - which is presumably the kind of thing your "restarter" is expecting to handle.
At the point when it failed, there had been 46380 updates, which at 360 per hour is just over 5 days.

Still no sign of reproducing the symptoms you've described. Have you had any luck running the same code in your environment?

**Comment by DenSmoke** [comment] 2020-04-20 08:16
Your new app still works and my app didn't fail. Only things I changed:

- async void ListenerRestarter to async Task
- called ListenerRestarter after while(isStarting) loop without await

No idea how it could fix the problem.

**Comment by jskeet** [comment] 2020-04-20 08:35
Hmm. Are you happy for us both to just keep an eye on things and we can investigate more actively if either of sees the failure? I don't want to close the issue while we don't understand what's going on, but I suspect that we could both waste quite a lot of time chasing things without any more data :(

**Comment by DenSmoke** [comment] 2020-04-20 08:44
I'll let know if I get more data

**Comment by jskeet** [comment] 2020-04-27 19:00
Just to check in on this, my tasks are still running... currently 65845 updates. Are yours all still running @DenSmoke?

**Comment by DenSmoke** [comment] 2020-04-27 19:19
Your app is still running, 35290 updates. Meanwhile, listeners in my app have already failed 2 times. It seems there is something specific that prevents exception throw. Before update I regularly saw "Server removed target", but now there are no such errors (no errors at all).

**Comment by jskeet** [comment] 2020-04-27 19:43
Interesting. I wonder if there's a deadlock somewhere? Hard to tell.

**Comment by DenSmoke** [comment] 2020-05-06 16:24
I added random delay interval for your Updater for more real conditions.
Also I added health check for listeners to my app. So may be I will catch some exception on FirestoreChangeListener.StopAsync after it's hang.
Interesting fact: most cases happened early in the morning - when the application is not heavily loaded and wakes up from standby.

**Comment by jskeet** [comment] 2020-05-06 18:13
Ah, that's definitely interesting. I wonder whether the process has gone to sleep and the connection has died. I'll have to work out the best way of simulating that. It may be that we need to run the updater in an entirely different service...

**Comment by jskeet** [comment] 2020-05-12 07:54
Just coming back to this, could you clarify what you mean by "and wakes up from standby"? What kind of "standby" is this?

I'm going to change my code to remove the updater part, so I can just update periodically from the Firestore console, and see whether that reproduces the issue. (The current one is still going strong after three weeks, so I don't expect it to fail now.)

**Comment by DenSmoke** [comment] 2020-05-12 08:08
I mean the application almost does nothing for a while, when there are no active users at night, while the process is still alive. Then it should get first changes from Firestore but listener doesn't react

**Comment by jskeet** [comment] 2020-05-12 08:13
Right. So nothing is actually suspending the process, for example. That's good to know. (gRPC has a connection heartbeat that should still be happening in the background.)

Will redeploy my app and see how we go.

**Comment by jskeet** [comment] 2020-05-13 07:37
Just to update: I've redeployed my app, and written a small console app to run from my laptop that just updates the documents. First update was handled fine - I'll probably try this a few times on some days, just once on some days, and not at all over the weekend, in order to get a mixture of situations.

**Comment by jskeet** [comment] 2020-05-15 13:17
Worked yesterday, worked today. Will leave it over the weekend with no updates.

**Comment by jskeet** [comment] 2020-05-20 08:11
Have been trying periodically - and still no issues.

@DenSmoke: Are you still seeing the problem? I'm not sure what the next step is - if building a small app from nothing doesn't reproduce it, are you able to reduce your *real* app step by step to something you'd be able to share (potentially privately)?

**Comment by DenSmoke** [comment] 2020-05-22 14:02
I solved this problem by health check - if there were no updates within N minutes - just restart listener. 
It seems that no one else has faced this problem so I'll understand if you decide to close issue.
If you want to continue I think I can extract this app from solution and share with you but I have no free time right now unfortunately.

**Comment by jskeet** [comment] 2020-05-22 14:58
Thanks - I think it's best to close this for now, but we can reopen it if anyone faces the same thing. I can easily see us both spending a lot of time trying to get to the bottom of it, when you already have a good workaround. Obviously there's a frustration in not understanding the root cause, but life's too short to understand everything :)

**Closed by jskeet** 2020-05-22 14:58 UTC
Labels: api: firestore, priority: p2, type: bug
