### ISSUE TITLE
Google.Cloud.BigQuery.Storage.V1: How to deserialize avro response?

### ISSUE THREAD

**Issue by jpsgamboa** [googleapis/google-cloud-dotnet#7627] opened 2021-12-16 12:21 UTC
I'm attempting to read the avro response but I can't make it work with Apache.Avro, AvroConvert or Microsoft.Avro.Core.
All fail to parse the `AvroRows.SerializedBinaryRows` returned in the response.
Am I looking at this wrong?
There is no example (that I can find) of how to process this response in dotnet.

For reference, my request is as follows:
```c#
BigQueryReadClient client = BigQueryReadClient.Create();
var readSession = new ReadSession
{
    TableAsTableName = new TableName(projectId, datasetId, tableId),
    DataFormat = DataFormat.Avro,
    ReadOptions = new ReadSession.Types.TableReadOptions()
            {
                RowRestriction =  datetime > '2021-04-11' and datetime < '2021-04-12'"
            };
};

readSession = client.CreateReadSession(new ProjectName(projectId), readSession, 0);

foreach (var stream in readSession.Streams)
{
    var response = client.ReadRows(stream.ReadStreamName, 0L);

    await foreach (var item in response.GetResponseStream())
    {
         // I'm trying to parse the data here
    }
}
```

Attempting with Microsoft.Avro.Core:

```c#
using (var ms = new MemoryStream(item.AvroRows.SerializedBinaryRows.ToByteArray()))
{
    using (var reader = AvroContainer.CreateGenericReader(item.AvroSchema.Schema, ms, false, new CodecFactory()))
    {
        
    }
}
```

This errors with:
```c#
System.Runtime.Serialization.SerializationException: 'Invalid Avro object container in a stream. The header cannot be recognized.'
```

AvroConvert has a DeserializeHeadless:
````c#
var result = AvroConvert.DeserializeHeadless<MyEvent>(item.AvroRows.SerializedBinaryRows.ToByteArray(), readSession.AvroSchema.Schema);
````
This, however, fails to parse when a `DateTime` is included in the query.

Can someone please shed some light on the intended way to process the avro response, or link to some examples on how to do so?

**Comment by jskeet** [comment] 2021-12-16 12:55
Assigned to @shivgautam as this is his team's area, but I'll have a poke around and see what I can work out...

**Comment by jskeet** [comment] 2021-12-16 13:00
Just to clarify, am I right in saying that `DesearilizeHeadless` works when you don't have a `DateTime` value? When it fails, what's the error?

I'm not very familiar with Avro, but hopefully this information will help others who have more experience.

**Comment by jpsgamboa** [comment] 2021-12-16 13:44
> Just to clarify, am I right in saying that `DeserializeHeadless` works when you don't have a `DateTime` value? When it fails, what's the error?

When including a DateTime, the following error occurs:

`System.Runtime.Serialization.SerializationException: 'Unknown LogicalType schema :'datetime'.'`

Which hints that AvroConvert has not implemented this logical type, but I'm also unfamiliar with Avro to know for sure if this is expected. 

Otherwise, `DeserializeHeadless` returns one instance of `MyEvent` with expected values, but not the expected ~1000 records reported by `ReadRowsResponse.RowCount`. 

I'm probably using AvroConvert wrong here, but my problem starts with not really understanding how to use the AvroRows payload.

Also, I should note that while `ReadRowsResponse.RowCount` reports ~1000 records, `ReadRowsResponse.AvroRows.RowCount` is always 0.

**Comment by jskeet** [comment] 2021-12-16 14:15
Thanks for the clarification.

I suspect without either of us having much Avro experience, we may not get anywhere *very* soon, and I believe @shivgautam is taking a vacation day tomorrow as well.

I would say that it's very unlikely that any of this is specific to the .NET client library (although it may be specific to the .NET Avro library), so if you (or some colleagues) are able to try it with a different language, that may be useful.

**Comment by jpsgamboa** [comment] 2021-12-16 14:58
Thank you @jskeet for the quick feedback.

As suggested, I tried the same workflow in Python using the example [on the docs](https://cloud.google.com/bigquery/docs/reference/storage/libraries) and was able to successfully get the desired data. 

However, the example uses a `google-cloud-bigquery-storage[fastavro]` lib which abstracts all the hard work.

In any case, I have no reason to believe there is an issue with the .NET client lib, other than the lack of docs/examples on how to process the incoming Avro data in dotnet.

**Comment by Rishabh-V** [comment] 2022-02-17 04:47
Hi @jpsgamboa, 
I am able to reproduce the issue with `DateTime` type column using Apache.Avro library. With `DateTime` column, API returns the 'datetime' logical Type in the `AvroSchema`, which as per [current Avro spec](https://avro.apache.org/docs/current/spec.html#:~:text=Language%20implementations%20must%20ignore%20unknown%20logical%20types%20when%20reading%2C%20and%20should%20use%20the%20underlying%20Avro%20type.%20If%20a%20logical%20type%20is%20invalid%2C%20for%20example%20a%20decimal%20with%20scale%20greater%20than%20its%20precision%2C%20then%20implementations%20should%20ignore%20the%20logical%20type%20and%20use%20the%20underlying%20Avro%20type.) should be ignored and underlying Avro type should be returned. The exception itself is due to a [known bug in the .NET Apache Avro library](https://issues.apache.org/jira/browse/AVRO-3012)

I would talk with the product team about both the row count and the unexpected logicalType.

**Comment by jskeet** [comment] 2022-02-21 11:26
I'll close this issue now as unfortunately there's nothing we'd be able to do in the client library.

**Closed by jskeet** 2022-02-21 11:26 UTC
Labels: type: question, api: bigquerystorage
