### ISSUE TITLE
"The Application Default Credentials are not available" error when running in windows nodes with service account

### ISSUE THREAD

**Issue by orbengigi** [googleapis/google-cloud-dotnet#4751] opened 2020-03-31 10:02 UTC
I have a Google kubernetes cluster configured, and I've created a windows node pool in it using gcloud, with specified service account: 
```
gcloud container node-pools create windows-pool --cluster=test --image-type=WINDOWS_SAC --enable-autoupgrade --machine-type=n1-standard-2 --zone=us-east4 --num-nodes=1 --service-account=test@projectId.iam.gserviceaccount.com
```
in Google console UI I see the node pool was created with the service account I specified: 
![image](https://user-images.githubusercontent.com/17527093/78013417-21820080-734f-11ea-9d8c-d6a71c222f3b.png)

I also created a linux node pool the same way (with specified service account): 
```
gcloud container node-pools create linux-pool --cluster=test--enable-autoupgrade --machine-type=n1-standard-1 --zone=us-east4 --num-nodes=1 --service-account=test@projectId.iam.gserviceaccount.com
```

I deployed to each node pool an application that uses Google services (Firestore\Storage...).
the Linux nodes are able to authenticate to the required services, but in the windows nodes I get the error:
"Exception":"System.InvalidOperationException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.  
at Google.Apis.Auth.OAuth2.DefaultCredentialProvider.CreateDefaultCredentialAsync() 
at Google.Api.Gax.Grpc.ChannelPool.CreateChannelCredentialsUncached() 
at Google.Api.Gax.Grpc.ChannelPool.GetChannelAsync(ServiceEndpoint endpoint, IEnumerable\u00601 channelOptions)
at Google.Cloud.PubSub.V1.SubscriberServiceApiClient.CreateAsync(ServiceEndpoint endpoint, SubscriberServiceApiSettings settings)...

How can I use the service account I configured by default in the windows node pool same as the linux one?
I'm trying to avoid saving the credentials inside the cluster and specifying the GOOGLE_APPLICATION_CREDENTIALS environment variable, and I expected that setting the service account for the node pool will work same as it did in Linux nodes.

appreciate help on this!

**Comment by amanda-tarafa** [comment] 2020-03-31 10:22
Have you taken a look at this tutorial: https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform. From Step 3 onwards you can see how to configure your application to use the default credentials. The tutorial is using a PubSub sample application but configuring the service credentials should be the same for your application.
Let me know if this doesn't help so we can look further.

**Comment by amanda-tarafa** [comment] 2020-03-31 10:31
Okay, I may have replied too soon, I see now that you are trying to avoid using GOOGLE_APPLICATION_CREDENTIALS. Let me check that and get back to you.

**Comment by amanda-tarafa** [comment] 2020-03-31 11:38
Can you provide us with a similar screenshot of your Linux pool?

**Comment by orbengigi** [comment] 2020-03-31 12:08
thanks for the response @amanda-tarafa ,
here is the linux pool config: 
![image](https://user-images.githubusercontent.com/17527093/78024622-5a2ad580-7361-11ea-8318-3aa360b7177d.png)

**Comment by amanda-tarafa** [comment] 2020-03-31 13:09
Thanks, I'm trying some things out and will get back to you as soon as I know more.

**Comment by amanda-tarafa** [comment] 2020-03-31 14:13
It would be great if you could try the following and report back with the results. This check is basically the same check that we do [here](https://github.com/googleapis/google-api-dotnet-client/blob/03fd262975f8e96c32e7b42907f403d3adc900eb/Src/Support/Google.Apis.Auth/OAuth2/ComputeCredential.cs#L173) to find out if we are running on GCE (GKE nodes are ultimately GCE instances). Only I'd like you to try it directly on the command line of the windows instance in the windows pool.

1. First RDP on the Windows instance from your Windows Pool (go directly to step 2 if you already know how to do that):
  1.1 On the windows-pool details page (the one on your screenshot), scroll to the bottom to where it says Instance Groups.
  1.2 You should have only one entry there looking something like `gke-<cluster-name>-windows-pool...`. Click on it.
  1.3 On the page that appears, we don't care about the section named Instance Templates, instead go to the list after that, it should have only one entry which corresponds to the Windows instance which is your only node.
  1.4 On the right of that entry you should see a button with a down arrow that says RDP. Click on the arrow and select "Set Windows Password". Follow the instructions there and copy the password.
  1.5 Now click on the RDP button itself, and enter the user and password that you just set up.
  1.6 You should see a CMD window.
2. Copy the following command on the CMD window (the same as we do on our client libraries to determine whether we are running on GCE or not, just sending a HEAD request to the GCE metadata server with the Google metadata flavor header):
   `curl -I -H "Metadata-Flavor: Google" http://169.254.169.254`
3. If you could paste the response here that'd be great, else, just confirm whether or not, as part of the response, you see "Metadata-Flavor: Google" back.

**Comment by orbengigi** [comment] 2020-04-01 06:15
actually all instance groups under the windows pool look the same: 
![image](https://user-images.githubusercontent.com/17527093/78105148-33b87900-73f9-11ea-96c0-472fd79fc812.png)

I RDP to all of them, and run the command you requested, they all came up with the same result:
![image](https://user-images.githubusercontent.com/17527093/78104421-e1c32380-73f7-11ea-853e-800e8b04f844.png)

**Comment by amanda-tarafa** [comment] 2020-04-01 09:11
OK, so that probably explains why it's not working. See the 405 error returned?
It's not a problem with the library but with the windows image. Let me ask around and see what best we can do to move forward. In the meantime, and even though you were avoiding it, you can try setting the GOOGLE_APPLICATION_CREDENTIALS as a temporary alternative.

**Comment by orbengigi** [comment] 2020-04-01 09:18
@amanda-tarafa I'm trying to solve auto rotation for the authentication in Google cloud, from what I can tell, there is no solution for Windows nodes, as [Workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity?_ga=2.101331009.-1557059849.1558595207) is also not supported in this case: 
![image](https://user-images.githubusercontent.com/17527093/78120447-a4b85a80-7412-11ea-86bb-b46317aba6d9.png)

setting the environment variable is a temporary fix for our scenario.

**Comment by amanda-tarafa** [comment] 2020-04-01 10:01
Ah I see, so, one of the features request I'll be working on soon is googleapis/google-api-dotnet-client#1447, to support key rotation at the client library level. It won't be auto rotation in that we won't be changing the keys ourselves, but if the key changes, we will pick up the new one. So that might help with what you want to do. Subscribe to that issue so you can track the work. There's no ETA as of yet, I have a few things that I have to work on first, but that will be coming at some point.

Anyway, I'll dig a little deeper and try to find a solution for this, either on our side or on the side of the Window images producers. I'll come back to this issue once I know more.

**Comment by orbengigi** [comment] 2020-04-01 10:06
thanks for the information @amanda-tarafa !
waiting on a response from you to see if setting the service account is possible on Windows nodes.

**Comment by Mistic92** [comment] 2020-04-02 07:41
I have the same issue on linux nodes using .UseGoogleDiagnostics with project id. I'm trying to find more logs about this issue but can't :/ 

```
System.InvalidOperationException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
at Google.Apis.Auth.OAuth2.DefaultCredentialProvider.CreateDefaultCredentialAsync
at Google.Api.Gax.Grpc.ChannelPool.CreateChannelCredentialsUncached
at Google.Api.Gax.TaskExtensions.WaitWithUnwrappedExceptions
at Google.Api.Gax.TaskExtensions.ResultWithUnwrappedExceptions[T]
at Google.Api.Gax.Grpc.ChannelPool.GetChannel
at Google.Api.Gax.Grpc.ChannelPool.GetChannel
at Google.Cloud.Trace.V1.TraceServiceClient.Create
at Google.Cloud.Diagnostics.AspNetCore.CloudTraceExtension.AddGoogleTrace
at Google.Cloud.Diagnostics.AspNetCore.GoogleDiagnosticsWebHostBuilderExtensions.ConfigureGoogleDiagnosticsServices
at Google.Cloud.Diagnostics.AspNetCore.GoogleDiagnosticsWebHostBuilderExtensions.<>c__DisplayClass0_0.<UseGoogleDiagnostics>b__0
at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0
at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build
```

**Comment by amanda-tarafa** [comment] 2020-04-02 09:12
OK, I'll work on this today and see if we can get to the bottom of it.
I haven't been able to reproduce it myself so I'll aks you for a lot of information to see if I can recreate your environments/projects as closely as possible.

@orbengigi I'm not so sure about my assesment from yesterday that the 405 error was the problem. The curl I asked you to execute was a HEAD request and what we really do is a GET request and then only look at headers. Could you RDP again (one node is enough) and execute this instead and then look at temp.txt and see whether "Metadata-Flavor: Google" is present and whether you got an HTTP Error or not?
`curl -D temp.txt -H "Metadata-Flavor: Google" http://169.254.169.254`

@Mistic92 Can you share a screenshot of your pool configuration? Are you creating a specific Service Account or ar you using the default Service Account created with the nodes etc?

@orbengigi and @Mistic92 If you both could share a minimal project that fails for you, including .yaml and Dockerfile that'd be great, change any sensitive information you might have in configuration files or code by something like "my-sensitive-information" and be sure **not to include** the .json file containing the service account private key.
Else, please do share as much info as you can about your projects, such as:

- Target .NET Frameworks.
- Versions of all dependencies, specially of Google client libraries. (@orbengigi from this line here at 

> Google.Api.Gax.Grpc.ChannelPool.GetChannelAsync(ServiceEndpoint endpoint, IEnumerable\u00601 channelOptions)

 in your stack trace I can see that you are not using the latest Google.Cloud.PubSub.V1 2.0.0-beta02, if you could update to that and try that'd be great as well).
- Full stack trace and line of code where the exception is thrown.
- Which docker images are you using.

Again, I'm sorry it seems the burden is on you, I'm just trying to get as much info so I can reproduce this myself and get to the bottom of it.

**Comment by Mistic92** [comment] 2020-04-02 15:03
I found that lib had trouble to get credentials because of istio sidecar. After one restart of app container istio was ready to proxy traffic and it worked. 
Unfortunatelly I have issue with Datastore credentials but I think I'll create other issue as it's more grpc related and missing method from samples.

**Comment by amanda-tarafa** [comment] 2020-04-02 15:06
@Mistic92 good to know to you have solved your issue around getting default credentials. And yes, please do create new issues in the appropiate repo for other problems you might encounter.

**Comment by amanda-tarafa** [comment] 2020-04-02 15:23
@orbengigi I've been playing around with different combinations of nodes and deployments and I haven't been able to reproduce the issue. I've created this very simple project that could help us diagnose why you are not able to load the credentials. If you could deploy it **exactly** as you are deploying your failing application that'd be best. If this fails on your setup then it's really an environment problem and I would need all the details of it to try and reproduce. If this doens't fail on your setup then it's probably your code (might be as simple as old dependency versions) and then I would need a minimum application that reproduces the problem.
Or let me know if there's something else you think would help us with diagnosing.
[TestingGKE.zip](https://github.com/googleapis/google-cloud-dotnet/files/4421934/TestingGKE.zip)

**Comment by orbengigi** [comment] 2020-04-05 07:46
@amanda-tarafa I tried running the command you requested,  here is the result:
![image](https://user-images.githubusercontent.com/17527093/78469458-31705a80-772a-11ea-8143-40a350903338.png)

these are the client versions I'm using:
```
    <PackageReference Include="Google.Cloud.Firestore" Version="1.1.0" />
    <PackageReference Include="Google.Cloud.PubSub.V1" Version="1.0.0" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="2.5.0" />
    <PackageReference Include="Google.Protobuf" Version="3.11.4" />
```
this is my target framework: 
```
    <TargetFramework>netcoreapp3.1</TargetFramework>
```
I'll try using the project you uploaded and update if it worked in my environment.

**Comment by amanda-tarafa** [comment] 2020-04-06 09:32
> I tried running the command you requested, here is the result:

OK, that result indicates that the GCE metadata server is responding properly on the Windows node to the exact same question we ask to determine if we can use compute's default credential. This is consistent with me not being able to reproduce it and probably means that the problem lies with either your specific setup or your code. 

   ```
    <PackageReference Include="Google.Cloud.Firestore" Version="1.1.0" />
    <PackageReference Include="Google.Cloud.PubSub.V1" Version="1.0.0" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="2.5.0" />
    <PackageReference Include="Google.Protobuf" Version="3.11.4" />
```
There are some issues with your dependencies. I would strongly recommend you fix these before moving forward. Once you have fixed them just try again to deploy your application on Windows pool.
- Your PubSub dependency is really outdated. The version you are using is from over a year ago. I would strongly recommend that you update your PubSub dependency to at least version 1.1.0.
  - Is the PubSub code that fails the first to execute? Is Firestore or Storage code executing first and succeeding in obtaining the credentials? If that is the case then almost certainly updating the PubSub dependency will fix your issue.
- Why are you adding an explicit version of Google.Protobuf dependency? You shouldn't need to since both PubSub and Firestore depend on Google.Protobuf, by forcing the use of a specific Protobuf version you might be creating problems for yourself, at least in the future when you update the libraries.
- If you are able to have beta dependencies, I would recommend that you update the three libraries to the latest version, which are betas. We'll be releasing GA versions of these libraries shortly.

> I'll try using the project you uploaded and update if it worked in my environment.

Please do so and report back. Else, for me to be able to reproduce this, having tried with different combinations of nodes and containers, I would need to be able to recreate your setup exactly:
- How are you creating your cluster/pool (in the command you pasted you only created a node, but then on a comment you mentioned you had 3 nodes), that shouldn't be relevant, but any other change could.
- Which container you are using and it's configuration file (the Dockerfile if you are using Docker, for instance).
- How are you deploying you application to the nodes.

Ideally full step by step instructions and a small application to reproduce it would be best.

**Comment by amanda-tarafa** [comment] 2020-04-14 08:18
@orbengigi have you been able to try my code or updating the dependencies? Let me know as soon as you have so we can try and move forward. I really can't do much more without more info. Thanks!

**Comment by amanda-tarafa** [comment] 2020-04-20 10:22
@orbengigi I'll be closing this issue now since there's not much we can do without more info. Please do leave a comment if you can share the info requested or can run the code I sent.

**Closed by amanda-tarafa** 2020-04-20 10:22 UTC
Labels: needs more info, type: question
