### ISSUE TITLE
Getting data from image

### ISSUE THREAD

**Issue by ALMLAMBO** [googleapis/google-cloud-dotnet#4439] opened 2020-02-29 12:41 UTC
Hi,
I want to ask why on c# getting data from an image in the console app is working perfectly and in a web application (blazor) is not working? Below is the code.

```
Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", filepath);
ImageAnnotatorClient client = ImageAnnotatorClient.Create();
Image image = Image.FromFile(imageDir);
IReadOnlyList<EntityAnnotation> annotations = client.DetectTextAsync(image).Result;
```

It stops working on the web on the last line.

**Comment by jskeet** [comment] 2020-02-29 13:14
What exactly do you mean by "stops working"? Does it throw an exception? Hang? Using `.Result` like that looks like a bad idea that could be causing the problem - you should be awaiting the result rather than blocking on it. If you really want a synchronous call, use `DetectText` instead. But without more information, we'll just be guessing.

**Comment by ALMLAMBO** [comment] 2020-02-29 13:21
No, it does not throw an exception. I tried also with DetectText method and again the same thing - when it reaches the line for getting a text from the image the whole program stops on this line and does not continue.

**Comment by jskeet** [comment] 2020-02-29 13:25
When you say "the whole program stops" - just that thread? Does the server respond to other requests? Have you tried this in a regular ASP.NET Core app rather than a Blazor app? What kind of Blazor app is this? I wouldn't expect anything gRPC-based to work via client-side Blazor, but server-side Blazor should be fine.

**Comment by ALMLAMBO** [comment] 2020-02-29 13:31
It stops only this thread the rest part of the app is working fine and I am using Blazor server-side app.

**Comment by jskeet** [comment] 2020-02-29 13:48
If you could try in a regular ASP.NET Core app, that would be handy. Are you using any other Google libraries? I wonder whether gRPC isn't being loaded properly.

**Comment by jskeet** [comment] 2020-02-29 13:48
Oh, and which versions are you using for everything?

**Comment by ALMLAMBO** [comment] 2020-02-29 13:52
For Blazor app I am using version 3.1.1 and for cloud vision library version is 1.7.0. I also libraries for cloud firestore and cloud storage.

**Comment by ALMLAMBO** [comment] 2020-02-29 14:04
I tried the same thing on the MVC app and it is working fine.

**Comment by jskeet** [comment] 2020-02-29 15:09
I suspect the problem is using ASP.NET Core 3.x with that version of Cloud Vision - see the first part of the [README](https://github.com/googleapis/google-cloud-dotnet) for a little more detail.

Please try with Google.Cloud.Vision.V1 version 2.0.0-beta01 - I suspect that will fix it.

**Comment by ALMLAMBO** [comment] 2020-02-29 15:30
I try with version 2.0.0-beta01 but again not working.

**Comment by jskeet** [comment] 2020-02-29 15:32
Okay, I'll try to reproduce this on Monday. If you could provide a complete but minimal example in a zip file, that would really help.

**Comment by ALMLAMBO** [comment] 2020-03-03 17:26
Any news about this problem?

**Comment by jskeet** [comment] 2020-03-03 17:28
Looking into it now - but as I said before, if you have a minimal example that would really help.

**Comment by jskeet** [comment] 2020-03-03 17:41
I've just tried this, and it worked fine for me. Steps:

- Create a new Blazor app from the template
- Add Google.Cloud.Vision.V1 version 2.0.0-beta01 as a dependency
Change `WeatherForecastService.cs` to have the following `GetForecastAsync` method:

```csharp
public async Task<WeatherForecast[]> GetForecastAsync(DateTime startDate)
{
    var client = await ImageAnnotatorClient.CreateAsync();
    var image = await Image.FromFileAsync(ImagePath);
    IReadOnlyList<EntityAnnotation> annotations = await client.DetectTextAsync(image);

    var rng = new Random();
    return annotations.Select((annotation, index) => new WeatherForecast
    {
        Date = startDate.AddDays(index),
        TemperatureC = rng.Next(-20, 55),
        Summary = annotation.Description
    }).ToArray();
}
```

Note that I've used async calls throughout, but it actually worked fine for me when using `Crteate()` and `FromFile()` without the async part. Your mileage may vary on that part.

So given that my code is working, we really need to find out the difference between my sample and your code. Do you have any other Google dependencies?

**Comment by jskeet** [comment] 2020-03-09 07:57
Any update on this? If I don't hear anything more in a few days I'll close the issue. (There's nothing more we can do until we can reproduce it or at least have more information that could help us *try* to reproduce it.)

**Comment by jskeet** [comment] 2020-03-12 07:08
Closing due to lack of information. Please add another comment if you're still having problems and would like this reopened - and please include more information so we can try to reproduce the problem.

**Closed by jskeet** 2020-03-12 07:08 UTC
Labels: api: vision, needs more info, type: question
