### ISSUE TITLE
Can't set phrase hints in Dialogflow SDK

### ISSUE THREAD

**Issue by HStuart18** [googleapis/google-cloud-dotnet#2825] opened 2019-01-23 15:19 UTC
I am using the Dialogflow V2 Client Library to make a streaming detect intent request. I would like to provide phrase hints, however, the object seems to have the "parameter" set as `read-only`. Is there anyway I can provide phrase hints? Or will I need to use the Google Speech API separately from the Dialogflow API? 

This is an image showing the problem:

[https://drive.google.com/file/d/1eKZzuWdWg1_vfo4GUWBhy-scfPVC8a78/view?usp=sharing](url)

and this is the link to the documentation which indicates that phrase hints are allowed with streaming detect intent requests:

[https://cloud.google.com/dialogflow-enterprise/docs/reference/rpc/google.cloud.dialogflow.v2](url)

**Comment by jskeet** [comment] 2019-01-23 15:24
It's a repeated field - you don't set the property, you just add to it. You can do that in a collection initializer, e.g.

```csharp
AudioConfig = new InputAudioConfig
{
    AudioEncoding = ...,
    SampleRateHertz = 16000,
    LanguageCode = "en-AU",
    PhraseHints = { "foo", "bar", "baz" }
}
```

Closing as this is working as intended, although I'll readily admit it's not as discoverable as I'd like it to be. (All repeated fields in C# protobuf work this way, by the way.)

**Closed by jskeet** 2019-01-23 15:24 UTC

**Comment by HStuart18** [comment] 2019-01-23 15:33
My apologies, I was expecting some sort of `PhraseHints` object that I would have to set. That makes sense, thanks!

**Comment by HStuart18** [comment] 2019-01-23 15:58
Sorry for my ignorance, but I seem to be struggling with the protobuf repeated field still. If I have a `RepeatedField<string>` object or a `List<string>` object, how can I "add" it to the "PhraseHints" property? The reason I want to do this, is because the phrase hints will actually be determined by another method. Such that

`PhraseHints = myPhraseHintsObject`

Can I do something along the lines of:

`PhraseHints = { myPhraseHintsObject }`

Thanks

**Comment by jskeet** [comment] 2019-01-23 16:08
Yes, `RepeatedlyField<T>` has an overload of `Add` accepting an `IEnumerable<T>` specifically do that you can do that within a collection initializer (including using it with LINQ if you want).
