### ISSUE TITLE
Some time there is no final response in Response stream result

### ISSUE THREAD

**Issue by 20092738** [googleapis/google-cloud-dotnet#2519] opened 2018-09-18 12:27 UTC
I'm making an real time speech to text application with Microphone.
While streaming audio, normally my application receives final response after received some interim results.
but some time, there is no final response even interim result is received long time before.
Is there any way to make my application always received final result after received interim result ?

**Comment by jskeet** [comment] 2018-09-18 12:34
Did the stream end in the normal way? If so, I suspect that's a matter of the speech recognition engine deciding that it didn't have a good enough final option to include. I doubt that this is an issue in the .NET client library specifically, so it's unlikely to result in a code change here.

If you have a sample file we could use to reproduce this, I could report it to the Speech team internally, if that would be helpful?

**Comment by 20092738** [comment] 2018-09-19 04:09
Hi @jskeet ,
Thank you for your support!
I've already recorded to sample file with sample rate 16000Hz. But my test language is Japanese. 
Please refer to attachment bellow:
[FileStream.zip](https://github.com/googleapis/google-cloud-dotnet/files/2395368/FileStream.zip)

I think it's difficult to analyze this problem with Japanese but please help me if you can.
With this sample file, I expect to received final response at 8s, 13s, 35s, 55s but response from google API was interim result with very long text.

**Comment by jskeet** [comment] 2018-09-19 08:40
Okay - while I personally don't understand Japanese, hopefully that'll be okay for the Speech team to investigate. Please could you show the exact settings you're using? It would be unfortunate if I made assumptions and then found out we'd been trying different code.

(If you could supply a complete console app that demonstrates the problem, that would be ideal - but otherwise just the settings would probably be enough.)

**Comment by 20092738** [comment] 2018-09-19 12:01
You can procedure this problem with Sample Recognize application already existed here:
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/speech/api/Recognize
(Use StreamingRecognizeAsync() function for audio file streaming recognize)
about recognize setting, I kept all of them as sample source code except language code.
you should change language code to "ja" for Japanese recognition.

if you have any concern, let me know!

**Comment by jskeet** [comment] 2018-09-19 13:46
Hmm. I can't reproduce the problem - I always get a final response (4 of them in fact).

Here's the code:

[Repro.zip](https://github.com/googleapis/google-cloud-dotnet/files/2397294/Repro.zip)

And here's the output:

```text
00:00.839: Length: 1; Confidence: 0; Final? False
00:00.980: Length: 4; Confidence: 0; Final? False
00:01.258: Length: 8; Confidence: 0; Final? False
00:01.313: Length: 4; Confidence: 0; Final? False
00:01.428: Length: 6; Confidence: 0; Final? False
00:01.442: Length: 5; Confidence: 0; Final? False
00:01.644: Length: 6; Confidence: 0; Final? False
00:01.704: Length: 6; Confidence: 0; Final? False
00:03.676: Length: 14; Confidence: 0; Final? False
00:03.795: Length: 12; Confidence: 0; Final? False
00:03.825: Length: 10; Confidence: 0; Final? False
00:04.098: Length: 11; Confidence: 0; Final? False
00:04.158: Length: 12; Confidence: 0; Final? False
00:04.599: Length: 12; Confidence: 0; Final? False
00:06.143: Length: 14; Confidence: 0; Final? False
00:06.174: Length: 14; Confidence: 0; Final? False
00:06.239: Length: 16; Confidence: 0; Final? False
00:06.622: Length: 17; Confidence: 0; Final? False
00:06.684: Length: 18; Confidence: 0; Final? False
00:06.782: Length: 18; Confidence: 0; Final? False
00:09.644: Length: 21; Confidence: 0; Final? False
00:09.717: Length: 22; Confidence: 0; Final? False
00:09.731: Length: 23; Confidence: 0; Final? False
00:09.765: Length: 23; Confidence: 0; Final? False
00:10.145: Length: 25; Confidence: 0; Final? False
00:10.241: Length: 25; Confidence: 0; Final? False
00:13.214: Length: 27; Confidence: 0; Final? False
00:13.259: Length: 27; Confidence: 0; Final? False
00:13.442: Length: 30; Confidence: 0; Final? False
00:13.457: Length: 29; Confidence: 0; Final? False
00:13.661: Length: 30; Confidence: 0; Final? False
00:13.776: Length: 31; Confidence: 0; Final? False
00:13.792: Length: 32; Confidence: 0; Final? False
00:14.220: Length: 32; Confidence: 0; Final? False
00:15.253: Length: 34; Confidence: 0; Final? False
00:15.310: Length: 36; Confidence: 0; Final? False
00:15.708: Length: 37; Confidence: 0; Final? False
00:15.768: Length: 38; Confidence: 0; Final? False
00:16.192: Length: 38; Confidence: 0; Final? False
00:16.858: Length: 39; Confidence: 0; Final? False
00:16.939: Length: 40; Confidence: 0; Final? False
00:17.217: Length: 40; Confidence: 0; Final? False
00:17.340: Length: 42; Confidence: 0; Final? False
00:17.358: Length: 43; Confidence: 0; Final? False
00:17.713: Length: 44; Confidence: 0; Final? False
00:17.803: Length: 44; Confidence: 0; Final? False
00:20.817: Length: 47; Confidence: 0; Final? False
00:21.235: Length: 49; Confidence: 0; Final? False
00:21.247: Length: 49; Confidence: 0; Final? False
00:21.337: Length: 49; Confidence: 0; Final? False
00:22.302: Length: 52; Confidence: 0; Final? False
00:22.717: Length: 54; Confidence: 0; Final? False
00:22.737: Length: 54; Confidence: 0; Final? False
00:22.827: Length: 54; Confidence: 0; Final? False
00:24.240: Length: 58; Confidence: 0; Final? False
00:24.265: Length: 59; Confidence: 0; Final? False
00:24.352: Length: 59; Confidence: 0; Final? False
00:26.293: Length: 61; Confidence: 0; Final? False
00:26.321: Length: 61; Confidence: 0; Final? False
00:26.382: Length: 63; Confidence: 0; Final? False
00:26.794: Length: 64; Confidence: 0; Final? False
00:26.843: Length: 65; Confidence: 0; Final? False
00:27.280: Length: 65; Confidence: 0; Final? False
00:30.138: Length: 65; Confidence: 0.9209557; Final? True
00:30.938: Length: 2; Confidence: 0; Final? False
00:31.006: Length: 2; Confidence: 0; Final? False
00:31.410: Length: 4; Confidence: 0; Final? False
00:31.450: Length: 5; Confidence: 0; Final? False
00:31.491: Length: 6; Confidence: 0; Final? False
00:31.888: Length: 6; Confidence: 0; Final? False
00:32.861: Length: 6; Confidence: 0.9362457; Final? True
00:34.417: Length: 2; Confidence: 0; Final? False
00:34.431: Length: 2; Confidence: 0; Final? False
00:34.474: Length: 2; Confidence: 0; Final? False
00:35.840: Length: 2; Confidence: 0.9260362; Final? True
00:37.920: Length: 2; Confidence: 0; Final? False
00:37.930: Length: 3; Confidence: 0; Final? False
00:37.998: Length: 4; Confidence: 0; Final? False
00:38.013: Length: 5; Confidence: 0; Final? False
00:38.440: Length: 5; Confidence: 0; Final? False
00:39.877: Length: 5; Confidence: 0.9614928; Final? True
```

Could you try that exact same code yourself?

**Comment by 20092738** [comment] 2018-09-19 16:15
hmmm.
I also get the same result.  It may be not bug.
But it take a long time to receive final result almost 30 seconds (00:30.138). could you tell me why ?
Moreover, duration between two interim results also to long (for example 00:06.782 -> 00:09.644). is possible to reduce it ?

**Comment by jskeet** [comment] 2018-09-19 16:31
No, I think this is just a consequence of the complexities of Speech recognition, particularly for long pieces of speech. (The first "final" result has a long transcript.)

Without the `Task.Delay(500)` in the code, the whole file completes after 14 seconds for me - but as streaming speech is not intended to be delivered much faster than real-time, I suspect that that will reduce reliability.

**Comment by jskeet** [comment] 2018-09-20 05:10
No, I don't know anything about the implementation. If you're still seeing situations where you don't get a final response, it would be good to try to reproduce that - that was the original intention of asking for a sample.

**Comment by 20092738** [comment] 2018-09-21 08:34
yes, I see.
I have last question about final result.
in my test, while receiving interim result, I send complete streaming command using WriteCompleteAsync(). Normally I received final result right after send complete streaming. 
Is Google Speech API always send final result after complete stream ?

**Comment by jskeet** [comment] 2018-09-21 08:48
I honestly don't know about that - I would expect so if there has been some speech, but if there's been no speech detected I wouldn't expect a final response. That's a question which isn't really about the .NET API - I'd suggest asking via one of the [general support mechanisms](https://cloud.google.com/speech-to-text/docs/support) for the Cloud Speech-to-Text API. The [Google Group](https://groups.google.com/forum/#!forum/cloud-speech-discuss) would probably be a good starting point.

I'm going to close this issue now as I don't think there's any work to be done in this repo for it.

**Closed by jskeet** 2018-09-21 08:48 UTC
Labels: type: question
