### ISSUE TITLE
Trace Waterfall View - only root span is displayed

### ISSUE THREAD

**Issue by xbrabec** [googleapis/google-cloud-dotnet#5155] opened 2020-07-09 10:49 UTC
I am not able to get the managed tracer spans to work in AspNetCore 3.1 app to work.

I've created a new seed project using `dotnet new webapi` and then followed all the steps depicted here: [https://googleapis.dev/dotnet/Google.Cloud.Diagnostics.AspNetCore/4.0.0/index.html](https://googleapis.dev/dotnet/Google.Cloud.Diagnostics.AspNetCore/4.0.0/index.html)

When I try to do manual tracing like this:
```c#
[HttpGet]
public IEnumerable<WeatherForecast> Get([FromServices] IManagedTracer tracer)
{
    var rng = new Random();

    using (tracer.StartSpan("test"))
    {
        _logger.LogWarning("Test log message");
        Thread.Sleep(100);
    }

    return Enumerable.Range(1, 5).Select(index => new WeatherForecast
    {
        Date = DateTime.Now.AddDays(index),
        TemperatureC = rng.Next(-20, 55),
        Summary = Summaries[rng.Next(Summaries.Length)]
    })
    .ToArray();
}
```
I only get the root span in StackDriver, but nothing under it, no waterfall
<img width="1551" alt="Snímek obrazovky 2020-07-09 v 12 43 29" src="https://user-images.githubusercontent.com/1808018/87030464-edd23480-c1e1-11ea-8bcf-34ea4f93d962.png">
Also no associated logs there either.

```c#
using Google.Cloud.Diagnostics.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace tracetest
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder
                        .UseGoogleDiagnostics(Constants.ProjectId, Constants.ServiceName, Constants.ServiceVersion)
                        .UseStartup<Startup>();
                });
    }
}
```

```c#
using Google.Cloud.Diagnostics.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace tracetest
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddHttpContextAccessor();
            services.AddGoogleExceptionLogging(options =>
            {
                // Replace ProjectId with your Google Cloud Project ID.
                options.ProjectId = Constants.ProjectId;
                // Replace Service with a name or identifier for the service.
                options.ServiceName = Constants.ServiceName;
                // Replace Version with a version for the service.
                options.Version = Constants.ServiceVersion;
            });
            services.AddGoogleTrace(options =>
            {
                options.ProjectId = Constants.ProjectId;
            });

            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseGoogleExceptionLogging();
            loggerFactory.AddGoogle(app.ApplicationServices, Constants.ProjectId);

            app.UseGoogleTrace();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}
```

What am I doing wrong?

Thanks a lot.
Honza

Sources:
[tracetest.zip](https://github.com/googleapis/google-cloud-dotnet/files/4896233/tracetest.zip)

**Comment by amanda-tarafa** [comment] 2020-07-09 11:01
@xbrabec thanks for the detail issue report and the code to reproduce.
Please note that we are still looking into #4750 (Properly supporting ASP.NET Core 3.1) so this might just be related to that. I won't close as duplicate just yet, until I've taken a look at your issue specifically. I'll update here when I know more, but I won't possibly get to this until next week.

**Comment by amanda-tarafa** [comment] 2020-07-15 09:40
@xbrabec The problem is that you are initializing Google Tracing (and Error Reporting and Logging) twice.

In Program.cs you have the following:

```
webBuilder
    .UseGoogleDiagnostics(Constants.ProjectId, Constants.ServiceName, Constants.ServiceVersion)
```

And then in Startup.cs:

```
        public void ConfigureServices(IServiceCollection services)
        {
            ...
            services.AddGoogleExceptionLogging(options =>
            { ... });
            services.AddGoogleTrace(options =>
            { ... });
            ...
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseGoogleExceptionLogging();
            loggerFactory.AddGoogle(app.ApplicationServices, Constants.ProjectId);

            app.UseGoogleTrace();
            ...
        }
```

Those are **alternative** ways to initialize Google Diagnostics. You can read about how to initialize Google Diagnostics and its individual components [here](https://googleapis.dev/dotnet/Google.Cloud.Diagnostics.AspNetCore/4.0.0/index.html). The short version is: 

- You use the code in your Program.cs file to initialize all three components of Google Diagnostics at once, Logging, Tracing, Error Reporting. You use this approach when you want to take advantage of all three components of Google Diagnostics. (This seems to be your case).
- Or you use all or some of the code in your Startup.cs file to initialize the components individually. You use this approach when you only want to use one or two of the componets of Google Diagnostics. Maybe you only want Error Reporting and Logging, but don't want to activate Tracing.

I've tested with your sample app, and using one or the other approach works perfectly, i.e. includes your manually created span on the trace.

**Comment by xbrabec** [comment] 2020-07-16 09:35
Almost Perfect :-) Thank you very much

I've removed the initialization from the Startup.cs and tracing waterfall view started showing the waterfall indeed. 
But I still do not see the related log messages.

![image](https://user-images.githubusercontent.com/1808018/87654117-c4238b00-c756-11ea-9878-078c46a40f6a.png)

The log message is in the StackDriver

![image](https://user-images.githubusercontent.com/1808018/87654676-91c65d80-c757-11ea-9af0-e26f1c7297f0.png)

I would expect this to happen automatically. The span id is there but **it starts with the pipe character and ends with dot**. 

```C#

[HttpGet]
public IEnumerable<WeatherForecast> Get([FromServices] IManagedTracer tracer)
{
    var rng = new Random();

    using (tracer.StartSpan("test"))
    {
        _logger.LogWarning("Test log message");

        Thread.Sleep(100);
    }

    return Enumerable.Range(1, 5).Select(index => new WeatherForecast
    {
        Date = DateTime.Now.AddDays(index),
        TemperatureC = rng.Next(-20, 55),
        Summary = Summaries[rng.Next(Summaries.Length)]
    })
    .ToArray();
}
```

Thanks a lot
Honza

**Comment by amanda-tarafa** [comment] 2020-07-16 09:55
Hmmm, that's interesting. Let me look at it and get back here when I know more.

**Comment by amanda-tarafa** [comment] 2020-07-16 13:43
OK, there are two separate issues that I'll be commenting on:

1. First, I've created #5190 because we are not associating log entries to traces started on the current request (as is your case) but only to traces that are being propagated from the initiator of the request. I'm working on a fix for that.
2. Second, the TraceId and SpanId that you see in the log entry there (the one like |*.) has nothing to do with the Google trace and span. You can see it's set in scopes, and it's set by Asp.Net Core (more accurately, possibly, the web server you are using) through the `ILogger.BeginScope<TState>(TState state)`, which is a mechanism independent of Google tracing. You can check these IDs against the ones for the trace and span shown in the Trace Waterfall View to confirm that they are not the same. So, this is not a problem, it is just extra information added by the web server in a format decided by the web server, and there's nothing we can do at the library level about this. If you'd like the format of this information to be different, you'd probably need to configure your web server accordingly.

I'll close this issue now. I'll track log entry-trace/span association separetely in #5190 because that's a very different problem to your original question. Apart from that, I believe there's no outstanding items here. Please do add another comment if you believe otherwise.

**Comment by amanda-tarafa** [comment] 2020-07-16 13:44
Closing. Outstanding issue being tracked in #5190.

**Closed by amanda-tarafa** 2020-07-16 13:44 UTC
Labels: api: cloudtrace, type: question
