### ISSUE TITLE
Passing the wrong Project Id to loggerFactory.AddGoogle() yields no warnings, errors, or exceptions.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/google-cloud-dotnet#2630] opened 2018-10-23 22:02 UTC
I accidentally passed the wrong Project Id to loggerFactory.AddGoogle().  It did not match the Project Id of my service account.  I was running the app locally.  I saw no warnings, errors, or exceptions.  This is extremely frustrating, because I could never find my log statements in the logging dashboard..  Users mistake their Project Id all the time.

    <PackageReference Include="Google.Cloud.Diagnostics.AspNetCore" Version="2.0.1" />

**Comment by jskeet** [comment] 2018-10-23 22:05
Hmm. I'm not sure whether we'd want to make a sort of "test call" on start-up just to check that it's all working, although that might be an option. Assigned to Amanda to think about.

**Comment by SurferJeffAtGoogle** [comment] 2018-10-23 23:15
To be useful, it doesn't have to throw an exception when I call loggerFactory.AddGoogle().  If it threw an exception at the first attempt to log something, that would still 100% wake me up to my error.

**Comment by jskeet** [comment] 2018-10-24 12:48
We've typically tried to avoid throwing exceptions when logging. Maybe we should do so in developer mode but not in production mode... if I've misconfigured logging and deployed my site to production, I suspect that continuing is still better than having a web site that throws user-facing errors. More pondering and discussion required, I think.

(Maybe we could make this an option when configuring logging to start with?)

**Comment by iantalarico** [comment] 2018-10-24 14:21
I'm going to echo what Jon said a little and give some context.  When building these libraries by design made them never throw exceptions as this could result in us taking down users applications as we run with the application (we are not a separate process).  We do have some optional configuration where you can change this behavior to throw, retry and throw or just ignore if the stackdriver calls fail.

We could always add some form of logging when this happens but then the issue if if you are looking for logs in stackdriver and they are broken you are in trouble.

I think Jon's ideas may be good.  Throwing in dev mode and maybe adding an option to only throw on the first call?

**Comment by SurferJeffAtGoogle** [comment] 2018-10-24 16:17
How about logging an error?  That should announce itself pretty loudly in my debugging session.  And I like  your idea of only throwing an exception or logging an error once, the first time.

**Comment by jskeet** [comment] 2018-10-24 16:23
> How about logging an error? 

How though? We're saying there's a problem with logging, so how would I log the error? While we *could* write to the console, I'm generally really reluctant to do that.

A one-time exception would definitely avoid the "production web site is permanently broken" issue.

**Comment by amanda-tarafa** [comment] 2019-01-04 11:04
Closing via #2784

**Closed by amanda-tarafa** 2019-01-04 11:04 UTC
Labels: api: logging, priority: p2
