### ISSUE TITLE
ListDocumentsAsync inconsistent with results

### ISSUE THREAD

**Issue by elvogel** [googleapis/google-cloud-dotnet#3374] opened 2019-08-20 15:00 UTC
OS: Linux  Mint 19.2
.NET version: 2,2
Package version: Google.Apis.Firestore.v1beta1
---

I have an ASP.NET Core application where I have an entity that points to a sub-collection of entities. 

My code looked like this:

```csharp
var ret = client.Collection(path).ListDocumentsAsync();
await ret.ForEachAsync(async x =>
{
    var y = await x.GetSnapshotAsync();
    list.Add(y.ConvertTo<Job>());
});
return list;
```
Despite having a record in said `path`, I kept getting an empty list returned. Only when I went to debug the issue - either by stepping through the repository containing this code or through another part of the stack - did it actually return anything. 

Ultimately the fix for this (for me) was to use `GetSnapshotAsync` method which returns everything (what I wanted in the first place), but I thought I'd bring it up in case anyone else ran into something similar.

**Comment by jskeet** [comment] 2019-08-20 15:03
Could you clarify which package you're using? You've specified Google.Apis.Firestore.v1beta1, but this looks like Google.Cloud.Firestore.

Next, it would help if you could clarify the situation in terms of where there are documents, and what the path is. If you could provide a [mcve] that would be ideal. I'd definitely like to work out what's going on here.

**Comment by elvogel** [comment] 2019-08-20 15:08
Sure - I'm using Google Cloud Firestore. The particular path I was using was `/companies/<guid>/savedJobs` . I don't have an immediate [mcve] beyond the snippet, unfortunately, but I could probably put one together...

**Comment by jskeet** [comment] 2019-08-20 15:31
And are there documents *directly* in that collection, or are there only documents in subcollections? If you have time to put a mcve together that would be great - but if not, I can probably try to put one together myself, that probably *won't* show the issue, but will show how I'd expect to reproduce it. You may well be able to tweak that more easily than starting from scratch :)

**Comment by elvogel** [comment] 2019-08-20 15:42
There are documents in both the collection and the subcollection. I get the sub-documents successfully using `GetSnapshotAsync` but it's inconsistent with `ListDocumentsAsync`. 

I don't currently have anything in the way of [mcve] samples put together that I could post.

**Comment by jskeet** [comment] 2019-08-20 15:52
Thanks for the extra info. I'll try to put something together in the next couple of days to reproduce. (It would normally be sooner, but summer tends to slow things down...)

**Comment by jskeet** [comment] 2019-08-21 11:47
Okay, here's a program that *doesn't* reproduce the problem for me, but which I think should mirror your scenario as far as I'm aware of it:

```csharp
using Google.Cloud.Firestore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Issue3374
{
    class Program
    {
        static async Task Main(string[] args)
        {
            if (args.Length != 1)
            {
                Console.WriteLine("Please provide a project ID");
                return;
            }
            string projectId = args[0];
            var db = FirestoreDb.Create(projectId);
            var docId = Guid.NewGuid().ToString();
            CollectionReference collection = db.Collection($"Issue3374/{docId}/jobs");

            var created = new List<DocumentReference>();
            // Populate the collection
            int documentCount = 10;
            for (int i = 0; i < documentCount; i++)
            {
                created.Add(await collection.AddAsync(new { Index = i }));
            }
            
            // Now list the contents
            var docs = collection.ListDocumentsAsync();
            var fetched = await docs.ToList();

            Console.WriteLine($"Created {created.Count}; fetched {fetched.Count}");

            var createdIds = created.Select(doc => doc.Id).OrderBy(id => id);
            var fetchedIds = fetched.Select(doc => doc.Id).OrderBy(id => id);
            Console.WriteLine($"Created IDs: {string.Join(", ", createdIds)}");
            Console.WriteLine($"Fetched IDs: {string.Join(", ", fetchedIds)}");
        }
    }
}
```

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="1.0.0" />
  </ItemGroup>

</Project>
```

Are you able to try that in your environment?

Is this issue reproducible with your own code? Could you give me any more context about what's creating the documents and the timing of that operation vs the listing of them?

**Comment by elvogel** [comment] 2019-08-21 13:51
I took your code and made a couple of tweaks to demonstrate a little bit of the structure, added what I was doing (see "the Vogel method" comments), and it reproduces my error. 

```csharp
        static async Task Main(string[] args)
        {
            if (args.Length != 1)
            {
                Console.WriteLine("Please provide a project ID");
                return;
            }
            string projectId = args[0];
            var db = FirestoreDb.Create(projectId);
            var docId = Guid.NewGuid().ToString();
            var path = $"Issue3374/{docId}/jobs";
            CollectionReference collection = db.Collection(path);

            var created = new List<string>();
            // Populate the collection
            int documentCount = 10;
            for (int i = 0; i < documentCount; i++)
            {
                var d = Guid.NewGuid().ToString("N");
                await db.Collection(path).Document(d).SetAsync(new MyFakeType
                    {externalId = Guid.NewGuid().ToString("N"), randomNumber = i});
                created.Add(d);
            }

            //"the Vogel method"
            var ret = db.Collection(path).ListDocumentsAsync();
            var list = new List<MyFakeType>();
            await ret.ForEachAsync(async x =>
            {
                var y = await x.GetSnapshotAsync();
                list.Add(y.ConvertTo<MyFakeType>());
            });
            Console.WriteLine($"the Vogel method returns {list.Count}");

            // Now list the contents
            var docs = collection.ListDocumentsAsync();
            var fetched = await docs.ToList();

            Console.WriteLine($"Created {created.Count}; fetched {fetched.Count}");

            var createdIds = created.Select(doc => doc).OrderBy(id => id);
            var fetchedIds = fetched.Select(doc => doc.Id).OrderBy(id => id);
            Console.WriteLine($"Created IDs: {string.Join(", ", createdIds)}");
            Console.WriteLine($"Fetched IDs: {string.Join(", ", fetchedIds)}");

        }

    [FirestoreData]
    public class MyFakeType
    {
        [FirestoreProperty]
        public string externalId { get; set; }

        [FirestoreProperty]
        public int randomNumber { get; set; }
    }
```

Your code definitely works, and mine definitely doesn't - unless I try debugging :)

**Comment by jskeet** [comment] 2019-08-21 15:50
Great, thanks. I'm not in a position to work on this further tomorrow, but if your modified code fails for me as well, that'll make it much easier to work out what's going on.

**Comment by elvogel** [comment] 2019-08-21 15:58
Not a problem. You've given me more than enough workarounds to continue development, so I'll go ahead and make the changes I need to work around the issue. Thank you!

**Comment by jskeet** [comment] 2019-08-21 20:11
Okay, I understand now. I can reproduce it more simply with my original code, but from the "Now list the contents comment" use:

```csharp
// Now list the contents
var docs = collection.ListDocumentsAsync();
int count = 0;
await docs.ForEachAsync(async doc =>
{
    await doc.GetSnapshotAsync();
    count++;
});
Console.WriteLine($"Count immediately afterwards: {count}");
for (int i = 0; i < 5; i++)
{
    await Task.Delay(500);
    Console.WriteLine($"Count after a pause: {count}");
}
```

The problem is that `ForEachAsync` accepts `Action<T>` delegates, not `Func<T, Task>` delegates. It waits for the *action* to complete, but in the case of an async action, that doesn't mean the whole lambda expression has completed.

It'll be much easier to handle this in C# 8 with built-in language constructs - although we're going to need a whole new major version to support that, annoyingly :(

If you convert the sequence to a list using `var references = await docs.ToList();` and then iterate over the list, that's probably the best way of doing what you were after. You could potentially write your own `ForEachAsync` extension method if you wanted, instead.

I'm going to close this now as it's not really a Firestore issue - do let me know if you want any more details.

**Closed by jskeet** 2019-08-21 20:11 UTC
Labels: api: firestore, priority: p2, type: bug
