### ISSUE TITLE
Latest Vision API throws `MissingMethodException`  for all calls.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/google-cloud-dotnet#3240] opened 2019-07-12 23:17 UTC
In my code that calls the Vision API, I upgraded the Vision API version number from 1.4 to 1.5:
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/839/files

And now all the API calls fail with the same mysterious exception:
```
[xUnit.net 00:00:01.81]       System.TypeInitializationException : The type initializer for 'Google.Cloud.Vision.V1.ImageAnnotator' threw an exception.
[xUnit.net 00:00:01.81]       ---- System.TypeInitializationException : The type initializer for 'Google.Cloud.Vision.V1.BatchAnnotateFilesRequest' threw an exception.
[xUnit.net 00:00:01.81]       -------- System.TypeInitializationException : The type initializer for 'Google.Cloud.Vision.V1.AnnotateFileRequest' threw an exception.
[xUnit.net 00:00:01.81]       ------------ System.MissingMethodException : Method not found: 'Google.Protobuf.FieldCodec`1<Int32> Google.Protobuf.FieldCodec.ForInt32(UInt32)'.
[xUnit.net 00:00:01.81]       Stack Trace:
[xUnit.net 00:00:01.81]         T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\ImageAnnotatorGrpc.cs(190,0): at Google.Cloud.Vision.V1.ImageAnnotator.ImageAnnotatorClient.BatchAnnotateImages(BatchAnnotateImagesRequest request, CallOptions options)
[xUnit.net 00:00:01.81]         T:\src\github\gax-dotnet\releasebuild\Google.Api.Gax.Grpc\ApiCall.cs(92,0): at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
[xUnit.net 00:00:01.81]         T:\src\github\gax-dotnet\releasebuild\Google.Api.Gax.Grpc\ApiCallRetryExtensions.cs(84,0): at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
[xUnit.net 00:00:01.81]         T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\ImageAnnotatorClientPartial.cs(446,0): at Google.Cloud.Vision.V1.ImageAnnotatorClient.Annotate(AnnotateImageRequest request, CallSettings settings)
[xUnit.net 00:00:01.81]         T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\ImageAnnotatorClientPartial.cs(504,0): at Google.Cloud.Vision.V1.ImageAnnotatorClient.AnnotateSingleFeatureType[T](Type featureType, Func`2 annotationExtractor, Image image, ImageContext context, Int32 maxResults, CallSettings callSettings)
[xUnit.net 00:00:01.81]         T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\ImageAnnotatorClientPartial.cs(43,0): at Google.Cloud.Vision.V1.ImageAnnotatorClient.DetectFaces(Image image, ImageContext context, Int32 maxResults, CallSettings callSettings)
[xUnit.net 00:00:01.81]         C:\Users\rennie\gitrepos\dotnet-docs-samples\vision\api\DetectFaces\DetectFaces.cs(44,0): at GoogleCloudSamples.DetectFaces.Main(String[] args)
[xUnit.net 00:00:01.81]         C:\Users\rennie\gitrepos\dotnet-docs-samples\testutil\TestUtil.cs(137,0): at GoogleCloudSamples.CommandLineRunner.Run(String[] arguments)
[xUnit.net 00:00:01.81]         C:\Users\rennie\gitrepos\dotnet-docs-samples\vision\api\VisionTest\VisionTest.cs(60,0): at GoogleCloudSamples.TutorialTests.TestFacesWithFace()
[xUnit.net 00:00:01.81]         ----- Inner Stack Trace -----
[xUnit.net 00:00:01.81]         T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\ImageAnnotator.cs(6270,0): at Google.Cloud.Vision.V1.BatchAnnotateFilesRequest.get_Parser()
[xUnit.net 00:00:01.81]         T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\ImageAnnotatorGrpc.cs(38,0): at Google.Cloud.Vision.V1.ImageAnnotator..cctor()
[xUnit.net 00:00:01.81]         ----- Inner Stack Trace -----
[xUnit.net 00:00:01.81]         T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\ImageAnnotator.cs(6032,0): at Google.Cloud.Vision.V1.AnnotateFileRequest.get_Parser()
[xUnit.net 00:00:01.81]         T:\src\github\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Vision.V1\Google.Cloud.Vision.V1\ImageAnnotator.cs(6302,0): at Google.Cloud.Vision.V1.BatchAnnotateFilesRequest..cctor()
[xUnit.net 00:00:01.81]         ----- Inner Stack Trace -----
[xUnit.net 00:00:01.81]            at Google.Cloud.Vision.V1.AnnotateFileRequest..cctor()
[xUnit.net 00:00:01.82]   Finished:    VisionTest
----- Test Execution Summary -----
```

**Comment by jskeet** [comment] 2019-07-13 04:59
Ouch. That sounds like Google.Protobuf made an incompatible change :( Will investigate ASAP

**Comment by jskeet** [comment] 2019-07-13 05:47
Okay, there was definitely a breaking change in Google.Protobuf, as I've reported here: https://github.com/protocolbuffers/protobuf/issues/6379

But that doesn't fully explain what's going on, as Vision 1.5.0 should have been *compiled* against the new version of protobuf too. 

Marking this as p1 as it may well affect *all* the APIs I released earlier in the week. Will first try to reproduce in your repo.

**Comment by jskeet** [comment] 2019-07-13 06:21
Okay, I've reproduced it in the dotnet-docs-samples repo. The integration tests in google-cloud-dotnet pass though, so I suspect it's some sort of version mismatch. Continuing to investigate.

**Comment by jskeet** [comment] 2019-07-13 06:33
Okay, I've figured out the problem. It turns out the bug is in Google.Protobuf 3.9.0, which was just released yesterday. Our APIs depend on 3.8.0 or earlier - but some of the projects in dotnet-docs-samples have explicit dependencies on Google.Protobuf, and they're being upgraded by the gardener.

For the moment, the solutions to fix dotnet-docs-samples are:

- Pin Google.Protobuf to 3.8.0
- Remove the explicit Google.Protobuf dependencies entirely

(These solutions apply to the Detect and ProductSearch projects - but there may well be other projects in the repo with the same issue.)

This is being addressed in Google.Protobuf as well, but if I were to update *our* dependency to Google.Protobuf 3.9.0 and recompile and rerelease everything, that would probably work too. I'll discuss it with @chrisdunelm on Monday, but at least we have a handle on what's going on, and advice for the moment: avoid Google.Protobuf 3.9.0.

**Comment by jskeet** [comment] 2019-07-15 10:46
Leaving this open for the moment, but there's almost certainly nothing we want to do here except *not* depend on Google.Protobuf 3.9.0, which we may even want to delist. I'm hoping there'll be a bugfix release (of Google.Protobuf) out soon.

**Comment by SurferJeffAtGoogle** [comment] 2019-07-15 15:52
Thank you for the investigation, jskeet.  I'll modify dotnet-docs-samples.

**Comment by jskeet** [comment] 2019-07-25 07:59
Google.Protobuf 3.9.0 is delisted, so I believe we don't need to be particularly careful here any more - closing.

**Closed by jskeet** 2019-07-25 07:59 UTC
Labels: api: vision, priority: p1, status: blocked, type: bug
