### ISSUE TITLE
Google cloud speech to text is not giving optimal result .

### ISSUE THREAD

**Issue by harsh-tukadiya** [googleapis/google-cloud-dotnet#4334] opened 2020-02-18 10:21 UTC
my code for speech to text is ,

static object AsyncRecognizeGcs(string storageUri)
        {
            var speech = SpeechClient.Create();
            var longOperation = speech.LongRunningRecognize(new RecognitionConfig()
            {
                Encoding = RecognitionConfig.Types.AudioEncoding.Flac,
                SampleRateHertz = 44100,
                AudioChannelCount = 3,
                LanguageCode = LanguageCodes.English.UnitedKingdom,
                EnableSeparateRecognitionPerChannel = true,
                EnableAutomaticPunctuation = true,

            },

            RecognitionAudio.FromStorageUri(storageUri));

            longOperation = longOperation.PollUntilCompleted();

            var response = longOperation.Result;
            string data = null;
            ////while (1 > 0)
            //{
            foreach (var result in response.Results)
            {
                foreach (var alternative in result.Alternatives)
                {
                    data = alternative.Transcript;
                    Console.WriteLine(alternative.Transcript);
                }
            }
            //}
            Console.WriteLine(data);
            return 0;
        }
}

**Comment by jskeet** [comment] 2020-02-18 10:31
I'm afraid at the moment you haven't provided enough information for us to help you. You've shown us your code, but the only hint we have about the problem is that it's "not giving optimal result".

Please provide significantly more detail about the problem, and if you're able to test it with the online version at https://cloud.google.com/speech-to-text/, that would be helpful too. (My guess is this won't be a problem with the client library at all, but either with the service or with your configuration.)

Are you sure you really have 3 channels in your audio? That's pretty unusual.

**Comment by harsh-tukadiya** [comment] 2020-02-18 10:37
@jskeet  I am trying to convert to speech to text of a call recording and it is not giving an optimal result (as some words are neglected) so I want to know how to optimize it and it is taking a lot of time to convert it to speech to text so how to make the result optimal and how to run it faster

**Comment by jskeet** [comment] 2020-02-18 10:43
These don't sound like problems with the client library itself. Unless you believe that the client library is not correctly conveying your requests to the Speech-to-Text service, I suggest you follow one of the channels listed on the [Speech-to-Text support page](https://cloud.google.com/speech-to-text/docs/getting-support). The maintainers of this repository are not experts in individual APIs - instead, we're focused on making sure we correctly represent the APIs via client libraries.

When you ask a question in whichever channel you choose, I suggest you add more information though:

- What's the quality of the call recording like to start with? Are you able to provide a sample, and highlight words that are omitted?
- How large is the file, how long is the call, and how long does it take to convert?
- Does your file really have 3-channel sound?
- If it's a recording of a call, does it really need more than 1 channel? Most telephone calls are mono.

I'll close this issue now as I don't believe there's anything related to the client library here.

**Closed by jskeet** 2020-02-18 10:43 UTC
Labels: needs more info, type: question

**Comment by harsh-tukadiya** [comment] 2020-02-18 11:01
@jskeet 
File size is 36000kb(FLAC) , It takes around 3 minutes
File have 3 channel sound

**Comment by jskeet** [comment] 2020-02-18 11:04
Please read my earlier comment - those are pieces of information I suggest you add *when asking a detailed question in a more suitable forum*.
