### ISSUE TITLE
Google cloud speech to text

### ISSUE THREAD

**Issue by harsh-tukadiya** [googleapis/google-cloud-dotnet#4815] opened 2020-04-06 06:08 UTC
I converted speech to text using Google cloud Speech to text API. I converted .wav filebut i faced error in audio channle count . sometimes i need audio channel count 1 and sometimes audio channel count 2 . So, what can i do for this

**Comment by jskeet** [comment] 2020-04-06 06:17
When there are two channels, do you need them to be transcribed separately? If so, set `AudioChannelCount = 2` and `EnableSeparateRecognitionPerChannel = true`.

It's not clear what problem you're currently facing. You say "I faced error" but you haven't told us what that error is. Please give more details. If you have a stereo file but the API requires a mono file, I suggest you convert the file to mono first. There are plenty of free tools available for this, but it's rather outside the scope of the client library itself. I don't see anything specific to the C# client library in this issue - for more general advice about the Speech API, please use one of the [Speech-to-Text support channels](https://cloud.google.com/speech-to-text/docs/support). If you believe this is a problem with the client library itself of course, that's a different matter. Please be more specific.

**Comment by harsh-tukadiya** [comment] 2020-04-06 06:31
@jskeet 
Exception is **Grpc.Core.RpcException: 'Status(StatusCode=InvalidArgument, Detail="Must use single channel (mono) audio, but WAV header indicates 1 channels.")'**

I don't know it's stereo file or mono  file 
so, is there any idea for working both file mono and stereo

**Comment by jskeet** [comment] 2020-04-06 06:43
> I don't know it's stereo file or mono file

Then find that out by reading the file header. There are lots of libraries that will help you with that - I'd suggest starting with NAudio. If you discover you have a stereo file, convert it to a mono file. (Again, NAudio may well be able to do that for you.) If you are able to just drop one of the channels, that would be simplest - but I'm sure there are ways of merging channels instead.

Does the error message really say "but WAV header indicates 1 channels"? That would seem very odd, given that "1 channels" *is* a single channel.

**Comment by harsh-tukadiya** [comment] 2020-04-06 07:03
@jskeet 
Ya it's really gives that exception

**Comment by jskeet** [comment] 2020-04-06 07:22
Could you provide a complete example, including a wav file? (It doesn't need to be a real file you're using in production - just a test file that exhibits the same behaviour.) If I can reproduce that, I'll file an issue internally with the API team.

**Comment by jskeet** [comment] 2020-04-08 11:13
Please note that without further information, we will not be able to help on this issue. If there's no more information in a few days, I'll close this issue.

**Comment by jskeet** [comment] 2020-04-14 05:50
Closing due to lack of information.

**Closed by jskeet** 2020-04-14 05:50 UTC
Labels: api: speech, needs more info, type: question
