### ISSUE TITLE
PubSub Subscription randomly stops pulling messages from a topic. 

### ISSUE THREAD

**Issue by michaelcastle** [googleapis/google-cloud-dotnet#5231] opened 2020-08-05 03:17 UTC
PubSub Subscription randomly stops pulling messages from a topic. 
It seems to happen about once every day or so. 
Sometimes after a period of time it will fix itself and other times it will never start consuming messages.
The messages published to the topic are always very small.
There are no logs in pubsub with any errors and it never shows any messages failing to be processed due to a timeout error or any other error. (I have gone through Google's Support and can confirm pubsub is working as expected.)
The subscription does not return or have any exceptions and so never had to retry via Polly.
We suspect the issue is not a problem with pubsub but rather the .net client library?
We have other subscriptions for the same topic receiving messages but they have been written in go and they are working as expected.
We can see in the .net subscription for the topic that there are messages not being pulled from the queue.
The publisher is working ok and we can confirm that all messages are sent to the topic.

I am currently running a single subscriber per subscription and a single instance of the application with the following
- .net version: mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim 
- running: docker - linux
- nuget: \google.cloud.pubsub.v1\2.0.0

I have re-written the code a few times and it still happens. There are multiple (3 to 6) subscriptions running at once for different topics. The messages are very sporadic, sometimes there will be no messages for hours and other times there will be many. The failures happen with no pattern that we can determine.
Unfortunately I can not reproduce reliably as it is intermittent but here is the code.

```
namespace EventBus.GcpPubSub
{
    public class Subscription<E, T>
        where E : ISubscribeEvent, new()
        where T : class, ISubscriptionHandler<E>
    {
        private readonly ILogger<Subscription> logger;
        private readonly GcpPubSubSettings gcpPubSubSettings;
        private readonly IServiceProvider serviceProvider;

        private readonly string topicId;
        private readonly string subscriptionId;

        public Subscription(ILogger<Subscription> logger, IOptions<GcpPubSubSettings> gcpPubSubSettingsAccessor, IServiceProvider serviceProvider)
        {
            this.logger = logger;
            gcpPubSubSettings = gcpPubSubSettingsAccessor.Value;
            this.serviceProvider = serviceProvider;

            var @event = new E();
            topicId = @event.TopicId;
            subscriptionId = @event.SubscriptionId;
        }

        public void Start()
        {
            AddResilientSubscriptionAndHandler()
                .ContinueWith(t => logger.LogError("[pub/sub diagnostics] Unrecoverable error occured with {EventName} with {EventHandler}", subscriptionId, topicId),
                    TaskContinuationOptions.OnlyOnFaulted);
        }

        private async Task AddResilientSubscriptionAndHandler()
        {
            try
            {
                var retries = 0;
                var retryOnException = Polly.Policy
                    .Handle<Exception>()
                    .WaitAndRetryForeverAsync(
                        attempt => TimeSpan.FromSeconds(1),
                        (exception, calculatedWaitDuration, timespan) =>
                        {
                            retries++;
                            logger.LogError(exception, "[pub/sub diagnostics] Subscription Exception detected on attempt {retry}", retries);
                        }
                    );

                var retryOnConnectionLost = Polly.Policy
                    .HandleResult<Task>(t => t.IsCompleted)
                    .WaitAndRetryForeverAsync(
                        attempt => TimeSpan.FromSeconds(1),
                        (result, calculatedWaitDuration, timespan) =>
                        {
                            retries++;
                            logger.LogError("[pub/sub diagnostics] Subscription disconnection detected on attempt {retry}", retries);
                        }
                    );

                await retryOnException.ExecuteAsync(async () =>
                {
                    await retryOnConnectionLost.ExecuteAsync(async () =>
                    {
                        await AddSubscriptionAndHandler().ConfigureAwait(false);

                        logger.LogError("[pub/sub diagnostics] Subscriber returned. restarting");

                        return Task.CompletedTask;
                    }).ConfigureAwait(false);

                    logger.LogError("[pub/sub diagnostics] Subscription failed for some unknown reason. restarting");

                }).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "[pub/sub diagnostics] Subscription failed with exception.");
            }
            logger.LogError("[pub/sub diagnostics] Subscription failed and cannot restart for some unknown reason.");
        }

        private async Task AddSubscriptionAndHandler()
        {
            var subscriptionName = SubscriptionName.FromProjectSubscription(gcpPubSubSettings.ProjectId, subscriptionId);
            var subscriberClient = await SubscriberClient.CreateAsync(
                subscriptionName,
                settings: new SubscriberClient.Settings
                {
                    AckExtensionWindow = (TimeSpan?)TimeSpan.FromSeconds(30),
                    AckDeadline = (TimeSpan?)TimeSpan.FromSeconds(60),
                    FlowControlSettings = new Google.Api.Gax.FlowControlSettings(
                        maxOutstandingElementCount: 10,
                        MaxOutstandingByteCount: null
                    )
                }).ConfigureAwait(false);

            logger.LogTrace("[pub/sub diagnostics] Start Subscriber {@subscription}", subscriptionName);

            await subscriberClient.StartAsync(HandlerAsync).ConfigureAwait(false);
        }

        private async Task<SubscriberClient.Reply> HandlerAsync(PubsubMessage message, CancellationToken cancellationToken)
        {
            logger.LogInformation("[pub/sub diagnostics] Received message {MessageId} on topic {topicId}, published at {PublishTime}: {contents}", message?.MessageId, topicId, message?.PublishTime?.ToDateTime(), message?.Data?.ToStringUtf8());
            try
            {
                var data = message?.Data?.ToStringUtf8();
                var @event = data == null ? null : JsonSerializer.Deserialize<MessageDto>(data);

                var handler = serviceProvider.GetRequiredService<T>();
                await handler.Handle(@event, cancellationToken).ConfigureAwait(false);
                return SubscriberClient.Reply.Ack;
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "[pub/sub diagnostics] Message/Subscription failed {MessageId}: {message}", message?.MessageId, message?.Data?.ToStringUtf8());
            }
            return SubscriberClient.Reply.Ack;
        }
    }
}
```

**Comment by jskeet** [comment] 2020-08-05 05:47
Chris, do you have the bandwidth to look at this? (I've assigned the label "bug" for now, but obviously it *might* not be.)

**Comment by chrisdunelm** [comment] 2020-08-05 13:47
I will see if I can reproduce this. Thanks for the detailed issue report.
@michaelcastle roughly how long after starting subscribing does it stop receiving any further messages? This will be useful for me when trying to reproduce.
And you mention "multiple (3 to 6) subscriptions running at once for different topics" - do you mean you have similar code to this running multiple times concurrently within the same .NET process, one for each subscription? And do you have these multiple subscribers all running when you see this problem? To be clear, this is expected to work fine, I just want to understand your situation as well as possible.

**Comment by michaelcastle** [comment] 2020-08-05 21:23
It can take from 15 minutes and up to maybe 4-5 days max for one of the subscriptions to stop receiving messages.
All the subscriptions are running in the same ASP.NET Core Web Application. They all begin on startup and run the entire time. The topics receive messages very sporadically.

**Comment by chrisdunelm** [comment] 2020-08-06 09:27
Thanks for the extra details - one more question: How many messages are in each burst, and how fast would the messages typically be published? If you could give me some rough ranges that'd be helpful.

I've had a test running for ~16 hours now to try to reproduce this which simulates the publication gaps+bursts you describe with a continuous subscription, but so far it's all working as expected. I'll continue running the test.

**Comment by michaelcastle** [comment] 2020-08-06 21:43
Hi, thanks for looking into this. Does this graph help show the burstiness over the last week?

![image](https://user-images.githubusercontent.com/23348743/89585284-ec4b6900-d880-11ea-9e15-3a453ff1998f.png)

You can see in the next graph the subscription failing Fri 31 and only processing after the service was manually restarted

![image](https://user-images.githubusercontent.com/23348743/89585404-2288e880-d881-11ea-9bdd-714c345723e8.png)

The other go services with another different subscription to this topic all processed fine.

**Comment by michaelcastle** [comment] 2020-08-13 21:45
If it helps to reproduce, the processing for each message can take from 1 to 3 seconds to complete. I am not sure if that is relevant.

**Comment by chrisdunelm** [comment] 2020-08-17 11:48
Thanks @michaelcastle. Are those 1-to-3 seconds synchronous code? So is this using the thread all that time? Or is it async code that spends most of it's time waiting on something (e.g. IO)?

**Comment by michaelcastle** [comment] 2020-08-17 22:18
The 1-3 seconds is async code. Mostly it does a bunch of external api calls and they take about 300ms each

**Comment by michaelcastle** [comment] 2020-08-24 03:31
Hi, just wondering if you've been able to reproduce this issue or if there is any more information regarding its progress?

**Comment by chrisdunelm** [comment] 2020-08-25 16:05
@michaelcastle I'm running two long-running tests now, one on Windows and one on Linux. They started a few hours ago, so I expect to be running them for another few days. I haven't yet seen any reproduction of your failure case.

**Comment by cviktor** [comment] 2020-09-02 16:08
We have the same problem with a very similar setup. We have basically a log message that says a message was published and when we receive a message in a different service the first thing we do is another log message to indicate that we received something. Sometimes it is up to 60 sec+ for a published message to be received by a subscriber. We don't have any error or connection issue, because that it is logged and we have recovery logic for a disconnected subscription, but that's not the case here. 

We are running in GPC Kubernetes, we also have services written in Go that has no issues like this. 
The environment is the same as described in the original comment (runtime, nuget version etc.).
Maybe it's worth mentioning that we see this error very randomly and mostly on the test system where there is just a few interactions and message. On the other hand our production system just went live so we also have just a few users there, therefore I cannot confirm if the issue persist with higher number of messages.

Our first idea was that there is some performance degradation or cold start for a given pubsub topic if it's not used for a long time, but I think 60 sec or more is too much of a delay even for that.

Are there any internal logging or diagnostics for the pubsub library that we can use to monitor the connectivity status or something like that? Maybe log the GRPC messages?

**Comment by chrisdunelm** [comment] 2020-09-03 16:11
@cviktor thanks for the report - what kind of application is this? I.e. ASP.NET [core]; a console app; ...? 
Do you always receive all published messages (albeit with a long delay)? Or do subscriber(s) sometimes just totally stop receiving messages, as seen by @michaelcastle?

I've been running various long-term tests for about a week now, and have not been able to reproduce the error. However I have not been running them inside docker/kubernetes, and I'm running both publishers and subscribers in a console app, not ASP.NET. I will try containerizing and ASP.NET next, in case these environments are part of the cause.

If you were able to create a simple test application that reproduces this problem, that'd be really helpful. Something like a standalone console or asp.net application that I can start on a machine and wait for a few days to see it fail.

**Comment by cviktor** [comment] 2020-09-04 08:22
@chrisdunelm 
We are running ASP.NET Core applications.
We receive every message, no message lost, or possibly received by another client for the same subscription.
It's not totally stopping just "slowing down" but eventually we receive the message.
I will try to create some example but the problem is that I cannot reproduce the error either. Mostly QA reports some bug and we can see in the logs, that the reason for the slowness or the timeout was a slow pubsub communication in the system.
I will report back if I find something useful.

**Comment by michaelcastle** [comment] 2020-09-09 04:31
I noticed the library has just been updated to version 2.1. I've upgraded my services to use this and I'm currently testing if that has fixed the issue. It's been running 2 days and no failures so far. I will keep monitoring for failures for the next week or so and report back.

**Comment by michaelcastle** [comment] 2020-09-15 04:09
So far the issue is still happening after the 2.1 upgrade (possibly less frequently) but so far every time it has fixed itself within 6-10 minutes which is a definite improvement which may or may not be coincidence. Interestingly some failures now happen across services at the same time and fix themselves at the same time, which is unusual.
In our environment we have a single machine (2 vCpu 7.5GB ram) with a single VM for roughly 23 docker container services for the backend and another VM with 2 front end services. (We know not ideal and moving to kubernetes asap)

**Comment by jskeet** [comment] 2020-10-06 06:53
@michaelcastle: Now we've had a bit more time for observation, could you let us know if the problem still occurs, and with what frequency? (And is it still fixing itself in 6-10 minutes?)

**Comment by michaelcastle** [comment] 2020-10-06 07:06
@jskeet It is still happening and it still seems to reliably fix itself in about 10 minutes, which is a definite improvement from the previous 2.0 version. We recently migrated our dev environment from VM's to kubernetes (with 1 instance of the subscriber app) and so far I haven't seen it fail there. It's been a week or 2 without a fail in our dev environment. We will soon migrate the UAT environment as well and I was going to monitor that before I was more confident that it was no longer occurring.

**Comment by jskeet** [comment] 2020-10-06 07:17
Interesting, thanks. I don't know enough about PubSub to speculate on why that change would affect things, but I'm glad it's working for you in dev...

**Comment by michaelcastle** [comment] 2020-11-13 02:45
As an update, it doesn't seem to fail as often or as long but **still** randomly fails for several minutes.

**Comment by michaelcastle** [comment] 2020-12-04 01:45
I've now been monitoring this for a while now and it seems to be reliable after the move to k8s. Which is great news for us.

**Comment by jskeet** [comment] 2020-12-04 07:33
@michaelcastle: Very glad to hear it! I'll close this for now, but please add another comment if you have more information or if there are any further issues.

**Closed by jskeet** 2020-12-04 07:33 UTC
Labels: api: pubsub, priority: p2, type: bug

**Comment by gothraven** [comment] 2022-01-07 16:40
It is reassuring to see we're not the only ones having this issue.

For a while now, we noticed that the code just stops pulling new messages so randomly, sometimes it takes few weeks, sometimes days before that happens, and we always had to re-start the service for this to work again.

We're using:
- `@google-cloud/pubsub: 2.18.3`
- `node: 16.5.0-alpine3.14`

This was marked as resolved, but I don't understand what we're supposed to do to fix it.

**Comment by jskeet** [comment] 2022-01-07 16:48
@gothraven: This issue is in the .NET repository. If you're seeing a problem with the Node client, please could you file an issue in https://github.com/googleapis/nodejs-pubsub?

**Comment by gothraven** [comment] 2022-01-07 16:49
@jskeet Honestly didn't even notice it was for .NET 😄 my bad, I can remove these comments if you'd like to !

**Comment by jskeet** [comment] 2022-01-07 16:51
@gothraven: Not a problem. Might as well leave the comments, in case they're useful for anyone else who happens to see something similar. If you reference this issue when you create a Node one, the link will be there for future folks...
