### ISSUE TITLE
OperationsClient in library version 2.0.0 Throws Grpc.Core.RpcException

### ISSUE THREAD

**Issue by a3caicedo** [googleapis/google-cloud-dotnet#4843] opened 2020-04-09 04:50 UTC
When using the version 2.0.0  library, the OperationsClient
```
var operationsClient = new OperationsClientBuilder { CredentialsPath = "GoogleServiceAccount.json" }.Build();
var operation = operationsClient.GetOperation("3637912932635009144");
```
 throws the following exception and stacktrace:
```
Grpc.Core.RpcException: Status(StatusCode=Cancelled, Detail="Received http2 header with status: 404")
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.LongRunning.Operations.OperationsClient.GetOperation(GetOperationRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.<>c__DisplayClass10_0.<WithCallSettingsOverlay>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.LongRunning.OperationsClientImpl.GetOperation(GetOperationRequest request, CallSettings callSettings)
   at Google.LongRunning.OperationsClient.GetOperation(String name, CallSettings callSettings)
   at TranscripcionAPI.Controllers.WeatherForecastController.GetResult(String operationName) in C:\Users\andresfelipe\source\repos\TranscripcionAPI\TranscripcionAPI\TranscripcionAPI\Controllers\WeatherForecastController.cs:line 146
```

**Comment by jskeet** [comment] 2020-04-09 05:54
That's not the format of operation resource name I'd expect to see. It's odd that 404 is being translated into cancelled somewhere, but I believe the problem is basically with the operation name.
Which API is the operation part of, and where did you get the operation name from? I suspect it should be "operations/3637912932635009144".

**Comment by jskeet** [comment] 2020-04-09 05:55
(I've marked this as a question rather than as a bug as I very much doubt there's a client library bug here - I believe we're making the RPC as requested, and it's coming back with an error response. So what we're trying to do is work out how to make a request that doesn't error.)

**Comment by a3caicedo** [comment] 2020-04-09 18:16
I've got that operation name as a result of calling the SpeechClient's LongRunningRecognize method:

```
var speech = new SpeechClientBuilder { CredentialsPath = "GoogleServiceAccount.json" }.Build();
var longOperation = speech.LongRunningRecognize(new RecognitionConfig()
{
    Encoding = RecognitionConfig.Types.AudioEncoding.Flac,
    SampleRateHertz = 16000,
    LanguageCode = "en",
}, RecognitionAudio.FromStorageUri(storageURI));
Debug.WriteLine($"Operation Name: { longOperation.Name}"); 
```

I've got the operation successfully with Google Cloud SDK Shell with:
```
gcloud ml speech operations describe 3637912932635009144
```
![image](https://user-images.githubusercontent.com/63386734/78927131-f6d92b80-7a63-11ea-8740-37be9d34b8de.png)

And I've tried postman as well:

![image](https://user-images.githubusercontent.com/63386734/78927329-4e779700-7a64-11ea-9af8-8a3e404f8b0f.png)

**Comment by jskeet** [comment] 2020-04-09 19:06
Thanks for the extra information. That's definitely surprising. I suspect this *may* be a bug in the Speech API. Could you try using a name of `"operations/3637912932635009144"`?

I'll try to reproduce this myself, but please be aware that tomorrow and Monday are public holidays in the UK. I may find the time to reproduce it anyway, but we'll see.

**Comment by a3caicedo** [comment] 2020-04-09 19:26
Hi! I just tried the name `"operations/3637912932635009144"` but it still throws the same exception:

`Exception thrown: 'Grpc.Core.RpcException' in System.Private.CoreLib.dll
Status(StatusCode=Cancelled, Detail="Received http2 header with status: 404")`

Thank you for your help.

**Comment by jskeet** [comment] 2020-04-09 19:33
Okay. I'll try to reproduce tomorrow. Any other information, e.g. are you behind a proxy? Does everything else work?

**Comment by a3caicedo** [comment] 2020-04-09 20:01
Well, what I've done is:

1. Upload a file to a Google Cloud Storage Bucket with **StorageClient** from the `Google.Cloud.Storage.V1 v2.5.0 library`. It works fine.
2. Run a LongRunningRecognize on the uploaded file with the **SpeechClient** from the `Google.Cloud.Speech.V1 V2.0.0 library`. This works fine too.
3. Query the LongRunningRecognize Operation's Result with the **OperationsClient** from the `Google.Cloud.Speech.V1 V2.0.0 library`. This is where the exception is thrown.

I´m not behind a proxy.

**Comment by jskeet** [comment] 2020-04-09 20:14
Ah, I have it now - sorry, I should have paid more attention before to how you were making the call. You shouldn't be building a new `OperationsClient` yourself. It doesn't know which service to ask for the operation.

Instead, use the `SpeechClient` you used in step 2, and call `PollOnceLongRunningRecognize` to fetch the operation associated with the `LongRunningRecognize` operation.

(If you *really* want to use `OperationsClient` directly, you can do so by specifying the speech endpoint, but that's not the intended way of using it.)

I suspect the reason you're getting a 404 is because it's calling to some endpoint that doesn't really have an operations service implementation.

**Comment by a3caicedo** [comment] 2020-04-09 20:33
That's right!! That way did the trick:
```
var speech = new SpeechClientBuilder { CredentialsPath = "GoogleServiceAccount.json" }.Build();
var operation = speech.PollOnceLongRunningRecognize(operationName);
```
I've been searching through the Internet over the last week, but couldn't find any specific example.

Thank you very much!

**Comment by jskeet** [comment] 2020-04-09 20:35
Hooray! Very glad we've sorted it. I'll close this issue now.

**Closed by jskeet** 2020-04-09 20:35 UTC
Labels: needs more info, type: question
