### ISSUE TITLE
Insight into "GOAWAY received" responses

### ISSUE THREAD

**Issue by veatcha** [googleapis/google-cloud-dotnet#2829] opened 2019-01-24 16:49 UTC
We are seeing sporadic errors of this type when invoking SetAysnc() and CreateAsync() on DocumentReferences:
```
Status(StatusCode=Internal, Detail="GOAWAY received")

Grpc.Core.RpcException:
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions+<>c__DisplayClass0_0`2+<<WithRetry>b__0>d.MoveNext (Google.Api.Gax.Grpc, Version=2.5.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47)
   at Google.Cloud.Firestore.WriteBatch+<CommitAsync>d__15.MoveNext (Google.Cloud.Firestore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0)
   at Google.Cloud.Firestore.DocumentReference+<SetAsync>d__24.MoveNext (Google.Cloud.Firestore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=185c282632e132a0)
```

And I'm looking for insight on what might cause them.

#### Environment details

  - OS: Windows
  - .NET version: 4.6.2
  - Package name and version: Google.Cloud.Firestore 1.0.0-beta17, Grpc.Core 1.18.0

#### Steps to reproduce

- I'm unable to reproduce this consistently, or find a discernible pattern that causes the error.  I have seen other very specific errors related to concurrency issues on documents - so I'm assuming if we will see those errors when exceeding the documented 1 write/doc/sec threshold. 

- In terms of overall request rate, we typically range between 200-500 requests/min with occasional bursts to 1-2k per min.  I have not found that the errors correspond at all to the bursts of increased activity.

- We've implemented some retry logic with exponential backoff and some randomness, and in some cases that will allow the request to succeed, and in others, it will fail over the course of 5 retries over the following minute or two.

Thank you!

**Comment by jskeet** [comment] 2019-01-24 16:57
Thanks for the issue - I'll need to pass this on to server folks to find out about, as I doubt that it's .NET-specific. Will let you know of any updates, or if we need specific information.

**Comment by jskeet** [comment] 2019-01-25 08:05
We'd like to create an internal bug to track this. Could you email me (jonskeet@google.com) with your project ID as well as details of where this code is running (e.g. a VM on GCP, or desktops in your company, or somewhere else) in case that's relevant?

**Comment by jskeet** [comment] 2019-03-22 07:43
Hi @veatcha - apologies for the lack of communication since January.

There's been a lot of activity on the internal bug and we *may* have a solution, which (if I've understood correctly) will require an update to Grpc.Core - but the fix isn't in a package yet. I'll let you know when there's a version that's worth trying for this.
In the meantime, are you still seeing the issue regularly? (I understand if your retry logic makes that hard to determine.)

**Comment by veatcha** [comment] 2019-03-22 19:26
Hi Jon -

Thanks for following up!  Yes, we still see some sporadic issues that get
past the retry logic. Somewhere between 5-20 times a day (out of thousands
of requests).

Thanks,
Andrew

**Comment by jskeet** [comment] 2019-05-23 08:44
There's now a release of Grpc.Core 1.21.0. There are lots of different *potential* causes for this issue, which makes it hard to know for sure whether it'll help, but if you're happy to try that (just by adding an explicit dependency on Grpc.Core 1.21.0 from your app) and see if it helps, that information would be really useful. Apologies that this is taking so long to resolve.

**Comment by veatcha** [comment] 2019-06-11 18:00
I've got Grpc.Core 1.21.0 running now as well as Google.Cloud.Firestore 1.0.0-beta20.

That's been released since around 6/4, and we've noticed since then a steady stream of the GOAWAY errors occurring - about 500 since then, spaced throughout the day.

One problem is it seems to correlate with other issues we've been experiencing, that we've been trying to track down directly with the Firestore team.  On 5/21, the response time on all of our requests to Firestore skyrocketed without any changes in production code/usage on our end, and stayed there roughly until we updated our application with the latest GRPC/Firestore dependencies.  We appear to have traded the elevated response time for a slow but steady stream of the GOAWAY errors.  It's difficult to untangle what is related here, but I'm happy to try to dig up and provide additional information.  It does seem like something is changed on the Firestore end of things that is causing fluctuations in behavior though.

**Comment by jskeet** [comment] 2019-06-11 18:03
Thanks for the update. Sorry to hear the GOAWAY errors are still occurring, and the response time as well. I'll follow up internally with the Firestore team to see if they have further suggestions.

**Comment by jskeet** [comment] 2019-06-13 14:18
@veatcha: Our gRPC team have requested gRPC logs with `GRPC_TRACE=client_channel_routing,pick_first` - does that sound feasible for you to obtain? (I completely understand it could be very difficult.) If it's feasible, let me know and I'll walk you through the steps to enable that logging, and possibly dump it to a file instead of stdout...

**Comment by veatcha** [comment] 2019-06-13 14:30
@jskeet - I can definitely do that - I did some work previously to get logging out given our environment (running in Service Fabric in Azure, pumping traces out to Application Insights) - I ended up implementing a `Grpc.Core.Logging.ILogger` and setting it using `GrpcEnvironment.SetLogger` - I don't recall how far I got it, but I will resume that work - and if there's a better approach, I'm all ears.

**Comment by jskeet** [comment] 2019-06-13 14:39
That's definitely the way to go - it sounds like you know all about it then :)

Do you need any more information from me about what we're looking for, beyond that list of trace categories? Obviously it would be useful if you could also provide information about when you see the errors, so we can correlate them in the logs.

Thank you so much for being so patient and helpful as we try to get to the bottom of this.

**Comment by veatcha** [comment] 2019-06-18 13:34
@jskeet I've grabbed some logs - what's the best way to get them to you?

**Comment by jskeet** [comment] 2019-06-18 14:05
If you could email them to jonskeet@google.com, that would be great. Thanks so much!

**Comment by jskeet** [comment] 2019-08-19 12:37
Hi @veatcha, I assume you're still seeing this?

I'm going to try writing a small app which does nothing but read and write documents, to see if I can reproduce this.

Do you have any suggestions in terms of the minimum set of operations you do in order to see it? For example, if you have one service that *only* ever performs reads (or *only* performs writes) and still encounters the problem, that would be helpful.

**Comment by jskeet** [comment] 2019-09-16 06:46
I've been running a test for the last 2 1/2 days. 5 tasks have each been fetching and updating one document each. (Each task has its own document.)

In that times, we've made 23717095 requests, with 8 failures;

- 1 timeout
- 4 socket closed
- 3 connection reset by peer

Closing this as "not reproducible"; we can always reopen later if necessary.

**Closed by jskeet** 2019-09-16 06:46 UTC
Labels: :rotating_light:, api: firestore, priority: p2, type: bug

**Comment by nforysinski** [comment] 2021-10-05 18:02
Hi @jskeet 

I wanted to pick up where @veatcha left off. It been a little over a year, and we've found ways to mitigate this issue a bit here and there, but are starting to see it re-appear stubborn places that are harder to workaround.

To answer the original question you asked on 8-19-19

> Hi @veatcha, I assume you're still seeing this?
> 
> I'm going to try writing a small app which does nothing but read and write documents, to see if I can reproduce this.
> 
> Do you have any suggestions in terms of the minimum set of operations you do in order to see it? For example, if you have one service that _only_ ever performs reads (or _only_ performs writes) and still encounters the problem, that would be helpful.

We are certainly still seeing this. It appears mostly in places that are doing writing only -- most of our apps either entirely read or entirely write. Few (any?) read and write in one service/application. I don't believe we've ever encountered this error in a read scenario.

In the locations we see this occur, we have multiple service writing to different docs, but often at the same exact times. The scenario in question is a service that handles multiple messages off a queue, and because its scaled up, we could be doing many of them at a time.

I agree with @veatcha initial assessment -- we dont seem to see the errors directly correlated with activity. More activity isn't guaranteed to cause the problem, and it can happen at times of relatively little activity, or in services that do fairly atomic operations (i.e. simply write 2 docs with fair amount of data in them, in the level of KB, not MB). 

Here is a recent version of the error we are seeing:

`Status(StatusCode="Unavailable", Detail="GOAWAY received", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1633356923.392000000","description":"Error received from peer ipv4:142.250.188.42:443","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1068,"grpc_message":"GOAWAY received","grpc_status":14}") `

We are using Google.Cloud.Firestore nuget package version 2.3.1, and Grpc.Core 2.37.0

What else can I provide?

**Comment by jskeet** [comment] 2021-10-06 08:05
@nforysinski: How feasible would it be for you to create a complete example that demonstrates the problem for you? A plain console app would be ideal here, but I'll take anything I can get, of course.

Using a single FirestoreClient is expected and preferred - that definitely *shouldn't* be causing a problem.

You say you've got multiple services writing to different docs at the same time - do you have logs confirming that the failed RPCs occur when writing to a doc that another service has written to at "pretty much the same time"? That would definitely help in terms of trying to reproduce the issue. I completely understand if you *don't* have such logs.

**Comment by nforysinski** [comment] 2021-10-07 21:04
@jskeet sorry for the delay but I finally got the application put together. Its available here: https://github.com/nforysinski/firestore-sample

I added some notes in the readme, but please let me know if anything is unclear or not working. There is a `ConfigProvder` class for you to put your specific firestore credentials.

**Comment by jskeet** [comment] 2021-10-07 21:11
Thanks - I'll have a closer look tomorrow.

Just to confirm, have you been able to see the problem running this sample app - and if so, how many concurrent "copies" of the app did you need running to see it?

**Comment by nforysinski** [comment] 2021-10-07 21:20
> Thanks - I'll have a closer look tomorrow.
> 
> Just to confirm, have you been able to see the problem running this sample app - and if so, how many concurrent "copies" of the app did you need running to see it?

I have not tried to recreate it with the app -- we see it enough in production to know its still happening. I will run some tests tomorrow with it scaled up a bit and against a more used project.

**Comment by jskeet** [comment] 2021-10-14 11:23
One extra question, based on looking at the internal discussion back in 2019: could you let me know what platform you're accessing Firestore from? I'm wondering if there's a network connection issue somewhere, possibly around keepalive processing...

**Comment by jskeet** [comment] 2021-10-18 15:50
Ah... and do you happen to know whether other network operations on that server were "normal" during that time? (I completely understand if your logs don't happen to reveal that.)

It feels like we're getting closer. I'm wondering whether something on the server has effectively reset the network stack or something similar (while the app is still running). I could be completely off, of course, and it may be *just* Firestore that's having the problem...

**Comment by nforysinski** [comment] 2021-10-19 14:11
Thats a great question -- I went back to our logs in App Insights and it appears that _every_ instance of this issue was on the same VM. I am hoping thats because thats actually true and not an artifact of something being logged incorrectly. I did confirm other log messages came from other VMs so I do actually believe there might have been something up with that particular VM. Why that might only affect GRPC and Firestore, I can't say.

**Comment by jskeet** [comment] 2021-10-21 14:38
@nforysinski: Thanks very much for coming back to me. I suggest we reclose this for now - but if it happens again, please file a new issue (so we can avoid repeatedly notifying the original issue raiser for this one!) and we'll see whether we can spot a pattern.

**Comment by dex3r** [comment] 2022-01-08 19:16
I just want to report that I've started seeing this exception, specifically:

> Exception: Grpc.Core.RpcException: Status(StatusCode=\"Unavailable\", Detail=\"GOAWAY received\", DebugException=\"Grpc.Core.Internal.CoreErrorDetailException: {\"created\":\"@1641668302.728649582\",\"description\":\"Error received from peer ipv4:172.253.120.95:443\",\"file\":\"/var/local/git/grpc/src/core/lib/surface/call.cc\",\"file_line\":1068,\"grpc_message\":\"GOAWAY received\",\"grpc_status\":14}\

[(stack trace)](https://gist.github.com/dex3r/65ba7ffef915c85c13336cefe650482d)

I won't be able to reproduce this for now, as I have too small traffic, but I may come back with this in the future.
