### ISSUE TITLE
Google.Cloud.Asset.V1 issue enumerating results on Linux

### ISSUE THREAD

**Issue by davidobrien1985** [googleapis/google-cloud-dotnet#5861] opened 2021-01-20 05:11 UTC
```
<PackageReference Include="Google.Cloud.Asset.V1" Version="2.6.0" />
    <PackageReference Include="Grpc.Core" Version="2.34.0" />
```

netcoreapp3.1

As mentioned on the other [issue ](https://github.com/googleapis/google-cloud-dotnet/issues/5835#issuecomment-763272314) we referenced the Grpc directly and that got rid of the `FileNotFound` error.
However, now we are, still only on Linux, experiencing issues where our GCP Asset Inventory query fails.

We see this error in prod and also locally with the debugger attached.

![image](https://user-images.githubusercontent.com/8554521/105129394-1516a080-5b39-11eb-9a70-5a217e9f0362.png)

The code used to work before we ended up in this "having to have to reference Grpc directly" situation and it works perfectly fine on Windows (some of our devs are on Windows and tested it, but our prod environment is Linux).

```
var gcpResourceTypes = new string[] {
                "appengine.googleapis.com/Application",
                "container.googleapis.com/Cluster"
            };
var assetClientBuilder = new AssetServiceClientBuilder { JsonCredentials = JsonConvert.SerializeObject(gcpKey) };
                var assetClient = await assetClientBuilder.BuildAsync();

                var requestOptions = new SearchAllResourcesRequest { Scope = "", PageToken = "" };
                requestOptions.Scope = $"projects/{projectId}";
                if (gcpResourceTypes != null)
                {
                    requestOptions.AssetTypes.AddRange(gcpResourceTypes);
                }
                do
                {
                    var pagedResponse = assetClient.SearchAllResourcesAsync(requestOptions).AsRawResponses();
                    var page = pagedResponse.First();

                    resources.AddRange(page.Results);
                    requestOptions.PageToken = page.NextPageToken;

                } while (!string.IsNullOrEmpty(requestOptions.PageToken));
```

I hope this example is enough for you to reproduce.
Again, never was an issue until we had to reference Grpc directly (due to the Azure Functions issue).

On @jskeet 's recommendation we updated

`var page = pagedResponse.ToEnumerable<SearchAllResourcesResponse>().First();`

However, this still fails with the same error.

**Comment by jskeet** [comment] 2021-01-20 05:16
Are you able to reproduce the error on Linux in a regular console app, or is this *only* a problem under the Azure Functions host?

**Comment by jskeet** [comment] 2021-01-20 05:18
Also please clarify this:

> We see this error in prod and also locally with the debugger attached.

Do you mean you're only seeing the problem when the debugger is attached, but both locally and in prod? If you're seeing it when a debugger *isn't* attached, what does that look like? (The only error you've shown so far is in the debugger.)

**Comment by davidobrien1985** [comment] 2021-01-20 05:21
> Are you able to reproduce the error on Linux in a regular console app, or is this only a problem under the Azure Functions host?

Need to test this. Might have to get one of our devs to do this though later on. I'm dangerous enough with code to make small changes ;) I'll let you know how we go. For now, this happens on the Azure Functions host.

> Do you mean you're only seeing the problem when the debugger is attached, but both locally and in prod? If you're seeing it when a debugger _isn't_ attached, what does that look like? (The only error you've shown so far is in the debugger.)

No, there's no debugger in prod.
In prod the Function times out after 5 minutes and the app stops. No exception is thrown.

**Comment by jskeet** [comment] 2021-01-20 05:26
Okay. I'll write a small console app myself first to check I can get that working on Linux and see sensible results, then I'll try it as a function. It may not be today though (with lots of other things going on).

**Comment by davidobrien1985** [comment] 2021-01-20 06:17
Well, what do you know... I managed :D

```
using Google.Cloud.Asset.V1;
using Google.Protobuf.Collections;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        public static void Main(string[] args)
        {
            var gcpResourceTypes = new string[] {
                "appengine.googleapis.com/Application",
                "container.googleapis.com/Cluster"
            };
            var resources = GetResources(gcpResourceTypes, args[0], args[1]);
            foreach (var resource in resources.Result)
            {
                Console.WriteLine(resource.DisplayName);
            }
        }
        public static async Task<IEnumerable<ResourceSearchResult>> GetResources(IEnumerable<string> assetTypes, string jsonPath, string projectId)
        {
            var resources = new RepeatedField<ResourceSearchResult>();
            var assetClientBuilder = new AssetServiceClientBuilder { CredentialsPath = jsonPath };
            var assetClient = await assetClientBuilder.BuildAsync();
            var requestOptions = new SearchAllResourcesRequest { Scope = "", PageToken = "" };
            requestOptions.Scope = projectId;
            requestOptions.AssetTypes.AddRange(assetTypes);
            do
            {
                var pagedResponse = assetClient.SearchAllResources(requestOptions).AsRawResponses();
                var page = pagedResponse.First();

                resources.AddRange(page.Results);
                requestOptions.PageToken = page.NextPageToken;

            } while (!string.IsNullOrEmpty(requestOptions.PageToken));
            return resources;
        }
    }
}
```

![image](https://user-images.githubusercontent.com/8554521/105134857-295f9b00-5b43-11eb-8cb3-4c76dc2122ba.png)

Works as a console app then. 
Any idea why this wouldn't work in an Azure Functions runtime? (I know you're far from being responsible or even super familiar with that runtime) Appreciate any pointers.

**Comment by jskeet** [comment] 2021-01-20 06:27
I'm just looking at your do/while loop, by the way - it seems to be equivalent to just:

```csharp
resources = await assetClient.SearchAllResourcesAsync(request).ToListAsync();
```

The returned `PagedAsyncEnumerable` is specifically designed to avoid user code having to include that sort of loop.
(I'm still trying it with your code though... I wouldn't expect that to be the issue.)

I note there's a potentially-significant difference between your console app and the function, by the way - you use `SearchAllResourcesAsync` in the function, but `SearchAllResources` in the console app. Although I couldn't get your function code to compile, as `First()` doesn't exist in `IAsyncEnumerable<T>`. Does your function *actually* use async and then use `await pagedResponse.FirstAsync()`?

**Comment by jskeet** [comment] 2021-01-20 06:32
Okay, I've reproduced the issue now. Investigating - although I suspect unless it's actually pretty simple to fix, I'll rapidly be in "I don't know enough about gRPC to fix this" territory.

**Comment by davidobrien1985** [comment] 2021-01-20 06:34
Sorry, ignore the `async`, no, that was just a test and shouldn't have been copied here. It doesn't make a difference to the issue.

> Okay, I've reproduced the issue now. Investigating - although I suspect unless it's actually pretty simple to fix, I'll rapidly be in "I don't know enough about gRPC to fix this" territory.

Any help is appreciated. Great OSS support @jskeet !

**Comment by jskeet** [comment] 2021-01-20 06:53
Okay, so far:

- I've reproduced it in Linux in Docker; the console app works, and the function doesn't
- Using the simpler code of `var resources = assetClient.SearchAllResources(requestOptions).ToList();` doesn't change this (although I'd recommend using it)
- Changing to Grpc.Core versions 2.34.1 or 2.35.0-pre1 doesn't help

Will keep looking (although again, time will be spotty). Ideally I'd like to get to a situation where I can present a complete example to the gRPC team, as I *suspect* they'll be the ones to actually diagnose this.

**Comment by jskeet** [comment] 2021-01-20 12:44
I've reproduced this in a simpler way without involving the client libraries at all, and filed https://github.com/grpc/grpc/issues/25208 to cover it. I'll close this issue now as there's nothing we can do within the client library repo to fix this, I'm afraid. You may well want to share that issue link with the Azure Functions folks as well.

**Closed by jskeet** 2021-01-20 12:44 UTC
Labels: external, type: bug

**Comment by davidobrien1985** [comment] 2021-01-21 06:11
@jskeet thanks Jon! Very much appreciate your great support with this and the other issue!
