### ISSUE TITLE
Google.Api.Gax.Platform.Instance().ProjectId is null when deployed to Google Cloud Run

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/google-cloud-dotnet#3086] opened 2019-05-20 23:23 UTC
Without it, I have to query the metadata server, which is many more lines of code:
```
            // Query the metadata server.
            HttpClient http = new HttpClient();
            http.DefaultRequestHeaders.Add("Metadata-Flavor", "Google");
            http.BaseAddress = new Uri(
                @"http://metadata.google.internal/computeMetadata/v1/project/");
            return http.GetStringAsync("project-id").Result;
```

**Comment by jskeet** [comment] 2019-05-21 05:06
Closing as a duplicate of https://github.com/googleapis/gax-dotnet/issues/314 - but yes, we want to fix this.

**Closed by jskeet** 2019-05-21 05:06 UTC
