### ISSUE TITLE
 Google.Cloud.Speech.V1.RecognitionConfig.SpeechContexts has no effect on results

### ISSUE THREAD

**Issue by philipag** [googleapis/google-cloud-dotnet#3010] opened 2019-04-08 22:18 UTC
#### Environment details

  - OS: Android
  - .NET version: 2.0
  - Package name and version:  Google.Cloud.Speech.V1    v1.1.0

#### Steps to reproduce

Given the code below, the sample phrase "shwazil hoful day" is not recognized.  In fact it does not seem to matter which phrases I add (none of them have any effect on results) so perhaps the C# classes are out of date and sending the wrong JSON to google cloud?

			string[] tagPhrases = { "shwazil hoful day" };

			var sc = new SpeechContext();
			sc.Phrases.Add(tagPhrases);
			var phrases = new List<SpeechContext>();
			phrases.Add(sc);

			var config = new RecognitionConfig
			{
				Encoding = RecognitionConfig.Types.AudioEncoding.Flac,
				SampleRateHertz = 16000,
				LanguageCode = LanguageCodes.English.UnitedStates,
			};
			config.SpeechContexts.Add(phrases);

			var audio = RecognitionAudio.FromFile(path + "/shwazil_hoful.flac");

**Comment by jskeet** [comment] 2019-04-09 06:25
There's no JSON involved (this library uses Protobuf and gRPC) and the classes are up to date.
Does recognition work fine apart from this? Could you attach the flac file (zipping if necessary) so I can reproduce it with the same data? In the meantime I'll try recording a flac file myself.

**Comment by jskeet** [comment] 2019-04-09 06:36
Firstly, I'm intrigued that you're talking about Android as the OS. We don't support Android as a platform. If you're using some custom way of getting gRPC working on Android, it's *possible* that that's having an impact here, but I'd expect the whole thing to fail or work.

I've just tried it myself, and although it couldn't recognize your custom phrase, I tried a different one of "fleegle blurple" and it worked fine. Here's the code I used, which demonstrates a slightly simpler way of building up the config:

```csharp
var config = new RecognitionConfig
{
    Encoding = RecognitionConfig.Types.AudioEncoding.Flac,
    SampleRateHertz = 16000,
    LanguageCode = LanguageCodes.English.UnitedStates,
    SpeechContexts = { new SpeechContext { Phrases = { "fleegle blurple" } } }
};

var audio = RecognitionAudio.FromFile("test2.flac");

var client = SpeechClient.Create();
var response = client.Recognize(config, audio);
Console.WriteLine(response);
```

(Even if you want to create the `SpeechContext` directly, you can just add a `string` to the `Phrases` property, without creating an array. Likewise you can add a `SpeechContext` directly to the `SpeechContexts` property without creating a list.)

This gives the right result for the file I'd recorded, whereas without the custom phrase it recognized "fleegle" as "pliego".

I'm going to close this issue now as I don't believe there's an issue in the .NET client library. For general Cloud Speech API support (e.g. for help tuning your custom phrases), please see the [support options page](https://cloud.google.com/speech-to-text/docs/getting-support).

**Closed by jskeet** 2019-04-09 06:36 UTC

**Comment by philipag** [comment] 2019-04-09 09:53
The sample I am using is actually from Microsoft: "gs://speech-demo/shwazil_hoful.flac" which is supposed to produce the result "shwazil hoful day" but does not.  Can you try this out?

Could you attach the sample audio file you create which works with the phrase "fleegle blurple"?  This would be a good sanity test for me since other test phrases I used appear to have no effect.

I am using Xamarin Forms and your package supports .net standard and therefore also Xamarin.  Everything appears to function normally so perhaps after some testing it makes sense to add Xamarin Forms as a supported platform?

I am using the more complicated declaration method because the phrases are intended to be built dynamically not hard-coded into the declaration.

Thanks

**Comment by jskeet** [comment] 2019-04-09 10:56
> Could you attach the sample audio file you create which works with the phrase "fleegle blurple"? This would be a good sanity test for me since other test phrases I used appear to have no effect.

I've attached it here, zipped: [fleegle.zip](https://github.com/googleapis/google-cloud-dotnet/files/3058503/fleegle.zip)

I'll try the Googe-provided file in a moment and report back the result.

> I am using Xamarin Forms and your package supports .net standard and therefore also Xamarin. 

Interesting. While we only depend on .NET Standard directly, we also depend on Grpc.Core, which uses a native library. It looks like Grpc.Core 1.19.0 includes Android binaries for arm64-v8a, armeabi-v7a and x86, as well as an iOS binary.

Given that we have no tests for this, and the authentication for the client libraries is really designed for *service* accounts which I'd normally recommend against embedding in libraries, I'm reluctant to claim that Xamarin is supported at the moment, but it's good to know it works. One problem with claiming it as "supported" is that then there would be a reasonable expectation that if someone reported a Xamarin-specific problem, we'd be in a position to investigate it quickly - and while I'd certainly give it a go, the team isn't set up for that at the moment.

> I am using the more complicated declaration method because the phrases are intended to be built dynamically not hard-coded into the declaration.

Even if you have multiple phrases, you still don't need to create a `List<SpeechContext>`, unless you really have multiple contexts as well.

**Comment by jskeet** [comment] 2019-04-09 11:05
Okay, I've tried it with that file, and I can't get it to recognize "shwazil hoful day" either, whether that's using the words together as a single phrase or separated.

Here's an example which *does* show the benefit of using a speech context, although interestingly one piece of speech still has "Chrome Cast" separately.

```csharp
using Google.Cloud.Speech.V1;
using System;

namespace Issue3010
{
    class Program
    {
        static void Main(string[] args)
        {
            var config = new RecognitionConfig
            {
                Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                SampleRateHertz = 8000,
                LanguageCode = LanguageCodes.English.UnitedStates,
                SpeechContexts = { new SpeechContext { Phrases = { "Chromecast"} } }
            };

            var audio = RecognitionAudio.FromStorageUri("gs://cloud-samples-tests/speech/commercial_mono.wav");

            var client = SpeechClient.Create();
            var response = client.Recognize(config, audio);
            Console.WriteLine(response);
        }
    }
}
```

(Run with and without the context for the difference.)

For the "shwazil hoful day" example, I suggest you ask on the [cloud-speech-discuss](https://groups.google.com/forum/#!forum/cloud-speech-discuss) group - I expect the Speech API team is involved there, but they don't monitor the client library repos.
