### ISSUE TITLE
Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")

### ISSUE THREAD

**Issue by eflorespalma** [googleapis/google-cloud-dotnet#5346] opened 2020-09-23 18:55 UTC
Hi Folks,

I have and Azure Function calling the pubsub gcp service and it is constantly throwing me the following error. Sometimes works correctly and others throw exceptions

```
Error sync-notification_activity Message : Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded") Date: 09/23/2020 11:29:23
Error sync-notification_activity StackTrace : at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Google.Cloud.PubSub.V1.Tasks.ForwardingAwaiter`1.GetResult() at Google.Cloud.PubSub.V1.Tasks.Extensions.<>c__DisplayClass5_0`1.<<ConfigureAwaitHideErrors>g__Inner|0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Google.Cloud.PubSub.V1.Tasks.ForwardingAwaiter`1.GetResult() at Google.Cloud.PubSub.V1.PublisherClientImpl.PublishAsync(PubsubMessage message) at Notification.Service.PubSubService.PublishToTopic[T](T model) in /myagent/_work/248/s/Notification/Notification.Service/Google/PubSub/PubSubService.cs:line 38 at Notification.Process.ProcessHandler.SyncNotification(NotificationMessage request, ILogger log) in /myagent/_work/248/s/Notification/Notification.Process/Application/ProcessHandler.cs:line 34 at Notification.Process.Sync.SyncAbandonedCallsActivity(NotificationMessage request, ILogger log) in /myagent/_work/248/s/Notification/Notification.Process/Sync.cs:line 141 Date: 09/23/2020 11:29:23
```
This my connection method.

```
        public async Task<PublisherClient> CreateClient(TopicName topicName)
        {
            if (_client == null)
            {

                var isWebApp = _configuration["isWebApp"];
                var binDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
                var rootDirectory = Path.GetFullPath(Path.Combine(binDirectory, ".."));

                var config = Path.Combine(rootDirectory, "authgcp.json");

                GoogleCredential credential = null;
                using (var jsonStream = new FileStream(config, FileMode.Open, FileAccess.Read, FileShare.Read))
                    credential = GoogleCredential.FromStream(jsonStream);

                var createSettings = new PublisherClient.ClientCreationSettings(credentials: credential.ToChannelCredentials());

                _client = await PublisherClient.CreateAsync(topicName, clientCreationSettings: createSettings);
            }

            return _client;
        }
```

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.PubSub.V1" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="3.1.7" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.7" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>

</Project>
```

**Comment by jskeet** [comment] 2020-09-23 19:05
Chris, is this something you're able to look at, at all?

My initial guess is that this could be caused by Azure Functions effectively spinning down the CPU, whereas the PubSub code expects to get enough CPU to work with the PubSub service continuously (perhaps only a trickle of CPU, but not being put to sleep for very long periods - potentially killing network connections within that). Chris, does the publisher client expect a long-running connection, or is it only "when publishing"?

**Comment by eflorespalma** [comment] 2020-09-23 19:52
Hi @jskeet we need the publisher client just for publishing, but I use the same strategy with the bigquery client and works perfectly in Azure Function.

**Comment by jskeet** [comment] 2020-09-23 19:54
Yes, BigQuery client is a simpler "make a simple RPC". Chris knows more than me about what the publisher does here... I'm hoping there will be some options here that can help make it work for you.

**Comment by eflorespalma** [comment] 2020-09-23 20:38
Ok, I will wait for @chrisdunelm

**Comment by kingerson** [comment] 2020-09-23 20:40
I have the same problem using from azure app service any news about this? 
@jskeet
@chrisdunelm

**Comment by jskeet** [comment] 2020-09-23 20:43
@kingerson: The issue was only raised 2 hours ago - well outside UK working hours. Please be patient.

**Comment by chrisdunelm** [comment] 2020-09-24 12:15
The `PublisherClient` requires background processing to continue after the call to the Publish method.
For example, by default it doesn't send the published message until 10ms after your call to the Publish method (in low-traffic scenarios).

On Azure, it may be most suitable to not use `PublisherClient`, but instead use `PublisherServiceApiClient`, which does no background processing and just sends the messages immediately with no further processing.

**Comment by eflorespalma** [comment] 2020-09-24 14:30
Hi @chrisdunelm , thank you so much for the answer, we will do the test and I comment how it goes.

**Comment by kingerson** [comment] 2020-09-24 14:50
Hello @jskeet  sorry I did not realize that the incident had just been registered. On the other hand, @chrisdunelm  do you have an example of how I can make my connection with the PublisherServiceApiClient, since I see that it does not have the same method

**Comment by chrisdunelm** [comment] 2020-09-24 15:15
@kingerson This is the simplest way:
```
using Google.Cloud.PubSub.V1;
...
var client = PublisherServiceApiClient.Create();
TopicName topicName = ...;
client.Publish(topicName, new [] { new PubsubMessage { ... } });
```
You may well need to customize client creation, which is easiest done using the `PublisherServiceApiClientBuilder` builder class.

**Comment by kingerson** [comment] 2020-09-24 15:27
Hi @chrisdunelm , I checked the following link in the documentation, but I don't know how I could authenticate as I did before with my json file since using the PublisherServiceApiClientBuilder class I don't see the way to do it

https://googleapis.github.io/google-cloud-dotnet/docs/guides/call-settings.html

**Comment by jskeet** [comment] 2020-09-24 15:36
@kingerson: It's not part of CallSettings - you would set the `CredentialsPath` property on the builder to the path to the JSON file.

**Comment by kingerson** [comment] 2020-09-24 16:47
Hi @chrisdunelm, @jskeet thank you very much for your quick help I have already done the respective tests and everything is working correctly.

**Comment by jskeet** [comment] 2020-09-24 16:49
@kingerson: That's good to know. If @eflorespalma has the same experience, I suggest we make a note of this in the top-level documentation for the client, but make no code changes.

**Comment by eflorespalma** [comment] 2020-09-24 16:54
Hola @jskeet @chrisdunelm thank you very much for your help. I have carried out the necessary tests to verify if the problem persisted, but everything is working perfectly. Finally I use the following line to authenticate myself.

`PublisherServiceApiClient publisherService = await new PublisherServiceApiClientBuilder { ChannelCredentials = credential.ToChannelCredentials() }.BuildAsync();`

**Comment by jskeet** [comment] 2020-09-24 16:56
Great! Really glad to hear it all worked :) I'll leave this issue open, but assign it to myself to write a little bit more documentation.

**Closed** 2020-09-25 10:28 UTC
Labels: api: pubsub, type: question
