### ISSUE TITLE
`cloudTasksClient.CreateTaskAsync` requires always-allocated CPU on Cloud Run

### ISSUE THREAD

**Issue by atrauzzi** [googleapis/google-cloud-dotnet#8207] opened 2022-02-27 20:33 UTC
#### Environment details

  - OS: Linux
  - .NET version: 6.0.x
  - Package name and version: `Google.Cloud.Tasks.V2` `2.4.0`
  - Cloud Run

#### Steps to reproduce

I've been tracing some inconsistent dispatch behaviour in my Cloud Run deployed .NET services. I eventually was able to pin it down to a `StatusCode=DeadlineExceeded` exception being thrown whenever I was calling `cloudTasksClient.CreateTaskAsync`.

I eventually found [this commit](https://github.com/jskeet/google-cloud-dotnet/commit/154c210f2570ab1f3e36151bff23d2e7bcd11291) which got me to thinking if Cloud Tasks was subject to a similar constraint as it is also GRPC centric.

Sure enough, switching to always-allocated alleviated the issue, although of course I'd prefer to have the most minimal and least resource intensive deployment possible. :innocent: 

Is there any chance there's a solution to this other than enabling always-allocated CPUs?  Failing that, I feel like it's a bug in the library to have such a constraint, so perhaps there's work internally that can be done to remove the constraint?

:heart:

**Comment by jskeet** [comment] 2022-02-28 09:05
I wouldn't expect it to have the same constraint, no. The issue with PubSub is that the "wrapper" classes (`PublisherClient` and `SubscriberClient`) perform buffering/batching etc. As far as I'm aware, the Tasks library is just simple RPCs. I'd expect that potentially the gRPC client would have to transparently recreate the network connection if the Cloud Run instance had been idle for a long time, but I'd still expect it to work.

Are you able to share a minimal example that demonstrates the problem? (Ideally using something like GetTask rather than CreateTask to avoid creating huge numbers of tasks while testing, but we'll go with whatever is required of course.)

**Comment by atrauzzi** [comment] 2022-02-28 14:42
I have the following middleware which is responsible for dispatching to Cloud Tasks after a request is completed:

```csharp
public class MediatorQueueDispatcherMiddleware : IMiddleware
{
    private readonly ActivitySource activitySource;

    private readonly IServiceProvider services;

    public MediatorQueueDispatcherMiddleware(
        ActivitySource activitySource,
        IServiceProvider services
    )
    {
        this.activitySource = activitySource;
        this.services = services;
    }

    public async Task InvokeAsync(HttpContext context, RequestDelegate next)
    {
        var requestServices = context.RequestServices;

        var mediator = requestServices.GetRequiredService<Mediator.Mediator>();

        context.Response.OnCompleted(() =>
        {
            var pendingRequests = mediator.PendingQueueRequests;

            // note: This is deliberately not awaited as doing so still somehow causes the request to hang for some reason, even though we're in `OnCompleted`...
            Task.Run(async () =>
            {
                using var activity = activitySource.StartActivity("Queue-Dispatch");

                if (! pendingRequests.Any())
                {
                    activity?.AddTag("action", "skipped");

                    return;
                }

                var queueDispatcher = services.GetRequiredService<QueueDispatcher>();

                await pendingRequests
                    .ToAsyncEnumerable()
                    .ForEachAwaitAsync(async (queueEnvelope) => await queueDispatcher.Push(queueEnvelope.Queue, queueEnvelope));

                activity?.AddTag("action", "dispatched");
                activity?.AddTag("count", pendingRequests.Count);
            });

            return Task.FromResult(true);
        });

        await next(context);
    }
}
```

This is the `QueueDispatcher` implementation that ultimately gets called:

```csharp
public class GoogleCloudRunTaskDispatcher : QueueDispatcher
{
    private readonly GoogleCloudConfiguration configuration;

    private readonly ActivitySource activitySource;

    private readonly CloudTasksClient cloudTasksClient;

    public GoogleCloudRunTaskDispatcher(
        ActivitySource activitySource,
        IOptions<GoogleCloudConfiguration> configuration,
        CloudTasksClient cloudTasksClient
    )
    {
        this.activitySource = activitySource;
        this.cloudTasksClient = cloudTasksClient;
        this.configuration = configuration.Value;
    }

    public async Task Push(string queueName, QueueEnvelope envelope)
    {
        using var activity = activitySource.StartActivity("Task-Dispatch");

        activity?.AddTag("queue", envelope.Queue);

        try
        {
            await HandlePush(activity, queueName, envelope);
        }
        catch (Exception ex)
        {
            activity.RecordException(ex);
        }
    }

    private async Task HandlePush(Activity? activity, string queueName, QueueEnvelope envelope)
    {
        if (! configuration.TaskQueues.TryGetValue(queueName, out var queue))
        {
            throw new($"Queue {queueName} is not configured.");
        }

        var parent = new QueueName(configuration.ProjectId, queue.Location, queue.Name);

        await cloudTasksClient.CreateTaskAsync(new()
        {
            Parent = parent.ToString(),
            Task = new()
            {
                ScheduleTime = envelope.At.HasValue ? Timestamp.FromDateTime(envelope.At.Value.ToDateTimeUtc()) : null,
                HttpRequest = new()
                {
                    OidcToken = new()
                    {
                        ServiceAccountEmail = configuration.ServiceAccountEmail,
                    },
                    HttpMethod = HttpMethod.Post,
                    Url = $"{queue.BaseUri}/handle-cloud-task",
                    Body = ByteString.CopyFromUtf8(envelope.ToDiscriminatedJson()),
                    Headers =
                    {
                        { "content-type", "application/json" },
                    },
                },
            },
        });
    }
}
```

I'll mention again that the behaviour is odd as the first time the `Task.Run` is encountered above as a result of a request, none of the code inside of it appears to be executed.

The second time a request comes in though, I believe I end up seeing the exception (which causes some tasks to fail), and then all the dispatches for the current request.

As soon as I always-allocate the CPU, things end up functioning more like what I had assumed.  Is it plausible that I'm effectively creating the same batching/buffering scenario you describe?

**Comment by jskeet** [comment] 2022-02-28 15:13
Okay, well it looks to me like the problem is here:

```csharp
// note: This is deliberately not awaited as doing so still somehow causes the request to hang for some reason, even though we're in `OnCompleted`...
```

You're effectively trying to perform background work - which is fine if there's CPU allocated to *do* background work, but not in the normal Cloud Run configuration where the process is effectively paused when the request completes.

So for this particular code, I'm not surprised that you're running into problems.

I suggest you focus on making the delegate you pass to `context.Response.OnCompleted` execute in the expected way - I'd start off just by awaiting a `Task.Delay(3000)` and check that that just pauses the response for 3 seconds, etc.

**Comment by atrauzzi** [comment] 2022-02-28 15:26
OnCompleted definitely holds the response up. I'm contemplating reporting it as a bug. Though I feel like that's ultimately not going to help. The - perfectly legitimate - takeaway here is probably that I need always-allocated in order to do this.

It makes sense too because once the response is sent Cloud Run is designed to take back the CPU time talking-stick. I just want to make sure I'm not missing any opportunity to work around it. 🙂

**Comment by jskeet** [comment] 2022-02-28 17:18
If you want to do work after the response has already been sent to the client, then that's not really about the .NET client libraries at all - it's fundamental to Cloud Run. The maintainers of this repo aren't experts in Cloud Run - you probably want to use one of the [Cloud Run support routes](https://cloud.google.com/run/docs/support). You may end up deciding to have *some* code running on Cloud Run, but with some other code running on a always-on basis that is more suitable to this.

I'll close this issue now as I don't believe it's fundamentally a gRPC client issue.

**Closed by jskeet** 2022-02-28 17:18 UTC
Labels: type: question

**Comment by atrauzzi** [comment] 2022-03-01 00:56
> You may end up deciding to have some code running on Cloud Run, but with some other code running on a always-on basis that is more suitable to this.

Are you able to just quickly clarify what you mean by this?

**Comment by jskeet** [comment] 2022-03-01 07:46
> Are you able to just quickly clarify what you mean by this?

I mean that you can have one Cloud Run service doing most of the work for your request handling, but then make a call to another "always-on" service that handles the aspects that take longer (creating cloud tasks etc) - but which returns immediately. You could do that either by making a request directly to a service, or use something like Pub/Sub to separate out the two aspects.

**Comment by atrauzzi** [comment] 2022-03-01 15:32
Good stuff, thank you so much.  I think for now I'll stick with always-on on my current service.  Once I have a little more time to tinker, I'll investigate some more.

:pray:
