### ISSUE TITLE
Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")

### ISSUE THREAD

**Issue by laljikanjareeya** [googleapis/google-cloud-dotnet#2985] opened 2019-03-28 05:31 UTC
Hi, I gone through this issue #2533 but did't find solution of my problem.
I am getting exception : **Grpc.Core.RpcException: Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")** while creating table in Bigtable.

I am doing below operation in sequence:
1. Check Table
2. Create Table if not exists
3. Add Data into table
4. Delete Table

Please find below code and Package information.

```javascript
Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", [Path]);
BigtableTableAdminClient bigtableTableAdminClient = BigtableTableAdminClient.Create();
InstanceName parent = new InstanceName([ProjectId],[InstanceId]);
Table table = new Table();
Table response = bigtableTableAdminClient.CreateTable(parent, [TableName], table);
```
Packages:
```javascript
  <package id="Google.Api.CommonProtos" version="1.6.0" targetFramework="net461" />
  <package id="Google.Api.Gax" version="2.6.0" targetFramework="net461" />
  <package id="Google.Api.Gax.Grpc" version="2.6.0" targetFramework="net461" />
  <package id="Google.Api.Gax.Grpc.Gcp" version="2.6.0" targetFramework="net461" />
  <package id="Google.Apis" version="1.38.0" targetFramework="net461" />
  <package id="Google.Apis.Auth" version="1.38.0" targetFramework="net461" />
  <package id="Google.Apis.Core" version="1.38.0" targetFramework="net461" />
  <package id="Google.Cloud.Bigtable.Admin.V2" version="1.0.0-beta05" targetFramework="net461" />
  <package id="Google.Cloud.Bigtable.Common.V2" version="1.0.0-beta05" targetFramework="net461" />
  <package id="Google.Cloud.Bigtable.V2" version="1.0.0-beta05" targetFramework="net461" />
```
Thanks!

**Comment by jskeet** [comment] 2019-03-28 07:26
A few questions to help us work out what's happening:

- Does this happen all the time, or just occasionally?
- What sort of network are you on? Does it have good connectivity?
- Are you behind a proxy that might have difficulties with HTTP/2.0?
- Have you observed how long it tries to create the table for? It looks like it should only fail after 10 minutes

**Comment by laljikanjareeya** [comment] 2019-03-28 07:40
@jskeet Please find Below Answers of your question:

* **it happens while deleting table and re-creating it again within few second with same name.**
* my network is stable no proxy is there and it have good connectivity.
* it throws exception within 10-15 seconds.

**Comment by jskeet** [comment] 2019-03-28 08:15
Could you post the complete stack trace? It would be odd for CreateTable to time out that quickly. I wonder whether this is an internal deadline error that's being propagated...

**Comment by laljikanjareeya** [comment] 2019-03-28 09:19
@jskeet find below stack trace:
```javascript
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.Bigtable.Admin.V2.BigtableTableAdmin.BigtableTableAdminClient.CreateTable(CreateTableRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__1(TRequest req, CallSettings cs)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCall`2.Sync(TRequest request, CallSettings perCallCallSettings)
   at Google.Cloud.Bigtable.Admin.V2.BigtableTableAdminClientImpl.CreateTable(CreateTableRequest request, CallSettings callSettings)
   at Google.Cloud.Bigtable.Admin.V2.BigtableTableAdminClient.CreateTable(InstanceName parent, String tableId, Table table, CallSettings callSettings)
   at BigtableDemo.Program.CreateTable() in G:\Research Project\BigtableDemo\BigtableDemo\Program.cs:line 32
```

I have created demo for you, it will create and delete table, first time it will run successfully, however if you run it again immediately it throws above exception.
```javascript
    class Program
    {
        const string projectId = "grass-clump-479";
        const string instanceId = "dotnet-perf-2";
        const string tableName = "my-table";
        const string credentialPath = @"D:\google_client_credential.json";
        static void Main(string[] args)
        {
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", credentialPath);
            CreateTable();
            DeleteTable();
        }

        static void CreateTable()
        {
            try
            {
                if (IsTableExists())
                    return;
                BigtableTableAdminClient bigtableTableAdminClient = BigtableTableAdminClient.Create();
                InstanceName parent = new InstanceName(projectId, instanceId);
                Table table = new Table();
                Table response = bigtableTableAdminClient.CreateTable(parent, tableName, table);

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        static void DeleteTable()
        {
            try
            {
                BigtableTableAdminClient bigtableTableAdminClient = BigtableTableAdminClient.Create();
                bigtableTableAdminClient.DeleteTable(new TableName(projectId, instanceId, tableName));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        static bool IsTableExists()
        {
            try
            {
                BigtableTableAdminClient bigtableTableAdminClient = BigtableTableAdminClient.Create();
                InstanceName instanceName = new InstanceName(projectId, instanceId);
                var tables = bigtableTableAdminClient.ListTables(instanceName);
                return tables.Any(x => x.TableName.TableId == tableName);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
```
I also got surprise that even after this exception table has been created in Bigtable.
Let me know if you need more information.

**Comment by jskeet** [comment] 2019-03-28 09:36
Thanks, I'll try to reproduce the error shortly.

**Comment by jskeet** [comment] 2019-03-28 10:34
Thanks - I've managed to reproduce it with this slightly shorter code:

```csharp
using Google.Cloud.Bigtable.Admin.V2;
using Google.Cloud.Bigtable.Common.V2;
using System;

namespace Issue2985
{
    class Program
    {
        static void Main(string[] args)
        {
            if (args.Length != 3)
            {
                Console.WriteLine("Please specify project ID, instance ID and table ID");
                return;
            }
            try
            {
                string projectId = args[0];
                string instanceId = args[1];
                string tableId = args[2];
                var instanceName = new InstanceName(projectId, instanceId);
                var tableName = new TableName(projectId, instanceId, tableId);
                var client = BigtableTableAdminClient.Create();
                for (int i = 0; i < 100; i++)
                {
                    Log($"Iteration {i}");
                    Log($"Creating table");
                    client.CreateTable(instanceName, tableId, new Table());
                    Log($"Deleting table");
                    client.DeleteTable(tableName);
                }
            }
            catch (Exception e)
            {
                Log($"Exception: {e}");
            }

            void Log(string message) => Console.WriteLine($"{DateTime.UtcNow:HH:mm:ss.FFF}: {message}");
        }
    }
}
```

It looks like it fails after exactly 20 seconds, which is the initial timeout for the client. I suspect the problem is that the settings don't retry on timeout - but the initial timeout should probably be longer. Will experiment.

**Comment by jskeet** [comment] 2019-03-28 11:05
Right, it looks like the call will succeed *eventually* - but it takes a couple of minutes or so. Here's a log:


There are two ways of specifying timing, via a CallSetting:

## Client-wide setting

```csharp
var clientSettings = BigtableTableAdminSettings.GetDefault();
var longTimeout = CallTiming.FromTimeout(TimeSpan.FromMinutes(3));
clientSettings.CreateTableSettings = clientSettings.CreateTableSettings.WithCallTiming(longTimeout);
var client = BigtableTableAdminClient.Create(settings: clientSettings);
// Call CreateTable as normal
```

## Call-specific 
// Build the client with the default settings, but when you call CreateTable, specify a timeout
var longTimeoutSettings = CallSettings.FromCallTiming(CallTiming.FromTimeout(TimeSpan.FromMinutes(3)));
...
client.CreateTable(instanceName, tableId, new Table(), longTimeoutSettings);
```

The two approaches are basically equivalent. I'll start a conversation internally about changing the defaults.

**Comment by laljikanjareeya** [comment] 2019-03-28 11:48
I think you forgot to attach the logs, however it's more important that you got the issue.
really appreciate your effort on this issue.

**Comment by jskeet** [comment] 2019-03-28 11:51
@laljikanjareeya: Whoops! Edited the log in now. Assuming you're able to try the workaround, please could you let me know whether it worked for you?

**Comment by laljikanjareeya** [comment] 2019-03-28 12:00
yes above workaround is works for me, Thanks @jskeet.

**Comment by jskeet** [comment] 2019-03-28 12:03
Great! I'll close this issue now, but we'll hopefully have a better resolution in terms of the defaults over time.

**Closed by jskeet** 2019-03-28 12:03 UTC
Labels: priority: p2, type: question
