### ISSUE TITLE
"Wildcard resource ids must not contain / (Parameter 'value')"

### ISSUE THREAD

**Issue by aruns05** [googleapis/google-cloud-dotnet#5885] opened 2021-01-26 18:45 UTC
"Wildcard resource ids must not contain / (Parameter 'value')"
Getting this error while running the code. 

```csharp
SecretManagerServiceClientBuilder scb = new SecretManagerServiceClientBuilder();
scb.CredentialsPath = "/path/filename.json";
//scb.CredentialsPath = "filename.json";
SecretManagerServiceClient client = scb.Build();

// Build the parent project name.
SecretName sname = new SecretName(projectId, secretId);
ProjectName projectName = new ProjectName(projectId);
Secret s = client.GetSecret("projects/111721269447/secrets/secretname");
SecretVersionName secretVersionName = new SecretVersionName(projectId, "projects/111721269447/secrets/secretname", "latest");

AccessSecretVersionResponse result = client.AccessSecretVersion(secretVersionName);
```

**Comment by jskeet** [comment] 2021-01-26 18:50
Please could you post the full stack trace? That will make it easier to work out what's going wrong. I strongly suspect there's a problem in the proto that this is generated from.

**Comment by aruns05** [comment] 2021-01-27 01:03
@jskeet 

System.ArgumentException: "Wildcard resource ids must not contain / (Parameter 'value')"
  at Google.Api.Gax.PathTemplate.Segment.ValidateWildcardValue(String value)\n   at Google.Api.Gax.PathTemplate.ValidateResourceIds(String[] resourceIds)\n   at Google.Api.Gax.PathTemplate.ExpandWithService(String serviceName, String[] resourceIds)\n   at Google.Api.Gax.PathTemplate.Expand(String[] resourceIds)\n   at Google.Cloud.SecretManager.V1.SecretName.ToString()\n   at Google.Cloud.Iam.V1.GetIamPolicyRequest.set_ResourceAsResourceName(IResourceName value)\n   at clientsecretpoc.Program.Createaccess() in /Users/arunsridhar/Desktop/Work/dotnetcore/clientsecretpoc/clientsecretpoc/Program.cs:line 65\n   at clientsecretpoc.Program.Main(String[] args) in /Users/arunsridhar/Desktop/Work/dotnetcore/clientsecretpoc/clientsecretpoc/Program.cs:20

**Comment by jskeet** [comment] 2021-01-27 07:17
That stack trace doesn't look like it corresponds to the code you've provided - it looks like you're setting the `ResourceAsResourceName` property of a `GetIamPolicyRequest`, and that's where it's failing.

I will say that this part of your code looks like it could cause a problem though, and indeed cause the exception you're seeing.

```csharp
new SecretVersionName(projectId, "projects/111721269447/secrets/secretname", "latest");
```

The second argument there is meant to just be the secret ID, which looks like it's "secretname" in this case.

For example, if you run:

```csharp
var svn = new SecretVersionName("my-project", "secretname", "latest");
Console.WriteLine(svn);
```

then the output is `projects/my-project/secrets/secretname/versions/latest` - that's the full resource name derived from the three segments.

So quite possibly all you need to do is change that constructor call.

**Comment by aruns05** [comment] 2021-01-27 07:34
Hello @jskeet     Below is the code and the stack trace. I am getting error at 
            AccessSecretVersionResponse result = client.AccessSecretVersion(secretVersionName);
Also when I go and see Secret manager i didnt find secret iD , I could see only name. Can you advise
<img width="1792" alt="Screenshot 2021-01-27 at 1 02 12 PM" src="https://user-images.githubusercontent.com/15269023/105957973-fc117080-609f-11eb-84b9-b153b3f18e46.png">


static void Getsecrets()
        {
            string projectId = "petsmartnew";
            string secretId = "projects/111721269447/secrets/<name>”;
         

            SecretManagerServiceClientBuilder scb = new SecretManagerServiceClientBuilder();
            scb.CredentialsPath = "/Users/arunsridhar/desktop/<>”;
            //scb.CredentialsPath = "proceapidev.json";
            SecretManagerServiceClient client = scb.Build();


            // Build the parent project name.
            SecretName sname = new SecretName(projectId, secretId);
            ProjectName projectName = new ProjectName(projectId);
            Secret s = client.GetSecret("projects/111721269447/secrets/<name>");   //not seeing any ID in secret manager.
            SecretVersionName secretVersionName = new SecretVersionName(projectId, "projects/111721269447/secrets/<name>”, "latest");


            AccessSecretVersionResponse result = client.AccessSecretVersion(secretVersionName);

        }


System.ArgumentException: "Wildcard resource ids must not contain / (Parameter 'value')"
  at Google.Api.Gax.PathTemplate.Segment.ValidateWildcardValue(String value)\n   at Google.Api.Gax.PathTemplate.ValidateResourceIds(String[] resourceIds)\n   at Google.Api.Gax.PathTemplate.ExpandWithService(String serviceName, String[] resourceIds)\n   at Google.Api.Gax.PathTemplate.Expand(String[] resourceIds)\n   at Google.Cloud.SecretManager.V1.SecretVersionName.ToString()\n   at Google.Cloud.SecretManager.V1.AccessSecretVersionRequest.set_SecretVersionName(SecretVersionName value)\n   at Google.Cloud.SecretManager.V1.SecretManagerServiceClient.AccessSecretVersion(SecretVersionName name, CallSettings callSettings)\n   at clientsecretpoc.Program.Createnewaccess() in /Users/arunsridhar/Desktop/Work/dotnetcore/clientsecretpoc/clientsecretpoc/Program.cs:line 42\n   at clientsecretpoc.Program.Main(String[] args) in /Users/arunsridhar/Desktop/Work/dotnetcore/clientsecretpoc/clientsecretpoc/Program.cs:20


Thanks a lot for helping

**Comment by jskeet** [comment] 2021-01-27 07:48
Right, that's not the stack trace you showed before, but that makes more sense.

As I say, the problem is the second argument you're passing to the `SecretVersionName` constructor. You should just pass the secret ID, not the complete resource name.

**Comment by aruns05** [comment] 2021-01-27 10:50
@jskeet   Thanks a lot that worked. Also is there any way we can restrict access to the secret manager altogether NOT the individual secrets

**Comment by jskeet** [comment] 2021-01-27 10:52
> Also is there any way we can restrict access to the secret manager altogether NOT the individual secrets

I'm afraid I don't know exactly what you mean, but I doubt I'd have the answer anyway - the maintainers of this repository know a lot about the client libraries, but not about the individual APIs. I suggest you use one of the support routes listed at https://cloud.google.com/secret-manager/docs/getting-support to ask SecretManager-specific questions.

I'll close this issue now as I don't think any changes are required in the libraries.

**Closed by jskeet** 2021-01-27 10:52 UTC
Labels: api: secretmanager, type: question
