### ISSUE TITLE
Slow read of only final result for streaming speech

### ISSUE THREAD

**Issue by markboyall** [googleapis/google-cloud-dotnet#3450] opened 2019-09-16 15:23 UTC
I'm having trouble with a performance problem with our service. I've tracked this to the Google.Cloud.Speech library, using StreamingRecognizeStream.

When we receive audio from the client, we stream it to the stream. We have an async loop running in the background which continually awaits ResponseStream.MoveNext. We gather up the results as they are returned and return them to the client. When the client requests completion, we call WriteCompleteAsync and then wait.

The problem is that after calling StreamingRecognizeStream.WriteCompleteAsync, the last result containing the final recognition takes an enormous amount of time to be read- e.g. 15-20 seconds. This is a poor experience for our user and triggers a few timeouts and such on our end. This time is all spent waiting for ResponseStream.MoveNext.

I've attached the profiler but due to the use of TCSes, the result isn't very useful, however I've determined that the actual task continuations themselves don't take any time (e.g. HandleReadFinished). It just takes a very long time for them to be triggered. Since this is the final result, rather than the "stream finished" result, this does not include time for closing the stream.

This only seems to occur sometimes; with the "sometimes" being determined at application startup time.

I've tried:
* Upgraded from v1.1 to v1.2
* Downgraded GRPC core from 2.22 to 1.22
* Start the read loop on the thread pool rather than from an ASP.NET controller context

I saw that the underlying GRPC stream is implemented in native code and this is what is not triggering the events quickly. Can you guys expose or recommend any kind of profiling or debugging options there?

**Comment by jskeet** [comment] 2019-09-16 15:37
I've transferred it myself :)

**Comment by jskeet** [comment] 2019-09-16 16:15
I *suspect* this isn't really a performance issue or a client library issue - I suspect it's just that the API doesn't provide the finalized results for a little while. I've observed the same thing, and seen it in Python as well as C#.

One way of spotting this would be to enable gRPC logging (which can admittedly be a little overwhelming - it's tricky to work out what logs to enable). Of course, if the problem is actually in the gRPC core library, that possibly wouldn't pick it up - but I really think it's about the API itself. Do you have any reason to suspect this is a client-side problem? Perhaps it would be worth providing some sample timings (when you start, how much data you write, when you finish, when you get the results) in the [cloud-speech-discuss Google Group](https://groups.google.com/forum/#!forum/cloud-speech-discuss/join) to see whether the API team expects the kind of results you're seeing?

**Comment by markboyall** [comment] 2019-09-17 13:20
I'll take a look at gRPC logging shortly, but here's the timings:

2019-09-17 14:04:43,913 [10] DEBUG - Starting google session
2019-09-17 14:05:44,350 [15] DEBUG - Ending Google session (we call WriteCompleteAsync, then wait for our MoveNext async loop to complete)
2019-09-17 14:05:44,446 [25] DEBUG - Got hypothesis for Google session
2019-09-17 14:05:49,463 [10] ERROR - Failed to post audio for Google session - timeout is triggered, so the client retries, but WriteCompleteAsync was already called, so the server fails.
repeat that quite a bit
2019-09-17 14:06:10,941 [6] DEBUG - Got final result for Google session - this is the IsFinal result which contains complete recognized text.

**Comment by jskeet** [comment] 2019-09-17 14:38
I don't understand the 4th line of code - is this a timeout you've added yourself? It's also a little odd that you're writing all the data in 0.4 seconds... if you're streaming, I'd expect you to write data over a longer period.

Are you able to put together a sample app that demonstrates what you're doing?

**Comment by markboyall** [comment] 2019-09-17 15:00
Our client posts audio to our service, which forwards it on to Google. The request the client makes to post audio can close the session if certain conditions are met (in this case, 60 second duration limit). The timeout on this request (5 seconds) is what fails when closing the session takes too long. This is kinda broken for us if the server is actually still alive but just taking too long as we don't properly control multiple requests per session, but that's another matter.

The data is being written over one minute and 0.4 seconds- it's 60 seconds of me just reading random news articles.

I will look at the sample app.

**Comment by jskeet** [comment] 2019-09-17 15:29
I'll try this locally, but I believe you should expect that sometimes it *will* take more than 5 seconds to get the final result, particularly if there's been a long time since the previous finalized result.

**Comment by markboyall** [comment] 2019-09-17 15:45
I noticed that we basically never receive final results until the session closes anymore, unless the user stops speaking for a long time. This means the last result is for the minute of audio. However in some tests I've clocked this at over a minute which seems excessive. Another reason I discounted that theory is that the problem is nondeterministic- if it's just about audio quantity, it should be at least roughly consistent, not 1 second to 1 minute.

It's end of my work say here but I will work on the sample app tomorrow.

**Comment by jskeet** [comment] 2019-09-18 07:00
> unless the user stops speaking for a long time

Yes, that's by design. If you want interim results, you need to say so in the audio config - otherwise the Speech API assumes you only want the complete "chunk" of speech. If you ask for interim results, you can still detect the final results. See https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/883 for an example which shows both of these aspects.

I'd expect reasonably consistent timing *for the same speech* but if one sample contains a few sentences, then a pause, then one short final sentence, and the other contains a complete minute of speech, I would expect those to give different timings.

**Comment by markboyall** [comment] 2019-09-18 08:34
We have interim results set to true, and we receive them. However, the way it used to behave is that you would get multiple final results, since the user's speech at the 55th second isn't influencing what they're saying at the 5th second. Now we only get multiple final results if the user pauses for some time in the middle. This isn't really a problem, unless it contributes to/causes the other one, just slightly weird.

All the timings are for a complete minute of speech. If you pause and then speak just near the end, the problem doesn't seem to occur. But if you speak continuously for the minute, it can be nearly instant (the same as pausing and the expected behaviour) to over a minute for the final result.

Unfortunately I've not gotten anything useful from the GRPC logs; the ones I've tried so far log that they received the result after they invoke our code.

**Comment by jskeet** [comment] 2019-09-18 08:49
If you're receiving the interim results, it seems very unlikely that the client library is responsible for any delay you're seeing for the final results. It seems much more likely that the behaviour you're seeing is from the server, *not* the client library. If you believe the client library is responsible, could you clarify why you think that? Are you able to test the same kind of process using the Python client library, for example? I really expect you'll see the same thing.

**Comment by markboyall** [comment] 2019-09-18 11:55
It's more accurate to say that I simply can't get the client library to tell me what it thinks is going on, so I don't know whether it's a remote issue or a client library issue. I wish that I could use Wireshark to just intercept the traffic but it is protected.

I can try the Python library probably.

**Comment by markboyall** [comment] 2019-09-24 09:31
Sorry about the delay in getting back to you, I've been occupied with other things. However, I've captured a TCP log which indicates that GRPC simply isn't receiving TCP packets, so modulo something weird happening there, it's probably an issue on the remote end. I've pasted the content on https://pastebin.com/S2gRmFuY and added some helpful newlines where the gap occurs.

I suspect I should just raise this issue with the remote end directly now; need to arrange to pay for support.

**Comment by jskeet** [comment] 2019-09-24 10:41
Thanks very much for getting back to me. I'll close this issue now as we don't believe it to be a client library issue, but obviously we can reopen it if that changes. I suspect it's worth you updating your topic on cloud-speech-discuss as well; I know it hasn't had any traction so far, but that extra log may change things.

**Closed by jskeet** 2019-09-24 10:41 UTC
Labels: type: question
