### ISSUE TITLE
Google.Cloud.Diagnostics.AspNetCore.GoogleLogger does not work well with LoggerMessage ?

### ISSUE THREAD

**Issue by shengxue** [googleapis/google-cloud-dotnet#3098] opened 2019-05-28 18:56 UTC
I followed the steps of the doc [High-performance logging with LoggerMessage in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage?view=aspnetcore-2.1#feedback) to move from  logger extension methods to LoggerMessage.

When I used asp.net core logger extension methods for logging, my log entry in StackDriver has valid labels:
``` json
resource: {
  labels: {
   cluster_name:  "cluster-****"    
   container_name:  "******"    
   instance_id:  "****"    
   namespace_id:  "*****"    
   pod_id:  "*****"    
   project_id:  "******"    
   zone:  "****"    
  }
  type:  "container"   
 }
```

but when I use asp.net core LoggerMessage,  value of labels 'container_name', 'namespace_id' and 'pod_id' become empty.

**Comment by jskeet** [comment] 2019-05-28 18:58
I'll have a look at this when I can, but I'm afraid I'm on vacation this week so it probably won't be until next week.

**Comment by jskeet** [comment] 2019-06-06 13:41
Just getting back to this now - I apologise for the delay.

I'll try to reproduce the problem now, then look at a fix. (It does seem very odd for only those labels to be removed.)
Can I just confirm that the log entries are definitely being generated from GoogleLogger, not just from standard output?

**Comment by shengxue** [comment] 2019-06-06 13:57
yes, I think it is generated by GoogleLogger.  

I registered a ```Google.Cloud.Diagnostics.AspNetCore.ILogEntryLabelProvider```  to add my custom labels.  These resource labels and my custom labels are in the same LogEntry.  If these resource labels were not generated by GoogleLogger, they should not be in the same LogEntry that has my custom labels generated by ```Google.Cloud.Diagnostics.AspNetCore.ILogEntryLabelProvider```.

**Comment by jskeet** [comment] 2019-06-06 13:58
Good to know, thanks. Will keep this issue updated with anything I find out.

**Comment by jskeet** [comment] 2019-06-06 16:21
Hmm. Unfortunately I can't reproduce this. My app:

- Has a custom label provider
- Uses `services.AddSingleton<ILoggerProvider>` to configure logging
- Logs three messages in three different ways:
  - `logger.LogWarning`
  - `Console.WriteLine`
  - `LoggerMessage` action

Both the `logger.LogWarning` and `LoggerMessage` action contain the custom label and all seven resource labels.

Have you tried logging with the regular extension methods and `LoggerMessage` in the same piece of code, and then seen one message without the resource labels and one message with them?

**Comment by shengxue** [comment] 2019-06-07 12:00
yes.  the asp.net core code ```LoggingScopeHttpMessageHandler.cs``` RequestPipelineStart(...) method call LoggerMessage first, and then call regular log method.   Two log entries in Stackdriver are created side by side, one with all resource labels, one without some resource labels.

**Comment by shengxue** [comment] 2019-06-07 12:01
Is it possible to create custom Labels for logger extension methods?

**Comment by jskeet** [comment] 2019-06-07 12:15
Hmm. And both log messages have the labels provided by `ILogEntryLabelProvider`? I honestly have no idea why that would happen - they use the same monitored resource from the `LoggerOptions`. If I could reproduce it, I'm sure I could get to the bottom of it, but until then it's very hard to tell :(

I'm not quite sure what you're asking in terms of "custom labels for logger extension methods" - everything ends up going via `public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)`, which uses the label providers either way.

**Comment by jskeet** [comment] 2019-06-07 12:46
In terms of reproduction, are you in a position where you could create a trivial web app to reproduce this? I can share my one that *doesn't* reproduce it for me, if that would help...

**Comment by shengxue** [comment] 2019-06-10 21:18
My wrote some very simple test code is very simple, one line of code using logger extension methods, and another line of code using LoggerMessage.  

* When I ran the test code from my computer, with stackdriver enabled,  both line of codes log message into stackdriver exactly as what I expected: 1. custom labels are created. 2. My message is logged as jsonPayload of log entry.

* When I deployed the code into GCP kubernetes cluster, the line of code using logger extension method doesn't create custom labels, and my message is logged as textPayload of log entry.   while the line of code using LoggerMessage creates custom labels, and log my message as jsonPayload of log entry.

@jskeet, any idea on the different behaviors between local run and cloud run?   Many thanks!

**Comment by jskeet** [comment] 2019-06-10 22:17
I think I'll need to create a minimal complete example which works for me, and which you can deploy on your GKE cluster - because what you've described is exactly what I've done too, and I didn't see anything unusual. If we're both using the same code, it'll be a lot easier to compare.

**Comment by shengxue** [comment] 2019-06-11 06:39
Can you log your message into textPayload of a log entry by ```GoogleLogger```?  What's the switch condition for logging into textPayload or jsonPayload?  Maybe this can give me some hint.

yes, an example will be much helpful. thanks a lot!

**Comment by jskeet** [comment] 2019-06-11 07:36
Ah, I hadn't seen the part about it using `textPayload` - that is definitely *not* coming from the `GoogleLogger` which *always* sets `jsonPayload` ([source](https://github.com/googleapis/google-cloud-dotnet/blob/master/apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/GoogleLogger.cs#L126)).

I suspect the `textPayload` is coming from a console logger. It would help to clarify things if you could make absolutely sure you've disabled console logging.  For example, in your relevant appsettings.json:

```json
  "Logging": {
    "Console": {
      "LogLevel": {
        "Default": "None"
      }
    }
  }
```

I'll have a look at making my test app even more minimal, then I'll include it here as a zip file.

**Comment by jskeet** [comment] 2019-06-11 08:36
Okay, I've attached a really minimal web application here. You'll need to edit Program.cs to indicate your Kubernetes service name and Google Cloud project ID. (There are ways of autodetecting those, but I'm trying to make it as environment-proof as possible for now.)

Personally I've been deploying this using Cloud Build, but you've presumably already got a way of doing deployments, so I haven't supplied anything Kubernetes-specific. I've included a Dockerfile though - I personally run `dotnet publish` to build the app locally, then copy the Dockerfile into the publish directory and upload all of that to Cloud Build - your mileage may vary.

When you hit the index page and then look in Stack Driver, I'd expect to see three log entries:

- One with a message of "Error LoggerMessage for Index page" in the JSON payload. That's using LoggerMessage. This will have a custom "now" label.
- One with a message of "This is a warning message written with GoogleLogger; there should be a label" in the JSON payload. That's using the extension method. This will have a custom "now" label.
- One with a message of "This is a console message" in the text payload. This will have fluentd labels.

[Issue3098.zip](https://github.com/googleapis/google-cloud-dotnet/files/3275457/Issue3098.zip)

**Comment by shengxue** [comment] 2019-06-11 13:25
I saw the major difference between your code:
``` csharp
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                // Make sure there's no console logger configured
                .ConfigureLogging(builder => builder.ClearProviders())
```
and my code:
``` csharp
        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
                    logging.AddConsole();
                    logging.AddDebug();
                })
                .UseStartup<Startup>()
                .Build();
```
and my appsettings.json are like:

```json
  "Logging": {
    "Debug": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning"
      }
    }
  },
```
I guess Console logger or debug logger somewhat change the behavior of GoggleLogger on cloud.

**Comment by jskeet** [comment] 2019-06-11 13:29
No, the console logger doesn't change the behaviour of `GoogleLogger` - but fluentd will pick up any console log entries. That's why I explicitly disabled it in the sample application.

There's no sign in your code of using GoogleLogger at all, to be honest - so if you're seeing custom labels, there must be some other code to configure GoogleLogger specifically.

**Comment by shengxue** [comment] 2019-06-11 13:35
The code I copied above are in ```program.cs```, and I registered ```GoogleLogger``` and ```LogEntryLabelProvider``` in ```startup.cs```.

**Comment by jskeet** [comment] 2019-06-11 13:36
Okay - could you show how you've done that please? And again, I'd recommend disabling the console logger to avoid confusion when you're looking in the logs (and to avoid duplicate log entries, effectively).

**Comment by shengxue** [comment] 2019-06-11 14:08
```csharp
    public class LogEntryLabelProvider: ILogEntryLabelProvider
    {
        private readonly Action<Dictionary<string, string>> _action;

        public LogEntryLabelProvider(Action<Dictionary<string, string>> action)
        {
            _action = action;
        }
        public void Invoke(Dictionary<string, string> labels)
        {
            _action?.Invoke(labels);
        }
    }

public void ConfigureServices(IServiceCollection services)
 {
         ....
            services.AddGoogleExceptionLogging(options =>
            {
                options.ProjectId = projectId;
                options.ServiceName = serviceName;
                options.Version = version;
            });

            services.AddGoogleTrace(options =>
            {
                options.ProjectId = projectId;
            });

            services.AddLogEntryLabelProvider<LogEntryLabelProvider>(serviceProvider =>
                new LogEntryLabelProvider(labels =>
                    {
                        labels.Add("mylabel", "test");
                    }
                ));
            services.AddSingleton<ILoggerProvider>(sp => GoogleLoggerProvider.Create(sp, projectId));
}

public void Configure(IApplicationBuilder app)
{
            app.UseGoogleExceptionLogging();
            app.UseGoogleTrace();
}
```

**Comment by shengxue** [comment] 2019-06-11 14:10
although I registered Console logger, I don't have any console log code like ```Console.WriteLine``` in my code.

**Comment by shengxue** [comment] 2019-06-11 14:12
I ran your code locally, "Error LoggerMessage for Index page" and "This is a warning message written with GoogleLogger; there should be a label" are logged in stackdriver.  "This is a console message" are not loggged.

**Comment by jskeet** [comment] 2019-06-11 14:21
Right, the console output wouldn't go to Stackdriver. But if you run that in GKE, it *will* be in Stackdriver. Have you deployed the sample app in your GKE cluster? That's where the original problem was observed, yes?

**Comment by shengxue** [comment] 2019-06-11 19:03
When I run it in GKE:
 - "Error LoggerMessage for Index page" and "This is a warning message written with GoogleLogger; there should be a label" are logged.  
 - "This is a console message" are not loggged.
 - Labels are created for both log entries logged by ```GoogleLogger```
 - Resource.Labels.container_name  is empty in both log entries.

**Comment by jskeet** [comment] 2019-06-11 19:07
I suspect "This is a console message" *is* logged, but possibly not where you're looking for it. Have you searched Stackdriver for that, e.g. without specifying the log name?

If `Resource.Labels.container_name` is empty, that suggests it hasn't been able to detect them. I observed this in my cluster when I had legacy auth disabled; we have an [issue in GAX](https://github.com/googleapis/gax-dotnet/issues/305) that tracks that.

Going back to your initial issue report though, I think we still need to work out where the various log entries came from - we still haven't ascertained why the values are only *sometimes* missing.

**Comment by shengxue** [comment] 2019-06-11 19:23
-Option 1:  I used filter: ```textPayload: ("This is a console message")```, and didn't find any log.

-Option 2: 
   * I used filter ```jsonPayload.message:("This is a warning message written with GoogleLogger")```, got one log entry, whose time stamp is "2019-06-11T19:11:02.347648700Z".  And then I used filter ```jsonPayload.message:("Error LoggerMessage for Index page")``` got the second entry, whose timestamp is "2019-06-11T19:11:02.352401300Z".

   * I used filter

``` txt
timestamp >= "2019-06-11T19:11:02.347648700Z"  
timestamp <= "2019-06-11T19:11:02.352401300Z" 
```

I still couldn't get the log entry of "This is a console message"

**Comment by jskeet** [comment] 2019-06-11 19:32
What log were you searching through at the time? For example, here's me searching through all logs in GKE containers:

![2019-6-11 (33)](https://user-images.githubusercontent.com/17011/59300668-aba98d00-8c87-11e9-95cc-930490c13132.png)

Of course, it's possible that there's something else going on, like fluentd not running on your pods for some reason. For your earlier log entries that *did* have a `textPayload`, what labels were present? It looks like there are lots of things we still need to understand...

**Comment by shengxue** [comment] 2019-06-11 19:47
![image](https://user-images.githubusercontent.com/6092790/59301025-ed8b0100-8c90-11e9-94b1-6048f04658f7.png)

Possibly it is due to some settings of kubernetes or GCP?  I don't have much knowledge inside kubernetes. :(  I even didn't know fluentd before you mentioned it, and don't know how to check if it is running on my pod, how to make it run on my pod if it is not, etc.

**Comment by jskeet** [comment] 2019-06-11 19:53
The simplest way to find out whether fluentd is collecting console output as I'd expect it to be is to find the textPayload entry you mentioned in the earlier comments ("my message is logged as textPayload of log entry"). Look at the labels (not resource labels) on that message. For example, I have:

```json
labels: {
  compute.googleapis.com/resource_name:  "fluentd-gcp-v3.2.0-szqgj"   
  container.googleapis.com/namespace_name:  "default"   
  container.googleapis.com/pod_name:  "diagnostics-test-7c45d88c7b-7l5rw"   
  container.googleapis.com/stream:  "stdout"   
 }
```

When your container starts, do you have entries for things like "Application started. Press Ctrl+C to shut down" which ASP.NET core emits automatically?

**Comment by shengxue** [comment] 2019-06-11 20:18
our labels are like:
```json
labels: {
  compute.googleapis.com/resource_name:  "gke-cluster-***-default-pool-***"   
  container.googleapis.com/namespace_name:  "***"   
  container.googleapis.com/pod_name:  "***"   
  container.googleapis.com/stream:  "stdout"   
 }
```

And, we have entries like "Application started. Press Ctrl+C to shut down".

**Comment by jskeet** [comment] 2019-06-11 20:27
Okay... I'm not sure why I've got fluentd and you haven't, and I also don't know why the initial console output is being captured but later output isn't. Hmm. This is tricky :( (This will be my last comment for tonight, by the way.)

**Comment by jskeet** [comment] 2019-06-12 15:39
Okay, moving away from the console part for the moment, my understanding is:

- In my sample application, you see all the resource labels, regardless of whether `LogWarning` is called or the `LoggerMessage` call is used
- In your application, you only see the resource labels with `LogWarning` (etc) extension methods, not when using `LoggerMessage`.

Is that correct? If so, are you able to copying some of your configuration into the sample application, so we can try to get to a point where the minimal example works like your application?

**Comment by jskeet** [comment] 2019-06-14 15:15
Are there any updates on this? At the moment there's nothing more I can do from this side of things, I'm afraid.

**Comment by jskeet** [comment] 2019-07-01 13:55
Closing for the moment due to a lack of information. Please add another comment with more information if you'd like me to reopen the issue.

**Closed by jskeet** 2019-07-01 13:55 UTC
Labels: needs more info, priority: p2, status: investigating, type: bug
