### ISSUE TITLE
Google.Apis.Requests.RequestError Not found: Job prj-test-n-test:job_8b0eb264_74f5_4199_ab76_3d6 

### ISSUE THREAD

**Issue by TejendraPrasad** [googleapis/google-cloud-dotnet#6332] opened 2021-04-12 20:34 UTC
Hi,

I am trying to cancel job using below code 

`await bigQueryClient.CancelJobAsync(projectId: gcpProjectID, jobId: jobId, options: cancelJobOptions);`

Note: I am creating new bigQueryClient Object 

           ` var credentials = GoogleCredential.FromFile(keyFilePath);

            return BigQueryClient.Create(gcpProjectID, credentials);`

Everytime i get error as below 

`Google.Apis.Requests.RequestError Not found: Job prj-test-n-test:job_8b0eb264_74f5_4199_ab76_3d6 `

But job id does exists in console.

What i am doing wrong here?

thank you!
Tej

**Comment by jskeet** [comment] 2021-04-12 20:39
How did you retrieve the job ID? Is it possible there's a whitespace error or something similar?

If you could provide an example which reproduces the problem, that would be very helpful.

**Comment by TejendraPrasad** [comment] 2021-04-13 08:01
We have two Button - Search and Cancel

**Search**
			User search(query) against Google Bigquery
			
			var credentials = GoogleCredential.FromFile(keyFilePath);

            var bigQueryClient = BigQueryClient.Create(gcpProjectID, credentials);
			
			  var job = await bigQueryClient.CreateQueryJobAsync(
                    sql: query, 
                    parameters: parameters, 
                    options: new QueryOptions { UseQueryCache = false },
                    cancellationToken: cancellationTokenSource.Token);

                //delegate - To Set Job ID
                setJobId?.Invoke(job.Reference.JobId);  -- STORE JOB ID IN HttpRuntime.Cache

                // Wait for the job to complete.
                job = await job.PollUntilCompletedAsync();
			
	
When user click **Cancel** button
	
				//Retrieve Job ID from - HttpRuntime.Cache
				
				var credentials = GoogleCredential.FromFile(keyFilePath);

				var bigQueryClient = BigQueryClient.Create(gcpProjectID, credentials);

                var cancelJobOptions = new CancelJobOptions();

               var reference = bigQueryClient.GetJobReference(gcpProjectID, jobId);

               var cancelJob = await bigQueryClient.CancelJobAsync(reference);  //FAILS

               // var cancelJob = await bigQueryClient.CancelJobAsync(projectId: gcpProjectID, jobId: jobId, options: cancelJobOptions); //FAILS


Is if failing due to job completed? Like can we cancel when Job state = done not pending..??

**Comment by jskeet** [comment] 2021-04-13 08:29
We still don't have a clear idea of where the job ID is coming from really - you've said that you're storing it in the cache, but it would be a lot simpler if we could just see a complete example (no UI) which *just* interacts with BigQuery. I'll try writing one now to test your theory about it being due to the job being completed.

**Comment by TejendraPrasad** [comment] 2021-04-13 08:52
Hi @jskeet - Yes, store in Cache, when user press cancel button retrieve Job id and send it for cancel button.

Console Application - can be as below
```

`		        public static void Main()
                 {
                         ExecuteGCPQuery().GetAwaiter().GetResult();
                }
```
		
		
		 private static async Task ExecuteGCPQuery()
        {
            try
            {
				var credentials = GoogleCredential.FromFile(keyFilePath);

				var bigQueryClient = BigQueryClient.Create(gcpProjectID, credentials);
				
				  var job = await bigQueryClient.CreateQueryJobAsync(
						sql: query, 
						parameters: parameters, 
						options: new QueryOptions { UseQueryCache = false },
						cancellationToken: cancellationTokenSource.Token);

					var  jobId = job.Reference.JobId;

					// Wait for the job to complete.
					job = await job.PollUntilCompletedAsync();
					
					
					 var cancelJobOptions = new CancelJobOptions();

				   //var reference = bigQueryClient.GetJobReference(gcpProjectID, jobId);

				   //var cancelJob = await bigQueryClient.CancelJobAsync(reference);

				    var cancelJob = await bigQueryClient.CancelJobAsync(projectId: gcpProjectID,
					jobId: jobId, options: cancelJobOptions); //ERROR
			}
			catch (Exception ex)
            {
                string error = string.IsNullOrWhiteSpace(ex.InnerException?.Message) ? ex.Message : ex.InnerException.Message;

                Console.WriteLine(error);
            }
            finally
            {
                Console.ReadLine();
            }
		}`

**Comment by amanda-tarafa** [comment] 2021-04-13 08:57
As per [BigQuery documentation](https://cloud.google.com/bigquery/docs/managing-jobs#canceling_jobs) you can only cancel jobs that are Pending or Running. And even so, not all jobs can be canceled.

It might be that your job completes before you attempt to cancel it, and this might be the root cause of the problem. (I would expect a different error message though).

**Comment by jskeet** [comment] 2021-04-13 08:58
Is it possible that your job reference is location-specific?

What happens if you try `job.Cancel();` just after you've called `PollUntilCompletedAsync()`? Here's a simpler example (no need to use async here just for a demo) which works fine for me. Just pass in the project ID, dataset ID and table name, and it'll execute a count against the table. Please try this and see whether it works for you - note that it tries to cancel in two different ways.

```csharp
using Google.Cloud.BigQuery.V2;
using System;

namespace Issue6332
{
    class Program
    {
        static void Main(string[] args)
        {
            var projectId = args[0];
            var datasetId = args[1];
            var tableId = args[2];

            var client = BigQueryClient.Create(projectId);
            var table = client.GetTable(datasetId, tableId);
            var job = client.CreateQueryJob($"SELECT COUNT FROM {table}", parameters: null);

            Console.WriteLine($"Created job with ID: {job.Reference.JobId}");
            job = job.PollUntilCompleted();
            Console.WriteLine($"Job completed; state={job.State}");
            job = job.Cancel();
            Console.WriteLine($"Job cancel call completed; state={job.State}");

            var jobReference = client.GetJobReference(job.Reference.JobId);
            Console.WriteLine("Cancelling via job reference...");
            job = client.CancelJob(jobReference);
            Console.WriteLine($"Done; state={job.State}");
        }
    }
}
```

**Comment by jskeet** [comment] 2021-04-13 09:00
(Note that that's a *complete* example - if you can reproduce the problem, it would be really handy to have a similar complete example that does so. Your previous comment doesn't provide a sufficiently complete example.)

**Comment by TejendraPrasad** [comment] 2021-04-13 09:00
@amanda-tarafa  Yes, that is why i am confused why its not throwing error different error rather than saying now found but in console i am able to see Job id - Created, Read, Completed...

**Comment by TejendraPrasad** [comment] 2021-04-13 09:01
@jskeet  thank you will try and update you with simple Query.. that will help me to determine either is location based or it cannot cancel completed job.. as my query is executed within Milliseconds ....

**Comment by TejendraPrasad** [comment] 2021-04-13 09:06
@jskeet  Below is the execution of Log and Failure

`**Created job with ID:** job_66c3c0ea_0ad7_49e4_b2ce_1d9c70660299
**Job completed**; state=Done
**Job cancel call completed**; state=Done
**Cancelling via job reference**...
Google.Apis.Requests.RequestError
Not found: Job prj-test-n-test:job_66c3c0ea_0ad7_49e4_b2ce_1d9c70660299 [404]
Errors [
        Message[Not found: Job prj-test-n-test:job_66c3c0ea_0ad7_49e4_b2ce_1d9c70660299] Location[ - ] Reason[notFound] Domain[global]
]
`

**Comment by jskeet** [comment] 2021-04-13 09:16
@TejendraPrasad: Right - so the problem is that the job reference is wrong the second time.

Try changing the line declaring `jobReference` to:

```csharp
var jobReference = client.GetJobReference(projectId, job.Reference.JobId, job.Reference.Location);
```

If that then works, then that's the problem, and you should just make sure you store the location as well as the job ID. (I'm not entirely convinced that storing it in the HTTP cache is a good idea, but that's a different matter.)

**Comment by TejendraPrasad** [comment] 2021-04-13 09:24
@jskeet  thank you no error when passing Job Location

**Created job with ID**: job_0dc7b1e2_a126_478d_924c_5fc6ff0251ab
**Job completed**; state=Done
**Job cancel call completed**; state=Done
**Cancelling via job referenc**e...
Done; state=Done

---- In Console---

 10:20 AM
jobservice.cancel
testdata-testapp-tej-poc@prj-test-n-control.iam.gserviceaccount.com has executed jobservice.cancel on cancel
10:20 AM
jobservice.cancel
testdata-testapp-tej-poc@prj-test-n-control.iam.gserviceaccount.com has executed jobservice.cancel on cancel
10:19 AM
Insert job
testdata-testapp-tej-poc@prj-test-n-control.iam.gserviceaccount.com has inserted a new job (QUERY) job_0dc7b1e2_a126_478d_924c_5fc6ff0251ab.
10:19 AM
Complete job
Job job_0dc7b1e2_a126_478d_924c_5fc6ff0251ab (QUERY) is completed.
10:19 AM
Insert job
testdata-testapp-tej-poc@prj-test-n-control.iam.gserviceaccount.com has inserted a new job ( query ) job_0dc7b1e2_a126_478d_924c_5fc6ff0251ab
10:19 AM
Complete BigQuery job
testdata-testapp-tej-poc@prj-test-n-control.iam.gserviceaccount.com c

-- So there is not meaning to cancel if job state is done...

**Comment by TejendraPrasad** [comment] 2021-04-13 09:27
@jskeet  - (I'm not entirely convinced that storing it in the HTTP cache is a good idea, but that's a different matter.) - I am not finding alternative way to do - as User should cancel if query execution time too long and that is different Button click event so need Job details to cancel the execution..

Please suggest is there any best way to do?

@jskeet  does Job cancel cost in terms of GCP? If so, then need to find out benefit, basically, we planning to cancel long query execution time  to save cost...

**Comment by jskeet** [comment] 2021-04-13 10:00
> I am not finding alternative way to do - as User should cancel if query execution time too long and that is different Button click event so need Job details to cancel the execution..

That sounds like information that should be stored client-side - or possibly in a client-specific session. But the way you're doing it now, I suspect that if there are multiple concurrent users one could cancel a job started by another. But that's really outside the scope of this issue.

> Does Job cancel save cost in terms of GCP?

I don't know, I'm afraid. I would expect so, but I only maintain the client libraries. I'm not part of the BigQuery product team. The [BigQuery pricing page](https://cloud.google.com/bigquery/pricing) has some details, but if that's not enough I would suggest looking at the [BigQuery-specific support options](https://cloud.google.com/bigquery/docs/support).

I'll close this issue now as it looks like we've got to the bottom of everything around the client library.

**Closed by jskeet** 2021-04-13 10:00 UTC
Labels: api: bigquery, needs more info, type: question

**Comment by TejendraPrasad** [comment] 2021-04-13 10:04
@jskeet Yes, thank you so much for the quick help.
