### ISSUE TITLE
Spanner Data Beta07 - Cause the application threads to be stuck

### ISSUE THREAD

**Issue by tomerpeled** [googleapis/google-cloud-dotnet#2887] opened 2019-02-19 21:25 UTC
Hi,

We tried to work with Google.Cloud.Spanner.Data Beta07, but we've encountered with a very bad experience when working in a "heavy" load.
After some investigation, it seems that if the MaximumActiveSessions is reached in a burst, it will cause the whole application to get stuck!

I've succeed to arrange a very simple program which simulate this issue, here it is:

* notice that Players table is a simple table with around 40 columns.
The primary key over there is PlayerId which is defined as STRING(32).
I guess you can simulate it with a table with only one column as well...

```csharp
async Task Main()
{
    SessionPoolManager.Default.SessionPoolOptions.MaximumActiveSessions = 12; // the default is 100 - I'm just setting this to low value in order to simulate the issue
    SessionPoolManager.Default.SessionPoolOptions.WaitOnResourcesExhausted = ResourcesExhaustedBehavior.Block; // this is the default

    var connectionString = "";

    // fetch players ids
    var playersCount = 13;
    var playerIds = await FetchPlayersIds(connectionString, playersCount);
    
    // prepare tasks of a simple query on the Players table
    var tasks = new List<Task>();
    foreach(var playerId in playerIds)
    {
        tasks.Add(FetchPlayerId(connectionString, playerId));
    }

    Console.WriteLine("Before running the parallel Players queries");

    // run the tasks parallel - this will cause the stuck!
    await Task.WhenAll(tasks);

    Console.WriteLine("Finished");

}

private static async Task<List<string>> FetchPlayersIds(string connectionString, int playersCount)
{
    var playerIds = new List<string>();
    using (var connection = new SpannerConnection(connectionString))
    {
        var cmd = connection.CreateSelectCommand($"SELECT PlayerId FROM Players LIMIT {playersCount}");
        using (var reader = await cmd.ExecuteReaderAsync())
        {
            while (await reader.ReadAsync())
            {
                playerIds.Add(reader.GetFieldValue<string>("PlayerId"));
            }
        }
    }
    
    return playerIds;
}

private static async Task FetchPlayerId(string connectionString, string playerId)
{
    using (var connection = new SpannerConnection(connectionString))
    {
        var cmd = connection.CreateSelectCommand($"SELECT PlayerId FROM Players where PlayerId = '{playerId}'");

        var reader = await cmd.ExecuteReaderAsync();
        if (reader.HasRows)
        {
            await reader.ReadAsync();
        }
    }
}
```

**Comment by tomerpeled** [comment] 2019-02-19 21:26
Sorry about the indentation, didn't succeed to make it look good...

**Comment by jskeet** [comment] 2019-02-19 21:39
Thanks, I'll look into this tomorrow.

**Comment by jskeet** [comment] 2019-02-20 07:18
This turned out to be simple - it's just because you're not disposing the `SpannerDataReader`. (You're also not disposing the command, but that's less of an issue in this particular case.)

With this fixed code, it completes with no problems. (I've parameterized the query as well, as I can't bear to have data in a query like that ;)

```csharp
using (var cmd = connection.CreateSelectCommand("SELECT PlayerId FROM Players where PlayerId = @PlayerId"))
{
    cmd.Parameters.Add("@PlayerId", SpannerDbType.String, playerId);
    using (var reader = await cmd.ExecuteReaderAsync())
    {
        if (reader.HasRows)
        {
            await reader.ReadAsync();
        }
    }
}
```

I'll leave this open for now in case you have a follow-up, but I don't believe this is a bug in the Spanner library.

**Comment by tomerpeled** [comment] 2019-02-20 07:31
I'll check this and get back to you.

Actually I tried to arrange a simple example of snippet only with the usage of the Spanner ADO.Net  Library.

On our servers, we use EFCore on top of it, maybe I missed something in this example and maybe it also relates to the issue that we have (I mean that the DataReader isn't get disposed correctly via our EFCore implementation).

Sorry about the parameters, as I said, it was an attempt to reproduce the issue that we are experiencing with, on a side snippet.

**Comment by jskeet** [comment] 2019-02-20 07:58
It's definitely much appreciated that you took the trouble to make this easily reproducible :)

I *thought* we had a finalizer in `PooledSession` that would have helped diagnose this, but it looks like we don't. (I now have vague recollections of it not being quite as simple as it sounded.)

Likewise it looks like it's pretty tricky or perhaps impossible to get hold of the session pool statistics - that would have made life simpler, as you could have added some periodic logging which would show that the session pool believes all the sessions are active. I've created a small change to allow access to this - I'll try to include it for the next release. (It's actually showing the number of active sessions going up to 13, which is interesting in itself and which I'll investigate further.

**Comment by jskeet** [comment] 2019-02-20 08:00
(Ah - the 13 part is easy to explain - it includes *pending* session acquisitions, i.e. the one that can't get a session because of all the rest.)

**Comment by tomerpeled** [comment] 2019-02-20 08:34
That will be great!
I was also wondering why I saw more sessions opened than allowed (according to the MaximumActiveSessions), that explains it :)

From tests that I've made, it seems that our EFCore lib, indeed might have an issue with the disposing of the DbDataReader, but it happens only on bursts and then the application gets stuck.

I'll investigate this further...

BTW, I'm wondering why we didn't encounter with this issue with Beta03.

**Comment by jskeet** [comment] 2019-02-20 08:38
Beta03 had an entirely different session pool, with all kinds of different behaviour. I wouldn't like to guess at what was going on behind the scenes in this situation to be honest - it's possible that it was reusing sessions when it shouldn't, or creating far too many sessions.
I'd suggest it's *good* that the new behaviour has highlighted an issue (at least under our current hypothesis!) with the EFCore lib. I know it may not feel like that immediately...

**Comment by jskeet** [comment] 2019-02-20 09:02
@tomerpeled: If you could have a look at #2888 and see if that's what you'd expect in terms of diagnostics, that would be helpful.

**Comment by tomerpeled** [comment] 2019-02-20 09:16
Sure, thanks!

**Comment by jskeet** [comment] 2019-02-21 06:51
I'm going to close this now as it sounds like it's a problem in your EF library, but do let me know if I can help further.
(The `GetSessionPoolDatabaseStatistics` method is now merged, but I haven't done a release. I wasn't planning on doing one *imminently*, but if you need it for your investigation, do let me know.)

**Closed by jskeet** 2019-02-21 06:51 UTC
Labels: api: spanner, status: working as intended, type: bug

**Comment by tomerpeled** [comment] 2019-02-21 07:19
OK.

Just to let you know, it seems to be a problem with the EFCore framework. We've opened a ticket over there:
https://github.com/aspnet/EntityFrameworkCore/issues/14759#issuecomment-465771578

Thanks!
