### ISSUE TITLE
Random Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Uri'

### ISSUE THREAD

**Issue by ramondelemos** [googleapis/google-cloud-dotnet#8552] opened 2022-06-02 23:10 UTC
Hi, after upgrading from `netcoreapp3.1` to `net6.0` we having facing some random `System.InvalidCastException`. It happens only on calls of **Google.Cloud.Storage.V1.StorageClient.UploadObject**.

#### Exemple of the code

```C#
using System.IO;
using NLog;
using Google.Cloud.Storage.V1;
using NewRelic.Api.Agent;

namespace Storage
{
    internal class GCPStorageClient : IStorageClient
    {
        private Logger _Logger;
        private StorageClient _StorageClient;        
        public GCPStorageClient()
        {
            this._Logger = LogManager.GetCurrentClassLogger();
            this._StorageClient = StorageClient.Create();
        }

        [Transaction]
        public void Download(string bucket, string localFilePath, string filename)
        {
            this._Logger.Info($"Preparing to download {filename} from the {bucket} bucket");

            using (var stream = File.OpenWrite(localFilePath))
            {
                this._StorageClient.DownloadObject(bucket, filename, stream);
            }

            this._Logger.Info($"Downloaded {filename} from the {bucket} bucket");
        }

        [Transaction]
        public void Upload(string bucket, string filename, FileStream stream)
        {
            this._Logger.Info($"Preparing to upload {filename} to the {bucket} bucket");

            this._StorageClient.UploadObject(bucket, filename, "application/octet-stream", stream);

            this._Logger.Info($"Uploaded {filename} to the {bucket} bucket");
        }
    }
}
```

#### Stack trace

```
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Uri'.
at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.CheckFinalProgress()
at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.Execute()
at Storage.GCPStorageClient.Upload(String bucket, String filename, FileStream stream) in /app/src/Storage/GCPStorageClient.cs:39
```

#### Project dependencies

```xml
    <PackageReference Include="AWSSDK.S3" Version="3.3.20" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="3.7.0" />
    <PackageReference Include="Microsoft.Extensions.CommandLineUtils" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.4" />
    <PackageReference Include="NLog" Version="4.7.2" />
    <PackageReference Include="RabbitMQ.Client" Version="6.3.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="NewRelic.Agent.Api" Version="8.37.0" />
```

#### Environment details

  - Programming language: C#
  - OS: Linux
  - Docker Image: mcr.microsoft.com/dotnet/runtime:6.0-alpine
  - Language runtime version: net6.0
  - Package: Google.Cloud.Storage.V1
  - Package version: 3.7.0

Thanks!

**Comment by jskeet** [comment] 2022-06-03 07:22
Transferred to google-cloud-dotnet as that's the repository containing Google.Cloud.Storage.V1.

**Comment by jskeet** [comment] 2022-06-03 07:24
When you say "random" - do you mean it only happens occasionally, or something else? Are you able to reproduce this in a standalone console app?

(Note that today is a UK public holiday, so I won't be able to look in detail, but if you could provide more information I'll look on Monday.)

**Comment by jskeet** [comment] 2022-06-08 10:42
Please note that we won't be able to help with this issue without any more information.

**Comment by jskeet** [comment] 2022-06-10 11:10
Closing due to lack of information. If you're able to reproduce this and/or provide more information, we can reopen it.

**Comment by lukas-iamd** [comment] 2023-02-10 07:17
Hi, 

In our production environment, we encountered the same error. 

It seems to happen randomly. When a user retries to upload the same file, it works. 
I have been trying to reproduce the exception locally to no avail.

The stack trace in our logs reads:
```
Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Uri'
at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.CheckFinalProgress() 
at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.ExecuteAsync(CancellationToken cancellationToken) 
at <our own app>
```

We are using Google.Cloud.Storage.V1 v4.2.0 and dotnet 6.0

Thanks!

**Comment by jskeet** [comment] 2023-02-10 07:20
@lukas-iamd: Thanks, I'll have another look at the underlying code. How often does this happen, and could you tell us more about the production environment? (For example, with your knowledge of the context, does it seem likely to be a threading issue, or is this a low-traffic service which is unlikely to be uploading multiple files at the same time?)

**Comment by jskeet** [comment] 2023-02-10 08:29
Ah - I think I understand. `CheckFinalProgress` will throw an exception if it's in the `IUploadProgress`. So basically, the exception is happening earlier, and it just *appears* to be thrown from `CheckFinalProgress`. That'll make it significantly harder to work out the original issue, of course... but I'll see what I can do.

**Comment by lukas-iamd** [comment] 2023-02-10 08:50
Thanks for the quick response!

It doesn't happen very often. On average like once a day. 

It could be that it happens when two users try to upload at the same time, but at this time, we do not have the logs to verify this. If it would help, I could add them.

**Comment by jskeet** [comment] 2023-02-10 09:54
Hmm... I've got one *possible* theory (around failed HTTP header parsing), but I haven't managed to reproduce this yet. Are you able to pinpoint *exactly* which version of .NET 6.0 you're using? Additionally, I suspect that using the built-in logging for the library may help too, but it would be very "chatty" by default - is this an ASP.NET Core app? (If I were to create an adapter from Google.Apis.Core.Logging.ILogger to propagate to a Microsoft.Extensions.Logging.ILogger, would you be able to use that?)

**Comment by jskeet** [comment] 2023-02-10 14:55
Okay, I've decided that without a better stack trace, we'd really have a hard time making progress on this.

I've added an extension method for `IUploadProgress` to produce better stack traces - but it'll take a while before that's available and integrated into a Google.Cloud.Storage.V1 build. Will ping this bug again when we've got a version ready for testing.

**Comment by jskeet** [comment] 2023-02-14 11:59
Just to set expectations, my estimated timeline for this is:

- Publish new Google.Apis and Google.Apis.Core libraries on Feb 20th
- Publish new Google.Cloud.Storage.V1 on 21st

The new library won't *fix* the problem - it'll just make it much, much easier to work out what's going on, by giving a decent stack trace. Once we've seen a good stack trace, we can diagnose things better. It's hard to estimate how long it will then take to fix - but hopefully it won't be *too* bad, particularly if we can reproduce it reliably based on the extra information.

**Comment by lukas-iamd** [comment] 2023-02-14 12:05
Thanks!

Once the new version is released, we will update to the lates version. When the problem occurs again, I will post the logs here.

**Comment by jskeet** [comment] 2023-02-21 09:35
@lukas-iamd: I've now released Google.Cloud.Storage.V1 version 4.4.0. You shouldn't need to change your code at all, but you should now get much more helpful stack traces. If you could update and then post those stack traces, that would be wonderful, thanks.

**Comment by lukas-iamd** [comment] 2023-03-03 06:52
Hi Jon

The error happend again. 

`Exception: Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Uri'.

StackTrace: at System.Net.Http.Headers.HttpResponseHeaders.get_Location() at Google.Apis.Upload.ResumableUpload`1.InitiateSessionAsync(CancellationToken cancellationToken) at Google.Apis.Upload.ResumableUpload.UploadAsync(CancellationToken cancellationToken) at Google.Apis.Upload.UploadProgress.ThrowOnFailure(IUploadProgress progress) at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.ExecuteAsync(CancellationToken cancellationToken)`

**Comment by lukas-iamd** [comment] 2023-03-03 09:12
The app is published as self-contained using dotnet version 6.0.10

**Comment by jskeet** [comment] 2023-03-03 09:38
Thank you, that's incredibly helpful. Will try using that version and will update this issue with any progress. It feels a lot closer now, thanks to your extra info.

**Comment by jskeet** [comment] 2023-03-03 14:29
@lukas-iamd: Having spent some hours on it this morning, I'm admitting partial defeat, and filing a bug on the dotnet repo. Please could you confirm other environment info, e.g. docker container, OS etc?

**Comment by lukas-iamd** [comment] 2023-03-03 14:44
It runs as a CLI via IIS on Windows Server 2019.

**Comment by jskeet** [comment] 2023-03-03 14:46
@lukas-iamd: That's good to know, thanks. (And makes it less of a problem that I'm debugging on Windows...)

Will update that issue.

**Comment by jskeet** [comment] 2023-03-03 17:29
@ramondelemos and @lukas-iamd: As mentioned in the linked issue, there was a problem with NewRelic a while ago which *could* have provoked this. Please could you let me know if you're using NewRelic?

**Comment by lukas-iamd** [comment] 2023-03-06 12:21
A NewRelic infrastructure agent is running on the server. We will disable it for a while and see if that solves the problem. 
I will report back in a few days.

**Comment by jskeet** [comment] 2023-03-06 12:32
@lukas-iamd: Great, thanks. Fingers crossed. (And if that *is* the problem, it sounds like you may just be able to update to a newer version.)

**Comment by jskeet** [comment] 2023-03-13 08:50
@lukas-iamd: So, it's been about a week - have you observed any issues since removing the agent integration? (To be clear, I don't believe the problem is in the agent itself, but in the .NET code that integrates *with* the agent.)

**Comment by lukas-iamd** [comment] 2023-03-16 09:40
@jskeet Sorry it took so long to get back to you. Removing the NewRelic agent required a restart of the server which had to be planned.

But since it was removed, we have not yet encountered the error again! (if it should happen again I will ping you)

Thank you very much for all the help!

**Comment by jskeet** [comment] 2023-03-16 09:42
Fabulous - that's really good to hear. Hopefully just upgrading to a new version should fix the problem.
I'll close this issue now as it sounds like we've got to the bottom of it - but please just add a new comment if it happens again, and I'll reopen the issue.

**Closed by jskeet** 2023-03-16 09:42 UTC
Labels: type: bug, api: storage, priority: p2
