### ISSUE TITLE
Running query performance is affected by use of ListRows vs GetQueryResults

### ISSUE THREAD

**Issue by Zhenya-Ren** [googleapis/google-cloud-dotnet#2876] opened 2019-02-14 08:11 UTC
#### Environment details

* OS: Windows 10 64 bit

* .NET version: .Net Framework 4.5

* Package name and version:
  Google.Cloud.BigQuery.V2.dll 1.2.0
  Google.Api.Gax.Rest 2.5.0
  Google.Apis.Bigquery.v2 1.36.1.1404
  Google.Api.Gax  2.5.0
  Google.Apis.Auth 1.36.1
  Newtonsoft.Json 12.0.1.22727
  Google.Apis 1.36.1
  Google.Apis.Core 1.36.1

#### Steps to reproduce

  1. We make a query to air_quality_annual_summary table of 1 gb. The query returns all columns, 10000 rows. Running the query in the web ui (beta) takes around 2.5 seconds and 0.02 sec if cached. 
  2. We ran the query via api, like this:

`BigQueryResults results = this.client.ExecuteQuery(query, null);`

Running this takes around 5-6 seconds and a bit more than 3 seconds if cached, which is probably fine due to sending and parsing the result. Or? Is is as expected?

3. Once we received BigQueryResults we iterate through the rows.

`foreach (BigQueryRow row in results)
{
   // do something quick
}`

This iteration takes another 5-6 seconds. I looked in the code - this happens because when running the query, the query is saved into destination table. When iterating the rows are read from destination table with ListRows method. This unfortunately takes twice as long as it could be.

4. We now use a workaround to speed things up:

`var job = this.client.CreateQueryJob(query, null);`
`JobsResource.GetQueryResultsRequest queryResults = this.client.Service.Jobs.GetQueryResults(job.Reference.ProjectId, job.Reference.JobId).Execute();`

// Running query takes again around 5-6 seconds for non-cached and around 3 seconds for cached.

`foreach (TableRow row in queryResults.Rows)
{
 // do something quick
}`

// Iteration takes around 100 ms regardless if data was cached or not.

So the performance is 5 vs 10 seconds for not cached data and 3 vs 8 seconds for cached data, which is quite a big difference.

Yes, it is true that if the returned result would be more than 10 mb, than we would have to read the following pages and it would take longer time (this I haven't tested), however many queries are smaller than that.

It feels like it would be a good option to be able to choose if destination table should be used.

Also, as long as destination table is used, then the 'rows' field could be excluded from the response using GetQueryResultsRequest.Fields. Then running the query was around 0.5 - 1 seconds faster for me.

Finally, I attach the file with the query that we ran. It is very long, due to the logic of our application, but I don't think it should matter for this issue.
[query.txt](https://github.com/googleapis/google-cloud-dotnet/files/2863880/query.txt)

**Comment by jskeet** [comment] 2019-02-14 08:42
> It feels like it would be a good option to be able to choose if destination table should be used.

You can do that via `QueryOptions.DestinationTable`, although I don't think it will help in this particular case.

I don't think I really follow what you think is happening though - `ExecuteQuery` itself does *not* receive the results, so there's very little to parse (just the JSON for the response of the table).

I suspect your workaround is quicker because you're not actually getting all the results - you're only iterating over the *first page* of results. If you add the code to use the page token in the response to get further results, I suspect you'll see the same timing as with the simpler code.

Likewise I suspect that the web UI is quick because again you're only seeing the first part of the results, not all of them.

**Comment by Zhenya-Ren** [comment] 2019-02-14 12:45
Yes, you are right, I got just a bit more than a half of results. After I changed to get all the results the difference is not that big: around 8 vs 10 seconds or 6 vs 8 seconds (for cached), for a very small table (3 rows) the difference is around 1 vs 2 seconds. For a bigger result (600000 rows) however the difference was around 24 vs 35 seconds. 

I did this time like this:

`pageResults = queryResults.Execute();`
`myResults.Add(pageResults);`
`while (pageResults.PageToken != null)`
` {
                    queryResults.PageToken = pageResults.PageToken;
                    pageResults = queryResults.Execute();
                    myResults.Add(pageResults);
                }`

> You can do that via `QueryOptions.DestinationTable`, although I don't think it will help in this particular case.

The documentation says: "A destination table to write the results into. If this is not specified, the results will be stored in a temporary table."
What I meant is to slip using DestinationTable at all, here it is said about temporary table. 
Also, I looked in this code of BigQueryResults.cs:

`public IEnumerator<BigQueryRow> GetEnumerator() =>
_client.ListRows(TableReference, Schema, _options).GetEnumerator();`

and from BigQueryJob.cs, GetQueryTableReference:

`var tableReference = query.DestinationTable;
if (tableReference == null)
{
    // This can happen if it's been fetched with an odd field mask.
    throw new InvalidOperationException("Query doesn't have a destination table");
}`

From this code I see, that the results were written to temporary table and then ListRows is used to read rows. Instead of reading rows directly from query execution response. That is what I meant. Of course, I cannot test all possible queries, so it may be so that it is faster doing like this in some cases.

**Comment by jskeet** [comment] 2019-02-14 13:20
Query results are *always* written to a table, whether you've specified one or not, and whether you use `GetQueryResults` or not. If no destination table is specified, it's a temporary table.

I really, really wouldn't expect your approach to be faster here. (Indeed, the approach we're using is the one the BigQuery team specifically requested for the client libraries.) Do you have a simple way of reproducing the problem at this point? If I could reproduce it easily, I can look into where the time is going.

**Comment by Zhenya-Ren** [comment] 2019-02-14 14:14
Thanks for looking into it.

Yes, here is the code to reproduce the issue:

`public static void Test(BigQueryClient client)
        {
            string sql = @"SELECT `air_quality_annual_summary`.`Column_2_1` AS `Column_1_1`, `air_quality_annual_summary`.`Column_2_3` AS `Column_1_2`,
                        MAX(`air_quality_annual_summary`.`Column_2_5`) AS `Column_1_3`, SUM(`air_quality_annual_summary`.`Column_2_4`) AS `Column_1_4` 
                        FROM (SELECT `air_quality_annual_summary`.`Column_3_1` AS `Column_2_1`, `air_quality_annual_summary`.`Column_3_1` AS `Column_2_2`,
                        `air_quality_annual_summary`.`Column_3_2` AS `Column_2_3`, `air_quality_annual_summary`.`Column_3_3` AS `Column_2_4`, 
                        `air_quality_annual_summary`.`Column_3_4` AS `Column_2_5`, 1 AS `Column_2_6` FROM 
                        (SELECT `bigquery-public-data.epa_historical_air_quality.air_quality_annual_summary`.`county_code` AS `Column_3_1`, 
                        `bigquery-public-data.epa_historical_air_quality.air_quality_annual_summary`.`first_max_datetime` AS `Column_3_2`, 
                        `bigquery-public-data.epa_historical_air_quality.air_quality_annual_summary`.`observation_percent` AS `Column_3_3`, 
                        FALSE AS `Column_3_4` FROM `bigquery-public-data`.`epa_historical_air_quality`.`air_quality_annual_summary` AS 
                        `bigquery-public-data.epa_historical_air_quality.air_quality_annual_summary`) AS `air_quality_annual_summary`) AS 
                        `air_quality_annual_summary` GROUP BY `air_quality_annual_summary`.`Column_2_1`, `air_quality_annual_summary`.`Column_2_3`";

            var stopwatch = Stopwatch.StartNew();

            BigQueryResults results = client.ExecuteQuery(sql, null);
            int i = 0;
            foreach (var row in results)
            {
                i++;
            }

            var job1 = client.GetJob(results.JobReference);
            Debug.WriteLine(
                "Running query and iterating " + i + " rows took: " +
                stopwatch.ElapsedMilliseconds + ". Bytes processed = " + job1.Statistics.TotalBytesProcessed);

            stopwatch = Stopwatch.StartNew();

            var job = client.CreateQueryJob(sql, null);
            JobsResource.GetQueryResultsRequest queryResults = client.Service.Jobs.GetQueryResults(job.Reference.ProjectId, job.Reference.JobId);

            var finalResults = new List<GetQueryResultsResponse>();

            GetQueryResultsResponse pageResults = queryResults.Execute();
            finalResults.Add(pageResults);

            while (pageResults.PageToken != null)
            {
                queryResults.PageToken = pageResults.PageToken;
                pageResults = queryResults.Execute();
                finalResults.Add(pageResults);
            }

            i = 0;
            foreach (var row in finalResults.SelectMany(response => response.Rows))
            {
                i++;
            }

            Debug.WriteLine(
                "Running query via job and iterating " +
                i + " rows took: " + stopwatch.ElapsedMilliseconds +
                ". Bytes processed = " + job.Statistics.TotalBytesProcessed);
        }`

Here is my output:
Running query and iterating 619037 rows took: 33139. Bytes processed = 0
Running query via job and iterating 619037 rows took: 23494. Bytes processed = 

Sorry for the format of the code - those symbols ` also used in my sql string.

**Comment by jskeet** [comment] 2019-02-14 14:15
Right, that's slightly harder for me to use though, without any data or table at the moment. Have you tried the same thing with a simple table of just a few columns, which is easy enough to create on demand? Don't worry if not - I can try to do that tomorrow.

**Comment by Zhenya-Ren** [comment] 2019-02-14 14:32
Oh, ok, I thought this public data is available for all. Yes, I tried with
small table with 3 rows and 5 columns with simple query that just selects
all. But tomorrow is fine.

**Comment by jskeet** [comment] 2019-02-14 14:39
Ah, I hadn't spotted that it was the public data set. Thanks, that'll make things simpler. It'll still be tomorrow before I can get to it, but hopefully I'll get to the bottom of it.

**Comment by jskeet** [comment] 2019-02-15 08:09
Update: I've reproduced this with a slightly smaller difference (27s vs 23s). I'm now looking further at where that time is being spent.

**Comment by Zhenya-Ren** [comment] 2019-02-15 08:17
Great! Thanks!

**Comment by jskeet** [comment] 2019-02-15 08:57
Okay, here's where I've got to:

By default, GetQueryResults appears to fetch at most 87,500 rows, whereas ListRows fetches 100,000. So I altered the code for the "simple" version to fetch 87,500 at a time. That way we can compare the requests more directly.

The requests to GetQueryResults that fetch 87,500 rows take 2.5-2.7 seconds each. The requests to ListRows that fetch 87,500 rows take 3.2-3.6 seconds each. That's despite the ListRows responses being very slightly smaller, as they don't include schema information. That's timing from Fiddler, so it shouldn't include any JSON decoding in .NET.

At this point, it *looks* to me like it's something I need to talk to the server team about. Given that they're fetching the same data, I can't see why ListRows would be slower. I'll ask internally and let you know anything I hear back (that I can make public, of course).

Thanks for bringing this to our attention, and including a repro - that does make things much simpler!

**Comment by jskeet** [comment] 2019-03-06 15:11
Just as an update, we're still not sure why ListRows is slower here, but the updated advice is for client libraries to use GetQueryResults now... so we *may* end up moving to that. However, that'll be a non-trivial amount of work (with more complex code as a result), so I'm planning on waiting until we know more about why ListRows is slower... if that can be fixed server-side, then I'd prefer to leave the client code as it is.

**Comment by BaronChen** [comment] 2019-03-26 00:19
Hi, any updates on this one? We are kind of facing the same issue.

**Comment by jskeet** [comment] 2019-03-26 07:07
@BaronChen: No, I'm afraid not. I'll ping the internal bug to hopefully find out more so we can make a plan.

**Closed** 2019-04-24 12:34 UTC
Labels: api: bigquery, needs work, status: investigating, type: question

**Comment by jskeet** [comment] 2019-04-24 13:52
@Zhenya-Ren @BaronChen: The library now uses GetQueryResults again, and is released as Google.Cloud.BigQuery.V2 version 1.4.0-beta01. Please let me know if you see any problems.
