### ISSUE TITLE
Conversion from DateTime to Timestamp requires the DateTime kind to be Utc

### ISSUE THREAD

**Issue by neil-gok** [googleapis/google-cloud-dotnet#6261] opened 2021-03-21 14:15 UTC
#### Environment details

  - OS:  Windows 10
  - .NET version: .net Core 3.1
  - Package name and version: Google.Cloud.Firestore 2.3.0

#### Steps to reproduce

  1. Insert record with Save C# DateTime property as UTC - Successful
  2. Get record previously saved.  

It appears that deserialization fails, when deserializing a Firestore timestamp into a .net DateTime property.

**Comment by jskeet** [comment] 2021-03-21 14:18
Deserialization wouldn't give you that error, because it would be converting *from* a Timestamp *into* a `DateTime` property.

Please provide a code sample of what you're trying to do... it's unclear exactly what's going on from just that brief description.

**Comment by neil-gok** [comment] 2021-03-21 14:43
Good point regarding deserialization.  I just found documentation on Timestamp.FromDateTime, which fixes my issue.  I'm fairly new to Firestore and this library, sorry for jumping the gun there.  Once I store something as Timestamp, it returns in "1970-01-01T00:00:00Z" format.  I'll need to display the original date that was saved on screen, so how can I convert it back to a DateTime?

**Comment by jskeet** [comment] 2021-03-21 14:49
> Once I store something as Timestamp, it returns in "1970-01-01T00:00:00Z" format.

I don't know what you mean by "it returns" - it's stored as a `Timestamp`, which is a native Firestore data type.

> I'll need to display the original date that was saved on screen, so how can I convert it back to a DateTime?

Well you can call `ToDateTime` to convert it back into a `DateTime`, but that will return a `DateTime` with a `Kind` of `Utc`... if you originally performed any time zone conversions, you'd need to perform the reverse conversions to get back to the original value.

**Comment by neil-gok** [comment] 2021-03-21 15:18
When I look at the record in Firestore, it looks like below.  

"Tue Mar 30 2021 20:00:00 GMT-0400 (Eastern Daylight Time)"

When I stated "it returns", what I meant is that when I query the record using the following command; 

Query query = repo.fireStoreDb.Collection(collectionName).WhereGreaterThanOrEqualTo(nameof(MyCustomObject.Date), sunday);

The Date values that are deserialized into the C# List, displays as {Timestamp: 1970-01-01T00:00:00Z}.  

When I attempt to convert it with ToDateTime, it does not convert it to the original date. 

records.FirstOrDefault().Date.ToDateTime()
{1/1/1970 12:00:00 AM}
    Date: {1/1/1970 12:00:00 AM}
    Day: 1
    DayOfWeek: Thursday
    DayOfYear: 1
    Hour: 0
    Kind: Utc
    Millisecond: 0
    Minute: 0
    Month: 1
    Second: 0
    Ticks: 621355968000000000
    TimeOfDay: {00:00:00}
    Year: 1970

I would like to get the original date of Mar 30 2021.

**Comment by jskeet** [comment] 2021-03-21 15:23
"displays as" - that's in the debugger, right? That's just a string representation. The value is a timestamp, not a string representation.

It looks like you haven't actually managed to retrieve the value properly. Unfortunately without a complete sample, it's going to be very hard to help you any further. Please provide actual code - but just individual lines, but a complete example that stores a value and retrieves it again, so that I can reproduce the problem. (At the moment we don't know how you're getting from `query` to `records`, or what your types look like.)

**Comment by neil-gok** [comment] 2021-03-21 22:59
I think you are right, I am not retrieving the value property, which is why I keep getting the default date 1/1/1970 12:00:00 AM.  My code sample is quite large, since I have a repo, base repo, and a type.  I'll work on distilling it down to a smaller sample to post here.

Should I be using a DateTime property in my class for the Date field, or the Google.Cloud.Firestore Timestamp type?  When I use DateTime, I keep throwing an exception "Unexpected character encountered while parsing value: {. Path 'Date', "

The Date property below is the issue.  When I change it to Timestamp, I keep returning 1/1/1970 12:00:00 AM when deserializing into the below type.  

I'll work on getting you the full code sample.  

public class MyCustomObject : FireStoreBase
    {
        [FirestoreProperty]
        public string StartTime { get; set; }
        [FirestoreProperty]
        public string EndTime { get; set; }
         [FirestoreProperty]
        public Location Location { get; set; }
        [FirestoreProperty]
        public ApplicationUser AddedBy { get; set; }
        [FirestoreProperty]
        public Timestamp StartDate { get; set; }
        [FirestoreProperty]
        public DateTime Date { get; set; }
    }

**Comment by neil-gok** [comment] 2021-03-21 23:44
I figured out my problem.  Thanks for the assistance.

**Comment by jskeet** [comment] 2021-03-22 06:10
Okay - I'll close this issue now.

**Closed by jskeet** 2021-03-22 06:10 UTC
Labels: api: firestore, type: question
