### ISSUE TITLE
Producing a Self contained file .NET 6 / Linux-x64 fails to run.

### ISSUE THREAD

**Issue by defjamuk** [googleapis/google-cloud-dotnet#8288] opened 2022-03-30 17:41 UTC
Build a linux-x64 self-contained executable using .net 6. on stock ubuntu 21.10
Use NUGET to install V2.5 of the Google.Cloud.Firestore library to connect to a Firestore instance.

Dotnet version: 6.0.201 [/usr/share/dotnet/sdk]
Project build details: 
"Enable Ready To Run": true
"Trim unused assemblies": true
"Produce Single File": true
"Include native libraries for self extract": true

A single file is produced and when executed an error is displayed:
**"Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libcoreclr.so' or one of its dependencies."**

If the executable is built **NOT** as a single file, the application executes successfully.

Any attempt to produce a single file results in an error on Linux.
The same settings but targetting win-x64 produces a single file that works without error (built on Linux, executed on Windows 11).

Enc stack trace --

[stack_trace.txt](https://github.com/googleapis/google-cloud-dotnet/files/8382872/stack_trace.txt)

**Comment by jskeet** [comment] 2022-03-30 17:46
I'll have a look at this when I get a chance (*hopefully* tomorrow) but if libcoreclr.so isn't found, that sounds like it may be a tooling issue more than a client library issue. Will dig a bit deeper.

(It may well be that moving from Grpc.Core to Grpc.Net.Client helps with this; I don't know yet...)

**Comment by jskeet** [comment] 2022-03-30 17:47
If you could provide a simple project file, Program.cs (I'd hope that a simple console app would demonstrate this) and command line that you're using to produce it would be great - the details you've given already are a good start, but files I can copy/paste/build are even better :)

**Comment by defjamuk** [comment] 2022-03-30 17:51
Give me an hour -- I'll get together a sample project

**Comment by jskeet** [comment] 2022-03-30 17:52
Cracking - I definitely won't be looking at this for another 12 hours anyway :)

**Comment by defjamuk** [comment] 2022-03-30 20:16
Enclosed is a zipped project that produces the problem. The appsettings.json are not correct so don't worry about privacy. The cert is a real one to allow the project to load correctly.

The proj file contains the settings needed to produce the single self contained file.
[ConsoleApp2.zip](https://github.com/googleapis/google-cloud-dotnet/files/8383784/ConsoleApp2.zip)

**Comment by defjamuk** [comment] 2022-03-31 11:54
After some more investigation, this config appears to be the culprit -- 

        <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>

This config (in the proj file) causes the resultant executable to also include the appsettings.json in the single produced file.
If the appsettings.json file is copied to the output separately, then the code runs as expected.

**Comment by jskeet** [comment] 2022-03-31 11:58
@defjamuk: Thanks so much for producing the repro *and* then continuing to investigate.

This doesn't sound like it's something that's really library-specific - are you happy for me to close the issue (and you might want to file it on a .NET tools repo) or would you like me to investigate further?

**Comment by defjamuk** [comment] 2022-03-31 12:06
I think it might warrant a little more investigation. If I remove the Firebase library then the error doesn't occur. Although this is a sample project, the original was a service app that connected to some AWS queues and moved data to other sub-systems. I was producing single file executables without issue. A requirement was added to send some queued data to a firestore endpoint. When I added the Firestore library I couldn't produce a single executable.

**Comment by jskeet** [comment] 2022-03-31 12:11
Okay. I'll investigate when I get a chance, but as you have a workaround I won't rush over it - which means I'll get to it next week, if that's okay. (My *guess* is that this is due to extra files being needed for Grpc.Core, but I want to investigate rather than going by guesswork :)

**Comment by defjamuk** [comment] 2022-03-31 12:13
Appreciated this -- Is there anything else I can look at to help with the debugging? Could I add the source for the library to the project and follow the calls? If so, do you know what projects would I need to add?

**Comment by jskeet** [comment] 2022-04-04 10:21
Ah - interestingly, for me at least, this only happens in a Release build, not Debug. But at least I've reproduced it. Investigating further.

**Comment by jskeet** [comment] 2022-04-04 14:44
Further notes:

## Reducing the program

I've managed to reproduce the same error with a smaller program:

```csharp
using System;
using Google.Cloud.Firestore;

var db = FirestoreDb.Create("project");
await foreach (var collection in db.ListRootCollectionsAsync())
{
    Console.WriteLine(db);
}
```

... and that's without any of the Microsoft.Extensions packages.

## Changing to Translate

If I try using Google.Cloud.Translate.V3 instead, with this program:

```csharp
using System;
using Google.Cloud.Translate.V3;

TranslationServiceClient client = TranslationServiceClient.Create();
TranslateTextRequest request = new TranslateTextRequest
{
    Contents = { "It is raining." },
    TargetLanguageCode = "fr-FR",
    Parent = "projects/xyz"
};
TranslateTextResponse response = client.TranslateText(request);
Console.WriteLine(response);
```

... then I get a different issue:

> Unhandled exception. System.TypeLoadException: Could not load type 'System.IEquatable`1' from assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

I can work around that with a bit of extra code to force `IEquatable<T>` to be retained:

```csharp
IEquatable<string> x = "";
Console.WriteLine(x.Equals("x"));
```

... although at this stage I'm really pretty sceptical about the whole feature.

## Getting really minimal

I can even remove appsettings.json, leaving just this:

```csharp
using System;
using Google.Cloud.Translate.V3;

IEquatable<string> x = "";
Console.WriteLine(x.Equals("x"));
TranslationServiceClient client = TranslationServiceClient.Create();
TranslateTextRequest request = new TranslateTextRequest
{
    Contents = { "It is raining." },
    TargetLanguageCode = "fr-FR",
    Parent = "projects/xyz"
};
TranslateTextResponse response = client.TranslateText(request);
Console.WriteLine(response);
```

and a project file of:

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <SelfContained>true</SelfContained>
        <PublishTrimmed>true</PublishTrimmed>
        <PublishReadyToRun>true</PublishReadyToRun>
        <PublishSingleFile>true</PublishSingleFile>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
        <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Google.Cloud.Translate.V3" Version="2.4.0" />
    </ItemGroup>
</Project>
```

My next step (tomorrow) will be to try to remove the Google Cloud Client library from the equation as well, using just Grpc.Core directly.

**Comment by jskeet** [comment] 2022-04-12 12:08
I'm going to close this issue now, as it doesn't look like it's specific to this repo.

**Closed by jskeet** 2022-04-12 12:08 UTC
Labels: type: question
