### ISSUE TITLE
LogError in Asp.NET Core app does not log the exception to Stackdriver

### ISSUE THREAD

**Issue by xbrabec** [googleapis/google-cloud-dotnet#2967] opened 2019-03-21 15:55 UTC
- OS: Linux, Mac
  - .NET version: DotNetCore 2.1
  - Package name and version: Google.Cloud.Diagnostics.AspNetCore, 3.0.0-beta10

#### Steps to reproduce

  1. Create a simple HelloWorld AspNet.Core project and enable logging to StackDriver
  2. log exception using ILogger.LogError and pass the exception in a parameter 

The log message shows up in the stack driver but there is no trace of the exception passed in.

Seems like GoogleLogger.cs is just calling formatter to get the exception into the message, but this by default does nothing. So the exception is completely ignored and not logged.

**Comment by jskeet** [comment] 2019-03-21 16:00
Thanks, I'll look at this in the next 24 hours. It may have been an oversight when adding custom exception formatting - I'll need to look through the history.

**Comment by jskeet** [comment] 2019-03-22 16:03
Right, now managed to reproduce. I now understand why it's behaving the way it does.
It looks like we probably want an extra field in the struct for the exception information.

Does adding a key of "exception" with the result of calling `ToString()` on the exception make sense to you? (Only when there's an exception, of course.)
I can see the benefits of an alternative approach of `exception_type` with the exception type, `exception_message` with the message, and `exception` with the whole of `ToString()`, but that might be overkill.

**Comment by xbrabec** [comment] 2019-03-22 16:09
I think that extra field exception with ex.ToString() is good enough.

ToString by default outputs exception type, message and stack trace, so from my perspective ... perfect.

Thanks.

**Comment by jskeet** [comment] 2019-03-22 16:15
Yes, all the information would definitely be present. I can imagine that being able to group or filter by the exception type could be useful - but that could come later.

**Comment by jskeet** [comment] 2019-03-25 07:10
This is now fixed in master; I'll do a release today as that will also improve other matters.

**Closed** 2019-03-25 07:09 UTC
Labels: api: logging, priority: p2, type: bug
