### ISSUE TITLE
Google cloud storage upload not throwing exception when internent conection is lost during upload

### ISSUE THREAD

**Issue by np441** [googleapis/google-cloud-dotnet#4946] opened 2020-05-06 13:43 UTC
Hi, when uploading file to GCS using .NET library, if internet connection is lost, upload just stops and that's it. It would make sense to throw exception if upload has been unresponsive for specified period of time. Could such feature be added to future .NET library versions?

**Comment by jskeet** [comment] 2020-05-06 13:51
Could you provide a short but complete example of this, including the package and version you're depending on? (There are two storage libraries for .NET - Google.Cloud.Storage.V1, which is a wrapper around Google.Apis.Storage.v1.) Last time I tried something similar (when a different issue was reported) it threw the exception I expected it to.

Note that the ResumableUpload code unfortunately _doesn't_ throw an exception directly - but it returns an `IProgress` which contains the relevant exception. That can't be changed now, for backward compatibility reasons. But if you use the result of the `IProgress` appropriately, you should be fine.

**Comment by np441** [comment] 2020-05-06 14:12
This is code I use:

            try
            {
                var cloudObject = new Google.Apis.Storage.v1.Data.Object
                {
                    Bucket = "MyBucket"
                    Name = "MyFile"
                };
                var memoryStream = new MemoryStream();
                var storage = StorageClient.Create();
                await storage.UploadObjectAsync(cloudObject, memoryStream, options: new UploadObjectOptions { ChunkSize = 4 * 262144 });
            }
            catch (Exception)
            {
                throw;
            }
and package details in the attached picture:
![image](https://user-images.githubusercontent.com/64908138/81187381-a8fd0800-8fbc-11ea-822d-e9adab3abbbe.png)

**Comment by jskeet** [comment] 2020-05-06 14:56
Okay, I'll try to reproduce the error with that code. What *exactly* do you observe? Does the task just not complete at all (so the `await` hangs, effectively)?

**Comment by np441** [comment] 2020-05-06 15:06
Yes, my program just hangs on await. Program is fully responsive, but code after await in never executed, it is just waiting for the upload to finish.

**Comment by jskeet** [comment] 2020-05-12 07:52
Apologies for not coming back to this before. I thought I'd added a comment already, but I must have been distracted. (Or tried to add the comment before re-enabling the network...)

Currently the code you've provided wouldn't compile. It's easy to *make* it compile, but then it's only uploading an empty object, so it's hard to make the network fail *during* that upload.
In my tests using your code, if I tried the code without a network connection, it fails immediately.

If you could provide a complete example which genuinely demonstrates the issue, that would really help. Note that you can provide a cancellation token to `UploadObjectAsync`, so while I would definitely *expect* it to fail at some point anyway (just due to an underlying `HttpClient` exception), you can effectively provide your own deadline by providing `new CancellationTokenSource(TimeSpan.FromMinutes(1)).Token`, for example.

**Comment by jskeet** [comment] 2020-05-18 06:52
Any more information about this? Without more information I'm afraid we won't be able to proceed any further - I'll close the issue if we haven't heard anything by the end of the week.

**Comment by jskeet** [comment] 2020-05-23 07:18
Closed due to lack of further information. We can reopen if we get more information.

**Comment by matsCacka** [comment] 2020-08-12 12:28
Hello,  I can attest to the same behavior when uploading files to GCS. If I try to upload file without network connection, code fails immediately, however if I disconnect from network in the middle of upload, it just freezes on await, no exception is thrown. (In some case it throws `WebException`, but it happens after 5-10, sometimes even more minutes.) I would like to know if it is normal behavior or there is some setting that could be used to control after how long inactive period task should be cancelled. Yes, I read your reply about providing my own `CancellationTokenSource` , but I would first like to address the underlying issue to see if it can be solved. I can provide full working example if you need. Also, this is my first post here and I am not sure if I this issue can be reopened or I need to add new issue?

**Comment by amanda-tarafa** [comment] 2020-08-12 13:16
@matsCacka If you can provide us with the minimum full working example that'd be great. We can try to reproduce. I'm reopenning for the time being becuse it does seem to be exactly the same behaviour initially described.

**Comment by matsCacka** [comment] 2020-08-13 12:10
@amanda-tarafa, hi, I have attached small sample, please change file path to some file on your system and try to disconnect from network in the middle of the upload.

[GcsSample.zip](https://github.com/googleapis/google-cloud-dotnet/files/5068766/GcsSample.zip)

.

**Comment by amanda-tarafa** [comment] 2020-08-14 10:39
Thanks, looking into it, I'll report back here when I know more.

**Comment by amanda-tarafa** [comment] 2020-08-20 14:05
@matsCacka I haven't been able to reproduce this issue nor by using your code, or very similar code on a console app instead of WPF. What I've done:

- I'm uploading a ~17 MB file that uploads fine when I don't cut the internet connection (by pulling the cable) in roughly 4 minutes.
- If I pull the cable and then start either your WPF app or my Console app, it fails inmediately after with the following exception:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'oauth2.googleapis.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.CheckFinalProgress() in /_/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/StorageClientImpl.UploadObject.cs:line 198
   at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.<ExecuteAsync>d__7.MoveNext() in /_/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/StorageClientImpl.UploadObject.cs:line 174
--- End of stack trace from previous location where exception was thrown ---

```

- With both WPF and console apps, if I pull the cable after the upload has started, either roughly at the beginning, the middle or the end of the upload, it always fails in less that 1minute with the following exception:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'storage.googleapis.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.CheckFinalProgress() in /_/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/StorageClientImpl.UploadObject.cs:line 198
   at Google.Cloud.Storage.V1.StorageClientImpl.UploadHelper.<ExecuteAsync>d__7.MoveNext() in /_/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/StorageClientImpl.UploadObject.cs:line 174
--- End of stack trace from previous location where exception was thrown ---

```

This is the expected behaviour in all cases.

As a side, a note about your test code: You don't need to read the file into a MemoryStream and pass that to the UploadObjectAsync method. You can pass the FileStream directly:

```
using (var file = File.OpenRead(@"your-file-path"))
{
    var storage = StorageClient.Create();
    await storage.UploadObjectAsync(cloudObject, file);
}
```

Unless you can provide more information that helps us reproduce this issue, there's little we can do.

**Comment by amanda-tarafa** [comment] 2020-08-20 14:33
@matsCacka, This issue might actually be down to Windows version, network card, or some other environment factors. Have you tried running that sample app in different environments? Does it consistently hangs for you? Could you try posting the file without using the library, directly using an HttpClient, pulling the cable and seeing if that fails or hangs?

If that's the case, there's not much we can do at the client library side, we rely on the HttpClient reaction to the lack of connectivity, if for some reason, HttpClient is not throwing then we can't tell that something went wrong. Using a cancellation token as @jskeet suggested in [this previous comment](https://github.com/googleapis/google-cloud-dotnet/issues/4946#issuecomment-627176470) might really be the cleanest solution for you.

**Comment by amanda-tarafa** [comment] 2020-08-24 08:54
@matsCacka I'll close this issue now since we strongly suspect this is not a problem with the client library but with the environment your app is being run in. Do please add a new comment if you think otherwise.

**Closed by amanda-tarafa** 2020-08-24 08:54 UTC
Labels: api: storage, needs more info, type: question
