### ISSUE TITLE
Use proxy with Google.Cloud.Storage.V1

### ISSUE THREAD

**Issue by amarlot** [googleapis/google-cloud-dotnet#1832] opened 2018-01-16 12:52 UTC
Hello team,

By design in our "on prem" datacenter we need to use a proxy to go though internet.
We have been able to upload some file to our GCS without any proxy but we are stuck to upload a file when we need to use a proxy.

We use:
- .NET Core 2
- Windows Server 2016 to run our website

Where should we define the proxy in the API ? We didn't find any way to do it ! Is it even possible ?
We tried several ways but without success.

Code is very basic : 
```
using (StreamReader r = new StreamReader("xxxx.json"))
            {
                string jsonFromStream = r.ReadToEnd();
                json = JsonConvert.DeserializeObject(jsonFromStream);
            }

            var credential = GoogleCredential.FromJson(json.ToString());
            var storageClient = StorageClient.Create(credential);
            storageClient.UploadObject("lr-xxxx-yyyy", "blogexample/image.png", null, image);
```

Thanks,
Alexandre

**Comment by jskeet** [comment] 2018-01-16 13:50
The Storage library uses `HttpClient` under the hood. I'd expect you to be able to configure your proxy in the same way you do for any other `HttpClient` - ideally at a system or application level.

(I believe that `WebRequest.DefaultWebProxy` is the simplest way to set a global proxy for the application.)

If you need to do it just for the specific `HttpClient`, you can modify the `HttpHandler` at the core in a slightly verbose way:

```csharp
var handler = storageClient.Service.HttpClient.MessageHandler;
while (true)
{
    if (handler is DelegatingHandler)
    {
        handler = ((DelegatingHandler) handler).InnerHandler;
    }
    else if (handler is HttpClientHandler)
    {
        break;
    }
    else
    {
        throw new Exception("Unexpected handler type");
    }
}
var clientHandler = (HttpClientHandler) handler;
clientHandler.Proxy = ...;
```

That's untested, but I'd expect it to work.

**Comment by cstech-carlcamilleri** [comment] 2018-01-16 14:13
Hi,

To add some further information:
storageClient.Service.HttpClient.MessageHandler is of type ConfigurableMessageHandler
Inheriting from DelegatingHandler
Inheriting from HttpMessageHandler
Implementing IDisposable

We cannot override the proxy at any level in .NET Core.

Essentially, we also note that this line:
`var storageClient = StorageClient.Create(credential);`
may need to get an OAuth token, so presumably the proxy needs to be taken into consideration even before that?

Thanks,
Carl

**Comment by jskeet** [comment] 2018-01-16 14:21
Doh, sorry - the first line should have been

```csharp
HttpMessageHandler handler = client.Service.HttpClient.MessageHandler;
```

Basically we need to loop to get the innermost handler.

However, you don't need to worry about the credentials part - creating the `StorageClient` doesn't fetch any credentials in itself - so long as you set the proxy before you make any calls, you should be okay.

**Comment by cstech-carlcamilleri** [comment] 2018-01-17 07:23
Hi,

This seems to work as expected! We'll be running further tests but looks OK for now, and we will post further updates to share other detail!

Thanks,
Carl

**Comment by jskeet** [comment] 2018-01-17 08:50
Great! Thanks for letting me know. Will close this for now - but you can still add updates.

**Comment by cstech-carlcamilleri** [comment] 2018-01-25 07:25
Hi,

We have made further tests on this and the results are as follows.

Considering the below code snippet:

 ```
 var credential = GoogleCredential.FromJson(json.ToString());
           var storageClient = StorageClient.Create(credential);
HttpMessageHandler handler = storageClient.Service.HttpClient.MessageHandler;

HttpClientHandler httpClientHandler = null;
while (true)
{
	if (handler is DelegatingHandler)
	{
		handler = ((DelegatingHandler)handler).InnerHandler;
	}
	else if (handler is HttpClientHandler)
	{
		break;
	}
	else
	{
		throw new Exception("Unexpected handler type");
	}
}
var clientHandler = (HttpClientHandler)handler;
clientHandler.Proxy = new WebProxy("127.0.0.1", 8888);
storageClient.UploadObject(req.BucketName, "blog/" + id + "/" + "CoverPhoto.png", null, req.CoverPhoto);
```
In the above, we are requesting that connections pass through a Fiddler installation.

In Fiddler, we see these requests:
![fiddler_requests](https://user-images.githubusercontent.com/35494465/35375840-c65afa32-01a8-11e8-8691-ea671fffd53e.png)

In fact we do not seem to see any requests to get Authentication tokens.

The behaviour that we currently have is that:
1. If we run the Dotnet application under the credentials of a user account that has a system proxy configured, the upload works fine and we see the above 3 requests in Fiddler
2. On the other hand, if we remove the proxy configuration from the user account (or run the application under another user account with no proxy configuration), the upload fails and we do not see any requests in Fiddler

This therefore suggests that the proxy configured from the above code snippet is being taken into account during the upload, however, the library is trying to make requests (potentially to get Auth tokens?) without considering the proxy configuration given in the code. In this case therefore, it uses the system proxy and therefore works with one system user account, but not with the other.

Any further support on this would be appreciated please

Thanks,
Carl

**Comment by jskeet** [comment] 2018-01-25 07:33
You're creating a GoogleCredential but not specifying any scopes - in that situation it will create a JWT, which doesn't require any additional requests to get auth tokens.

I do wonder whether Fiddler is changing the results here - my understanding is that that works *as a proxy*, so anything which is manually setting the proxy may effectively be bypassing Fiddler for that reason.

You might want to use Wireshark to see what connections are opened - you won't get as much information from the result, but you'd be able to see the network connections without interfering with them.

**Comment by cstech-carlcamilleri** [comment] 2018-01-25 10:43
Hi,

In fact we are manually setting the proxy to be Fiddler, in the following line:
`clientHandler.Proxy = new WebProxy("127.0.0.1", 8888);`

Since the upload is successful when running under a Windows User Account that has a System Proxy configured, but not when running the same application under a different Windows User Account that doesn't have a system proxy configured, does this not indicate that the library is making a connection without using the same `clientHandler` for which we are setting manually a proxy?

Thanks

**Comment by jskeet** [comment] 2018-01-25 10:54
Hmm... I'm slightly lost at this point.

To take the API part out of things, what happens if you get the `HttpClient` out of the service, and make a request to some HTTP site with it? You should be able to see what that's doing very clearly in Wireshark.

**Comment by jskeet** [comment] 2018-01-25 11:13
Ah, I've just thought of something that could be messing things up - these days there are potentially multiple `HttpClientHandler` objects created - see https://github.com/google/google-api-dotnet-client/blob/b84eae30720de5225a17f7b8d56b866cc120405e/Src/Support/Google.Apis.Core/Http/HttpClientFactory.cs#L50

In particular, the second client *will* be used for object download in Google.Cloud.Storage.V1, so that we can validate hashes correctly. I wouldn't expect it to cause a problem in object *upload* though. Hmm.

**Comment by cstech-carlcamilleri** [comment] 2018-01-25 16:16
Hi,

We have made further tests on this and in fact it does seem that there are other HTTP(S) requests being made with other HttpClientHandlers

The code that we have now is:

```
 var credential = GoogleCredential.FromJson(json.ToString());
var storageClient = StorageClient.Create(credential);
HttpMessageHandler handler = storageClient.Service.HttpClient.MessageHandler;

 
HttpClientHandler httpClientHandler = null;
while (true)
{
	if (handler is DelegatingHandler)
	{
		handler = ((DelegatingHandler)handler).InnerHandler;
	}
	else if (handler is HttpClientHandler)
	{
		break;
	}
	else
	{
		throw new Exception("Unexpected handler type");
	}
}


var clientHandler = (HttpClientHandler)handler;
string proxyIp = mConfigRoot.GetValue<string>("AppSettings:Proxy:IP");
var proxyPort = mConfigRoot.GetValue<int>("AppSettings:Proxy:Port");
var proxyByPassList = mConfigRoot.GetValue<string>("AppSettings:Proxy:ByPassList")?.Split(";");
if (proxyByPassList?.Length == 0)
	proxyByPassList = null;


if (!string.IsNullOrWhiteSpace(proxyIp))
{
	clientHandler.Proxy = new WebProxy(proxyIp, proxyPort);
	

	if (storageClient.Service.HttpClient.MessageHandler is Google.Apis.Http.ConfigurableMessageHandler)
	{
		foreach (var interceptor in ((Google.Apis.Http.ConfigurableMessageHandler)storageClient.Service.HttpClient.MessageHandler).ExecuteInterceptors)
		{
			if (interceptor is ServiceCredential)
			{
				HttpMessageHandler credentialHandler = ((ServiceCredential)interceptor).HttpClient?.MessageHandler;
				while(true)
				{
					if(credentialHandler is DelegatingHandler && ((DelegatingHandler)credentialHandler).InnerHandler is  DelegatingHandler)
					{
						credentialHandler =  ((DelegatingHandler)credentialHandler).InnerHandler as DelegatingHandler;
					}
					else if (credentialHandler is DelegatingHandler && ((DelegatingHandler)credentialHandler).InnerHandler is HttpClientHandler)
					{
						((HttpClientHandler)((DelegatingHandler)credentialHandler).InnerHandler).Proxy = new WebProxy(proxyIp, proxyPort);
						break;
					}
					else if (credentialHandler is HttpClientHandler)
					{
						((HttpClientHandler)credentialHandler).Proxy= new WebProxy(proxyIp, proxyPort);
						break;
					}
					else
					{
						throw new Exception("Unexpected handler type");
					}
				}
			}
		}
	}

	HttpMessageHandler underlyingCredentialHandler = ((ServiceAccountCredential)((GoogleCredential)storageClient.Service.HttpClientInitializer).UnderlyingCredential).HttpClient.MessageHandler;
	while (true)
	{
		if (underlyingCredentialHandler is DelegatingHandler && ((DelegatingHandler)underlyingCredentialHandler).InnerHandler is DelegatingHandler)
		{
			underlyingCredentialHandler = ((DelegatingHandler)underlyingCredentialHandler).InnerHandler as DelegatingHandler;
		}
		else if (underlyingCredentialHandler is DelegatingHandler && ((DelegatingHandler)underlyingCredentialHandler).InnerHandler is HttpClientHandler)
		{
			((HttpClientHandler)((DelegatingHandler)underlyingCredentialHandler).InnerHandler).Proxy = new WebProxy(proxyIp, proxyPort);
			break;
		}
		else if (underlyingCredentialHandler is HttpClientHandler)
		{
			((HttpClientHandler)underlyingCredentialHandler).Proxy = new WebProxy(proxyIp, proxyPort);
			break;
		}
		else
		{
			throw new Exception("Unexpected handler type");
		}
	}
}

storageClient.UploadObject(req.BucketName, "blog/" + id + "/" + "CoverPhoto.png", null, req.CoverPhoto);
```

Different from the previous version we are also setting the proxy configuration in:
1. storageClient.Service.HttpClient.MessageHandler
2. storageClient.Service.HttpClientInitializer.UnderlyingCredential

With this logic, if we set our proxy to Fiddler, we see more requests:
![fiddler](https://user-images.githubusercontent.com/35494465/35398852-3008e4e0-01f3-11e8-9f07-f23267e3c674.png)

Specifically the call to /oauth2/v4/token is being also passed through the proxy

Upload is therefore now being successful using the configured proxy, whilst running the application on a user account that has no system proxy configured.

We'll clean up the code a bit and post a new version for the interest

Thanks,
Carl

**Comment by jskeet** [comment] 2018-01-25 18:54
That's good detective work - sorry you had to go through it!

@chrisdunelm It feels like we should probably make all of this rather simpler. Thoughts?

**Comment by amarlot** [comment] 2018-01-26 08:21
Hello,
If could support an easy way to use a proxy it would be great :)
In France most of compagnies use proxy everywhere.
Alex

**Comment by jskeet** [comment] 2018-01-26 08:25
@amarlot: In most cases, it will work transparently, just using the system-defined or application-defined proxy. We'd only be providing extra support for the case where *just the Google API access* needed to use a proxy. I would hope that's a relatively rare use case.

**Comment by cstech-carlcamilleri** [comment] 2018-01-26 11:22
Hi,

To add some further detail, in fact our use case is that we need to use the same proxy throughout the application (for any external resource). 

In traditional .NET configuration, we could do this via a web.config setting e.g.:
```
<system.net>
		<defaultProxy>
			<proxy usesystemdefault="true" proxyaddress="http://1270.0.0.1:8080" bypassonlocal="true" />
			<bypasslist>
				<add address=".*localhost.*" />				
			</bypasslist>
		</defaultProxy>
	</system.net>
```

The issue is that in a .NET Core application, we cannot (so far) configure centrally a proxy for the application, and therefore the application:
1. Either inherits the proxy configuration for the user account under which it is running
2. Or, at code level, for every instance of HttpClient, the proxy is configured specifically (as we are doing in the code above).

A feature of GCP library as described by @amarlot would therefore help in any case where a proxy configuration is required to access external resources, and the application is not running under the privileges of a user account that has the proxy configured at the OS level.

Roughly speaking:
1. Custom code would instantiate a proxy configuration once:
`Google.Cloud.Proxy = new WebProxy(proxyIp, proxyPort);`
2. Then any HttpClient object instantiated throughout the library uses the proxy:
`myClient.Proxy = Google.Cloud.Proxy;`

Hence encapsulating the above logic

Thanks,
Carl

**Comment by jskeet** [comment] 2018-01-26 11:33
> The issue is that in a .NET Core application, we cannot (so far) configure centrally a proxy for the application

Hmm. This feels like something that would be better addressed at a .NET Core level, ideally. While we could potentially do something in Google.Apis for this, it could easily become redundant.

Digging through the .NET Core code, I *suspect* that setting the `http_proxy` environment variable would work on Unix boxes, but that's not ideal of course.

Are you aware of any feature request issues for Microsoft about this? If there aren't any, we should potentially raise one. That's not to say we can't also *consider* adding a feature to the Google library, but it feels like doing it app-wide would be cleaner.

**Comment by cstech-carlcamilleri** [comment] 2018-01-26 11:47
Hi,

Very much in agreement, in fact we do see a few related requests:
https://github.com/dotnet/corefx/issues/26493
https://github.com/dotnet/corefx/issues/24574

Thanks,
Carl

**Comment by jskeet** [comment] 2018-01-26 14:17
Thanks for those links. Will consider how best to provide support here with that in mind.

**Comment by driis** [comment] 2020-09-15 12:00
Has there been any development in this ? Is there an easy way to configure the `StorageClient` to use a proxy in the current version of the SDK ?

**Comment by jskeet** [comment] 2020-09-15 12:30
@driis: No, there hasn't been any change here. You can create a `StorageService` yourself, specifying an `HttpClientFactory` - but in most case I'd expect the operating system level proxy configuration to be applied automatically.

**Closed by jskeet** 2020-09-15 12:30 UTC
Labels: type: question

**Comment by liiri** [comment] 2021-03-31 06:53
Shorter version based on the solution provided by @cstech-carlcamilleri 

```
    public static class StorageClientExtensions
    {
        public static void SetProxyIfNeeded(this StorageClient storageClient, string httpProxy)
        {
            if (string.IsNullOrEmpty(httpProxy))
            {
                return;
            }

            var webProxy = new WebProxy(httpProxy);

            var handler = (HttpMessageHandler) storageClient.Service.HttpClient.MessageHandler;
            handler?.SetProxy(webProxy);

            foreach (var interceptor in storageClient.Service.HttpClient.MessageHandler.ExecuteInterceptors)
            {
                if (!(interceptor is ServiceCredential serviceCredential))
                {
                    continue;
                }

                serviceCredential.HttpClient?.MessageHandler?.SetProxy(webProxy);
            }

            var serviceAccountCredentialHandler = ((ServiceAccountCredential) ((GoogleCredential) storageClient.Service.HttpClientInitializer).UnderlyingCredential).HttpClient.MessageHandler;
            serviceAccountCredentialHandler?.SetProxy(webProxy);
        }

        private static void SetProxy(this HttpMessageHandler handler, IWebProxy webProxy)
        {
            while (!(handler is HttpClientHandler))
            {
                if (handler is DelegatingHandler delegatingHandler)
                {
                    handler = delegatingHandler.InnerHandler;
                }
                else
                {
                    throw new Exception($"Unexpected handler type - {handler?.GetType().GetDisplayName()}");
                }
            }

            ((HttpClientHandler) handler).Proxy = webProxy;
        }
    }
```

**Comment by amanda-tarafa** [comment] 2021-09-29 10:39
For posterity, we now have a better way to set a proxy for Google.Cloud.Storage.V1. If you are using Google.Cloud.Storage.V1 v3.5.0 (which is the latest at the moment of writing this) or an older version, you need to add an explicit dependency on Google.Api.Gax.Rest version 3.4.0.

```csharp
IWebProxy proxy = ...;
Google.Apis.Http.HttpClientFactory factory = HttpClientFactory.ForProxy(proxy);

var scopes = new string[] { ... };
var credential= GoogleCredential.FromFile(sa_file); //Or any other way of obtaining the a Google credential
credential = credential.CreateScoped(scopes).CreateWithHttpClientFactory(factory);

var clientBuilder = new StorageClientBuilder
{
    Credential = credential,
    // All HTTP client instances for API calls will be obtained from this factory
    HttpClientFactory = factory
}

var client = clientBuilder.Build();

// Use client to perform Storage operations normally.
```

**Comment by liiri** [comment] 2021-09-29 10:57
@amanda-tarafa thanks! any plans to integrate it also to `Google.Cloud.Logging.V2`? I don't see it in Logging V3.4.0

**Comment by amanda-tarafa** [comment] 2021-09-29 14:18
@liiri Google.Cloud.Logging.V2 works over gRPC not over HTTP so the way to set a proxy is different. There are two steps:

- For the credential, you use code just like the one above, i.e. create the credential with the HttpClientFactory that has a proxy set.
- Then, create the service client as follows (which will make all auth related requests go through the proxy):

  ```csharp
            GoogleCredential proxiedCredential = ...; // Similar to above
            LoggingServiceV2ClientBuilder builder = new LoggingServiceV2ClientBuilder
            {
                TokenAccessMethod = (proxiedCredential as ITokenAccess).GetAccessTokenForRequestAsync
            };
            var loggingClient = builder.Build();
           // Use loggingClient normally.
  ```
- For gRPC requests (i.e. the actual logging requests) to use a proxy, then, you need to look at what Grpc.Core requieres. And that is to set any of a number of environment variables as described on the first point in [gRPC environment variables docs](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md#grpc-environment-variables). Also you might want to take a look at issues like https://github.com/grpc/grpc/issues/13323 and https://github.com/grpc/grpc/issues/12815 which are related. If you cannot make this part work, It's better if you ask directly on https://github.com/grpc/grpc as we just rely on gRPC's implementation for proxy setting.
