### ISSUE TITLE
"Request had invalid authentication credentials" issue with Vision API

### ISSUE THREAD

**Issue by Uvindu96** [googleapis/google-cloud-dotnet#5882] opened 2021-01-25 15:08 UTC
Hi all,

Recently I'm using Google Vision API in my image processing application, I got everything right but after deploying the application in the Kubernetes cluster I'm getting an error like this,

![Screenshot from 2021-01-24 23-03-52](https://user-images.githubusercontent.com/31029812/105721974-2aca0280-5f4b-11eb-88c3-bd95c55e514a.png)

And this is the code sample

![Screenshot from 2021-01-25 20-35-04](https://user-images.githubusercontent.com/31029812/105723578-f22b2880-5f4c-11eb-8804-653e50629b71.png)

I can understand that this is an issue with authentication, I have already enabled the vision API in my cluster and I tried using default credentials and using my service account but nothing worked. Is there any solution for this?

#### Environment details

  - OS: Ubuntu 20.04
  - .NET version: mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
  - Package name and version: Google.Cloud.Vision.V1

Thanks!

**Comment by amanda-tarafa** [comment] 2021-01-25 15:56
A few questions to try and find out what might be happening.

Can you post a screenshot of your Cluster's and Pool's configuration? In particular the Security section and the Metadata section for each? (Black out any sensitive info that might be showing of course).

When you try with your service account:
- When you specify your service account, are you doing so with the `GOOGLE_APPLICATION_CREDENTIALS` env var? Are you certain that the correct service account key is on the path specified in the env var?
- Are you certain that your service account has access to the Vision API? Can you try with an OWNER service account even if temporarily, I just want to make sure that you have no missing permissions. To be honest, if it was this I would have expected a different error message, but it's better to make sure.

**Comment by amanda-tarafa** [comment] 2021-01-26 10:46
I'm trying to reproduce, but with no luck so far. It would be useful if you could share some of the information I've requested above.

**Comment by Uvindu96** [comment] 2021-01-26 10:48
@amanda-tarafa  Thanks for the quick response. These are the screenshots of my cluster configuration 

Node pool security 
![Screenshot from 2021-01-26 15-20-37](https://user-images.githubusercontent.com/31029812/105830387-72a06680-5feb-11eb-9338-4e2c6a71dfe4.png)

Node pool metadata section
![Screenshot from 2021-01-26 15-25-34](https://user-images.githubusercontent.com/31029812/105830454-89df5400-5feb-11eb-9b61-d212262778af.png)


Cluster security 
![Screenshot from 2021-01-26 15-21-22](https://user-images.githubusercontent.com/31029812/105830523-99f73380-5feb-11eb-9912-01723874dab8.png)

Cluster metadata section
![Screenshot from 2021-01-26 15-25-52](https://user-images.githubusercontent.com/31029812/105830548-a2e80500-5feb-11eb-99a0-35302cbcb81a.png)

In my project, I have enabled the API already
![Screenshot from 2021-01-26 15-52-37](https://user-images.githubusercontent.com/31029812/105832990-9c0ec180-5fee-11eb-8dac-fef9aacdaa5c.png)

I hope these are the screenshots that you requested.

I used the "export GOOGLE_APPLICATION_CREDENTIALS=PATH_TO_KEY_FILE" command to provide the Application default credentials in order to authenticate the API. and also I tried using "gcloud auth application-default login" command nothing woked. And I tried using a new service account with the OWNER role that also didn't work.

I would like to add more information I was trying out this sample (https://github.com/meteatamel/knative-tutorial/blob/master/docs/image-processing-pipeline.md) In this case I have [setup](https://github.com/meteatamel/knative-tutorial/tree/master/setup) 2 service accounts, so including default service account, there are 3 service accounts in total.

**Comment by Uvindu96** [comment] 2021-01-26 10:59
When I try to create new credientials for the vision API it says I already got the required credentials.
![Screenshot from 2021-01-26 16-23-48](https://user-images.githubusercontent.com/31029812/105836755-abdcd480-5ff3-11eb-97d2-be129683c89c.jpg)

**Comment by amanda-tarafa** [comment] 2021-01-26 11:07
That's perfect info @Uvindu96 . I'll try to reproduce with your configuration and get back here as soon as I know more.

Can I ask you to do one last test. Can you disable Workload Identity and try again? Report back even if you get a different error.

**Comment by Uvindu96** [comment] 2021-01-26 15:18
@amanda-tarafa  yes sure, I will try this without workload identity and let you know the results.

**Comment by Uvindu96** [comment] 2021-01-27 13:03
@amanda-tarafa I tested again as you requested, First I disable the workload identity. And also I manually disable the vision API and enable the API again. After those steps, I deployed the application  again and now I'm getting a different error, 

![Screenshot from 2021-01-27 18-27-20](https://user-images.githubusercontent.com/31029812/105994556-c4b9b880-60cd-11eb-97f9-14778f8f170e.png)

This the error now I'm getting. I think still its requesting permission for the API.

**Comment by amanda-tarafa** [comment] 2021-01-27 14:55
OK, but this is now something that is expected because of how you have configured your pool:

- For using the [Vision API annote image](https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1#imageannotator) features, you need one of the following scopes: https://www.googleapis.com/auth/cloud-platform or https://www.googleapis.com/auth/cloud-vision.
- The default access scopes (you can read on the ? tooltip) that you have configured for your pool (as per Pool security screenshot) do not include either.
- Unfurtunalately, access scopes cannot be modified after a pool has been created, so you'll have to create a new pool for the existing cluster (and make sure you deploy to the correct pool after) or a new cluster entirely.
- When creating the new pool, instead of selecting "Allow default access", select "Allow full access to all cloud APIs" or "Set access for each API".
- If you selected "Set access for each API" then make sure to set "Cloud Platform" to "Enabled". The rest that are configured are the same as the default ones.
- Also, make sure that the Compute Engine default service account has a role that allows it to use the Vision API. It's usually created with Editor role, and that is enough, but if you have restristect the account, please check. To check the account, on the Cloud Console, go to IAM & Admin -> IAM. On the list there should be an account named "Compute Engine default service account" and you should be able to confirm whether the role is Editor or not. You can read more about Compute Engine default service accounts and the differences between access roles and access scopes [here](https://cloud.google.com/compute/docs/access/service-accounts#default_service_account). 

The steps above should you make your code work and you can use as a workaround at least temporarily. Please let me know.

That said, there seems to be a problem with Workload Identity and at least the Compute Engine default service account, and possibly non default service accounts as well. I'm still trying to reproduce reliably (some unrelated issues are blocking me at the moment) but I'll get there. I'll get back to this issue when I know more, whether is a problem with the library or something else, etc.

**Comment by Uvindu96** [comment] 2021-01-28 10:55
@amanda-tarafa  Finally it worked...!!!! The only change I did was adding OWNER permission to the compute engine service account (Which allows all the resources). Thanks for the efforts you took to fix this and for your time. I had a good support from you.

![Screenshot from 2021-01-28 16-22-01](https://user-images.githubusercontent.com/31029812/106128482-710aa600-6185-11eb-8642-06778c34f774.png)

**Comment by amanda-tarafa** [comment] 2021-01-28 11:21
I'm glad it worked! I will close this issue now, since I'm looking at the Workload Identity related problems that you were having at first, internally. If there's some relevant infor, I will share here.

**Closed by amanda-tarafa** 2021-01-28 11:21 UTC
Labels: api: vision, type: question
