### ISSUE TITLE
Unclear documentation for generating protobuf schema

### ISSUE THREAD

**Issue by citrus-ben** [googleapis/google-cloud-dotnet#8846] opened 2022-07-05 03:37 UTC
I originally raised this against the [protobuf google group](https://groups.google.com/g/protobuf/c/ok447qzM1cc/m/-PiN6grbAQAJ) but was encouraged to raise this here instead.

I'm trying to using the BigQuery Storage V1 Write client to update bigquery in a C# app.
I'm following the example in [the dotnet reference](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.BigQuery.Storage.V1/latest/Google.Cloud.BigQuery.Storage.V1.BigQueryWriteClient#Google_Cloud_BigQuery_Storage_V1_BigQueryWriteClient_AppendRows_Google_Api_Gax_Grpc_CallSettings_Google_Api_Gax_Grpc_BidirectionalStreamingSettings_) but it doesn't contain a complete setup.
I've written a sample proto message that I believe follows the requirements laid out in the [documentation](https://cloud.google.com/bigquery/docs/reference/storage/rpc/google.cloud.bigquery.storage.v1#protoschema), but I get an error message when attempting to append a row.
This leads me to believe that I'm not creating my ProtoDescriptor correctly, and I'm unable to find the correct documentation on how to map a type to a ProtoDescriptor?

The documentation for the proto schema states that I should be able to include the known types.

My error message is: 
Grpc.Core.RpcException : Status(StatusCode="InvalidArgument", Detail="Invalid proto schema: BqMessage.proto: RequestSummaryTableMessage.request_id: ".google.protobuf.StringValue" is not defined
proto spec:
```text
syntax="proto3"
import "google/protobuf/wrappers.proto";
message TableUpdate {
 google.protobuf.StringValue request_id = 1;
}
```

C# code:

```csharp
var protoRows = new AppendRowsRequest.Types.ProtoData();
var mappedMessage =<irrelevant mapper to proto model>
// Initialize a request
var row = new ProtoRows
{
    SerializedRows = { mappedMessage.ToByteString() },
};

protoRows.Rows = row;
protoRows.WriterSchema = new ProtoSchema
{
    ProtoDescriptor = TableUpdateMessage.Descriptor.ToProto(),
};
AppendRowsRequest request = new ()
{
    WriteStreamAsWriteStreamName = WriteStreamName.FromProjectDatasetTableStream("[PROJECT]", "[DATASET]", "[TABLE_NAME]", "_default"),
    Offset = 0L,
    ProtoRows = protoRows,
    TraceId = string.Empty,
};
```

**Comment by jskeet** [comment] 2022-07-05 04:27
Thanks for reporting this here. I'm travelling this week which will make my updates slightly less frequent, but I'll do what I can.

Can I just check that your proto *actually* looks like this:

```text
syntax="proto3";
import "google/protobuf/wrappers.proto";
message TableUpdate {
  google.protobuf.StringValue request_id = 1;
}
```

(With semi-colons and "wrappers" instead of "wrapper".) That's what I'd expect... I just want to make sure that I'm reproducing the right thing.

Your code looks fine to me - given that the documentation says that the protobuf well-known types *don't* need to be included, I'd expect this to be okay.
Later today I'll try to reproduce this myself, and then (assuming I get the same error) get in touch with the BigQuery team to find out what's going on. I'll update this issue when I have more information.

**Comment by citrus-ben** [comment] 2022-07-05 04:35
Yeah that is correct, I've updated my example (We'll blame an anonymization process for removing the semi-colon)

**Comment by jskeet** [comment] 2022-07-05 04:39
No problem - thanks for the confirmation and the clear repro.

**Comment by jskeet** [comment] 2022-07-05 16:14
Okay, I've managed to reproduce the issue, using the code below. I'll ping the BQ team to find out what's happening.

message1.proto:

```proto
syntax="proto3";

message Message1 {
  string request_id = 1;
}
```

message2.proto:

```proto
syntax="proto3";

import "google/protobuf/wrappers.proto";

message Message2 {
  google.protobuf.StringValue request_id = 1;
}
```

Program.cs:

```csharp
using Google.Cloud.BigQuery.Storage.V1;
using Google.Protobuf;
using static Google.Cloud.BigQuery.Storage.V1.AppendRowsRequest.Types;

// This works
await WriteRowAsync("table1", new Message1 { RequestId = "test-message-1" });
// This fails with error:
// Invalid proto schema: BqMessage.proto: Message2.request_id: ".google.protobuf.StringValue" is not defined.
// Entity: projects/.../datasets/.../tables/.../streams/_default
await WriteRowAsync("table2", new Message2 { RequestId = "test-message-2" });

async Task WriteRowAsync(string tableId, IMessage message)
{
    // Change these to the appropriate project ID and dataset ID
    string projectId = "...";
    string datasetId = "...";

    var streamName = new WriteStreamName(projectId, datasetId, tableId, "_default");
    AppendRowsRequest request = new()
    {
        WriteStreamAsWriteStreamName = streamName,
        ProtoRows = new ProtoData
        {
            Rows = new ProtoRows { SerializedRows = { message.ToByteString() } },
            WriterSchema = new ProtoSchema { ProtoDescriptor = message.Descriptor.ToProto() }
        }
    };

    var client = BigQueryWriteClient.Create();
    var appendStream = client.AppendRows();

    await appendStream.WriteAsync(request);
    await appendStream.WriteCompleteAsync();
    await foreach (var response in appendStream.GetResponseStream())
    {
        Console.WriteLine(response);
    }
}
```

**Comment by jskeet** [comment] 2022-07-08 07:08
Okay, I've been in touch with the product team. Unfortunately the documentation was a little forward-looking - not all well-known types are supported at the moment; in particular the wrapper types are *not* currently supported.

The simplest approach to fixing this is to use `proto2` syntax instead of `proto3`. That way you get *field presence* within the wire format, and BigQuery is able to tell the difference between an explicitly-set empty string, and a field which hasn't been set. So for example, here's a proto:

```text
syntax="proto2";

message Message3 {
  optional string request_id = 1;
  optional string description = 2;
}
```

And code to write data (using the above framework):

```csharp
await WriteRowAsync("table3", new Message3 { Description = "No request ID" });
await WriteRowAsync("table3", new Message3 { RequestId = "", Description = "Empty request ID" });
await WriteRowAsync("table3", new Message3 { RequestId = "test-request-id", Description = "Non-empty request ID" });
```

And the result in the BigQuery console:

![BigQuery console showing inserted data](https://user-images.githubusercontent.com/17011/177936496-c9506748-bdce-4872-9b91-2b5791b91b28.png)

The documentation is currently being corrected; apologies that you ran into this. I believe the protobuf support for BigQuery Storage is still evolving, so hopefully this won't be the only solution in the future, but I can't give any concrete plans or dates.

I'll close this issue now as I don't believe any further work is needed in the client library, but hopefully the above approach will work for you.

**Closed by jskeet** 2022-07-08 07:08 UTC
