### ISSUE TITLE
[Firestore] Asynchronous methods from library hang and don't return anything. 

### ISSUE THREAD

**Issue by nmggithub** [googleapis/google-cloud-dotnet#4652] opened 2020-03-24 00:43 UTC
Hello. I am trying to incorporate Cloud Firestore into a C# application. I created the async method below (and I call it from the main method of my application):

```
        public async Task firebaseStuff()
        {
            FirestoreDb db = FirestoreDb.Create(projectId);
            CollectionReference collection = db.Collection("users");
            QuerySnapshot allUsers = await collection.GetSnapshotAsync();
            MessageBox.Show("Done Querying!");
            return;
        }
```

The users collection only has one document. The `GetSnapshotAsync()` method doesn't seem to return anything and the "Done Querying!" box never shows. Am I missing something?

**Comment by jskeet** [comment] 2020-03-24 06:46
Please show us your project file, which will include all the dependencies. You might see this if there's a mismatch between gRPC versions.

**Comment by nmggithub** [comment] 2020-03-24 15:16
I'm not sure how much I can share, as I signed an NDA with the company I am working for with this project. However, I did notice something when I woke up this morning. Some previous versions of the above method used write operations. Those write operations seem to have made it into the database.After testing out some write operations just now, it appears they work fairly quickly. However, the method itself in the code appears to not return and just hangs. Could this still be caused by mismatched gRPC versions?

**Comment by jskeet** [comment] 2020-03-24 15:21
You don't need to provide us any of your production code - a short but complete example that reproduces the problem would be better, in fact.

It's hard to tell just from that description whether the problem could still be due to gRPC versions, to be honest. We really need to see code and/or a project file.

**Comment by nmggithub** [comment] 2020-03-24 15:30
Would the `packages.config` file work to see the dependencies? As for example code, see my original comment. The method is called like so:
```
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS",  pathToServiceAccountJson);
            firebaseStuff().Wait();
```

I used `.Wait()` to avoid the rest of the program from interfering, but it also doesn't work without that. Below is a modification of the method that uses a write operation. As expressed, this writes to the database but never actually returns.

```
        public async Task<Google.Cloud.Firestore.DocumentReference> firebaseStuff()
        {
            FirestoreDb db = FirestoreDb.Create(projectId);
            CollectionReference collection = db.Collection("users");
            MessageBox.Show("Hello!");
            return await collection.AddAsync(new { Name = new { First = "Ada!!", Last = "Lovelace" }, Born = 1815, Time = DateTime.Now.ToString("yyyyMMddHHmmssffff") });
        }
```

**Comment by jskeet** [comment] 2020-03-24 15:39
> Would the packages.config file work to see the dependencies?

It would be a starting point, but not nearly as helpful as a complete example I can just build and run myself.

> As for example code, see my original comment. 

That's not a short but complete example though - it's just a single method. It looks like it's *probably* a WinForms app, but I'd rather not guess at everything going on - problems like this can be tough enough to diagnose even when we *have* both got exactly the same code. If I'm having to guess at half the code, it's going to be much harder.

> I used .Wait() to avoid the rest of the program from interfering

Ah. That may well be all of the problem then - if you're doing that from a WinForms app, you're probably deadlocking the UI thread. That's really nothing to do with Firestore - it's just a matter of how async works. If you replace your `firebaseStuff` method with `await Task.Delay(5000);` you'd probably see the same problem.

You haven't given us the context of where you're calling `firebaseStuff` from - if it's in another method that can be made asynchronous, you should await the resulting task rather than calling `Wait()`. If not - well, you'll need to give us more information.

**Comment by nmggithub** [comment] 2020-03-24 15:52
The app itself is a WPF app. I am calling the method from within the `MainWindow.xaml.cs` constructor which isn't (and can't be, to my knowledge) async. I just tried without `.Wait()` and it seems to have worked? I'm going to try and test it a few more ways before confirming.

**Comment by jskeet** [comment] 2020-03-24 15:56
Right, the constructor itself can't be asynchronous - but you can call a static factory method which *is* asynchronous, does all the async work, and then constructs an instance:

```csharp
public static MainWindow CreateAsync()
{
    var doc = await CreateFirebaseDoc();
    return new MainWindow(doc);
}
```

I don't know whether that will be the right solution for you or not, but it's one option to consider.

What's more important is that you understand why your previous code failed - by calling `Wait()`, you were saying "I'm not going to let the WPF dispatcher thread do anything else until the task returned by `firebaseStuff` has completed". Unfortunately, the `firebaseStuff` method has said "When the task returned by AddAsync completes, I need to come back to the WPF Dispatcher thread in order to return and set the task result". That's why you've got a deadlock.

I'm going to close this issue now as it really isn't related to Firestore or the client library - it's just a matter of working correctly with async methods.

**Closed by jskeet** 2020-03-24 15:56 UTC
Labels: needs more info, type: question
