### ISSUE TITLE
RecognitionAudio never returns - please help

### ISSUE THREAD

**Issue by SafeCab** [googleapis/google-cloud-dotnet#3127] opened 2019-06-13 05:49 UTC
Here is my code. I am quite new to coding and am trying to get the basics working but for some reason it never returns once it executes speech.Recognize.  I can see the credentials are loaded ok though

```csharp
using System;
using Google.Cloud.Speech.V1;
using Google.Apis.Auth.OAuth2;

namespace BounceApi.Speech
{
    public class Speech
    {
        public static void TestSpeechToText()
        {
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", @"c:\speech.json");
            var speech = SpeechClient.Create();
            RecognitionConfig config = new RecognitionConfig
            {
                Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                SampleRateHertz = 16000,
                LanguageCode = LanguageCodes.English.UnitedStates
            };

            var responseX = speech.Recognize(config, RecognitionAudio.FetchFromUri("https://www.voiptroubleshooter.com/open_speech/american/OSR_us_000_0010_8k.wav"));
            foreach (var result in responseX.Results)
            {
                foreach (var alternative in result.Alternatives)
                {
                    var X = alternative.Transcript;
                }
            }
        }
   }
}
```

**Comment by jskeet** [comment] 2019-06-13 06:30
Thank you for the complete example - that's very helpful.

When I run that code myself, I initially get an error:

> Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=InvalidArgument, Detail="sample_rate_hertz (16000) in RecognitionConfig must either be omitted or match the value in the WAV header ( 8000).")

Changing the sample rate to 8000, the code completes without errors. Changing the code to print out the transcripts, I get the following results:

```text
the Birch canoes lid on the smooth planks
 glue the seat to the dark blue background
 it is easy to tell the death of a well.
 These days a chicken leg has a word dish.
 Rice is often served in round bowls.
 Did use of lemon snakes find punch.
 The box was down beside the park truck.
 the Hogs of the popcorn and garbage
 4 hours of study work face to us
 a large size in stockings is hard to sell.
```

Issues with methods not returning *tend* to be network issues - such as being on a network that's behind a proxy that doesn't support HTTP/2.0. Are you able to try your code in a different environment?

Another avenue of investigation would be to try another API. The Language API is a simple one to use for this. After enabling the API and adding the Google.Cloud.Language.V1 package to your project, here's some simple code to call it:

```csharp
var client = LanguageServiceClient.Create();
var document = Document.FromPlainText("Richard of York gave battle in vain.");
var result = client.AnalyzeSyntax(document);
Console.WriteLine(result);
```

Could you try that and see what happens?

**Comment by SafeCab** [comment] 2019-06-14 11:23
hi,

I took your advice and tried on another PC and it worked.  Seems ok on Windows 7 but is failing on Windows 8.  I am using visual Studio 2015.

Thanks

Steve

**Comment by jskeet** [comment] 2019-06-14 11:29
I'd be surprised if the problem was the version of Windows - it seems more likely that it would be a network issue. Was the different PC on a different network? Are you able to try a Windows 7 machine and a Windows 8 machine on the same network?

(Given that Windows 8 .1 is now out of mainstream support, if it *does* turn out to be a Windows-version-specific issue, I'm not sure whether that's likely to get fixed - this is probably somewhere in gRPC, and I suspect the team would deprioritise issues with very old operating systems.)

**Comment by SafeCab** [comment] 2019-06-14 11:33
agreed.  yes it was exactly the same code running on both machines (sharing the project via dropbox)  both were on exactly the same network as well.

I will keep digging but any pointers would be great.

Thanks

Steve

**Comment by jskeet** [comment] 2019-06-14 12:22
Did you try the Language API example, by the way? Did that behave the same way as Speech?

Hmm... I think my next step would be to introduce gRPC trace logging in the tiny sample app. See http://googleapis.github.io/google-cloud-dotnet/docs/faq.html#how-can-i-trace-grpc-issues for how to do that. I'd run it with logging on both machines, and compare the two.

**Comment by SafeCab** [comment] 2019-06-14 17:09
hi,  I did and I seem to get the following error - this is also when I deploy to azure web app 

The type initializer for ''Grpc.Core.Internal.PlatformApis'' threw an exception.

Thanks

Steve

**Comment by jskeet** [comment] 2019-06-14 17:42
I'd assumed that when you said the method "never returned" that it hung. If you've got an exception, that should be a lot easier to fix. Please show the complete exception, including any inner exceptions.

**Comment by SafeCab** [comment] 2019-06-14 19:28
hi,  That's because I switched to using an azure web app.  I am now seeing an error.  here is what I see

Outer most exception
==============
The type initializer for ''Grpc.Core.Internal.PlatformApis'' threw an exception.
at Grpc.Core.Internal.PlatformApis.get_IsXamarinIOS()
   at Grpc.Core.GrpcEnvironment.get_IsNativeShutdownAllowed()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, ChannelCredentials credentials)
   at BounceApi.GeneralRoutines.Routines.translatespeech(String telephoneNumber, String redirectedTelephoneNumber, String communicatorTelephoneNumber, String communicationId, String fromlanguage, String tolanguage)


Next level of exception
==============
Exception has been thrown by the target of an invocation.
 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Grpc.Core.Internal.PlatformApis..cctor()


Inner most exception
==============
ECall methods must be packaged into a system module.
at UnityEngine.Application.get_platform()

I am not sure what the UnityEngine is - but I am not referencing any Unity code

Thanks

Steve

**Comment by jskeet** [comment] 2019-06-14 21:08
That's *very* odd. What sort of Azure web app is this? ([This issue](https://github.com/grpc/grpc/issues/18203) could be relevant, mind you.)

I suspect it may be worth putting that to one side for the moment though - let's concentrate on the original problem first, comparing the working machine with the one that doesn't work, with log files. Am I right in saying the application that fails locally *is* just hanging?

**Comment by SafeCab** [comment] 2019-06-15 18:44
hi, 

Yes I think that is 100% relevant as I also use QRCode to generate QR codes.  I did try removing it but it still gave me the same error.

I will try to set up the traces tomorrow to see if that help with the windows 8 hanging - which it is still doing.

Thanks for all your help

Steve

**Comment by jskeet** [comment] 2019-06-19 10:53
Any updates on this?

**Comment by SafeCab** [comment] 2019-06-21 17:14
Hi,

It seems an issue with windows 8.  I created a brand new class and stripped everything else out.  Its still failed to return on windows 8 but was fine on windows 7 and azure app was then fine.  I got around the issue by creating a second web.api to do the translation and  it almost works perfectly - but that's another issue I will ask on another thread

**Comment by jskeet** [comment] 2019-07-01 13:54
I'm going to close this now as I doubt that we'll ever be able to support Windows 8, and it seems the problem is isolated to that.

**Closed by jskeet** 2019-07-01 13:54 UTC
Labels: api: speech, needs more info, priority: p2, status: investigating, type: question
