### ISSUE TITLE
Status(StatusCode=Unavailable, Detail="Deadline Exceeded")

### ISSUE THREAD

**Issue by rupreetg** [googleapis/google-cloud-dotnet#2533] opened 2018-09-22 12:30 UTC
I am getting this error when I am calling the Upsert call on the datastore. All the Get/query calls are passing and have no issues but upsert calls are failing with this error.

I've added only this package to my .net core 2.1 solution
    <PackageReference Include="Google.Cloud.Datastore.V1" Version="2.2.0-beta01" />

Initially I thought I need to add some other packages are detailed out in #1903 but as my Get calls are passing only save calls are failing am guessing its something else. 

Note: I am running this on my dev laptop. 

Below is the stacktrace - 
 at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCall.cs:line 75
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core\DefaultCallInvoker.cs:line 46
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx) in T:\src\github\grpc\src\csharp\Grpc.Core\Interceptors\InterceptingCallInvoker.cs:line 51
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation) in T:\src\github\grpc\src\csharp\Grpc.Core\ClientBase.cs:line 174
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core\Interceptors\InterceptingCallInvoker.cs:line 48
   at Google.Cloud.Datastore.V1.Datastore.DatastoreClient.BeginTransaction(BeginTransactionRequest request, CallOptions options) in C:\jenkins\workspace\Release\releasebuild\apis\Google.Cloud.Datastore.V1\Google.Cloud.Datastore.V1\DatastoreGrpc.cs:line 324
   at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings) in C:\Users\atarafamas\source\repos\gax-dotnet\releasebuild\src\Google.Api.Gax.Grpc\ApiCall.cs:line 92
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings) in C:\Users\atarafamas\source\repos\gax-dotnet\releasebuild\src\Google.Api.Gax.Grpc\ApiCallRetryExtensions.cs:line 84
   at Google.Cloud.Datastore.V1.DatastoreClientImpl.BeginTransaction(BeginTransactionRequest request, CallSettings callSettings) in C:\jenkins\workspace\Release\releasebuild\apis\Google.Cloud.Datastore.V1\Google.Cloud.Datastore.V1\DatastoreClient.cs:line 1774
   at Google.Cloud.Datastore.V1.DatastoreDbImpl.BeginTransaction(CallSettings callSettings) in C:\jenkins\workspace\Release\releasebuild\apis\Google.Cloud.Datastore.V1\Google.Cloud.Datastore.V1\DatastoreDbImpl.cs:line 142
   at Marshaler.Stocks.DataStore.GCPDataStore.SaveDailyData(String symbol, StockTimeSeries stocks) in C:\Z\p\M.Stocks.Data\GCPDataStore.cs:line 265

**Comment by jskeet** [comment] 2018-09-23 16:10
This wouldn't be caused by missing packages - it would basically be caused by an operation timing out.

Are you setting a deadline manually at all, or just using the default? It's BeginTransaction that looks like it's failing, and that's got a one minute timeout.

Are you able to reproduce this in a simple console application which just performs an upsert operation? Is there anything unusual about your set-up at all? (Are you behind a proxy which might be causing issues, for example?)

**Comment by rupreetg** [comment] 2018-09-25 17:08
Sorry for the delay, Initially I thought it got resolved but I can still see the issue. Here are more details - 

I was able to get it working, Upsert is working now (I wasn't using UpsertAsync initially).

Since morning, I've been running heavy test - doing get/save calls quite frequently and now I am seeing similar errors. Below is the latest error - 

Exception in UpdateInternal: stock: ADANIPOWER, tradeType: Daily, exception Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")

Exception in UpdateInternal: stock: CENTRALBK, tradeType: Daily, exception Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")

Exception in UpdateInternal: stock: CIPLA, tradeType: Daily, exception Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")

Exception in UpdateInternal: stock: HCLTECH, tradeType: Daily, exception Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")

After getting all these errors, the program stopped and got this error - 
One or more errors occurred. (Status(StatusCode=Internal, Detail="keepalive watchdog timeout"))

I don't have a console app to showcase but I can show the code

   dataStore = DatastoreDb.Create(projectId);
   historicalKeyFactory = dataStore.CreateKeyFactory(historical);
             

public async Task SaveMonthlyData(string symbol, StockTimeSeries stocks)
        {
            foreach (var stockData in stocks.DataPoints)
            {
                Entity entity = new Entity()
                {
                    Key = historicalKeyFactory.CreateIncompleteKey(),
                    [stocksymbol] = symbol,
                    [date] = stockData.Time.ToUniversalTime(),
                    [type] = (int)TimeSeriesType.Monthly,
                    [openprice] = (double)stockData.OpeningPrice,
                    [closeprice] = (double)stockData.ClosingPrice,
                    [highestprice] = (double)stockData.HighestPrice,
                    [lowestprice] = (double)stockData.LowestPrice,
                    [volume] = stockData.Volume
                };
                await dataStore.UpsertAsync(entity);
            }
        } 

Package references: 
<ItemGroup>
    <PackageReference Include="Google.Cloud.Datastore.V1" Version="2.2.0-beta01" />
  </ItemGroup>

Let me know if you need more information.

**Comment by jskeet** [comment] 2018-09-26 06:40
A few questions:

- Do you have any timings for how long the calls took in each case? When the calls fail, are they genuinely timing out as far as you can see?
- Is there any reason you're upserting each entity individually, rather than using batches? I'd expect that to be more efficient
- Do you have a rough idea of how many requests of what kind you were making, over what period of time?
- Was this observed on a computer with a stable network? 

Given the last error, it sounds like the gRPC channel had become unhealthy, but it's hard to tell why.

**Comment by rupreetg** [comment] 2018-09-27 18:55
Thanks @jskeet for followup. 

I've done some more optimization but yet to run the full test so will share the results. I've done batching at both Get and Save calls so it should reduce the number of calls significantly - somewhere around 1-2 get calls in an hour and around 2-4 save calls in an hour. 

Before the optimization, I was doing get and save - 4 get calls per minute but might be 100-400 saves per minute. 

I am running on my machine and it has pretty stable network. 

Right now I am stuck with another issue (https://github.com/googleapis/google-cloud-node/issues/1319), do let me know if you have any idea how to fix this. Basically I am projecting Date field in my query because of which I am getting integer value instead of datetime type. Can't convert to DateTime as it returns incorrect value. The proposed workaround in the given bug is also not working for me so any help would be appreciated.

**Comment by rupreetg** [comment] 2018-09-28 14:48
Yes, I also thought that 400 calls were not high, yet I was intermittently getting errors related to deadline, etc. 

I'll keep updating this thread with the results of the optimizations. 

Regarding the other issue, it is not specific to node, its specific to datastore. As I understand from the other thread, its about how datastore projection types like datetime. I'll open a new issue for this.

**Comment by rupreetg** [comment] 2018-09-29 03:14
Update, now that my save is only 1-2 calls (with 500 records in a batch), I am getting the below error -

Message: Status(StatusCode=Unknown, Detail="Stream removed")
StackTrace:
 
```
  at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Google.Cloud.Datastore.V1.DatastoreDbImpl.CommitAsync[T](IEnumerable`1 values, Func`2 conversion, Action`2 keyPropagation, String parameterName, CallSettings callSettings) in C:\jenkins\workspace\Release\releasebuild\apis\Google.Cloud.Datastore.V1\Google.Cloud.Datastore.V1\DatastoreDbImpl.cs:line 255
   at Marshaler.Stocks.DataStore.GCPDataStore.SaveData(List`1 stockList) in C:\Z\p\M.S.Data\GCPDataStore.cs:line 305
   at M.S.S.Update()  
```

Below is the code I am using to save data

```
public async Task SaveD_Data(List<StockTimeSeries> stockList)
        {
            List<Entity> entities = new List<Entity>();
         
            foreach(var stock in stockList)
            {
                if (stock == null || stock.DataPoints == null)
                    continue;

                foreach (var stockData in stock.DataPoints)
                {
                    if (stockData == null)
                        continue;

                    Entity entity = new Entity()
                    {
                        Key = historicalKeyFactory.CreateIncompleteKey(),
                        [stocksymbol] = stock.Symbol,
                        [date] = stockData.Time.ToUniversalTime(),
                        [type] = (int)TimeSeriesType.Daily,
                        [openprice] = (double)stockData.OpeningPrice,
                        [closeprice] = (double)stockData.ClosingPrice,
                        [highestprice] = (double)stockData.HighestPrice,
                        [lowestprice] = (double)stockData.LowestPrice,
                        [volume] = stockData.Volume
                    };

                    entities.Add(entity);
                }
            }

            foreach(var items in entities.Batch<Entity>(500))
            {
                await dataStore.UpsertAsync(items);
            }
        }
```

**Comment by rupreetg** [comment] 2018-09-29 07:28
I'm outside right now but here are quick details: 

- Running in window 10 laptop at home without any proxy or load balancer. Still in development phase.

- network is stable, have been fetching data from multiple sources without any issues.

- running in debug mode in visual studio as I am still developing the system.

**Comment by jskeet** [comment] 2018-09-29 08:06
Thanks for the extra information - although it leaves me a little stumped. Out of interest, is your app loading the CPU heavily? One of the comments in the gRPC issue referred to that as making the problem happen more frequently. I would still suggest adding a comment to the gRPC issue - the gRPC team may be able to suggest additional diagnostics that would help us track down what's going on.

Have you spotted any patterns as to when this happens? Is it always after a particular length of time?

**Comment by rupreetg** [comment] 2018-09-29 10:18
Unfortunately, no. This is a simple job which will fetch data from multiple source and push to datastore in a structured manner, nothing much beside this. I did see that issue you mentioned before posting this issue, I don't see any high CPU or any specific patterns. My wild guess is the amount of data might be causing so am reducing the batch size and adding retry pattern to see if it works. 

Do let me know if you find anything that can help me, I wanted to complete this module this weekend and now am kinda blocked.

**Comment by jskeet** [comment] 2018-09-29 11:30
I'm afraid I'm unlikely to be able to think of anything more in the short term - and I'm travelling next week. I suspect the gRPC team are your best hope, but again there may not be much feedback on a weekend.

**Comment by rupreetg** [comment] 2018-09-29 15:30
I tried couple of things like reducing the batch size to 200, retrying in case of failure but its just not working. By gRPC team, do you mean I should open a bug somewhere else or are you including them in this thread? Seems like batching isn't working for me. I was able to save records individually but with batching can't save. 

Aren't other people facing similar issues - these are simple get/save calls, am surprised that these are giving me trouble and not able to focus on my product.

**Comment by jskeet** [comment] 2018-09-29 16:14
I'm saying you should add a comment to [this gRPC issue](https://github.com/grpc/grpc/issues/15623) that I linked to before. That looks like it's affected multiple users with various different client libraries (including ones that aren't for Google APIs at all). I don't believe this is specific to the Datastore library, and no, we haven't had reports of other people facing this issue with this specific library.

If you could post a complete example (like the one I posted in the other issue - a console app with everything required to copy/paste/run) that reliably reproduces the problem, I'd be happy to run that here as a check whether it's environmental.

**Comment by luistejadaa** [comment] 2018-10-07 23:16
I'm having the same problem.


` System.Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", @"credential.json");
            var credential = GoogleCredential.GetApplicationDefault();

            FirestoreDb firesToreDb = FirestoreDb.Create("sta-managertest");
            CollectionReference lessonsReference = firesToreDb.Collection("Lessons");
            var v = new Dictionary<string, object>() { { "valor", 5 } };
            await lessonsReference.Document("Ejemplo").CreateAsync(v);`

**Comment by luistejadaa** [comment] 2018-10-08 00:10
I have checked that if I first make a query and then try to insert if it works.

Example: 

`await lessonsReference.WhereEqualTo("isLocked", true).WhereEqualTo("isGenerated", false).GetSnapshotAsync();
            await lessonsReference.Document("DSA").SetAsync(new Dictionary<string, object>() { { "a", 3 } });`

**Comment by jtattermusch** [comment] 2018-10-24 09:57
If you are still able to reproduce the "stream removed" problem, please consider posting additional info in grpc's tracking bug as requested in grpc/grpc#15623 (comment), that should help with debugging.

**Comment by rupreetg** [comment] 2018-10-24 16:00
Thanks but with GCloud, I was facing lot many issues without timely help/fixes so I had to switch over to AWS. I won't be able to help you on this issue now.

**Comment by jskeet** [comment] 2018-12-03 17:05
Given the lack of additional information, I'm going to close this for now. I've seen the error message myself when a laptop wakes up from sleep, but I think that's reasonable.
If we get any more reports, we can reopen.

**Closed by jskeet** 2018-12-03 17:05 UTC
Labels: priority: p2, type: question

**Comment by laljikanjareeya** [comment] 2019-02-28 15:13
@jskeet I am also facing same issue could you help me out on same please find below code and exception details:
``` javascript
Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", credentialPath);
var bigtableTableAdminClient = BigtableTableAdminClient.Create();
bigtableTableAdminClient.CreateTable(
     new InstanceName(projectId, instanceId),
     tableName, new Table
     {
         Granularity = Table.Types.TimestampGranularity.Millis,
         ColumnFamilies =
         {
                    {
                        columnFamily, new ColumnFamily
                        {
                            GcRule = new GcRule
                            {
                                MaxNumVersions = 1
                            }
                        }
                    }
         }
     });
```
**Exception Details:**
``` javascript
   Status(StatusCode=DeadlineExceeded, Detail="Deadline Exceeded")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Google.Cloud.Bigtable.Admin.V2.BigtableTableAdmin.BigtableTableAdminClient.CreateTable(CreateTableRequest request, CallOptions options)
   at Google.Api.Gax.Grpc.ApiCall.GrpcCallAdapter`2.CallSync(TRequest request, CallSettings callSettings)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0(TRequest request, CallSettings callSettings)
   at GoogleBigTableAddIn.BigTableAdmin.CreateTable(String projectId, String instanceId, String tableName, String columnFamily, String credentialPath) in G:\Projects\GoogleBigTableAddIn\google-bigtable-addin\GoogleBigTableAddIn\BigTableAdmin.cs:line 62
```
Currently I am using all the latest stable package of Google could api and application use .net framework 4.6.1.

**Comment by jskeet** [comment] 2019-02-28 15:21
@laljikanjareeya: This issue has ended up with an awful lot of different errors in. Could you create a new issue so we can look at just the issue you're facing?

If you could measure how long it takes from "before the call" to "call fails" that would be good to know as well - it could be that the timeout we're using by default is insufficient.
