### ISSUE TITLE
TailLogEntries crashes every hour

### ISSUE THREAD

**Issue by DenSmoke** [googleapis/google-cloud-dotnet#7147] opened 2021-09-07 14:51 UTC
I understand that `TailLogEntries` is pre-GA, but maybe it will help.

#### Environment details

  - OS: Ubuntu 20.04
  - .NET version: 5.0.9
  - Package name and version: Google.Cloud.Logging.V2 3.4.0

#### Steps to reproduce
Code:
```cs
LoggingServiceV2Client client = await _gcpLoggingClientBuilder.BuildAsync(ct);

CallSettings callsettings = CallSettings.FromExpiration(Expiration.None);
LoggingServiceV2Client.TailLogEntriesStream response = client.TailLogEntries(callsettings);
ct.Register(async () => await response.WriteCompleteAsync());

Task responseHandlerTask = Task.Run(async () =>
{
    AsyncResponseStream<TailLogEntriesResponse> responseStream = response.GetResponseStream();
    await foreach (TailLogEntriesResponse responseItem in responseStream)
    {
        for (int i = 0; i < responseItem.Entries.Count; i++)
        {
            LogEntry entry = responseItem.Entries[i];
            await SendMessageAsync(entry, ct);
        }
    }
}, CancellationToken.None);

TailLogEntriesRequest request = new()
{
    ResourceNames = { _resourceName },
    Filter = _filter
};
await response.WriteAsync(request);

await responseHandlerTask;
```
`foreach` over `responseStream` fails every hour with:
`Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="The service is currently unavailable."`
`Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Connection reset by peer"`

Without `CallSettings callsettings = CallSettings.FromExpiration(Expiration.None);`  the error was
`Grpc.Core.RpcException: Status(StatusCode="DeadlineExceeded", Detail="Deadline Exceeded"`

UPD: Recently found that service just stopped receiving responses without any error

UPD: FYI we are doing `strip --strip-debug libgrpc_csharp_ext.x64.so` for builds, because this file is very huge. Could it be the reason? I think this is connected with #4813

**Comment by amanda-tarafa** [comment] 2021-09-08 08:13
I can confirm this behaviour is by design from the API side, not the library side.
You should have received a more informative error though, and we are looking into it.

We'd like to know more about your use case:
- Do you need the stream permanently open and why?
- Would it be possible for you to add some retry logic so that when the connection is lost you restart the stream again?

As for your updates:
- Not sure what you mean by "the service just stopped receiving responses without any error". Could you elaborate?
- No, this is not linked to #4813, as the stream is closed intentionally from the server side every hour.

(As a note, try to add updates as a new comment in the thread instead of as updates on previous, there are no notifications for comments being updated and I almost missed yours)

**Comment by DenSmoke** [comment] 2021-09-08 08:25
We use log streaming to catch certain events such as unhandled exceptions or service crashes and send them to Telegram channel using Bot API.
Yes I added retry logic but it seems it's not helpful, because error doesn't bubble up every time and loop over `responseStream` stays alive. For example, there were several errors this night in logs, but I didn't get them using log stream.

**Comment by amanda-tarafa** [comment] 2021-09-08 09:57
There might be [valid reasons](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Logging.V2/latest/Google.Cloud.Logging.V2.TailLogEntriesResponse#Google_Cloud_Logging_V2_TailLogEntriesResponse_SuppressionInfo) why you don receive some logs. If you are not consuming entries fast enough, you can always add a [filter](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Logging.V2/latest/Google.Cloud.Logging.V2.TailLogEntriesRequest#Google_Cloud_Logging_V2_TailLogEntriesRequest_Filter) to the streaming request to receive only the entries you are interested in.
Can you confirm wether this might have been the case last night? Obviously, if the stream is being closed and the exception is not bubling up, we'd look into it.

**Comment by DenSmoke** [comment] 2021-09-08 10:22
According to logs, next iteration of loop over `responseStream` never happened, so `SuppressionInfo` is not helpful here. As you can see, I applied a filter to the request. I checked and found that skipped log entries pass the filter. 

Based on you comments, I changed `CallSettings.FromExpiration(Expiration.None)` to 30 minutes and added `catch` block for `DeadlineExceeded` exception. I hope this approach will be more resilient.

**Comment by amanda-tarafa** [comment] 2021-09-08 10:27
Thanks for confirming, we'll look into the closed stream error not bubbling up and update here when we know more. I agree that setting an expiration should work at least as a workaround.

**Comment by DenSmoke** [comment] 2021-09-08 14:42
Unfortunately, this workaround didn't change anything. The requested log entries are being skipped.

**Comment by amanda-tarafa** [comment] 2021-09-08 14:49
As a side note (we are still looking into surfacing better errors and always bubling them up), the API team has recommended a different, more suitable setup for your use case, and that's to [export log entries to Pub/Sub for further processing](https://cloud.google.com/logging/docs/export/configure_export_v2). The tailing feature is intended for more interactive scenarios where a human is looking at the logs for a period of time.

**Comment by DenSmoke** [comment] 2021-09-09 10:18
Looks like removing custom `CallSettings` was helpful. None of the requested log entries have been skipped in the last 12 hours.
There was only one exception succefully handled by retry logic.
`Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="GOAWAY received", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1631174485.038898115","description":"Error received from peer ipv4:142.250.150.95:443","file":"/var/local/git/grpc/src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"GOAWAY received","grpc_status":14}")`

**Comment by amanda-tarafa** [comment] 2021-09-09 14:01
OK, are you saying that the stream was only closed once in 12 hours? Or are you receiving and retrying on the original `Deadline Exceeded` errors that you were getting at the very beginning, which made you specify custom `CallSettings`?

**Comment by DenSmoke** [comment] 2021-09-09 14:35
I mean it was being closed every hour with `DeadlineExceeded` as supposed. And once with `Unavailable`

**Comment by amanda-tarafa** [comment] 2021-09-09 14:52
OK, that makes sense. The shorter default timeout is probably more reliable than receiving the `Unavailable` error when the stream is closed, so you can recover sooner and more reliably as well. And that means you don't miss entries that are written in between recoveries.
Still the API team suggests that, for your use case, it's best if you export logs instead of tailing them.

We are still looking at improving the error message from when the stream is closed, btw.

**Comment by amanda-tarafa** [comment] 2021-09-09 14:56
Here is a [Google Post on Alerts from Google Cloud](https://medium.com/google-cloud/can-you-alert-on-logs-in-stackdriver-7dfb07f495c0) and [Qwiklab](https://www.qwiklabs.com/focuses/619?parent=catalog).

**Comment by jtattermusch** [comment] 2021-09-10 09:32
> UPD: FYI we are doing `strip --strip-debug libgrpc_csharp_ext.x64.so` for builds, because this file is very huge. Could it be the reason? I think this is connected with #4813

This is very likely unrelated to the issue. In fact, we started stripping the  libgrpc_csharp_ext.x64.so in the nugets packages recently as part of the release (see https://github.com/grpc/grpc/pull/25729).

**Comment by DenSmoke** [comment] 2021-09-10 14:19
> In fact, we started stripping the libgrpc_csharp_ext.x64.so in the nugets packages recently

There are projects still using old gRPC. For example, `Google.Cloud.Logging.NLog` adds these files:
![image](https://user-images.githubusercontent.com/16131575/132867850-2548d667-b226-4ff3-9f7f-695fc5743b2f.png)

**Comment by amanda-tarafa** [comment] 2021-09-10 15:31
@DenSmoke I'll be closing this issue now as there not much we can do on the library side of things.

There's an internal issue for exploring why the error is not reliable and the expected one and there's also a request for better describing log tailing use cases vs. log exporting.
I'll update here when the issues with the errors have been looked into.

Do feel free to leave another comment here if you think there's something else we can do.

**Closed by amanda-tarafa** 2021-09-10 15:31 UTC
Labels: type: question, api: logging, priority: p2
