### ISSUE TITLE
FirestoreChangeListener won't receive updates after 1 hour

### ISSUE THREAD

**Issue by pauloevpr** [googleapis/google-cloud-dotnet#2536] opened 2018-09-26 00:29 UTC
I have been facing an issue with the real time capabilities of Firestore API. I was reading Firestore documentation when I found out that [user authentication tokens expire in 1 hour](https://firebase.google.com/docs/auth/admin/manage-sessions). This led me to the question: If the token expires in 1 hour, what happens to FirestoreChangeListener after expiration?

I then proceeded to run a simple test to find out. It turns out that FirestoreChangeListener does stop receiving updates after 1 hour. This is the test output:

``` c#
9/26/2018 8:43:30 AM: Listener started
9/26/2018 8:43:30 AM: Document has changed
9/26/2018 8:43:36 AM: Document has changed // Document actually updated
9/26/2018 8:53:30 AM: Document has changed
9/26/2018 9:03:30 AM: Document has changed
9/26/2018 9:13:30 AM: Document has changed
9/26/2018 9:23:30 AM: Document has changed
9/26/2018 9:33:30 AM: Document has changed
9/26/2018 9:39:45 AM: Document has changed // Document actually updated
9/26/2018 9:40:00 AM: Document has changed // Document actually updated
9/26/2018 9:43:30 AM: Document has changed
// Document updated many times for the next 30 minutes
// No more updates received 
```
As you can see, after precisely 1 hour, updates are no longer received. It is important to point that I am authenticated with an user account, not a service account. I haven't tested this behavior using a service account.

It is interesting how FirestoreChangeListener receives an update every 10 minutes even when the document was not changed. That is probably because Firestore resets the stream every 10 minutes. I am wondering if these extra updates are billed.

**Comment by jskeet** [comment] 2018-09-26 06:32
Hmm... I'll have to ask the team about both of these aspects, I'm afraid. I think I'd *expect* the server to request a reset, which would cause the library to issue a new request with a new auth token. (It performs refreshes automatically.)

I have absolutely no idea on the billing side.

Thanks for bringing this up, and I hope I'll be able to provide more information in the next day or two.

**Comment by pauloevpr** [comment] 2018-09-26 06:44
Thank you for taking the time once again to reply.

**Comment by schmidt-sebastian** [comment] 2018-09-26 17:49
Hi @pauloevpr, let me try to answer your questions.

First off, what SDK are you using? As far as I am aware, the .Net SDK only supports Service Account authentication. Please do prove me wrong here :)

Secondly, your stream will stop once an hour when the auth token expires. The SDK should re-connect automatically and hide this from you. Since we will resume the query from the last state that the backend sent to us, you should not incur additional document reads. Hence, this should not have an impact on billing.

As for the superfluous "Document has changed" lines in your log output - are you printing this from inside the SDK or from the Listener? If your Listener is getting called without any document updates, we may have an issue in the SDK here. The SDK itself will periodically get pinged from the backend, but again, this should be hidden from end users.

**Comment by jskeet** [comment] 2018-09-27 06:52
Service account vs user account: the client code doesn't care which authentication mechanism you use. I don't know whether there are any server-side differences that could affect things though.

I'll look into both aspects of this when I get the chance. (We'll want to add a cross-platform conformance test for the non-reporting of non-changes, too.) Thanks for reporting it.

**Comment by pauloevpr** [comment] 2018-09-27 07:42
Hi @schmidt-sebastian, thank you for taking the time to reply.

> First off, what SDK are you using? As far as I am aware, the .Net SDK only supports Service Account authentication.

I am using .Net SDK, and I am using an user account, not a service account. I am working on a Windows desktop application. This is how I am getting authentication done for an user account:

``` c#
private FirestoreDb BuildFirestoreDb(string bearerToken)
{
    var credentials = GetCredentials(bearerToken);
    var grpcChannel = new Channel(FirestoreHost, credentials);
    var firestoreClient = new Firestore.FirestoreClient(grpcChannel);
    var firestoreClientImpl = new FirestoreClientImpl(firestoreClient, FirestoreSettings.GetDefault());
    return FirestoreDb.Create(ProjectId, null, firestoreClientImpl);
}
private static ChannelCredentials GetCredentials(string firebaseToken = null)
{
    var callCredentials = CallCredentials.FromInterceptor(async (context, metadata) =>
    {
        await Task.Run(() =>
        {
            if (firebaseToken != null) metadata.Add("authorization", $"Bearer {firebaseToken}");
        });
    });
    return ChannelCredentials.Create(new SslCredentials(), callCredentials);
}
```
Note that `bearerToken` is obtained via Firebase REST authentication.

> As for the superfluous "Document has changed" lines in your log output - are you printing this from inside the SDK or from the Listener?

I am getting this from the Listener. I am using the package published to nuget.org. So I have no access to the internal API.

**Comment by jskeet** [comment] 2018-09-27 07:46
Ah - if you're implementing credentials yourself, then that could well be the cause of the "one hour" problem. There's no token refresh in your code.

If you can go through `Google.Apis.Auth.OAuth2.UserCredential` (and then call the `ToChannelCredentials` extension method) that should refresh automatically.

If you need to keep using the Firebase authentication, you should implement token refresh.

**Comment by pauloevpr** [comment] 2018-09-27 07:49
I am going to give this a try. I will keep you posted.

**Comment by pauloevpr** [comment] 2018-09-27 07:56
Could you please point me to any documentation about using `Google.Apis.Auth.OAuth2.UserCredential` with Firebase authentication?

**Comment by jskeet** [comment] 2018-09-27 08:05
I'm afraid I don't know anything about Firebase authentication. It may not be applicable for `UserCredential`, which is designed for Google users to authenticate to APIs.

Note that the library here is really designed for servers, using service accounts - that's why there's no offline support etc. I don't know what the plans are for desktop applications. (We should probably make that clearer in the documentation.) That said, I'd expect that you *could* get it to work by implementing token refresh. I don't know if there are libraries for Firebase authentication to do that for you, or whether you'll need to implement it yourself.

**Comment by pauloevpr** [comment] 2018-09-27 08:08
Refreshing the token is not a problem. I known how to do that. What I dont know is, after getting a new token, how to pass it to FirestoreDb so the listeners keep working.

**Comment by jskeet** [comment] 2018-09-27 08:14
I would *hope* it would just work automatically, once your credentials do the right thing. I need to try the same test with a service account when I get time, but I'd expect the streaming request to fail, and then the listener to recreate it transparently - at which point it will use the new token, and work.

**Comment by schmidt-sebastian** [comment] 2018-09-27 11:00
Re: The 10 minute update interval.

I suspect that you are hitting a request timeout here, possibly due to an RPC timeout that is defined by the client. The retry logic that we have build into the Watch protocol should essentially hide this from you - but maybe the C# client always issues a Watch Snapshot once the stream has been re-established?

**Comment by pauloevpr** [comment] 2018-09-27 11:20
> I would hope it would just work automatically, once your credentials do the right thing.

Once again you are correct. I have spent the day testing the behavior to conclude that the SDK behaves as expected as long as  the underlying `ChannelCredentials` provides an up to date authentication token.

This is the output now after fixing the `ChannelCredentials`. The listener continues to work after 1 hour.

``` c#
27/09/2018 8:01:45 PM: Starting listener
27/09/2018 8:01:45 PM: CallCredentialsProvider invoked. Updating credentials with current token
27/09/2018 8:01:45 PM: Document has changed
27/09/2018 8:11:45 PM: CallCredentialsProvider invoked. Updating credentials with current token
27/09/2018 8:11:45 PM: Document has changed
27/09/2018 8:21:45 PM: CallCredentialsProvider invoked. Updating credentials with current token
27/09/2018 8:21:45 PM: Document has changed
27/09/2018 8:31:45 PM: CallCredentialsProvider invoked. Updating credentials with current token
27/09/2018 8:31:45 PM: Document has changed
27/09/2018 8:41:45 PM: CallCredentialsProvider invoked. Updating credentials with current token
27/09/2018 8:41:45 PM: Document has changed
27/09/2018 8:51:45 PM: CallCredentialsProvider invoked. Updating credentials with current token
27/09/2018 8:51:45 PM: Document has changed
27/09/2018 8:59:45 PM: Refreshing token // Token refreshed
27/09/2018 9:01:45 PM: CallCredentialsProvider invoked. Updating credentials with current token
27/09/2018 9:01:46 PM: Document has changed
27/09/2018 9:11:46 PM: CallCredentialsProvider invoked. Updating credentials with current token
27/09/2018 9:11:46 PM: Document has changed
```
Notice how the token is refreshed right before expiring. Also notice that every time the stream is reset, the SDK correctly retrieves the latest credentials from then underlying `ChannelCredentials`.

And that is my code base now:

``` c#
public FirestoreDb CreateDb(Func<string> tokenProvider)
{
    var callCredentialsInterceptor = async (context, metadata) =>
    {
        await Task.Run(() =>
        {
            metadata.Clear();
            if (_firebaseToken != null) metadata.Add("authorization", $"Bearer {tokenProvider()}");
        });
    };
    var callCredentials = CallCredentials.FromInterceptor(_callCredentialsInterceptor);
    var credentials = ChannelCredentials.Create(new SslCredentials(), callCredentials);
    var grpcChannel = new Channel(FirestoreHost, credentials);
    var grcpClient = new Firestore.FirestoreClient(grpcChannel);
    var firestoreClient = new FirestoreClientImpl(grcpClient, FirestoreSettings.GetDefault());

    return FirestoreDb.Create(ProjectId, null, firestoreClient);
}
```
As long as you have a valid authentication token, the SDK seems to work pretty well even when using user accounts.

**Comment by jskeet** [comment] 2018-09-27 13:53
Hooray. Given that we've learned a lot more, I'm going to close this issue so that we can keep track of it in #2542 without confusion.

Thanks for all your efforts tracking things down!

**Closed by jskeet** 2018-09-27 13:53 UTC
Labels: priority: p2, type: bug
