### ISSUE TITLE
Missing exception message information

### ISSUE THREAD

**Issue by EatonZ** [googleapis/google-cloud-dotnet#7158] opened 2021-09-10 22:17 UTC
I am running into an issue where exception messages aren't showing completely in [GCP's Error Reporting area](https://console.cloud.google.com/errors).

To demonstrate, open [this sample project](https://github.com/googleapis/google-cloud-dotnet/files/7147012/ErrorAPI.zip).

1. Add your project ID to Program.cs
2. Run the project. The browser will open to a 404. Ignore that, and navigate to /test.
3. It will confirm when the error report was sent.
4. Check your Error Reporting area and you will see an error like this:

```
Data: THIS IS DATA
   at ErrorAPI.ServiceInterface.UpdateService.Get(GetAppReleaseHistory request)
```

If you look at the APIException class in the sample project, you'll notice how most of the exception message is missing from the error report.

5. In UpdateService.cs, change "THIS IS DATA" to null.
6. Re-try starting from step 2, and this time you will see a much better error report:

```
ErrorAPI.ServiceInterface.Helpers.ErrorLogging+APIException: 404 Not Found
Operation Name: GetAppReleaseHistory
Error Message: Document not found.
   at ErrorAPI.ServiceInterface.UpdateService.Get(GetAppReleaseHistory request)
```

The issue is that most of the information was omitted in the first case. If you debug and look at the exception's message before it gets logged, it is correct, so something is happening deeper down.

A correct GCP error report display should look like this:

```
ErrorAPI.ServiceInterface.Helpers.ErrorLogging+APIException: 404 Not Found
Operation Name: GetAppReleaseHistory
Error Message: Document not found.
Data: THIS IS DATA
   at ErrorAPI.ServiceInterface.UpdateService.Get(GetAppReleaseHistory request)
```

**Comment by amanda-tarafa** [comment] 2021-09-13 11:10
Ok, I've been able to reproduce, but this is not a library issue, this is a UI issue. If you click on the error detail you can see at the bottom a tab called `Parsed` and a tab called `Raw`. The `Parsed` tab shows the incomplete message but the `Raw` shows the complete message, which means we are sending the etry with the full error. See the images:

![image](https://user-images.githubusercontent.com/14878252/133069578-642c3b12-d880-4038-9a38-f0262fd7e561.png)

![image](https://user-images.githubusercontent.com/14878252/133069966-51a1a7ba-fdb1-4346-9457-ffc49ad4043a.png)

Also, I know what it is the UI is having trouble with, the new line. I changed the newlines in your message with `--` and now I get the whole message both in `Parsed` and `Raw`. See the images:

![image](https://user-images.githubusercontent.com/14878252/133071234-bd1f86c7-7ba2-4e30-9cfd-78db3f080aa1.png)

![image](https://user-images.githubusercontent.com/14878252/133071386-fff6106f-a728-4803-862d-eb35ed89fe3a.png)

In both cases, if you go to the corresponding Log Entry, you can see the full exception message there as well. 

I think the best way for you to get support on this is directly through the UI. On the top right corner there's a `?` button. If you click there you can both click `Get Support`, which will send you to a page with different options and `Send Feedback` wich will allow you to report this issue. I believe that you cannot track the internal issue created with `Send Feedback`, but on your support options (depending on your level of support) you might be able to open a new Support Case that you can follow up on.

I'm closing this issue now since there's not much we can do library side, but do please add more comments if you think otherwise.

**Closed by amanda-tarafa** 2021-09-13 11:10 UTC
Labels: type: question, api: clouderrorreporting, priority: p2

**Comment by EatonZ** [comment] 2021-09-13 15:53
> In both cases, if you go to the corresponding Log Entry, you can see the full exception message there as well.

You are correct - the log entry shows everything, while the UI does not. So the library is clearly sending everything... but maybe the solution here is to update the library to replace new lines with `--`? Would you be willing to do that, or is that not a good, permanent solution?

**Comment by amanda-tarafa** [comment] 2021-09-13 16:06
No not really, we wouldn't want to modify an application exception message in any way. If client code adds new lines, it's not for us to modify them, specially because we have no trouble handling them. If for some weird reason the UI couldn't handle them, then it would be up to them to parse them differently, usin `--` or anything else they can handle.

**Comment by EatonZ** [comment] 2021-09-13 16:09
@amanda-tarafa Ok. I'll try and get a bug report or feedback item filed for this in the UI.
