### ISSUE TITLE
Error connecting to Firestore Emulator (DNS resolution failed for service)

### ISSUE THREAD

**Issue by oantawilliam** [googleapis/google-cloud-dotnet#5912] opened 2021-02-07 11:53 UTC
I was trying to connect to FirestoreEmulator using Google.Cloud.Firestore 2.3.0 and F# on a MacBookPro using JetBrains Rider. I have the following function for creating the Firestore Emulator:

```
static member private createEmulator() =
            let emuBuilder = FirestoreDbBuilder()
            emuBuilder.ProjectId <- FirestoreConnector.PROJECT_ID
            emuBuilder.EmulatorDetection <- EmulatorDetection.EmulatorOnly 
            emuBuilder.Build()
```

When I run it and try to save a document using 

```
let documentReference = this.emulatorDb.Collection(usersCollectionId).Document(userId)
            
let userDataWriteResult = documentReference.SetAsync(userData, SetOptions.MergeAll)
                        |> Async.AwaitTask |> Async.RunSynchronously
```

I get the following exception:

```
System.AggregateException: One or more errors occurred. (Status(StatusCode="Unavailable", Detail="DNS resolution failed for service: "localhost:8080"", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1612698369.435120000","description":"Resolver transient failure","file":"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/ext/filters/client_channel/resolving_lb_policy.cc","file_line":214,"referenced_errors":[{"created":"@1612698369.435119000","description":"DNS resolution failed for service: "localhost:8080"","file":"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":378,"grpc_status":14,"referenced_errors":[{"created":"@1612698369.434934000","description":"C-ares status is not ARES_SUCCESS qtype=A name="localhost is_balancer=0: Domain name not found","file":"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":287,"referenced_errors":[{"created":"@1612698369.430395000","description":"C-ares status is not ARES_SUCCESS qtype=AAAA name="localhost is_balancer=0: DNS server returned answer with no data","file":"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":287}]}]}]}")) ---> Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="DNS resolution failed for service: "localhost:8080"", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1612698369.435120000","description":"Resolver transient failure","file":"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/ext/filters/client_channel/resolving_lb_policy.cc","file_line":214,"referenced_errors":[{"created":"@1612698369.435119000","description":"DNS resolution failed for service: "localhost:8080"","file":"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":378,"grpc_status":14,"referenced_errors":[{"created":"@1612698369.434934000","description":"C-ares status is not ARES_SUCCESS qtype=A name="localhost is_balancer=0: Domain name not found","file":"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":287,"referenced_errors":[{"created":"@1612698369.430395000","description":"C-ares status is not ARES_SUCCESS qtype=AAAA name="localhost is_balancer=0: DNS server returned answer with no data","file":"/tmpfs/src/github/grpc/workspace_csharp_ext_macos_x64/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":287}]}]}]}")
  at at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
  at at Google.Cloud.Firestore.WriteBatch.CommitAsync(ByteString transactionId, CancellationToken cancellationToken)
  at at Google.Cloud.Firestore.DocumentReference.SetAsync(Object documentData, SetOptions options, CancellationToken cancellationToken)
  --- End of inner exception stack trace ---
  at Microsoft.FSharp.Control.AsyncResult`1.Commit() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:350
  at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:882
  at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:890
  at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:1154
  at Guidelines.Firestore.UserConnector.saveUser(User user) in /Users/william.richard/Documents/Healthify/guidelines/src/guidelines/Firestore.fs:176
  at Program.Program.main(String[] argv) in /Users/william.richard/Documents/Healthify/guidelines/src/tests/Program.fs:87

```

I've read the steps required to connect to the emulator 

> To connect to the Firestore Emulator, you need to:
Connect to the emulator endpoint
Use ChannelCredentials.Insecure as the channel credentials
Specify an "Authorization: Bearer owner" header on each request

Given that I use the `EmulatorOnly` field I defined the `FIRESTORE_EMULATOR_HOST="localhost:8080"` and did not set the endpoint or channel credentials (because an exception is raised if setting them with `EmulatorOnly`)

I have not done the last step of setting the Authorization header because I do not know where or how to add the header in the code. 

The Firestore Emulator was installed with standard configuration.

Any ideas on how to solve the above error? Thanks!

**Comment by jskeet** [comment] 2021-02-07 13:53
I'm surprised it was trying DNS resolution at all for localhost:8080 - I'd expect it to recognize that that address means the local computer.

It does look like there have been some Mac-specific issues with localhost in the past - see https://superuser.com/questions/142736/cant-resolve-localhost-on-mac-os-x-server for example. (That's 10 years old, admittedly.)

If you try just "ping localhost" from a terminal, what does that show? You might also want to try using "127.0.0.1:8080" as the address instead of "localhost:8080", at least as a short term workaround.

**Comment by oantawilliam** [comment] 2021-02-07 13:59
This is what I get for `ping localhost`
```
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.038 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.068 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.071 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.054 ms
```

I tried all versions above, and still I get the same error:
`0.0.0.0:8080`
`127.0.0.1:8080`
`localhost:8080`
`https://localhost:8080`
`https://127.0.0.1:8080`

**Comment by jskeet** [comment] 2021-02-07 14:16
Right - that's interesting and surprising.

It might be worth trying the bottom two again, but using `https` instead of `http`.

The next thing I'd do is trying adding a package reference to `Grpc.Core` version 2.35.0. The transitive dependency via Google.Cloud.Firestore version 2.3.0 is to Grpc.Core 2.31.0. I don't know any reason why it would be fixed in later versions, but it's always worth a try.

After that, I'd try a small program that *just* tries to make a gRPC call to whatever address you specify. It's just a sample call with no useful information - it's not a valid Firestore RPC.

Here's a project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.Core" Version="2.35.0" />
  </ItemGroup>
</Project>
```

... and the source code:

```csharp
using System;
using System.Text;
using Grpc.Core;

class Program
{
    static void Main(string[] args)
    {
        if (args.Length == 0)
        {
            Console.WriteLine("Please pass in an address to connect to");
            return;
        }
        string address = args[0];
        var marshaller = new Marshaller<string>(Encoding.UTF8.GetBytes, Encoding.UTF8.GetString);
        var method = new Method<string, string>(
            MethodType.Unary, "test-service", "test-method", marshaller, marshaller);
        var channel = new Channel(address, ChannelCredentials.Insecure);
        var callInvoker = channel.CreateCallInvoker();
        callInvoker.BlockingUnaryCall(method, address, new CallOptions(), "request");
    }
}
```

On my machine, here's the error I received when running `dotnet run localhost:8080` without the Firestore emulator running:

```text
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1612707238.499000000","description":"Failed to pick subchannel","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file_line":5391,"referenced_errors":[{"created":"@1612707238.499000000","description":"failed to connect to all addresses","file":"..\..\..\src\core\ext\filters\client_channel\lb_policy\pick_first\pick_first.cc","file_line":398,"grpc_status":14}]}")
```

When I'd started the emulator with `gcloud beta emulators firestore start --host-port=localhost:8080` I saw a different error:

```text
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Unimplemented", Detail="Method not found: test-service/test-method", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1612707166.600000000","description":"Error received from peer ipv4:127.0.0.1:8080","file":"..\..\..\src\core\lib\surface\call.cc","file_line":1068,"grpc_message":"Method not found: test-service/test-method","grpc_status":12}")
```

Could you give that code a try? If it still reports the same error about DNS resolution for you, then the problem is presumably not in the Firestore library, and it would be worth you asking a question in the gRPC repo: https://github.com/grpc/grpc

**Comment by oantawilliam** [comment] 2021-02-07 14:24
Thank you very much. I'll try that out.

**Comment by jskeet** [comment] 2021-02-24 16:11
Any update on this? If we don't hear back in the next few days, I'll close the issue.

**Closed** 2021-02-26 07:23 UTC
Labels: api: firestore, needs more info, type: question
