### ISSUE TITLE
Deadline Exceeded or Stream Removed  : On batch operations

### ISSUE THREAD

**Issue by yashhema** [googleapis/google-cloud-dotnet#8452] opened 2022-05-05 22:19 UTC
#### Environment details

OS: Windows 11
.NET version: .Net core 3.1
Package name and version: Google.Cloud.Datastore.V1 (3.5) and Google.Cloud.Datastore.Admin.V1 (1.4)

#### Steps to reproduce

  1. Try to run batch jobs in transaction and without transaction with batch size of 500 (upsert/delete) , will randomly get Deadline exceeded/ Stream Removed 
 
```csharp
        static async Task<bool> insertdata()
        {
            //initializedb();
            var googcred1 = GoogleCredential.FromFile(@"D:\firebaseDatabase\key\mydatastoreproj.json");
            string projid = "mydatastoreproj-81e64";
            var channelCredentials = googcred1.ToChannelCredentials();
            var datastoreClient = new DatastoreClientBuilder
            {
                CredentialsPath = @"D:\firebaseDatabase\key\mydatastoreproj.json",
                GrpcChannelOptions = GrpcChannelOptions.Empty
        .WithCustomOption("grpc.keepalive_permit_without_calls", 1)
        .WithCustomOption("grpc.http2.max_pings_without_data", 1000)
            }.Build();

            db12 = DatastoreDb.Create(projid, client: datastoreClient);
            int maxrecordincommit = 450;
            int curindexcounter = 0;
            var transaction = db12.BeginTransaction();
            string entityid = "1000";
            var parentKeyFactory = db12.CreateKeyFactory("SERVICEPROVIDERINFO");
            Key parentKey = parentKeyFactory.CreateKey(entityid);
            var keyFactory = new KeyFactory(parentKey, "MYINSERTTEST");
            Google.Cloud.Datastore.V1.Query query = new Google.Cloud.Datastore.V1.Query("MYINSERTTEST")
            {
                Filter = Google.Cloud.Datastore.V1.Filter.And(Google.Cloud.Datastore.V1.Filter.HasAncestor(parentKey)),
                Projection = { "__key__" }
            };

            var e = await db12.RunQueryAsync(query);
            List<List<Key>> gotkeys = new List<List<Key>>();
            List<Key> curlist = null;
            foreach (var ce in e.Entities)
            {
                if (curlist == null || curlist.Count > maxrecordincommit)
                {
                    curlist = new List<Key>();
                    gotkeys.Add(curlist);
                }
                curlist.Add(ce.Key);
            }

            
            foreach (var l in gotkeys)
            {
                await db12.DeleteAsync(l);
            }
            
            
            
            
            for (int i = 0; i < 15000; i++)
            {
                

                Key mykey = keyFactory.CreateIncompleteKey();


                Entity task22 = new Entity()
                {
                    Key = mykey,
                    ["mykey"] = "HELLOI" +entityid,
                    ["dt"] = "Personal",
                    ["ptype"] = i+10,
                    ["userid"] = i+20,
                    ["done"] = false,
                    ["priority"] = i,
                    ["description"] = "Learn Cloud Datastore" +i,


                };
                curindexcounter = curindexcounter + 1;
                if (curindexcounter == maxrecordincommit)
                {
                    transaction.Commit();
                    transaction = db12.BeginTransaction();
                    curindexcounter = 0;
                }
                transaction.Upsert(task22);
            }

            return true;
        }
```

InnerException | {"Status(StatusCode=\"Unknown\", Detail=\"Stream removed\", DebugException=\"Grpc.Core.Internal.CoreErrorDetailException: {\"created\":\"@1651788768.561000000\",\"description\":\"Error received from peer ipv6:[2607:f8b0:4007:817::200a]:443\",\"file\":\"..\\..\\..\\src\\core\\lib\\surface\\call.cc\",\"file_line\":1070,\"grpc_message\":\"Stream removed\",\"grpc_status\":2}\")"} | System.Exception {Grpc.Core.RpcException}
```text
GRPC Logs:
I0505 18:12:27.405929 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:29.146444 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:31.342854 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:33.026026 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:35.230152 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:37.878727 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:40.430379 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:42.709614 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:44.296775 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:45.393557 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:45.546088 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:46.664073 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:46.870561 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:47.943913 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:182: ConnectivityStateTracker client_channel[00000247C6D0B430]: get current state: READY
I0505 18:12:48.561432 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:159: ConnectivityStateTracker client_transport[00000247C736EA78]: READY -> SHUTDOWN (close_transport, OK)
I0505 18:12:48.561815 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:167: ConnectivityStateTracker client_transport[00000247C736EA78]: notifying watcher 00000247C7343040: READY -> SHUTDOWN
I0505 18:12:48.564632 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:79: watcher 00000247C7343040: delivering async notification for SHUTDOWN (OK)
I0505 18:12:48.564776 0 ..\..\..\src\core\lib\transport\connectivity_state.cc:159: ConnectivityStateTracker client_channel[00000247C6D0B430]: READY -> IDLE (helper, OK)
```

**Comment by jskeet** [comment] 2022-05-06 07:38
Thanks for the code. I've refactored it a bit to make it easier (for me) to understand and reconfigure. Please could you try this code and see whether it still reproduced the problem for you?

On my laptop, with 15,000 entities to delete and reinsert, I'm seeing take about 70 seconds, and insertion take about 7 seconds. However, I haven't seen any errors.

As with your previous questions, I really think the problem here is with the network connection - if you're using a connection that gets dropped in the middle of a non-retriable RPC, I'm not surprised that you're seeing problems, and there's nothing we can really do about that from a client library perspective.

```csharp
using Google.Api.Gax.Grpc;
using Google.Cloud.Datastore.V1;

class Program
{
    // null to use application default credentials, a path
    // to load them from that path.
    private const string CredentialFile = null;
    private const string ProjectId = "jonskeet-integration-tests";
    private const string RootKeyName = "Issue8452";
    private const string SubKeyName = "Test1";
    private const string EntityKind = "InsertTest";
    private const int BatchSize = 450;
    private const int EntitiesToInsert = 15000;

    private static async Task Main()
    {
        var db = CreateDatastoreDb();
        await DeleteExistingEntities(db);
        await InsertEntities(db);
    }

    private static DatastoreDb CreateDatastoreDb()
    {
        var datastoreClient = new DatastoreClientBuilder
        {
            CredentialsPath = CredentialFile,
            GrpcChannelOptions = GrpcChannelOptions.Empty
                .WithCustomOption("grpc.keepalive_permit_without_calls", 1)
                .WithCustomOption("grpc.http2.max_pings_without_data", 1000)
        }.Build();
        return DatastoreDb.Create(ProjectId, client: datastoreClient);
    }

    private static async Task DeleteExistingEntities(DatastoreDb db)
    {
        var rootKeyFactory = db.CreateKeyFactory(RootKeyName);
        Key subKey = rootKeyFactory.CreateKey(SubKeyName);
        Query query = new Query(EntityKind)
        {
            Filter = Filter.HasAncestor(subKey),
            Projection = { DatastoreConstants.KeyProperty }
        };

        var queryResult = await db.RunQueryAsync(query);
        if (queryResult.Entities.Count == 0)
        {
            Log("No existing entities to delete.");
            return;
        }


        // TODO: Use queryResult.MoreResults
        var batches = new List<List<Key>>();
        var currentBatch = new List<Key>();
        foreach (var entity in queryResult.Entities)
        {
            currentBatch.Add(entity.Key);
            if (currentBatch.Count == BatchSize)
            {
                batches.Add(currentBatch);
                currentBatch = new List<Key>();
            }
        }
        if (currentBatch.Count > 0)
        {
            batches.Add(currentBatch);
        }

        Log($"Deleting {queryResult.Entities.Count} entities in {batches.Count} batches");
        foreach (var batch in batches)
        {
            await db.DeleteAsync(batch);
        }
        Log("Deletion complete");
    }

    private static async Task InsertEntities(DatastoreDb db)
    {
        var rootKeyFactory = db.CreateKeyFactory(RootKeyName);
        Key subKey = rootKeyFactory.CreateKey(SubKeyName);
        var subKeyFactory = new KeyFactory(subKey, EntityKind);

        int transactionsCommitted = 0;
        var transaction = await db.BeginTransactionAsync();
        int transactionSize = 0;

        Log($"Inserting {EntitiesToInsert} entities.");
        for (int i = 0; i < EntitiesToInsert; i++)
        {
            var entity = new Entity
            {
                Key = subKeyFactory.CreateIncompleteKey(),
                ["counter"] = i
            };

            transaction.Upsert(entity);
            transactionSize++;

            if (transactionSize == BatchSize)
            {
                await transaction.CommitAsync();
                transaction = await db.BeginTransactionAsync();
                transactionSize = 0;
                transactionsCommitted++;
            }
        }
        if (transactionSize == 0)
        {
            await transaction.RollbackAsync();
        }
        else
        {
            await transaction.CommitAsync();
            transactionsCommitted++;
        }
        Log($"Insertion complete. {transactionsCommitted} transactions committed.");
    }

    private static void Log(string message) =>
        Console.WriteLine($"{DateTime.UtcNow:yyyy-MM-dd'T'HH:mm:ss}Z: {message}");
}
```

**Comment by jskeet** [comment] 2022-05-06 08:18
I've just rerun this inserting a million entities, and it worked fine, taking about 8 1/2 minutes (and 2223 transactions). So I really don't think I'll be able to reproduce this...

**Comment by jskeet** [comment] 2022-05-16 07:07
Closing due to lack of information. Please add a comment with more information and we can reopen this issue.

**Closed by jskeet** 2022-05-16 07:07 UTC
Labels: type: question, api: datastore, needs more info, priority: p3
