### ISSUE TITLE
SpeechClient Recognize function freezes after call

### ISSUE THREAD

**Issue by drronnie85** [googleapis/google-cloud-dotnet#5204] opened 2020-07-24 21:42 UTC
Hello.
When I call Recognize function of SpeechClient it never respond.
On my home PC it works properly, but on the work PC not.
Work PC has default proxy server that configured by Active Directory.
I tried setup environment variable HTTP_PROXY to empty string, to space, to fiddler (http://127.0.0.1:888) but without success.
When I setup fiddler as proxy server on work PC I see recurring calls "CONNECT speech.googleapis.com:443 HTTP/1.0" with responses "HTTP/1.0 200 Connection Established".
When I setup fiddler as proxy server on home PC I see similar calls and have same behaviour (freezes of Recognize).
Please help to resolve this problem.

```csharp
var client = SpeechClient.Create();
// freezes on next line
var response = client.Recognize(
  new RecognitionConfig() {
    Encoding = GetAudioEncoding(options.Encoding),
    SampleRateHertz = options.SampleRateHertz,
    LanguageCode = GetLanguageCode(options.Language),                        
  },
  RecognitionAudio.FromBytes(content));
```

#### Environment details
  - OS: Windows 10 x64
  - .NET version: .NET Core 3.1.201
  - Package name and version: Google.Cloud.Speech.V1 (2.0.0)

**Comment by jskeet** [comment] 2020-07-24 21:56
I'll answer in more detail on Monday, but my *guess* is that the proxy server doesn't support HTTP 2 properly.

**Comment by drronnie85** [comment] 2020-07-25 05:55
@jskeet  thank you for your answer.
If your guess is correct I have two questions:
1. How to disable using proxy?
I tried `Environment.SetEnvironmentVariable("HTTP_PROXY", "");` but without success.
2. Is it correct behavior? 
I think library should throw exception when it can't connect to endpoint (by any reason).

I build Google.Cloud.Speech.V1 from sources and after debug I determined that problem is in Grpc.Core.
I also tried to build Grpc.Core from sources but without success.

**Comment by jskeet** [comment] 2020-07-27 07:41
Hmm... I can't reproduce the problem even when running with Fiddler. It does sound like this is a gRPC issue rather than a client library issue.
I suggest you file a new issue on https://github.com/grpc/grpc with appropriate details and a short but *complete* example. Here's the complex example I was trying with:

```csharp
using Google.Cloud.Speech.V1;
using System;

class Program
{
    static void Main(string[] args)
    {
        var client = SpeechClient.Create();
        var config = new RecognitionConfig
        {
            Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
            SampleRateHertz = 16000,
            LanguageCode = "en-US",
        };
        var audio = RecognitionAudio.FromBytes(new byte[10]);
        var response = client.Recognize(config, audio);
        Console.WriteLine(response);
    }
}
```

The library *does* time out with unsuccessful calls, but the `Recognize` call has a timeout of 5000s (nearly an hour and a half). So if the networking issue means that the client thinks the request has been sent successfully, but it can't get a reply back, that will take a long time to fail.

Here's an example of creating a client with a much shorter timeout for `Recognize`:

```csharp
var settings = SpeechSettings.GetDefault();
settings.RecognizeSettings = settings.RecognizeSettings.WithTimeout(TimeSpan.FromSeconds(5));
var client = new SpeechClientBuilder { Settings = settings }.Build();
```

I would like to close this issue at this point, as I don't believe there's further work to do in this repository. I'm hoping that the gRPC folks can help you diagnose what's going wrong. Is that okay?

**Comment by drronnie85** [comment] 2020-07-27 09:52
@jskeet thank you for your answer. And also thanks for sample of code with Recognize timeout.
I tried your example
`
        static void Main(string[] args)
        {
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", @".\rzstt.json");
            Environment.SetEnvironmentVariable("HTTP_PROXY", @"http:\\127.0.0.1:8888");

            var settings = SpeechSettings.GetDefault();
            settings.RecognizeSettings = settings.RecognizeSettings.WithTimeout(TimeSpan.FromSeconds(5));
            var client = new SpeechClientBuilder { Settings = settings }.Build();

            //var client = SpeechClient.Create();
            var config = new RecognitionConfig
            {
                Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                SampleRateHertz = 16000,
                LanguageCode = "en-US",
            };
            var audio = RecognitionAudio.FromBytes(new byte[10]);
            var response = client.Recognize(config, audio);
            Console.WriteLine(response);
        }
`
And I have next results.
At home:
Without proxy works properly.
Through Fiddler i got Grpc.Core.RpcException: 'Status(StatusCode=Unavailable, Detail="DNS resolution failed")'
At work:
When i set HTTP_PROXY to null it use default proxy.
Through Fiddler i got Grpc.Core.RpcException: 'Status(StatusCode=Unavailable, Detail="failed to connect to all addresses")'
Through Charles (web debugger like a Fiddler) it works properly.

Maybe you know how to disable using proxy or setup not through environment variable?. (Something like property IWebProxy Proxy { get; set; })
If disabling of Proxy can't help I create new issue in grpc project.
Thank you.

**Comment by jskeet** [comment] 2020-07-27 09:58
You could try using the `NO_PROXY` environment variable - in this case setting it to `speech.googleapis.com`, I expect. But I'm not an expert in the gRPC proxy configuration - I would suggest asking about it on the gRPC repository.

I'll close this now, as it's really about proxy configuration which isn't done in the library.

**Closed by jskeet** 2020-07-27 09:58 UTC
Labels: type: question

**Comment by drronnie85** [comment] 2020-07-27 11:00
@jskeet NO_PROXY solve my problem. Thank you for your answers!
