### ISSUE TITLE
Returns only one resultset when executing Procedure

### ISSUE THREAD

**Issue by gowthammano** [googleapis/google-cloud-dotnet#3772] opened 2019-11-19 13:47 UTC
I'm using the Google.Cloud.BigQuery.V2 version="1.4.0-beta06" to execute CALL <Procedure>();
My Procedure calls 2 other procedures, each of which has a resultset.
When executing the wrapper procedure via console, I can see both result sets by clicking on "VIEW RESULTS".
But via code, bqClient.ExecuteQuery returns only the second result set.

**Comment by amanda-tarafa** [comment] 2019-11-19 14:18
I believe this might be that the API is only returning the last result set. I will confirm with the BigQuery team and update this thread with more info.

**Comment by amanda-tarafa** [comment] 2019-11-19 15:33
I've been able to reproduce this without the need of calling procedures. When executing the code below, only one row is returned, the one corresponding to the last SELECT.
```
BigQueryClient client = BigQueryClient.Create(ProjectId);

string sql = "SELECT 5; SELECT 6, 7;";
BigQueryResults results = client.ExecuteQuery(sql, null).ThrowOnAnyError();

BigQueryRow row = results.Single();
Console.WriteLine($"Returned row: ({row[0]}, {row[1]})");
```

This is not a client library issue though, `BigQueryResult` is wrapping [the response from `jobs.getQueryResults` API method](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults#response-body) to provide seemless result pagination, but not much more. The [`jobs.getQueryResults` response](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults#response-body) is not clearly designed to support returning multiple result sets, and the API method is definetely not doing so at the moment.

This looks more like a feature request for the BigQuery API  team, so I'd advise you to create a feature request for them [here](https://issuetracker.google.com/issues/new?component=187149&template=1162659).
You can also take a look and vote on other open issues/feature requests [here](https://issuetracker.google.com/savedsearches/559654).

I'll be closing this issue for now, since I believe there's nothing we can do on the client library side. Please feel free to reopen if you believe different, or create new issues if you encounter other problems using the client library.

**Closed by amanda-tarafa** 2019-11-19 15:33 UTC
Labels: api: bigquery, type: question
