### ISSUE TITLE
Firestore.DocumentReference.GetSnapshotAsync fails with RpcException: Status(StatusCode=PermissionDenied, Detail="Missing or insufficient permissions.")

### ISSUE THREAD

**Issue by pauloevpr** [googleapis/google-cloud-dotnet#2771] opened 2018-12-14 16:43 UTC
Hi,

I have an ASP.NET Core 2.1 Web API running on Google Cloud App Engine Flexible. The application uses Firestore 1.0.0-beta13 with default authentication.

Eventually, calling `Google.Cloud.Firestore.DocumentReference.GetSnapshotAsync()` throws the following exception:

```
Grpc.Core.RpcException: Status(StatusCode=PermissionDenied, Detail="Missing or insufficient permissions.")
   at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token)
   at Google.Cloud.Firestore.FirestoreDb.GetDocumentSnapshotsAsync(IEnumerable`1 documents, ByteString transactionId, CancellationToken cancellationToken)
   at Google.Cloud.Firestore.DocumentReference.GetSnapshotAsync(ByteString transactionId, CancellationToken cancellationToken)
```

According to Stackdriver reports, I have seen this error at least 10 times in the past 30 days. It is hard to reproduce the issue as the error appears to happen randomly.

I have emailed @jskeet with my GCP project details for further investigation.

**Comment by jskeet** [comment] 2018-12-15 10:57
@pauloevpr: Quick question from the backend team - are you hitting Firestore from any other platforms, e.g. a mobile SDK? If you could let us know which platforms you're using, that would help us understand the logs better. (Feel free to send that by email if you'd rather keep it private, of course.)

**Comment by pauloevpr** [comment] 2018-12-15 11:02
Besides the Asp.Net Core Web API, I am also hitting Firestore from a .NET Desktop application (WPF). Both use Firestore .NET SDK 1.0.0-beta13.

**Comment by pauloevpr** [comment] 2018-12-15 21:53
That is right. I only access Firebase services from .NET applications.

**Comment by jskeet** [comment] 2018-12-18 08:47
Can I check how you're acquiring/providing the access token? You'll see this error if you pass in an empty access token, but that's the only way I've managed to reproduce it. If you're using the default credentials, the tokens should just be refreshed for you automatically - but based on your feedback in #2772 I wonder whether the problem is some custom code that's dealing with access tokens?

**Comment by pauloevpr** [comment] 2018-12-18 10:57
I am using custom authentication only for the client application. The server application, where I have seen the PermissionDenied error, is an Asp.Net Core WebAPI running on Google Cloud App Engine, and it uses default credentials.

**Comment by pauloevpr** [comment] 2018-12-18 11:05
This how I create instances of FirestoreDb on my server application:

```c#
public FirestoreDb GetFirestoreDb()
{
    return FirestoreDb.Create(GcpInfo.FirebaseProjectId);
}
```

**Comment by pauloevpr** [comment] 2018-12-18 11:10
It is important to point that the PermissionDenied error happens very rarely. The operations that fail with this error are the same ones which work just fine most of the time. Could it be that the faulty operations take place right in the moment the SDK is refreshing the authentication token?

**Comment by jskeet** [comment] 2018-12-18 11:53
@pauloevpr: That's good to know, thanks. 

Just to check, this is without GOOGLE_APPLICATION_CREDENTIALS being set anywhere - it's just the ambient credentials you get for being on GCP? That would be `ComputeCredential` if so. (If you have the time to confirm that, logging `GoogleCredential.GetDefaultApplicationCredential().UnderlyingCredential.GetType()` would be great.)

I know that we changed the credential refresh mechanism [8 months ago](https://github.com/googleapis/google-api-dotnet-client/blob/master/Src/Support/Google.Apis.Auth/OAuth2/TokenRefreshManager.cs). It's possible there's a bug in that code.
I'll write a little test for that today, if I can... (Today is my last working day this year, and I have various things to wrap up, but I'd definitely like to fix this if I can...)

**Comment by jskeet** [comment] 2018-12-18 12:33
Great, thanks. I've looked over the code and can't see anything wrong with it by inspection, but I'll see if I can stress test it this afternoon. (I'll use 10 tasks that do nothing but ask for tokens all the time, and log any time they see a "new" token. We'll see if they ever end up returning a null or empty token.)

Thanks for being so responsive - it's really helpful!

**Comment by pauloevpr** [comment] 2018-12-18 12:35
It sounds promising. Looking forward to the results.

**Comment by jskeet** [comment] 2018-12-18 14:18
Sample code I'll be running:

```csharp
using Google.Apis.Auth.OAuth2;
using System;
using System.Linq;
using System.Threading.Tasks;

class Program
{
    const int TaskCount = 20;

    static void Main(string[] args)
    {
        var credential = GoogleCredential.GetApplicationDefault().CreateScoped("https://www.googleapis.com/auth/cloud-platform");
        var tasks = Enumerable
            .Range(0, TaskCount)
            .Select(index => FetchTokens(index, credential))
            .ToArray();
        Task.WaitAll(tasks);
    }

    static async Task FetchTokens(int index, ITokenAccess tokenAccess)
    {
        Console.WriteLine($"Starting task {index}");
        string lastToken = "invalid";
        while (true)
        {
            string nextToken = await tokenAccess.GetAccessTokenForRequestAsync();
            if (lastToken != nextToken)
            {
                Console.WriteLine($"{DateTime.UtcNow:HH:mm:ss}: task {index} received token length {nextToken}");
                lastToken = nextToken;
            }
            await Task.Yield();
        }
    }
}
```

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.36.1" />
  </ItemGroup>
</Project>
```

(Unfortunately we're likely to only see changes once every hour, but...)

**Comment by jskeet** [comment] 2018-12-18 16:06
I've got this running on 3 machines, btw. It looks like Compute credentials are only valid for 30 minutes rather than an hour, and we refresh them 6 minutes before we need to, so I'm seeing changes (x3) every 24 minutes. No empty access tokens yet though...

**Comment by jskeet** [comment] 2019-01-02 07:46
I didn't see any invalid use of credentials in my tests. Could I check whether you're still seeing this issue, or whether it's gone away by itself? (Such things have been known to happen.)

If it's still happening, I'll nudge the server team to continue looking.

**Comment by pauloevpr** [comment] 2019-01-07 01:34
According to Google Stackdriver Error Report, this issue was last seen December 15, 2018. Since then, no more occurrences popped up. It seems to have gone away by itself.

**Comment by jskeet** [comment] 2019-01-07 06:09
That's great to hear. I'll close this for now, assuming it was some sort of transient server-side issue. Of course, if you see it again, just add a comment here and we can reopen. (I admit I don't like closing issues where we don't know what was wrong in the first place, but I'm not sure what we can do about it in this case....)

**Closed by jskeet** 2019-01-07 06:09 UTC
Labels: api: firestore, priority: p2, type: bug
