### ISSUE TITLE
BigQueryResults.TotalRows throws InvalidOperationException

### ISSUE THREAD

**Issue by ef-computas** [googleapis/google-cloud-dotnet#2559] opened 2018-10-04 08:23 UTC
version: Google.Cloud.BigQuery.V2 1.3.0-beta05 and Google.Cloud.BigQuery.V2 1.2.0

Running a query that selects rows from a source table and appends to a destination table:

```
var options = new QueryOptions
{
    UseLegacySql = false,
    AllowLargeResults = true,
    DestinationTable = destinationTableRef,
    JobLocation = "EU",
    WriteDisposition = WriteDisposition.WriteAppend,
    ProjectId = projectId,
    DefaultDataset = client.GetDatasetReference(projectId, datasetId),
    Priority = QueryPriority.Interactive,
    DryRun = false
};

var query = @"SELECT *
                   FROM `" + sourceTable + "` " +
                   @"WHERE _PARTITIONTIME <= TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))";

var bigQueryResults = client
                .ExecuteQuery(query, null, queryOptions)
                .ThrowOnAnyError();

var totalRows = bigQueryResults.TotalRows; // this throws: InvalidOperationException: Nullable object must have a value. 
```
The query seem to run ok, but an exception is thrown when attempting to access bigQueryResults.TotalRows:

System.InvalidOperationException: Nullable object must have a value.
  at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
  at Google.Cloud.BigQuery.V2.BigQueryResults.get_TotalRows()

**Comment by jskeet** [comment] 2018-10-04 11:40
Hmm... that's worrying. That suggests the underlying `TotalRows` property is null. I don't know why that would be. I'd expect that to always bye populated on a successful query. I'll have to look into this. I'm afraid I'm travelling over the next couple of days, which is going to delay things somewhat, although I'll see if I can find pockets of time.

Does this happen every time, or just occasionally? It would be good to be able to reproduce this myself. If you access the rows themselves, do you get the data you expect?

**Comment by amanda-tarafa** [comment] 2018-10-05 11:59
@ef-computas I haven't been able to reproduce this issue. It would be of great help if you could provide more info to try and reproduce as faithfully as possible. For instance:

- How many rows are you expecting to get from your query?
- Have you tried accessing some of the other properties on `bigQueryResults`, what do you get? Specifically as @jskeet asked, can you access the rows themselves, and you get what you expected?
- How long does it take the query to (apparently) execute properly?

**Comment by amanda-tarafa** [comment] 2018-10-11 09:58
@ef-computas friendly ping in case you have more context to share with us or maybe this have sorted out for you? Thanks!

**Comment by ef-computas** [comment] 2018-10-11 21:04
@amanda-tarafa sorry for the late reply. I don't have all the information yet and I will hopefully have time to look more into this next week, but I can try to answer some of your questions. 

The number of selected rows from the source table should normally be less than ~67 000 000, but can be more in some cases. In the normal case I think that the number of selected rows from the source table is less than 1 000 000 rows. 

We have only verified that the number of rows in the destination table increases with the expected amount after the operation is complete, but we haven't tried to query the data itself. 

I think the query takes a couple of minutes to complete at most.

**Comment by amanda-tarafa** [comment] 2018-10-19 11:02
@ef-computas Just to let you know that I haven't had the chance to try and reproduce the issue with the new info you sent, I'll try to get on it early next week. Will update here when I know more.

**Comment by amanda-tarafa** [comment] 2018-10-23 13:32
@ef-computas I've just tried to reproduce your issue with a table with over 100 million rows and everything works as expected. If there is some error in the query or I force the query to timeout I get the expected Exception. If the query is correct, then queryResult.TotalRows always has the expected value. I'm not able to reproduce your issue. Here's the code I use:
```
            var projectId = "my-project-id";
            var datasetId = "testing_dataset";
            var client = BigQueryClient.Create(projectId);
            var userDataset = client.GetDataset(datasetId);
            var destinationTable = userDataset.GetTableReference("destination_table");

            var sql = "select * from `source_table` where _PARTITIONTIME <= TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY))";

            var queryResult = client
                .ExecuteQuery(sql, null,
                new QueryOptions
                {
                    DestinationTable = destinationTable,
                    UseLegacySql = false,
                    AllowLargeResults = true,
                    //JobLocation = "EU",
                    WriteDisposition = WriteDisposition.WriteAppend,
                    ProjectId = projectId,
                    DefaultDataset = client.GetDatasetReference(projectId, datasetId),
                    Priority = QueryPriority.Interactive,
                    DryRun = false
                })
                .ThrowOnAnyError();

            Assert.True(queryResult.TotalRows > 1);
```
Only thing I've had to changed with respect to your code was the JobLocation setting, because of how my testing project is configured. Can you test my code independently against your tables and see what happens?
Or if you provide us with a working console application that reproduces the issue, we'll be able to look into it more.

**Comment by amanda-tarafa** [comment] 2018-11-06 12:44
@ef-computas I'll be closing this for now, but if you continue to see this problem or can share a way to reproduce please feel free to reopen. We haven't found a way to reproduce this.

**Comment by jskeet** [comment] 2018-12-12 07:09
I've now seen this when trying to diagnose #2764. Will investigate further.

**Comment by jskeet** [comment] 2018-12-12 08:14
@ef-computas: Can I check whether you're still seeing this for queries? I would now expect it to happen for DML, but not for regular queries.

Unfortunately as we expose a `ulong`, it's hard to provide any appropriate value here. I'm considering adding a `HasTotalRows` property so you can easily check whether using `TotalRows` will be okay - would that help you? It's annoying to have to check the property first, but I can't see a better alternative at the moment. (If we could work out when it happens more accurately, that would make it easier to work out a way forward.)

**Comment by jskeet** [comment] 2018-12-12 08:16
(Another alternative: add a `SafeTotalRows` property of type `ulong?`. That might be better...)

**Comment by jskeet** [comment] 2018-12-12 15:31
@ef-computas: While we still don't know why you saw this in a query, #2765 (unreleased as yet) provides a way of getting the total rows in a safer way - so if you're still seeing the issue, you should be able to start using that new property when we next do a release.

**Closed by jskeet** 2018-12-12 15:31 UTC
Labels: priority: p2, status: investigating, type: bug

**Comment by jskeet** [comment] 2018-12-17 14:53
The v1.3.0-beta06 package is now available that includes the new property.
