### ISSUE TITLE
FirestoreChangeListeners throwing unhandled System.AggregateException if any network problems

### ISSUE THREAD

**Issue by damian4891** [googleapis/google-cloud-dotnet#5462] opened 2020-10-19 01:05 UTC
Hello,

I am creating several FirestoreChangeListeners (following the User Guide at https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/userguide.html) and everything is working fine, but when there is a network problem, _multiple_ unhandled System.AggregateExceptions are being thrown with the inner exception being a Grpc.Core.RpcException with Status of "Transport Closed" or "Failed to connect".

The problem is not the exception itself, but how to catch or handle these inner exceptions.

I've tried adding try/catch in multiple places, tried adding ContinueWith to the listener, but regardless I still get many unhandled System.AggregateExceptions. A single network error and single listener causes multiple exceptions in a row.

![2020-10-19 12_02_59-Window](https://user-images.githubusercontent.com/63281689/96391075-321e9900-1203-11eb-956a-0a3fdc673563.png)

My code is:

public void Connect()
    {
      // Authentication code...
    
      if (authenticated) CreateFirestoreChangeListeners();
    }
    
    public void CreateFirestoreChangeListeners()
    {
      foreach (var docRef in documentReferences.Values)
      {
        FirestoreChangeListener listener = docRef.Listen(querySnapshot =>
        {
          try
          {
            ProcessSnapshot(querySnapshot);
          }
          catch (Exception ex)
          {
            Debug.WriteLine("FirestoreChangeListener: " + ex);
          }
        });
    
        listener.ListenerTask.ContinueWith((task) =>
        {
          Console.WriteLine("Task faulted");
          var ae = task.Exception;
          if (ae != null)
          {
            ae.Flatten().Handle(ex =>
            {
              Console.WriteLine("Exception Handled");
              return true;
            });
          }
        });
        firestoreChangeListeners.Add(listener);
      }
    }

Interestingly, after a network problem the ContinueWith is firing correctly, but the Exception is **null**, meaning it is never caught or handled inside that method. Instead, an unhandled System.AggregateException will follow.

Thanks for your help.
Damian

**Comment by jskeet** [comment] 2020-10-19 06:29
Thanks, I'll try to take a look at this today.

**Comment by jskeet** [comment] 2020-10-19 06:30
One side note: could you let me know which version of .NET you're using, and which version of the Firestore library?

**Comment by damian4891** [comment] 2020-10-19 06:51
Thanks! I'm using .NET Framework 4.7.2 and Google.Cloud.Firestore v2.2.0

**Comment by jskeet** [comment] 2020-10-19 09:54
Okay, progress in terms of creating a minimal example... I originally reproduced in .NET 4.7.2 with an app.config file, but we get cleaner exceptions using .NET Core 2.1, using the `TaskScheduler.UnobservedTaskException` event:

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="2.2.0" />
  </ItemGroup>
</Project>
```

Program.cs:

```csharp
using Google.Cloud.Firestore;
using System;
using System.Threading.Tasks;

class Program
{
    static async Task Main()
    {
        TaskScheduler.UnobservedTaskException += (sender, args) =>
            Console.WriteLine($"Unhandled exception: {args.Exception.InnerException}");
        FirestoreDb db = FirestoreDb.Create("bad-project-id");
        var listener = db.Document("collection/doc").Listen(snapshot => Console.WriteLine("Callback executed"));

        // Give it time to try to connect...
        await Task.Delay(5000);

        // Wait for any failed tasks to be garbage collected
        GC.Collect();
        GC.WaitForPendingFinalizers();
    }
}

```

Run with `dotnet run -c Release`:

```text
Unhandled exception: Grpc.Core.RpcException: Status(StatusCode="NotFound", Detail="...", ...)
   at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\ClientResponseStream.cs:line 60
   at Google.Cloud.Firestore.WatchStream.<>c__DisplayClass15_0.<<StartAsync>g__GetNextResponse|0>d.MoveNext() in /_/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/WatchStream.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at Google.Cloud.Firestore.WatchStream.StartAsync() in /_/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/WatchStream.cs:line 101
   at Google.Cloud.Firestore.WatchStream.StartAsync() in /_/apis/Google.Cloud.Firestore/Google.Cloud.Firestore/WatchStream.cs:line 138
```

So that gives a reasonably clear place to look within Google.Cloud.Firestore...

**Comment by jskeet** [comment] 2020-10-19 10:01
However, when I add your `ContinueWith` code, that *does* handle the exception, and no exceptions are deemed unreported.

Will try generating a different failure mode...

**Comment by jskeet** [comment] 2020-10-19 10:08
Okay, I can reproduce it by providing a bad endpoint:

```csharp
FirestoreDb db = new FirestoreDbBuilder
{
    ProjectId = "bad-project-id",
    Endpoint = "10.1.1.1"
}.Build();
```

The connection loop within the watch stream repeatedly tries to connect - but I haven't yet worked out whether this is something where *we're* not observing the exception, or whether gRPC isn't even exposing it.

**Comment by jskeet** [comment] 2020-10-19 10:10
This may well be related: https://github.com/grpc/grpc/issues/24421

**Comment by jskeet** [comment] 2020-10-19 10:23
Okay, I've made *some* progress - oddly enough, it looks like the Firestore library code *is* catching exceptions representing the same failures... but it's as if two exceptions are generated internally in Grpc.Core, only one of which is propagated out to the caller, leaving the other to be unhandled.

I'll see if I can reproduce it with "just bare gRPC code" at which point it would definitely be a gRPC bug rather than one in the Firestore library. (The jury's out on that right now...)

As a workaround, you might want to just add a `TaskScheduler.UnobservedTaskException` handler to mark any RpcExceptions as handled.

**Comment by jskeet** [comment] 2020-10-19 10:31
Okay - I've reproduced this using only the gRPC-generated code, showing that this really *is* a gRPC bug. I'll add the repro to grpc/grpc#24421, but I'm going to close this issue now as we can't fix it within this library.

In terms of the workaround, I believe this should work for you:

```csharp
TaskScheduler.UnobservedTaskException += (sender, args) =>
{
    if (args.Exception is AggregateException && args.Exception.InnerException is RpcException)
    {
        args.SetObserved();
    }
};
```

Of course, you may want to add some logging...

**Closed by jskeet** 2020-10-19 10:31 UTC
Labels: api: firestore, type: bug

**Comment by damian4891** [comment] 2020-10-23 03:45
Hi Jon,

Thank you very much for your investigation and suggested workaround. That works fine and is a suitable solution.

Thanks again!
Damian
