### ISSUE TITLE
[OverflowException] Google.Cloud.Firestore

### ISSUE THREAD

**Issue by cschuchardt88** [googleapis/google-cloud-dotnet#10473] opened 2023-06-04 14:58 UTC
#### Environment details

  - OS: Windows 10 x64
  - .NET version: dotnet 7
  - Package name and version: Google.Cloud.Firestore 3.3.0

#### Steps to reproduce

  1. Unsure at this time, trying to find out why.

#### OverflowException: Arithmetic operation resulted in an overflow.
```
This exception was originally thrown at this call stack:
    Google.Cloud.Firestore.Converters.UInt64Converter.Serialize(Google.Cloud.Firestore.SerializationContext, object)
    Google.Cloud.Firestore.ValueSerializer.Serialize(Google.Cloud.Firestore.SerializationContext, object)
    Google.Cloud.Firestore.Converters.AttributedTypeConverter.AttributedProperty.GetProtoValue(Google.Cloud.Firestore.SerializationContext, object)
    Google.Cloud.Firestore.Converters.AttributedTypeConverter.SerializeMap(Google.Cloud.Firestore.SerializationContext, object, System.Collections.Generic.IDictionary<string, Google.Cloud.Firestore.V1.Value>)
    Google.Cloud.Firestore.ValueSerializer.SerializeMap(Google.Cloud.Firestore.SerializationContext, object)
    Google.Cloud.Firestore.WriteBatch.Create(Google.Cloud.Firestore.DocumentReference, object)
    Google.Cloud.Firestore.DocumentReference.CreateAsync(object, System.Threading.CancellationToken)
    Neo.Events.Node.HostedServices.NeoEventSystem.Test.AnonymousMethod__0() in NeoEventSystem.cs
```

**Comment by cschuchardt88** [comment] 2023-06-05 07:29
I'm away at the moment but I'll try to put something together ASAP


Im storing blockchain information that has huge nonce uint64(ulong) and it
crashing on the ulongs that are close to uint64.max

Im guessing google is using some kind of calculation in the converter. I
did create a custom converter to handle it as a work around just converting
it to a string.

**Comment by jskeet** [comment] 2023-06-05 07:43
> Will this problem be fixed or is it something that won't be fixed in the future release.

It's not a problem in the library. The library is behaving exactly as designed and documented, working with the set of data types that Firestore supports. I would be surprised to see Firestore extend its set of core datatypes.

We could *potentially* add some sort of option on converter attributes to say "serialize this ulong as a string" or "serialize this ulong as a long via an unchecked conversion" but I don't think we're likely to do that any time soon, to be honest. 

> U could use big integer class that way you can convert it back to decimal and vice versa.

If you mean using the Firestore floating point data type to store the value, I'd be *very* reluctant to do that. To be clear, this isn't about "how do we implement the functionality" - the *implementation* is likely to be simple for any choice we make. It's about "what Firestore data type do we use".

**Comment by jskeet** [comment] 2023-06-05 07:52
> If you do the conversion to string  you can't do a search in the console
for a number you have to do it as a value string is there any performance
difference between the integer way or doing it versus a string.

Well, a conversion between text and integer representations is always going to be slower than not doing a conversion.

If you want to keep a numeric representation, then you'll need to either move to use a signed representation in your own code, or use a custom conversion which uses an unchecked cast.

I'll close this issue now as the library is behaving as intended.

**Closed by jskeet** 2023-06-05 07:52 UTC
Labels: type: bug, priority: p2, needs more info, api: firestore
