### ISSUE TITLE
No traces with Google.Cloud.Logging.Console despite following documentation

### ISSUE THREAD

**Issue by christopheblin** [googleapis/google-cloud-dotnet#10574] opened 2023-06-22 10:02 UTC
https://github.com/googleapis/google-cloud-dotnet/issues/9948#issuecomment-1602270489

I've followed the documentation at https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Logging.Console/latest

I can see logs in Logs explorer and I can click on the left arrow to see all logs of the same trace

![image](https://github.com/googleapis/google-cloud-dotnet/assets/11044877/d0b89010-531e-4df4-a8c7-5eb837cb7b9b)

However, the view trace details is not working

![image](https://github.com/googleapis/google-cloud-dotnet/assets/11044877/bd6c835b-3422-4be2-b218-3944f55901fa)

Here is an example project (be aware to replace values in cloudbuild.yaml / cloudrun.yaml)

[gcp-log-trace.zip](https://github.com/googleapis/google-cloud-dotnet/files/11830416/gcp-log-trace.zip)

Given the doc https://cloud.google.com/dotnet/docs/reference/Google.Cloud.Logging.Console/latest#log-trace-correlation, I'd expect traces to work 
1. application exports log entries to Google Cloud Logging => yes because of cloud run
2. application exports traces to Google Cloud Trace.=> yes because of cloud run default
3. having trace context => yes becasuse of ASP.NET core
4. The console formatter configured with the Google Cloud Project ID => yes because of the line `builder.Logging.AddGoogleCloudConsole(options => options.TraceGoogleCloudProjectId = gcpProject);

IMHO, the point 2 is the issue : the doc says "by default Cloud run exports traces" but this is not the case I think and so the logs are not corerctly showing the trace

please note that we want the "CPU is only allocated during request processing"

**Comment by amanda-tarafa** [comment] 2023-06-22 12:08
Thanks! I'll get back here as soon as I know more

**Comment by amanda-tarafa** [comment] 2023-06-22 12:56
@christopheblin A couple of things for you to try.

- Try and find a log entry with the field `trace_sampled` set to true. I expect you'll be able to see the trace details for that. That's because Cloud Run does not sample traces for all incoming requests, instead it has maximum sampling rate of 0.1 per second. See https://cloud.google.com/run/docs/trace#trace_sampling_rate for more information.

- Else, go to the Trace Explorer in the Google Cloud Console and try to find one of the traces from the application you are testing with, see if it's correct and showing associated log entries. Then go back to the Logs Viewer and see whether the `View Trace Details` menu item is available or not and what's the value for the `trace_sampled` field in the log entries associated to the trace.

I'll see if I can reproduce and report back as well.

**Comment by christopheblin** [comment] 2023-06-22 13:57
For entries with traceSampled=true, it works

![image](https://github.com/googleapis/google-cloud-dotnet/assets/11044877/a9dd986b-c99c-48fd-bd7c-591550e9f94d)

And yes I have about 30 HTTP requests today and 4 have traceSampled=true so it matches the 0.1 rate you mentioned

I'll take a look to force traces because that was what we were doing when using the `AddGoogleDiagnosticsForAspNetCore`

So I need to find a way to force traces (without adding a header client side ...)

Do you have any idea about that ?

**Comment by amanda-tarafa** [comment] 2023-06-22 20:12
> So I need to find a way to force traces (without adding a header client side ...)

The Cloud Run team will be able to help you here. We don't have that much expertise on Cloud Run. See their [support pages](https://cloud.google.com/run/docs/support) or contact them through your usual support channels if you have a Support Package.

On the Public issue tracker for Cloud Run I did find this feature request: https://issuetracker.google.com/issues/171235561, and I've notified them internally of this thread.

I'll be closing this issue now as there's not much more we can do here. If you want to go back to Google.Cloud.Diagnostics and you run into problems, do create a new issue and we'll help there. But I'd recommend you do that as a last resort only, in particular given that you are running in a serverles environment.

Sorry we cannot be of more help here.

**Closed by amanda-tarafa** 2023-06-22 20:12 UTC
Labels: type: question, priority: p1
